/**
 * GENERATED by `python map-manual.py` from map-layout.txt - DO NOT HAND EDIT.
 * Edit map-layout.txt and re-run instead.
 *
 * Placement here is AUTHORED, not solved. Automatic placement kept the map
 * legal and never got it composed; on this plate its ceiling was 16 buildings
 * well-spaced against a roster of 19. Hand placement has no such ceiling.
 *
 * ROADS, RIVERS AND BRIDGES ARE PAINTED INTO bg-land.webp, so the vector
 * network stays empty - drawing one would put a second, disagreeing set of
 * roads over the painting.
 */
import type { Vec2 } from "@/lib/world/types";

export const FIT_RIVERS: Vec2[][] = [];
export const FIT_ROADS: Vec2[][] = [];
export const FIT_CROSSINGS: Vec2[] = [];
export const FIT_TRACKS: Vec2[][] = [];
export const FIT_PADS: { x: number; y: number; r: number }[] = [];

export const FIT_SITES: Record<string, Vec2> = {
  basecamp: { x: 0.8820, y: 0.6900 },
  commandpost: { x: 0.9240, y: 0.3380 },
  muster: { x: 0.8610, y: 0.9240 },
  powerstation: { x: 0.9310, y: 0.4830 },
  convoyroad: { x: 0.7910, y: 0.2300 },
  airfield: { x: 0.6510, y: 0.2230 },
  arena: { x: 0.7900, y: 0.3780 },
  ridgepass: { x: 0.5410, y: 0.1340 },
};

export const FIT_SLOTS: Vec2[] = [
  { x: 0.5210, y: 0.7880 },
  { x: 0.3970, y: 0.7410 },
  { x: 0.5190, y: 0.5230 },
  { x: 0.2470, y: 0.8420 },
  { x: 0.6650, y: 0.8630 },
  { x: 0.3100, y: 0.2480 },
  { x: 0.1520, y: 0.2390 },
  { x: 0.1290, y: 0.6670 },
  { x: 0.0550, y: 0.4520 },
  { x: 0.2740, y: 0.5290 },
];

/**
 * TANK ROUTES. Traced by hand over the painted roads, and NEVER DRAWN - the
 * roads already exist in the plate. These exist so rolling units have a
 * centreline to follow. Automatic extraction was tried and measured:
 * subtracting platforms from smooth ground left 836 fragments, largest holding
 * 13% of the network, because a road and a plaza are the same paint. Tracing
 * onto the picture cannot disagree with the picture.
 */
export const FIT_PATHS: Vec2[][] = [
  [{ x: 0.5080, y: 0.7850 }, { x: 0.4760, y: 0.9980 }, { x: 0.5080, y: 0.7850 }],
  [{ x: 0.2230, y: 0.2560 }, { x: 0.2550, y: 0.1180 }, { x: 0.2230, y: 0.2560 }],
  [{ x: 0.7020, y: 0.3570 }, { x: 0.6430, y: 0.4800 }, { x: 0.7020, y: 0.3570 }],
  [{ x: 0.8390, y: 0.4990 }, { x: 0.7780, y: 0.5990 }, { x: 0.8390, y: 0.4990 }],
  [{ x: 0.7680, y: 0.0310 }, { x: 0.6850, y: 0.1430 }, { x: 0.7680, y: 0.0310 }],
  [{ x: 0.2460, y: 0.0280 }, { x: 0.2580, y: 0.1310 }, { x: 0.2460, y: 0.0280 }],
  [{ x: 0.0020, y: 0.2050 }, { x: 0.1350, y: 0.3450 }, { x: 0.0020, y: 0.2050 }],
];

/**
 * THE PLAYER SAFE AREAS - where camped adventurers (holding nothing) scatter.
 * Authored as `camp cx cy rx ry` lines in map-layout.txt / dragged in
 * map-editor.html, AS MANY AS THE PLATE NEEDS. Campers are dealt across them
 * by area, so a big zone takes proportionally more tanks than a small one and
 * both end up the same density. Empty = derive from the muster sign (the
 * fallback), so old layouts keep working.
 */
export const FIT_CAMPS: { x: number; y: number; rx: number; ry: number }[] = [
  { x: 0.2460, y: 0.6770, rx: 0.2510, ry: 0.3000 },
  { x: 0.1640, y: 0.3150, rx: 0.1660, ry: 0.2140 },
  { x: 0.4150, y: 0.8820, rx: 0.0990, ry: 0.1180 },
];
