'use client';
import {useEffect,useState} from 'react';
import {useWorkshopCompetition} from '../_game/WorkshopCompetition';
import css from '../start/landing.module.css';
export default function Page(){
 const [connected,setConnected]=useState(false);useEffect(()=>{try{setConnected(!!JSON.parse(sessionStorage.getItem('mk8.wallet-session.v1')||'null')?.token)}catch{}},[]);
 const model=useWorkshopCompetition(true,0,connected),v=model.value;
 return <main className={css.page}><header className={css.nav}><a className={css.brand} href='/bots/start'>MODEL <b>KOMBAT</b></a><nav aria-label='Main navigation'><a href='/bots/start#steps'>Setup</a><a href='/bots/workshop?view=garage&entry=landing'>Play the game →</a></nav></header><div className={css.sectionTitle}><p className={css.eyebrow}>$2,000 COMPETITION</p><h1>Your results. Three ways to compete.</h1><p>{v.state==='draft'?'Coming soon. Start date to be announced.':!v.available?'Competition data is unavailable.':'Ranks are provisional until verified and finalized.'}</p></div><p className={css.notice}>All cash categories require verified Strategy trades on three distinct days per week, and both weeks for the final. Prelaunch activity does not count. Trading involves risk; prizes are not guaranteed. <a href='/bots/rules'>Full rules →</a></p><div className={css.boards}>{(['roi','profit','battles'] as const).map(category=><section key={category} className={css.board}><span className={css.eyebrow}>{category==='battles'?'$400':'$800'} PRIZE CATEGORY</span><h2>{category==='roi'?'ROI %':category==='profit'?'Realized profit $':'Battle points'}</h2><small>{category==='roi'?'Return relative to measured capital':category==='profit'?'Realized trading profit in USD':'Verified normal house wins'}</small>{v.state==='draft'?<p>Scoring has not started.</p>:!v.available?<p>Data unavailable. Try again shortly.</p>:model.boards[category].length?<ol>{model.boards[category].map((r,i)=><li key={`${r.rank}-${i}`}><span>#{r.rank} {r.name}</span><b>{category==='roi'?`${r.score.toFixed(2)}%`:category==='profit'?`$${r.score.toFixed(2)}`:r.score}</b></li>)}</ol>:<p>No verified rankings to show yet.</p>}<small>{connected&&v.categories[category].score!==null?`Your score: ${v.categories[category].score} · Rank ${v.categories[category].rank??'pending'}`:'Connect your wallet on the landing page to check your own status.'}</small></section>)}</div><div className={css.actions}><a className={css.primary} href='/bots/workshop?view=earn'>My eligibility & entry →</a><button onClick={()=>void model.refresh()}>Refresh results</button></div><footer className={css.footer}><a href='/bots/start'>← Back to setup</a><a href='/bots/rules'>Rules & prize breakdown</a></footer></main>
}
