import type { SubdomainConfig, SubdomainKey } from "@/types";

export const SUBDOMAINS: Record<SubdomainKey, SubdomainConfig> = {
  eth: {
    key: "eth",
    label: "Ethereum",
    description: "Deep dives into Ethereum: smart contracts, EIPs, tooling, and the roadmap.",
    accentColor: "blue",
    accentHex: "#3b9eff",
    glowHex: "rgba(59,158,255,0.15)",
    emoji: "⬡",
    gradientFrom: "#0d2d4d",
    gradientTo: "#0a0a0f",
  },
  sol: {
    key: "sol",
    label: "Solana",
    description: "Solana programs, SPL tokens, speed, and the Solana ecosystem explained.",
    accentColor: "green",
    accentHex: "#00e5a0",
    glowHex: "rgba(0,229,160,0.15)",
    emoji: "◎",
    gradientFrom: "#00291e",
    gradientTo: "#0a0a0f",
  },
  btc: {
    key: "btc",
    label: "Bitcoin",
    description: "Bitcoin fundamentals, Lightning Network, self-custody, and PoW mining.",
    accentColor: "orange",
    accentHex: "#ff7c35",
    glowHex: "rgba(255,124,53,0.15)",
    emoji: "₿",
    gradientFrom: "#2d1505",
    gradientTo: "#0a0a0f",
  },
  defi: {
    key: "defi",
    label: "DeFi",
    description: "Decentralised finance protocols, yield strategies, AMMs, and risk management.",
    accentColor: "accent",
    accentHex: "#7c6aff",
    glowHex: "rgba(124,106,255,0.15)",
    emoji: "⚡",
    gradientFrom: "#150f33",
    gradientTo: "#0a0a0f",
  },
  staking: {
    key: "staking",
    label: "Staking",
    description: "Validator setup, liquid staking, restaking, and maximising staking rewards.",
    accentColor: "green",
    accentHex: "#00e5a0",
    glowHex: "rgba(0,229,160,0.15)",
    emoji: "🔒",
    gradientFrom: "#00291e",
    gradientTo: "#0a0a0f",
  },
  layer2: {
    key: "layer2",
    label: "Layer 2",
    description: "Rollups, validiums, ZK proofs, and the L2 scaling landscape.",
    accentColor: "blue",
    accentHex: "#3b9eff",
    glowHex: "rgba(59,158,255,0.15)",
    emoji: "⬆",
    gradientFrom: "#0d2d4d",
    gradientTo: "#0a0a0f",
  },
  bridge: {
    key: "bridge",
    label: "Bridges",
    description: "Cross-chain bridges, canonical vs third-party bridges, and bridge security.",
    accentColor: "pink",
    accentHex: "#ff5fa3",
    glowHex: "rgba(255,95,163,0.15)",
    emoji: "🌉",
    gradientFrom: "#2d0f1e",
    gradientTo: "#0a0a0f",
  },
  rwa: {
    key: "rwa",
    label: "Real-World Assets",
    description: "Tokenised treasuries, real estate, commodities, and the RWA on-chain revolution.",
    accentColor: "yellow",
    accentHex: "#ffe135",
    glowHex: "rgba(255,225,53,0.15)",
    emoji: "🏦",
    gradientFrom: "#2d2700",
    gradientTo: "#0a0a0f",
  },
  legal: {
    key: "legal",
    label: "Crypto Legal",
    description: "Regulatory frameworks, DAO legal wrappers, securities law, and compliance.",
    accentColor: "blue",
    accentHex: "#3b9eff",
    glowHex: "rgba(59,158,255,0.15)",
    emoji: "⚖",
    gradientFrom: "#0d1a33",
    gradientTo: "#0a0a0f",
  },
  tax: {
    key: "tax",
    label: "Crypto Tax",
    description: "Capital gains, DeFi tax events, cost basis methods, and jurisdiction guides.",
    accentColor: "red",
    accentHex: "#ff4545",
    glowHex: "rgba(255,69,69,0.15)",
    emoji: "🧾",
    gradientFrom: "#2d0a0a",
    gradientTo: "#0a0a0f",
  },
  security: {
    key: "security",
    label: "Security",
    description: "Wallet security, seed phrase management, smart contract auditing, and avoiding scams.",
    accentColor: "red",
    accentHex: "#ff4545",
    glowHex: "rgba(255,69,69,0.15)",
    emoji: "🛡",
    gradientFrom: "#2d0a0a",
    gradientTo: "#0a0a0f",
  },
  easy: {
    key: "easy",
    label: "Easy Mode",
    description: "Crypto concepts distilled into plain English — no jargon, no fuss.",
    accentColor: "green",
    accentHex: "#00e5a0",
    glowHex: "rgba(0,229,160,0.15)",
    emoji: "✨",
    gradientFrom: "#00291e",
    gradientTo: "#0a0a0f",
  },
  beginner: {
    key: "beginner",
    label: "Beginner Hub",
    description: "Start your crypto journey here: wallets, exchanges, first trades, and staying safe.",
    accentColor: "accent",
    accentHex: "#7c6aff",
    glowHex: "rgba(124,106,255,0.15)",
    emoji: "🚀",
    gradientFrom: "#150f33",
    gradientTo: "#0a0a0f",
  },
  bigmike: {
    key: "bigmike",
    label: "Big Mike",
    description: "Big Mike's no-BS crypto takes: macro analysis, alpha calls, and market structure.",
    accentColor: "orange",
    accentHex: "#ff7c35",
    glowHex: "rgba(255,124,53,0.15)",
    emoji: "🎙",
    gradientFrom: "#2d1505",
    gradientTo: "#0a0a0f",
  },
};

export const VALID_SUBDOMAINS = Object.keys(SUBDOMAINS) as SubdomainKey[];

export function getSubdomainConfig(key: string): SubdomainConfig | null {
  if (VALID_SUBDOMAINS.includes(key as SubdomainKey)) {
    return SUBDOMAINS[key as SubdomainKey];
  }
  return null;
}

export const DEFAULT_SUBDOMAIN: SubdomainKey = "beginner";
