'use client';
import {useEffect,useState} from 'react';
import dynamic from 'next/dynamic';
import AnimatedFighter from '../_game/AnimatedFighter';
import EntryDialog from '../_game/EntryDialog';
import {useWorkshopCompetition} from '../_game/WorkshopCompetition';
import {STRATEGY_LINKS} from '@/lib/bots/strings';
import css from './landing.module.css';
const Wallet=dynamic(()=>import('../_game/WorkshopWalletConnect'),{ssr:false});
const DOC='https://docs.doma.xyz/agentic-commerce/mcp-server';
export default function Landing(){
 const [connect,setConnect]=useState(false),[address,setAddress]=useState(''),[copied,setCopied]=useState(false),[copyError,setCopyError]=useState(false);
 useEffect(()=>{try{setAddress(JSON.parse(sessionStorage.getItem('mk8.wallet-session.v1')||'null')?.address||'')}catch{}},[]);
 const model=useWorkshopCompetition(true,0,!!address),v=model.value;
 const status=v.state==='draft'?'Coming soon':!v.available?'Status unavailable':v.state==='active'?'See entry & eligibility':'Competition closed';
 const signIn=(token:string,wallet:string)=>{sessionStorage.setItem('mk8.wallet-session.v1',JSON.stringify({token,address:wallet}));setAddress(wallet);setConnect(false)};
 return <main className={css.page}>
  <header className={css.nav}><a href='/bots/start' className={css.brand}>MODEL <b>KOMBAT</b><small>A DOMA GAME</small></a><nav aria-label='Main navigation'><a href='#steps'>How it works</a><a href='/bots/leaderboard'>Leaderboards</a><button onClick={()=>setConnect(true)}>{address?`${address.slice(0,6)}…${address.slice(-4)}`:'Connect wallet'}</button></nav></header>
  <section className={css.hero}><div><p className={css.eyebrow}>DOMA TRADING. ROBOT BATTLES. YOUR NEXT MOVE.</p><h1>Trade smart.<br/><em>Fight for fun.</em></h1><p className={css.lead}>Set up your trading. Track your results.<br/>Build a robot and take it into the ring.</p><div className={css.actions}><a className={css.primary} href='#steps'>Get started ↓</a><a href='/bots/workshop?view=garage&entry=landing'>Play the game →</a></div><small>Free robot. No trading required to play.</small></div><div className={css.heroArt}><AnimatedFighter style='tank'/><span>Small robots. Big fight energy.</span></div></section>
  <section className={css.prize} aria-label='Competition prizes'><div><span>{status}</span><strong>$2,000</strong><small>Total cash prize pool</small></div><p><b>$800</b> ROI %<br/><small>Trading return</small></p><p><b>$800</b> Profit $<br/><small>Realized profit</small></p><p><b>$400</b> Battles<br/><small>Verified house wins</small></p><a href='/bots/rules'>Eligibility & rules ↗</a></section>
  <p className={css.notice}>{v.state==='draft'?'Start date to be announced. Prelaunch trades and fights do not count.':!v.available?'Competition status is unavailable. Do not assume entry or scoring has started.':'Check your entry, dates and verified eligibility on the leaderboard.'} All cash prizes require verified Strategy trading on three distinct days per week; both weeks for final prizes. Prizes are not guaranteed.</p>
  <section id='steps' className={css.steps}><div className={css.sectionTitle}><p className={css.eyebrow}>FOUR STEPS. ONE WALLET.</p><h2>Here’s how it works.</h2></div>
   <article><span className={css.number}>01</span><div><h3>Connect your wallet here.</h3><p>Use the same wallet you trade with on Doma. Sign a free message to identify your account.</p><button onClick={()=>setConnect(true)}>{address?'Wallet connected · Manage':'Connect wallet →'}</button><small>This sign-in does not approve spending or enter the competition.</small></div></article>
   <article><span className={css.number}>02</span><div><h3>Choose how you trade.</h3><div className={css.methods}><section><b>Doma Strategies</b><p>Choose a ready-made Strategy, set its trading rules and budget, then review permissions before starting.</p><a href={STRATEGY_LINKS.doma} target='_blank' rel='noopener noreferrer'>Open Strategies ↗</a></section><section><b>Doma MCP · your AI assistant</b><p>Add Doma’s MCP URL in your AI app. Ask it to check the network and quote a trade first. Authorize trading separately with a budget you choose.</p><button onClick={async()=>{try{await navigator.clipboard.writeText(STRATEGY_LINKS.mcp);setCopied(true);setCopyError(false)}catch{setCopyError(true)}}}>{copied?'Copied!':'Copy MCP URL'}</button><code>{STRATEGY_LINKS.mcp}</code>{copyError&&<small role='status'>Copy the address shown above.</small>}</section></div><div className={css.links}><a href={`${DOC}/connect`} target='_blank' rel='noopener noreferrer'>Setup guide ↗</a><a href={`${DOC}/authorization`} target='_blank' rel='noopener noreferrer'>Budgets & permissions ↗</a><a href={`${DOC}/tools`} target='_blank' rel='noopener noreferrer'>Current tools ↗</a><a href="https://app.doma.xyz/help/strategies-custom-trading-through-mcp" target="_blank" rel="noopener noreferrer">Custom Strategies guide ↗</a></div><small>Trading uses real funds and can lose money. Limit orders have separate token allowances. Connecting MCP alone does not satisfy Strategy-day eligibility.</small></div></article>
   <article><span className={css.number}>03</span><div><h3>Track your rewards.</h3><p>Three boards: ROI %, realized profit $, and battle points. See your verified activity, eligibility and provisional rank.</p><a href='/bots/leaderboard'>Open leaderboards →</a><small>More volume alone does not mean a better rank. Missing or pending data is labelled.</small></div></article>
   <article><span className={css.number}>04</span><div><h3>Play the game!</h3><p>Start with 250 game coins for your first robot. Choose a style, give it a name, then fight to earn coins for your next build.</p><a className={css.primary} href='/bots/workshop?view=garage&entry=landing'>Build. Battle. Make it yours. →</a><small>Workshop fights earn game coins within the daily limit. Trading rewards are tracked separately and cannot currently be spent on workshop parts. Game coins have no cash-out value.</small></div></article>
  </section><footer className={css.footer}><span>MODEL KOMBAT · A DOMA GAME</span><a href='/bots/rules'>Competition rules</a><a href='/bots/privacy'>Privacy</a><a href='/bots/terms'>Terms</a></footer>
  {connect&&<EntryDialog title='One wallet. Your progress.' onClose={()=>setConnect(false)}><Wallet onConnected={signIn}/></EntryDialog>}
 </main>
}
