"use client";
import {DISCOVERIES,type DiscoveryId} from '@/lib/chef/diner/decor-discoveries';
import {RestaurantProjectPanel} from './RestaurantProject';
import {CrewCards} from './PersonalTouches';
import { useState } from "react";
import { ConnectButton } from '@rainbow-me/rainbowkit';
import { useDinerAccess } from './DinerAccess';
import { BETA_RESET_NOTICE, BETA_SAVE_NOTICE } from './beta-access';
import { DINER_RULES, canVisitRestaurant, canCancelDinerRun, dinerRates, equipmentTierCap, runStrikeLimit, staffSlots, truckMenuCapacity, recipeEquipmentNeeded, type DinerCommand, type DinerState } from "@/lib/chef/diner/progression";
import { unlockedTruckHelpers } from '@/lib/chef/diner/service-level';
import { roundHelperCapacity } from '@/lib/chef/diner/round-staff';
import {CustomersPanel} from './CustomersPanel';
import {routeAccess} from '@/lib/chef/diner/routes';
import { TRUCK_EQUIPMENT, EQUIPMENT_BY_ID, RECIPES, RECIPE_BY_ID, ROUTES, TRUCK_TIERS } from "@/lib/chef/diner/content";
import { COSMETICS } from "@/lib/chef/diner/collections";
import type { SyncStatus, DinerSession } from './diner-sync';
import type { DinerSocialCommand } from '@/lib/chef/diner/social';
import FriendsPanel from './FriendsPanel';
import { DinerModal } from "./DinerModal";
import { DinerIcon } from "./DinerIcon";
import { ModelIcon } from "./ModelIcon";
import { RouteMap } from "./RouteMap";
import { HomeFinishes, RegularBook, StaffRitual, TruckExtras, TruckHelpers, PassportBook } from "./CollectionPanels";
import { HomeGrowth } from './HomeGrowth';
import type { RoomFinishChoice } from './RoomFinishPreview';
import { renovationRequirements } from '@/lib/chef/diner/renovation';
import { STAGE_COPY } from './RenovationPreview';
import type { FinishChoice } from './FinishPreview';
import { FurnishingCatalog } from './FurnishingCatalog';
import { RecipeBook } from './RecipeBook';
import { RecipeUpgrade } from './RecipeUpgrade';
import { equipmentUpgradeDescription, equipmentDisplayName, recipeEquipmentHint } from './RecipeLearning';
import { cookingGuideMenu, cookingGuideRecipe, cookingGuideSteps } from './cooking-guide';
import { PantryShelf } from './PantryShelf';
import css from "./diner.module.css";
import {ProblemReportPanel} from './ProblemReport';
import {ControlsPanel,ControlHelp} from './ControlPreferences';
import {RankedRally} from './RankedRally';
import {GroupArrange} from './GroupArrange';
import {RoomStyleStudio} from './RoomStyleStudio';
import {RestaurantPostcard} from './RestaurantPostcard';
import {NextGoal,GoalChoices,EarnedDisplays,RestaurantProfile} from './ProgressRewards';
import {CollectionRestaurant,type ClaimCollectionRoom} from './CollectionRestaurant';
import type {DomainId} from '@/lib/chef/diner/domain-worlds';

export interface PanelProps {collectionDomain?:DomainId;onCollectionRoom?:ClaimCollectionRoom;editCollectionPieces?:()=>void;collectionEquipment?:()=>void;}

export type PanelName='collectionRestaurant'|'community'|'project'|'report'|'postcard'|'firstShift'|'ranked'|'groupArrange'|'styleBundle'|'roomStyles'|'people'|'scrapbook'|'profile'|'goals'|'recipes'|'pantry'|'catalogue'|'staff'|'collections'|'settings'|'till'|'map'|'garage'|'truckMenu'|'customers'|'friends'|'help'|'finishes'|'grow'|'name'|'rallyExit'|'tripExit';
export interface PanelProps {findFurnishing?:(id:string)=>void;onCommunityPlaque?:(session:DinerSession)=>Promise<void>;communityReady?:boolean;quietView?:boolean;setQuietView?:(value:boolean)=>void;crewId?:string|null;reportsEnabled?:boolean;onRallyTrophy?:(session:DinerSession)=>Promise<void>;atmosphere?:import('./presentation').Atmosphere;quality?:import('./presentation').Quality;setAtmosphere?:(value:import('./presentation').Atmosphere)=>void;setQuality?:(value:import('./presentation').Quality)=>void;panel:PanelName;helpRecipeId?:string|null;state:DinerState;send:(command:DinerCommand)=>boolean;close:()=>void;open:(name:PanelName,recipeId?:string)=>void;place:(equipmentId:string)=>void;start:(route:string,assistance?:'cosy'|'regular')=>void;edit:()=>void;sound:boolean;setSound:(on:boolean)=>void;musicOn:boolean;setMusicOn:(on:boolean)=>void;musicVolume:number;setMusicVolume:(value:number)=>void;effectsVolume:number;setEffectsVolume:(value:number)=>void;paint:string;setPaint:(color:string)=>void;onShare:()=>void;syncStatus:SyncStatus;localSaveError?:string|null;serverEnabled:boolean;connect:()=>Promise<boolean>;read:(path:string,body?:unknown)=>Promise<unknown>;social:(command:DinerSocialCommand)=>Promise<unknown>;acceptSession:(session:DinerSession)=>Promise<unknown>;signOut?:()=>Promise<boolean>;editRoom:()=>void;previewRenovation:()=>void;previewRoomFinish:(choice:RoomFinishChoice)=>void;previewFinish:(choice:FinishChoice)=>void;}
const wrapColors:Record<typeof COSMETICS.wraps[number],string>={tomato:'#bd6a50',buttercream:'#eacb85',sage:'#456d58',sky:'#8cabb8'};
export const money=(n:number)=>Math.floor(n).toLocaleString('en-US');
function SmallIcon({kind,label,tier=1}:{kind:string;label:string;tier?:number}){return <ModelIcon kind={kind} tier={tier} label={label} size={52}/>;}

export default function DinerPanels(props:PanelProps){
  const {panel,state,send,close,open,place,start,edit}=props;
  const access=useDinerAccess(),beta=access?.mode==='beta';
  const [tab,setTab]=useState('all'),[name,setName]=useState(state.home.name),[helpRecipe,setHelpRecipe]=useState(()=>cookingGuideRecipe(state,props.helpRecipeId));
  if(panel==='tripExit')return <DinerModal title="End this trip early?" onClose={close}>
    <p className={css.panelLead}>Bank half your carried earnings after this lunch’s helper wages. Your equipment, recipes and restaurant stay yours.</p>
    <p>No completion bonus is awarded for this lunch.</p>
    <div className={css.actions}><button className={css.primary} onClick={close}>Keep cooking</button><button className={css.button} onClick={()=>{if(send({type:'abandonService'}))close();}}>End trip & return home</button></div>
  </DinerModal>;
  if(panel==='project')return <RestaurantProjectPanel state={state} send={send} close={close} open={open} place={place}/>;
  if(panel==='report')return <ProblemReportPanel close={close}/>;
  if(panel==='postcard')return <RestaurantPostcard state={state} close={close}/>;
  if(panel==='firstShift')return <DinerModal title="How would you like your first trip?" eyebrow="Downtown · choose your pace" onClose={close}>
    <p className={css.panelLead}>Both modes begin with one guided order. Learn to cook, serve and wash a plate before the rest of lunch begins.</p>
    <div className={css.grid}>
      <article className={css.card}><div className={css.cardBody}><span className={css.eyebrow}>Recommended for learning</span><h3>Cosy</h3><p>Guests are 50% more patient, and you can make five mistakes instead of three. Earn 20% fewer truck coins; recipes, equipment and permanent rewards stay yours.</p><button className={css.primary} onClick={()=>start('downtown','cosy')}>Start a Cosy trip</button></div></article>
      <article className={css.card}><div className={css.cardBody}><h3>Regular</h3><p>Normal patience, three mistakes and full truck earnings. A little more pressure once the guided order is finished.</p><button className={css.button} onClick={()=>start('downtown','regular')}>Start a Regular trip</button></div></article>
    </div>
    <p className={css.notice}>Cosy is available on Downtown only. Music Festival and every later route use Regular rules. You can change your Downtown preference in Settings between trips.</p>
  </DinerModal>;
  if(panel==='community')return props.communityReady&&state.career.services>=1&&(!state.run||canVisitRestaurant(state))?<RankedRally mode='community' close={close} onTrophy={props.onCommunityPlaque} onPlace={()=>place('prestige_picnic_plaque')}/>:<DinerModal title='Community feast' onClose={close}><p>Return between stops after your first completed lunch.</p></DinerModal>;
  if(panel==='ranked')return <RankedRally close={close} onTrophy={props.onRallyTrophy}/>;
  if(panel==='collectionRestaurant')return <CollectionRestaurant state={state} send={send} close={close} decorate={props.editCollectionPieces??props.editRoom} reviewDomain={props.collectionDomain} claim={props.collectionDomain?props.onCollectionRoom:undefined} equipment={props.collectionEquipment}/>;
  if(panel==='groupArrange')return <GroupArrange state={state} send={send} close={close}/>;
  if(panel==='styleBundle'||panel==='roomStyles')return <RoomStyleStudio state={state} send={send} close={close} reward={panel==='styleBundle'}/>;
  if(panel==='goals')return <DinerModal title="What shall we work toward?" onClose={close}><GoalChoices state={state} send={send} open={open}/></DinerModal>;
  if(panel==='profile')return <DinerModal title="Your restaurant profile" onClose={close}><RestaurantProfile state={state} share={props.onShare} rename={()=>open('name')}/><button className={css.button} onClick={()=>open('ranked')}>View my verified rally results</button></DinerModal>;
  if(panel==='people')return <DinerModal title="People make the place" onClose={close}><div className={css.grid}>{[{id:'scrapbook',name:'Regulars & scrapbook',detail:'Stories, requests, destinations and earned displays.'},{id:'customers',name:'Customer audiences',detail:'Choose who comes to your restaurant.'},{id:'friends',name:'Friends',detail:'Visits, gifts and ways to share.'},{id:'profile',name:'Your profile',detail:'Your name, style, achievements and postcards.'},{id:'staff',name:'Your crew',detail:'Your restaurant’s cooks, cashiers and servers.'}].map(p=><button className={css.button} key={p.id} onClick={()=>open(p.id as PanelName)}><strong>{p.name}</strong><span>{p.detail}</span></button>)}</div></DinerModal>;
  if(panel==='customers')return <DinerModal title="Who’s coming for lunch?" eyebrow="Your restaurant audience" onClose={close}><CustomersPanel state={state} send={send}/></DinerModal>;
  if(panel==='friends'&&beta)return <DinerModal title="Share your little diner" eyebrow="Open beta" onClose={close}><div className={css.empty}><DinerIcon name="friends" size={42}/><h3>A postcard for your friends</h3><p>Friend visits, invitations and trading aren&apos;t available in this beta yet. You can still save a postcard of your restaurant to share.</p></div><div className={css.actions}><button className={css.primary} onClick={props.onShare}>Save a postcard</button><button className={css.button} onClick={()=>open('name')}>Name your diner</button></div></DinerModal>;
  if(panel==='friends')return <DinerModal title="Your little street" eyebrow="Good neighbours, good food" onClose={close} wide><FriendsPanel state={state} syncStatus={props.syncStatus} serverEnabled={props.serverEnabled} connect={props.connect} read={props.read} social={props.social} acceptSession={props.acceptSession} signOut={props.signOut} onNameDiner={()=>open('name')}/></DinerModal>;
  if(panel==='recipes')return <DinerModal title="Menu & recipes" eyebrow="Your restaurant" onClose={close} wide>
    <RecipeBook state={state} initialRecipeId={props.helpRecipeId} send={send} openPantry={()=>open('pantry')}/>
  </DinerModal>;
  if(panel==='pantry')return <DinerModal title="Upgrade ingredients" eyebrow="Daily ingredient shop" onClose={close} wide>
    <PantryShelf state={state} send={send} close={close} openRecipes={()=>open('recipes')}/>
  </DinerModal>;
  if(panel==='finishes')return <DinerModal title="The little things make it yours" eyebrow="Finishes & keepsakes" onClose={close} wide><HomeFinishes state={state} send={send} place={place} onPreviewFinish={(slot,id)=>props.previewFinish({slot,id})}/></DinerModal>;
  if(panel==='grow')return <DinerModal title="A little room to grow" eyebrow="Build a busier, better diner" onClose={close}><HomeGrowth state={state} send={send} open={open} preview={props.previewRenovation}/></DinerModal>;
  if(panel==='catalogue')return <DinerModal title="Decorate" eyebrow="Your restaurant, your way" onClose={close} roomVisible footer={<><button className={css.button} onClick={()=>open('groupArrange')}><DinerIcon name="decorate"/>Move your furniture</button><button className={css.primary} onClick={close}>Done</button></>}>
    <div className={css.actions}><button className={css.button} onClick={()=>props.setQuietView?.(!props.quietView)}>{props.quietView?'Quiet view · switch to Live':'Live view · switch to Quiet'}</button><small>Restaurant earnings continue.</small></div>{state.home.roomPlan?.modules.some(m=>(m.condition??100)<40)&&<p className={css.notice}>Your facilities still need care. Quiet view does not clean or repair them.</p>}
    {(props.collectionDomain||Object.keys(state.domainRooms?.earned??{}).length>0)&&<button className={css.button} onClick={()=>open('collectionRestaurant')}>Collection restaurants</button>}
    <FurnishingCatalog state={state} send={send} place={place} moreStyle={()=>open('finishes')} onGrow={()=>open('grow')} onCook={()=>open('map')} onFind={props.findFurnishing} onBuild={props.editRoom} onPreviewRoomFinish={props.previewRoomFinish} onPreviewFinish={(slot,id)=>props.previewFinish({slot,id})}/>
  </DinerModal>;
  if(panel==='staff')return <DinerModal title="The people who make it" eyebrow="Your diner crew" onClose={close}>
    <CrewCards state={state} send={send} selected={props.crewId}/><p className={css.panelLead}>Chefs cook. Cashiers take burger-shop orders. Servers deliver food and clear dishes. Restaurant crew are permanent hires. Truck help is hired separately for each lunch.</p><div className={css.gridTwo+' '+css.grid}>{(['chef','waiter'] as const).map(role=><article className={css.card} key={role}><div className={css.cardArt}><ModelIcon kind={role} label={role}/></div><div className={css.cardBody}><h3>{role==='chef'?'Kitchen crew':'Dining crew'}</h3><p>{state.home.staff[role==='chef'?'chefs':'waiters']} on your team</p><button className={css.button} disabled={(state.home.staff.chefs+state.home.staff.waiters+(state.home.staff.cashiers??0))>=staffSlots(state)||state.coins<500} onClick={()=>send({type:'hire',role})}>Hire · 500 coins</button></div></article>)}</div><p className={css.notice}>{(state.home.staff.chefs+state.home.staff.waiters+(state.home.staff.cashiers??0))} / {staffSlots(state)} crew slots used. Restaurant levels make room for more staff. </p><StaffRitual state={state} send={send}/>
  </DinerModal>;
  if(panel==='till'){const rates=dinerRates(state),next=renovationRequirements(state);return <DinerModal title="A good little business" eyebrow="The restaurant keeps going" onClose={close}>
    <div className={css.summary}><DinerIcon name="coin" size={35}/><p className={css.summaryAmount}>{money(state.home.till.coins)}</p><p className={css.small}>coins waiting in your till</p><button className={css.primary} disabled={state.home.till.coins<1&&state.home.till.reputation<1} onClick={()=>send({type:'collectTill'})}>Collect coins & reputation</button></div>
    <div className={css.split}><div className={css.statBox}><span className={css.eyebrow}>At your current layout</span><strong>{money(rates.coins)} / hour</strong><span className={css.small}>Your current bottleneck: {rates.bottleneck=== 'arrivals'?'finding more customers':rates.bottleneck==='kitchen'?'cooking capacity':rates.bottleneck==='waiters'?'serving capacity':'available seats'}.</span></div><div className={css.statBox}><span className={css.eyebrow}>While you&apos;re away</span><strong>{money(rates.coins*.6)} / hour</strong><span className={css.small}>Up to eight hours in the till. Facilities wear with use. A quick clean or repair restores service.</span></div></div>
    <h3 className={css.sectionTitle}>Room to grow</h3><div className={css.row}><DinerIcon name="home"/><div><h3>{state.home.w} × {state.home.h} diner</h3><p>{next.stage?`Next: ${STAGE_COPY[next.stage].name} · ${money(next.cost)} coins`:'Your full-size restaurant is open.'}</p></div><button className={css.button} onClick={()=>open('grow')}>Renovations</button></div>
  </DinerModal>;}
  if(panel==='map')return <DinerModal title={state.run?'Your route':'Take the truck out'} eyebrow={state.run?`${state.run.routeId.replaceAll('_',' ')} · ${money(state.run.haul)} carried coins`:undefined} onClose={close} wide footer={state.run&&(!state.run.position||canCancelDinerRun(state))?<>{canVisitRestaurant(state)&&<button className={css.button} onClick={()=>{if(send({type:state.run?.location==='home'?'resumeTrip':'visitRestaurant'}))close();}}>{state.run.location==='home'?'Resume trip':'Visit restaurant'}</button>}<button className={css.button} onClick={()=>{if(send({type:'goHome'}))close();}}>{canCancelDinerRun(state)?'Back home':`Bank ${money(state.run.haul)} & end trip`}</button></>:undefined}>
    {state.run?<>{state.run.location==='home'&&<p className={css.notice}>Resume your parked trip to choose a stop. Your carried coins are still unbanked.</p>}{(()=>{const run=state.run,gift=run?.gifts?.[run.visited.at(-1)??''],offer=gift?.offers.find(o=>o.id===gift.claimed);return offer?.kind==='recipe'?<div className={css.actions}><span>New recipe: {RECIPE_BY_ID[offer.target].name}</span><button className={css.button} onClick={()=>open('truckMenu')}>Add to next menu</button></div>:null;})()}<RouteMap state={state} strikeLimit={runStrikeLimit(state)} run={state.run} choose={id=>{if(send({type:'chooseNode',nodeId:id}))close();}}/></>:<>{ROUTES.map(route=><div className={css.routeCard} key={route.id}><DinerIcon name="truck" size={40}/><div><h3>{route.name}</h3><p>{route.description}</p><small>{routeAccess(state,route.id)??(state.collections.routeWins.includes(route.id)?'Finale completed':'Eight lunches · choose your road')}</small></div><button className={css.primary} disabled={!!routeAccess(state,route.id)} onClick={()=>start(route.id)}>{routeAccess(state,route.id)?'Locked':'Travel there'}</button></div>)}<details><summary>Practice & competitions</summary><div className={css.actions}><button className={css.button} onClick={()=>{if(send({type:'startPractice'}))close();}}>Practice cooking</button><button className={css.button} onClick={()=>{if(send({type:'replayLesson'}))close();}}>Replay the lesson</button><button className={css.button} onClick={()=>{if(send({type:'startRally'}))close();}}>Weekly rally practice</button><button className={css.button} onClick={()=>open('ranked')}>Weekly rankings</button>{props.communityReady&&state.career.services>=1&&<button className={css.button} onClick={()=>open('community')}>Community feast</button>}</div></details></>}
  </DinerModal>;
  if(panel==='truckMenu')return <DinerModal title="What are we cooking?" eyebrow="A short menu, or a bigger challenge" onClose={close}>
    <p className={css.panelLead}>{(state.run?.menu??state.truckConfig.menu).length>truckMenuCapacity(state)?`Your existing ${(state.run?.menu??state.truckConfig.menu).length}-recipe menu is kept. New menus allow up to ${truckMenuCapacity(state)} recipes; grow your truck to add more.`:`Up to ${truckMenuCapacity(state)} recipes in this truck. More variety means more to juggle.`} Buying a recipe never selects it for you. Arrange its equipment and supplies before opening.</p><div className={css.grid}>{RECIPES.filter(r=>state.recipes[r.id]).map(recipe=>{
      const menu=state.run?.menu??state.truckConfig.menu,chosen=menu.includes(recipe.id),missing=recipeEquipmentNeeded(state,recipe.id),full=menu.length>=truckMenuCapacity(state),last=chosen&&menu.length===1;
      return <article className={css.card} key={recipe.id}><div className={css.cardArt}><ModelIcon kind="food" recipeId={recipe.id} label={recipe.name}/></div><div className={css.cardBody}><h3>{recipe.name}</h3><p>{recipe.steps.map(s=>s.label).join(' → ')}</p><p>{recipeEquipmentHint(state,recipe.id)}</p><button className={chosen?css.softButton:css.button} disabled={last||!chosen&&(missing.length>0||full)} onClick={()=>send({type:'setTruckMenu',recipeIds:chosen?menu.filter(id=>id!==recipe.id):[...menu,recipe.id]})}>{last?'On the menu · keep one dish':chosen?'Remove from menu':missing.length?'Get missing equipment':full?'Menu full':'Add to menu'}</button></div></article>;
    })}</div><p className={css.small}>The first Downtown market follows lunch three and guarantees fries and a fryer for 300 coins together. Later markets depend on your chosen path. You can keep a recipe while looking for its machine.</p>
  </DinerModal>;
  if(panel==='garage')return <DinerModal title="Your little adventure" eyebrow="The garage" onClose={close}>
    <div className={css.routeCard}><DinerIcon name="truck" size={47}/><div><h3>Tier {state.truckTier} food truck</h3><p>{TRUCK_TIERS[state.truckTier].w} × {TRUCK_TIERS[state.truckTier].h} kitchen · {state.truckConfig.tables.reduce((sum,table)=>sum+table.capacity,0)} seats arranged · {state.run&&state.run.mapVersion<6?unlockedTruckHelpers(state):roundHelperCapacity(state)} helper slots available</p></div></div><p className={css.small}>Downtown, Festival and Business Center finales grow your truck. Collect only the recipes you want to cook.</p>
    <p className={css.small}>Choose paid help in lunch preparation: 20% of food and tips per helper. Restaurant hiring is separate.</p>{state.run&&state.run.mapVersion<6&&<TruckHelpers state={state} send={send}/>}<h3 className={css.sectionTitle}>A fresh coat of paint</h3><div className={css.swatches}>{COSMETICS.wraps.map(id=><button key={id} aria-label={`${id[0].toUpperCase()+id.slice(1)} truck wrap`} aria-pressed={state.cosmetics.wrap===id} title={id[0].toUpperCase()+id.slice(1)} className={`${css.swatch} ${state.cosmetics.wrap===id?css.swatchSelected:''}`} style={{background:wrapColors[id]}} onClick={()=>send({type:'setCosmetic',slot:'wrap',id})}/>)}</div>
    <h3 className={css.sectionTitle}>Your truck&apos;s hello</h3><div className={css.tabs} role="group" aria-label="Truck horn">{COSMETICS.horns.map(id=><button key={id} aria-pressed={state.cosmetics.horn===id} className={state.cosmetics.horn===id?css.tabActive:''} onClick={()=>send({type:'setCosmetic',slot:'horn',id})}>{id[0].toUpperCase()+id.slice(1)}</button>)}</div><p className={css.small}>Rex likes a friendly or jazzy welcome when his favourite burger is on the menu.</p>
    <div className={css.actions}><button className={css.button} onClick={()=>open('truckMenu')}><DinerIcon name="book"/>Truck menu</button><button className={css.button} onClick={props.onShare}><DinerIcon name="gift"/>Save a postcard</button></div>
    <h3 className={css.sectionTitle}>In your garage</h3><div className={css.list}>{TRUCK_EQUIPMENT.filter(e=>state.equipment[e.id]?.truckOwned).map(e=><div className={css.row} key={e.id}><SmallIcon kind={e.id} tier={state.equipment[e.id].tier} label={equipmentDisplayName(e.id,state.equipment[e.id].tier)}/><div><h3>{equipmentDisplayName(e.id,state.equipment[e.id].tier)}</h3><p>Tier {state.equipment[e.id].tier} · {equipmentUpgradeDescription(e.id,state.equipment[e.id].tier)}</p></div></div>)}</div><p className={css.tiny}>Preparation upgrades reach tier {equipmentTierCap(state)} at your restaurant level. Roadside markets can offer an early tier-two find.</p><TruckExtras state={state} send={send} showHelpers={false}/>
  </DinerModal>;
  if(panel==='collections'||panel==='scrapbook')return <DinerModal title="Restaurant scrapbook" eyebrow="The people and places that made your restaurant" onClose={close}>
    {state.personal?.discoveries.length? <details><summary>Decorating discoveries · {state.personal.discoveries.length}/4</summary>{state.personal.discoveries.map(id=><p key={id}><strong>{DISCOVERIES[id as DiscoveryId].name}</strong> · {DISCOVERIES[id as DiscoveryId].hint}</p>)}</details>:null}<EarnedDisplays state={state} send={send} place={place}/><div className={css.tabs}>{['all','regulars','passport','trophies'].map(t=><button key={t} className={tab===t?css.tabActive:''} onClick={()=>setTab(t)}>{t==='all'?'Your favourites':t[0].toUpperCase()+t.slice(1)}</button>)}</div>
    {(tab==='all'||tab==='regulars')&&<RegularBook state={state} send={send} openRecipes={()=>open('recipes')} openDecor={()=>open('catalogue')} openCook={()=>open('map')}/>}
{(tab==='all'||tab==='passport')&&<PassportBook state={state} openRecipes={()=>open('recipes')} openCook={()=>open('map')}/>}
    {(tab==='all'||tab==='trophies')&&<><h3 className={css.sectionTitle}>A shelf for the good days</h3><div className={css.list}>{state.collections.trophies.map(t=><div className={css.row} key={t}><DinerIcon name="star" size={32}/><div><h3>{t.replace(/[:_]/g,' ')}</h3><p>{beta?'Earned by playing during the beta.':'Earned by playing. Always yours.'}</p></div></div>)}</div>{!state.collections.trophies.length&&<p className={css.small}>Master a recipe or clear a finale to earn something for this shelf.</p>}</>}
  </DinerModal>;
  if(panel==='name')return <DinerModal title="Name your diner" eyebrow="Make it yours" onClose={close} footer={<><button className={css.button} onClick={close}>Cancel</button><button className={css.primary} onClick={()=>{if(send({type:'settings',name}))close();}}>Save name</button></>}><label className={css.field}>Restaurant name<input autoFocus aria-label="Restaurant name" maxLength={24} value={name} onChange={event=>setName(event.target.value)} onKeyDown={event=>{if(event.key==='Enter'&&send({type:'settings',name}))close();}}/></label><p className={css.small}>Free to change anytime · up to 24 characters. {beta?'Your name appears on your restaurant and postcards.':'Friends see this name when you publish your diner. Your friend code stays the same.'}</p></DinerModal>;
  if(panel==='settings')return <DinerModal title="Settings" eyebrow="Make yourself comfortable" onClose={close}>
    <div className={css.row}><DinerIcon name="home"/><div><h3>{props.localSaveError?'Not saving on this device':props.syncStatus==='guest'?'Saved on this device':props.syncStatus==='offline'?'Waiting for a connection':props.syncStatus==='saving'?'Saving your diner…':'Your connected diner'}</h3><p>{props.localSaveError??(beta?BETA_SAVE_NOTICE:props.syncStatus==='guest'?'This development sandbox is saved only in this browser.':'Your wallet is your account. Sign-in uses a message signature, with no transaction or gas fee.')}</p></div>{props.serverEnabled&&<button className={css.button} disabled={props.syncStatus==='connecting'||props.syncStatus==='saved'||props.syncStatus==='saving'} onClick={()=>void props.connect()}>{props.syncStatus==='offline'?'Retry':'Reconnect account'}</button>}</div>
    {beta&&<><p className={css.notice}><strong>Beta · </strong>{BETA_RESET_NOTICE}</p><ConnectButton showBalance={false} chainStatus="none" accountStatus="address"/></>}
    <label className={css.field}>Your diner&apos;s name<input maxLength={24} value={name} onChange={event=>setName(event.target.value)}/></label><button className={css.button} onClick={()=>send({type:'settings',name})}>Save name</button>
    <ControlsPanel/>{props.reportsEnabled&&<button className={css.button} onClick={()=>open('report')}>Report a problem</button>}<h3 className={css.sectionTitle}>Play your way</h3><div className={css.row}><DinerIcon name="heart"/><div><h3>Downtown: Cosy mode</h3><p>50% more patience, five mistakes and 20% fewer truck coins. Choose between trips. Festival and every later route use Regular rules.</p></div><button className={state.settings.cosy?css.softButton:css.button} disabled={!!state.run} onClick={()=>send({type:'settings',cosy:!state.settings.cosy})}>{state.settings.cosy?'On':'Off'}</button></div><div className={css.row}><DinerIcon name={props.sound?'sound':'mute'}/><div><h3>Kitchen sounds</h3><p>A little sizzle, a little celebration.</p></div><button className={css.button} onClick={()=>props.setSound(!props.sound)}>{props.sound?'On':'Off'}</button></div>
    <label className={css.field}>Sound effects · {Math.round(props.effectsVolume*100)}%<input aria-label="Sound effects volume" type="range" min="0" max="1" step="0.05" value={props.effectsVolume} onChange={event=>props.setEffectsVolume(Number(event.target.value))}/></label>
    <div className={css.row}><DinerIcon name={props.musicOn?'sound':'mute'}/><div><h3>A little music</h3><p>Café Swing at home. Sunlit Groove on the road.</p></div><button className={css.button} onClick={()=>props.setMusicOn(!props.musicOn)}>{props.musicOn?'On':'Off'}</button></div>
    <label className={css.field}>Music · {Math.round(props.musicVolume*100)}%<input aria-label="Music volume" type="range" min="0" max="1" step="0.05" value={props.musicVolume} onChange={event=>props.setMusicVolume(Number(event.target.value))}/></label>
    <h3 className={css.sectionTitle}>The view from your window</h3><div className={css.tabs} role="group" aria-label="Atmosphere">{(['day','evening','rain'] as const).map(value=><button key={value} aria-pressed={(props.atmosphere??'day')===value} className={props.atmosphere===value?css.tabActive:''} onClick={()=>props.setAtmosphere?.(value)}>{value==='day'?'Daylight':value==='evening'?'Golden evening':'Rainy windows'}</button>)}</div><p className={css.small}>Just a change of scenery. Weather never changes cooking or patience.</p>
    <label className={css.field}>Graphics quality<select aria-label="Graphics quality" value={props.quality??'auto'} onChange={event=>props.setQuality?.(event.target.value as import('./presentation').Quality)}><option value="auto">Automatic · adapt to this device</option><option value="low">Light · fewer shadows</option><option value="medium">Balanced</option><option value="high">Detailed</option></select></label>
    <button className={css.button} onClick={()=>open('help')}>Cooking guide</button>
  </DinerModal>;
  if(panel==='rallyExit'){
    const finished=state.rally.service&&['complete','failed'].includes(state.rally.service.phase);
    return <DinerModal title="Head home from the rally?" eyebrow="Weekly truck rally" onClose={close} footer={<><button className={css.button} onClick={close}>Stay in the truck</button><button className={css.primary} onClick={()=>{if(send({type:finished?'finishRally':'endRally'}))close();}}>Back home</button></>}>
      <p className={css.panelLead}>{finished?'Your result will be saved before you head home.':'This unfinished attempt will not add a score. Your previous best score stays safe.'}</p><p className={css.small}>Your restaurant, coins and equipment stay yours. You can try the rally again anytime.</p>
    </DinerModal>;
  }
  if(panel==='help')return <DinerModal title="Good food, one step at a time" eyebrow="Your pocket cooking guide" onClose={close}>
    <div className={css.tabs} role="group" aria-label="Recipes for this kitchen">{cookingGuideMenu(state).map(id=><button key={id} aria-pressed={helpRecipe===id} className={helpRecipe===id?css.tabActive:''} onClick={()=>setHelpRecipe(id)}>{RECIPE_BY_ID[id].name}</button>)}</div>
    <div className={css.summary}><ModelIcon kind="food" recipeId={helpRecipe} label={RECIPE_BY_ID[helpRecipe]?.name}/><h3>{RECIPE_BY_ID[helpRecipe]?.name}</h3></div><ol className={css.stepList}>
      {cookingGuideSteps(state,helpRecipe).map((step,i)=><li key={i}>{step}</li>)}
    </ol><p className={css.small}>Prep ingredients before opening to get ahead.</p>
    <ControlHelp/>{!state.run&&!state.rally.service&&<RecipeUpgrade state={state} recipeId={helpRecipe} send={send} openBook={()=>open('recipes',helpRecipe)}/>}
    {props.reportsEnabled&&<button className={css.quietLink} onClick={()=>open('report')}>Still stuck? Report a problem</button>}
  </DinerModal>;
  return <DinerModal title="A place on the street" eyebrow="Good neighbours, good food" onClose={close}><div className={css.empty}><DinerIcon name="friends" size={42}/><p>Your diner is growing a neighbourhood.</p><p className={css.small}>Connected visits use their own diner accounts. Local preview saves stay on this device.</p></div><button className={css.button} onClick={props.onShare}><DinerIcon name="gift"/>Save a restaurant postcard</button></DinerModal>;
}
