"use client";
import dynamic from "next/dynamic";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { createDkSfx, type DkSfx } from "./audio";
import { DECOR_BY_ID } from "@/lib/chef/diner/collections";
import { DINER_RULES, dinerPauseCommand, type DinerCommand, type DinerState, type HomePlacement } from "@/lib/chef/diner/progression";
import { createService, serviceTargetIntent } from "@/lib/chef/diner/service";
import { buildServiceLoadout, makeStation, makeTable } from "@/lib/chef/diner/geometry";
import { EQUIPMENT_BY_ID, INGREDIENT_BY_ID, RECIPE_BY_ID, TRUCK_TIERS } from "@/lib/chef/diner/content";
import type { ServiceState } from "@/lib/chef/diner/types";
import { useDiner } from "./useDiner";
import { useHomeWorld, homeScene } from "./useHomeWorld";
import { serviceScene } from "./scene-adapter";
import type { DinerPerformance, DinerSceneProps } from "./scene-types";
import { DinerIcon } from "./DinerIcon";
import { DinerModal } from "./DinerModal";
import DinerPanels, { money, type PanelName } from "./DinerPanels";
import { ModelIcon } from "./ModelIcon";
import { RoadsideStop } from "./RoadsideStop";
import { HomeInteraction } from "./HomeInteraction";
import { HoldAction } from "./HoldAction";
import { GameEmblem } from "./GameEmblem";
import { ServiceFocus } from './ServiceFocus';
import { homeGestureCommands, type HomeSceneGesture } from "@/lib/chef/diner/home-gesture";
import css from "./diner.module.css";

const DinerScene=dynamic(()=>import('./DinerScene'),{ssr:false,loading:()=> <div className={css.sceneLoading}>Setting the tables…</div>});
const manualService=(state:DinerState|null)=>state?.run?.service??state?.rally?.service??null;
const preferenceKey='street_eats_preview_preferences_v1';
type TruckLayout={stations:{id:string;kind:ServiceState['stations'][number]['kind'];x:number;y:number;facing:0|1|2|3}[];tables:{id:string;x:number;y:number;capacity:2|4;rotation:0|1|2|3}[]};
function truckLayout(service:ServiceState):TruckLayout{return {stations:service.stations.map(({id,kind,x,y,facing})=>({id,kind,x,y,facing})),tables:service.tables.map(({id,x,y,capacity,rotation})=>({id,x,y,capacity,rotation}))};}

export default function DinerClient(){
  const {state,send:dispatch,announce,message,syncStatus,serverEnabled,connect,read,social,acceptSession}=useDiner();
  const homeWorld=useHomeWorld(state);
  const [panel,setPanel]=useState<PanelName|null>(null),[rotation,setRotation]=useState(0),[selected,setSelected]=useState<string|null>(null),[crate,setCrate]=useState(false);
  const [editing,setEditing]=useState<'home'|'truck'|null>(null),[placing,setPlacing]=useState<string|null>(null),[sound,setSound]=useState(true),[paint,setPaint]=useState('#b66751');
  const [summary,setSummary]=useState(false),[ready,setReady]=useState(false),[holding,setHolding]=useState(false),[performance,setPerformance]=useState<DinerPerformance|null>(null);
  const homeOriginal=useRef<HomePlacement[]|null>(null),truckOriginal=useRef<TruckLayout|null>(null),boot=useRef<string|null>(null),seenSummary=useRef<string|null>(null),sfx=useRef<DkSfx|null>(null),lastEvent=useRef(0);
  const stateRef=useRef(state);stateRef.current=state;
  const seenCareReceipts=useRef<Set<string>|null>(null);
  const [worldReward,setWorldReward]=useState<DinerSceneProps['worldReward']>(null);
  const seenParcel=useRef<{day:number;claimed:boolean;pantry:Record<string,number>}|null>(null);
  useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem(preferenceKey)||'{}');if(typeof saved.sound==='boolean')setSound(saved.sound);if(typeof saved.paint==='string'&&/^#[0-9a-f]{6}$/i.test(saved.paint))setPaint(saved.paint);}catch{}setReady(true);},[]);
  useEffect(()=>{if(ready)try{localStorage.setItem(preferenceKey,JSON.stringify({sound,paint}));}catch{}sfx.current?.setMuted(!sound);},[sound,paint,ready]);
  const play=useCallback((name:Parameters<DkSfx['play']>[0])=>{if(!sound)return;sfx.current??=createDkSfx(true);sfx.current.play(name);},[sound]);
  useEffect(()=>()=>sfx.current?.destroy(),[]);
  const send=useCallback((command:DinerCommand)=>{const mapped=command.type==='service'&&stateRef.current?.rally?.service?{type:'rallyService' as const,action:command.action}:command;const okay=dispatch(mapped);if(okay&&['buyOffer','buyHomeEquipment','upgradeRecipe','collectTill','claimCrate','chooseGift'].includes(command.type))play(command.type==='upgradeRecipe'?'unlock':'kaching');return okay;},[dispatch,play]);
  useEffect(()=>{
    if(!state||boot.current===state.seed)return;boot.current=state.seed;setPanel(null);setSummary(false);
  },[state,send]);
  useEffect(()=>{if(state?.lastRun&&seenSummary.current!==state.lastRun.id){seenSummary.current=state.lastRun.id;try{const key=`${preferenceKey}_seen_${state.seed}`;if(localStorage.getItem(key)===state.lastRun.id)return;localStorage.setItem(key,state.lastRun.id);}catch{}setPanel(null);setSummary(true);setEditing(null);setPlacing(null);}},[state?.lastRun?.id,state?.seed]);
  const service=manualService(state);
  useEffect(()=>{if(!service?.chef.holding)setHolding(false);},[service?.chef.holding]);
  useEffect(()=>{const events=service?.events??[];for(const event of events){if(event.id<=lastEvent.current)continue;lastEvent.current=event.id;if(event.type==='serve')play('serve');else if(event.type==='wash')play('bus');else if(event.type==='pay')play('kaching');else if(event.type==='arrive')play('doorbell');else if(event.type==='ready')play('heart');}},[service?.tick,play]);
  useEffect(()=>{lastEvent.current=0;setSelected(null);setCrate(false);setHolding(false);},[state?.run?.position,state?.run?.id]);
  const pauseWork=useCallback(()=>{const current=stateRef.current;if(current){const command=dinerPauseCommand(current);if(command)send(command);}},[send]);
  const openPanel=useCallback((name:PanelName)=>{pauseWork();setCrate(false);setPanel(name);},[pauseWork]);
  const release=useCallback(()=>{setHolding(false);if(manualService(stateRef.current)?.chef.holding)send({type:'service',action:{type:'hold',active:false}});},[send]);
  useEffect(()=>{
    const keyDown=(event:KeyboardEvent)=>{
      if(panel||summary||event.target instanceof HTMLInputElement||event.target instanceof HTMLTextAreaElement||event.target instanceof HTMLSelectElement||event.target instanceof HTMLButtonElement)return;
      const s=manualService(stateRef.current);if(!s||!['playing','closing'].includes(s.phase))return;
      if(event.code==='Space'){event.preventDefault();send({type:'service',action:{type:'pause'}});return;}
      if(event.key.toLowerCase()==='e'){
        event.preventDefault();if(event.repeat)return;
        const target=s.stations.find(station=>station.id===s.chef.targetId),job=target?.slots.find(slot=>slot.job&&!slot.job.ready)?.job;
        if(job?.action==='hold'||job?.action==='wash'){setHolding(true);send({type:'service',action:{type:'hold',active:true}});}
        else if(selected)send({type:'service',action:{type:'interact',targetId:selected}});return;
      }
      const dirs:Record<string,[number,number]>={w:[0,-1],s:[0,1],a:[-1,0],d:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1],ArrowLeft:[-1,0],ArrowRight:[1,0]};
      const dir=dirs[event.key];if(dir){event.preventDefault();const turns=((rotation%4)+4)%4;let [dx,dy]=dir;for(let i=0;i<turns;i++)[dx,dy]=[dy,-dx];send({type:'service',action:{type:'move',x:Math.round(s.chef.x)+dx,y:Math.round(s.chef.y)+dy}});}
    };
    const keyUp=(event:KeyboardEvent)=>{if(event.key.toLowerCase()==='e')release();};
    window.addEventListener('keydown',keyDown);window.addEventListener('keyup',keyUp);window.addEventListener('blur',release);
    return()=>{window.removeEventListener('keydown',keyDown);window.removeEventListener('keyup',keyUp);window.removeEventListener('blur',release);};
  },[panel,summary,selected,send,release,rotation]);
  const beginEdit=()=>{if(!state)return;pauseWork();setPanel(null);setSelected(null);setPlacing(null);if(service){truckOriginal.current=truckLayout(service);setEditing('truck');}else{homeOriginal.current=structuredClone(state.home.layout);setEditing('home');}};
  const finishEdit=(cancel=false)=>{if(cancel){if(editing==='home'&&homeOriginal.current)send({type:'homeLayout',layout:homeOriginal.current});if(editing==='truck'&&truckOriginal.current)send({type:'setupLayout',...truckOriginal.current});}setEditing(null);setSelected(null);setPlacing(null);};
  const onTarget=useCallback((id:string,seatId?:string)=>{
    const current=stateRef.current;if(!current)return;
    if(editing){const currentService=manualService(current);const movable=editing==='home'?current.home.layout.some(item=>item.id===id):currentService?.stations.some(item=>item.id===id)||currentService?.tables.some(item=>item.id===id);if(movable)setSelected(id);return;}
    setSelected(id);
    if(!manualService(current)){if(current.run?.event?.phase==='challenge')return;if(current.run){openPanel('garage');return;}pauseWork();if(id.startsWith('incident:')){send({type:'beginHomeTask',incidentId:id});return;}if(id==='home-till')openPanel('till');else if(id==='home-binder')openPanel('recipes');else if(id==='home-collections')openPanel('collections');else if(id.startsWith('chef_')||id.startsWith('waiter_'))openPanel('staff');return;}
    const s=manualService(current)!;if(s.phase==='setup'){if(id==='crate')openPanel('help');return;}
    if(s.phase==='paused'||s.phase==='complete'||s.phase==='failed')return;
    if(id==='crate'){setCrate(true);return;}
    setCrate(false);send({type:'service',action:{type:'interact',targetId:id,seatId}});
  },[editing,send,openPanel,pauseWork]);
  const onHomeGesture=useCallback((gesture:HomeSceneGesture)=>{
    const current=stateRef.current;if(!current||editing||panel||summary||current.run||current.rally?.service)return;
    if(gesture.type==='begin'||gesture.type==='parcel')setSelected(gesture.incidentId);
    for(const command of homeGestureCommands(current,gesture)){if(!send(command))break;}
  },[editing,panel,summary,send]);
  useEffect(()=>{
    if(!state)return;
    const receipts=new Set(state.daily.incidentClaims),previous=seenCareReceipts.current;seenCareReceipts.current=receipts;
    const earned=previous&&[...receipts].find(id=>!previous.has(id));
    if(earned){play('heart');announce('Lovely. +30 coins');setWorldReward({id:earned,label:'+30 coins',receipt:earned});setSelected(null);}
  },[state?.daily.incidentClaims,play,announce]);
  useEffect(()=>{
    if(!state)return;const previous=seenParcel.current;seenParcel.current={day:state.daily.day,claimed:state.daily.crate,pantry:state.pantry};
    if(previous?.day===state.daily.day&&!previous.claimed&&state.daily.crate){
      const ingredients=Object.entries(state.pantry).filter(([id,count])=>count>(previous.pantry[id]??0)).map(([id,count])=>`${INGREDIENT_BY_ID[id]?.name??id} +${count-(previous.pantry[id]??0)}`);
      play('unlock');announce(`For your pantry: ${ingredients.join(' · ')}`);setWorldReward({id:'home-parcel',label:'Fresh for your pantry!',receipt:`crate:${state.daily.day}`});setSelected(null);
    }
  },[state?.daily.day,state?.daily.crate,state?.pantry,play,announce]);
  useEffect(()=>{if(!worldReward)return;const timer=setTimeout(()=>setWorldReward(null),3200);return()=>clearTimeout(timer);},[worldReward]);
  const onTile=useCallback((x:number,y:number)=>{
    const current=stateRef.current;if(!current)return;
    if(editing==='home'){
      if(placing){const item:HomePlacement={id:`home-${crypto.randomUUID()}`,equipmentId:placing,x,y,rotation:0};if(send({type:'homeLayout',layout:[...current.home.layout,item]})){setPlacing(null);setSelected(item.id);if(placing==='fryer'){const menu={...current.home.menu,starter:[...new Set([...current.home.menu.starter,'fries'])].slice(0,1)};send({type:'setHomeMenu',menu});play('unlock');}}}
      else if(selected)send({type:'homeLayout',layout:current.home.layout.map(p=>p.id===selected?{...p,x,y}:p)});return;
    }
    if(editing==='truck'&&current.run?.service&&selected){const layout=truckLayout(current.run.service);layout.stations=layout.stations.map(p=>p.id===selected?{...p,x,y}:p);layout.tables=layout.tables.map(p=>p.id===selected?{...p,x,y}:p);send({type:'setupLayout',...layout});return;}
    if(manualService(current)&&['playing','closing'].includes(manualService(current)!.phase)){setCrate(false);send({type:'service',action:{type:'move',x,y}});}else if(!current.run){pauseWork();setSelected(null);}
  },[editing,placing,selected,send,play,pauseWork]);
  const rotateItem=()=>{if(!state||!selected)return;if(editing==='home')send({type:'homeLayout',layout:state.home.layout.map(p=>p.id===selected?{...p,rotation:((p.rotation+1)%4) as HomePlacement['rotation']}:p)});else if(service){const layout=truckLayout(service);layout.stations=layout.stations.map(p=>p.id===selected?{...p,facing:((p.facing+1)%4) as typeof p.facing}:p);layout.tables=layout.tables.map(p=>p.id===selected?{...p,rotation:((p.rotation+1)%4) as typeof p.rotation}:p);send({type:'setupLayout',...layout});}};
  const storeItem=()=>{if(!state||!selected)return;if(editing==='home'){if(send({type:'homeLayout',layout:state.home.layout.filter(p=>p.id!==selected)}))setSelected(null);}else if(service){const layout=truckLayout(service);layout.stations=layout.stations.filter(p=>p.id!==selected);layout.tables=layout.tables.filter(p=>p.id!==selected);if(send({type:'setupLayout',...layout}))setSelected(null);}};
  const place=(equipmentId:string)=>{if(!state)return;pauseWork();homeOriginal.current=structuredClone(state.home.layout);setPanel(null);setSummary(false);setEditing('home');setPlacing(equipmentId);setSelected(null);announce(`Choose a clear floor tile for your ${(EQUIPMENT_BY_ID[equipmentId]?.name??DECOR_BY_ID[equipmentId]?.name)?.toLowerCase()}.`);};
  const share=async()=>{const canvas=document.querySelector<HTMLCanvasElement>('[data-diner-canvas]')??document.querySelector<HTMLCanvasElement>(`.${css.scene} canvas`);if(!canvas){announce('The camera is still getting ready.',true);return;}try{const image=document.createElement('canvas');image.width=1200;image.height=900;const ctx=image.getContext('2d')!;ctx.fillStyle='#f6f1e4';ctx.fillRect(0,0,1200,900);const ratio=Math.min(1160/canvas.width,740/canvas.height);ctx.drawImage(canvas,(1200-canvas.width*ratio)/2,100,canvas.width*ratio,canvas.height*ratio);ctx.fillStyle='#456d58';ctx.textAlign='center';ctx.font='bold 34px Georgia';ctx.fillText(stateRef.current?.run?'A little adventure on the road':stateRef.current?.home.name??'My little diner',600,60);ctx.font='15px sans-serif';ctx.fillText('DOMAIN KITCHEN · made a little more mine',600,870);const a=document.createElement('a');a.href=image.toDataURL('image/png');a.download='domain-kitchen-postcard.png';a.click();announce('Your postcard is ready in Downloads.');}catch{announce('Your browser could not save this postcard.',true);}};
  const parked=useMemo(()=>{if(!state?.run||service)return null;const layout=state.truckConfig.stations.length?{stations:state.truckConfig.stations.map(p=>makeStation(p.id,p.kind,p.x,p.y,Math.min(3,state.equipment[p.kind]?.tier??1) as 1|2|3,p.facing)),tables:state.truckConfig.tables.map(p=>makeTable(p.id,p.x,p.y,p.capacity,Math.min(2,state.equipment[p.capacity===4?'table4':'table2']?.tier??1) as 1|2,p.rotation??0))}:buildServiceLoadout(state.truckTier,state.run.menu,Object.fromEntries(Object.entries(state.equipment).map(([id,e])=>[id,e.tier])));return createService({tier:state.truckTier,menu:state.run.menu,stations:layout.stations,tables:layout.tables});},[state?.run?.id,state?.run?.menu,state?.truckTier,state?.equipment,state?.truckConfig,service]);
  const scene=useMemo(()=>{
    if(!state)return null;
    const value=service?serviceScene(service,selected,paint):parked?serviceScene(parked,selected,paint):homeScene(state,homeWorld,selected,paint);
    value.uniform=state.cosmetics.uniform;value.wrap=state.cosmetics.wrap;
    for(const task of state.run?.event?.tasks??[])if(task.progress<task.required)value.objects.push({id:`cleanup:${task.id}`,kind:'spill',x:task.x,y:task.y,state:'working',progress:task.progress/task.required});
    return value;
  },[state,service,parked,homeWorld,selected,paint]);
  const performanceHandler=useCallback((next:DinerPerformance)=>setPerformance(next),[]);
  if(!state||!scene)return <main className={css.game}><div className={css.loading}><DinerIcon name="truck" size={55}/><strong>Setting out the good plates…</strong><span className={css.small}>Your little diner is almost ready.</span></div></main>;
  const run=state.run,node=run?.map.find(n=>n.id===run.position),isRally=!!state.rally?.service,isTruck=!!run||isRally,playing=service&&(service.phase==='playing'||service.phase==='closing'),paused=service?.phase==='paused',setup=service?.phase==='setup';
  const station=service?.stations.find(s=>s.id===service.chef.targetId),activeJob=station?.slots.find(slot=>slot.job&&!slot.job.ready)?.job,held=service?.chef.held,recipe=held?RECIPE_BY_ID[held.recipeId]:null;

  const nextStep=held&&recipe?recipe.steps[held.step]:null;
  const intent=service&&selected?serviceTargetIntent(service,selected):null;
  const selectedChore=scene.objects.find(object=>object.id===selected&&(object.id.startsWith('incident:')||object.id==='home-parcel'));
  const careHint=selectedChore?.kind==='spill'?'Wipe back and forth across the spill.':selectedChore?.kind==='parcel'?(selectedChore.progress??0)<1/3?'Peel the yellow tape.':(selectedChore.progress??0)<2/3?'Open the left flap.':'Open the right flap.':'Your place. Your pace.';
  const hint=editing?placing?`Place your ${(EQUIPMENT_BY_ID[placing]?.name??DECOR_BY_ID[placing]?.name)?.toLowerCase()}.`:'Choose a furnishing, then its new spot.':intent&&!intent.disabled?intent.label:service?.notice||careHint;
  const start=(route:string)=>{pauseWork();if(send({type:'startRun',routeId:route})){setPanel('map');setSummary(false);}};
  const smallServiceName=node?.name??(isRally?'Weekly truck rally':'Ready for the road');
  const strikeCount=run?.practice?service?.strikes??0:run?.strikes??service?.strikes??0,strikeLimit=isRally?service?.config.strikeLimit??3:run?.spices.includes('two_strikes')?2:state.settings.cosy?5:3;
  const progress=state.reputation-(DINER_RULES.reputationLevels[state.restaurantLevel-1]??0),needed=(DINER_RULES.reputationLevels[state.restaurantLevel]??state.reputation+100)-(DINER_RULES.reputationLevels[state.restaurantLevel-1]??0);
  const selectedFurnitureId=editing==='home'?state.home.layout.find(p=>p.id===selected)?.equipmentId:service?.stations.find(p=>p.id===selected)?.kind??(service?.tables.find(p=>p.id===selected)?.capacity===4?'table_4':'table_2');
  const selectedFurnitureName=(EQUIPMENT_BY_ID[selectedFurnitureId??'']??DECOR_BY_ID[selectedFurnitureId??''])?.name??'Selected furnishing';
  return <main className={css.game} data-diner-preview="v2" data-mode={isTruck?'truck':'home'} data-fps={performance?.fps.toFixed(1)}>
    <div className={css.scene}><DinerScene mode={isTruck?'truck':'home'} scene={scene} rotation={rotation} onRotate={setRotation} editing={!!editing} showWorldHints={!panel&&!summary} worldReward={worldReward} onTarget={onTarget} onTile={onTile} onHomeGesture={onHomeGesture} onPerformance={performanceHandler} onError={()=>{const pause=dinerPauseCommand(state);if(pause)send(pause);}}/></div>
    <header className={css.header}><div className={css.brand}><span className={css.brandIcon}><GameEmblem kind={isTruck?'cook':'chef'} size={62}/></span><div><div className={css.eyebrow}>{isTruck?'DOMAIN KITCHEN · ON THE ROAD':'DOMAIN KITCHEN'}</div><h1 className={css.title}>{isTruck?'The Little Lunch Truck':state.home.name}</h1><p className={css.subtitle}>{isTruck?'A little adventure. A very good lunch.':'Made with love. Made by you.'}</p>{!isTruck&&<div className={css.level}><span className={css.levelBadge}>{state.restaurantLevel}</span><span className={css.levelBar}><span style={{width:`${Math.min(100,progress/needed*100)}%`}}/></span><span className={css.levelNumbers}>{Math.floor(progress)} / {needed}</span></div>}</div></div><div className={css.headerRight}><span className={css.chip}><GameEmblem kind="coin" size={36}/>{money(run?run.haul:isRally?service?.coins??0:state.coins)}{isTruck&&<span className={css.tiny}>{isRally?'rally':'haul'}</span>}</span>{playing?<button className={css.iconButton} aria-label="Pause service" onClick={()=>send({type:'service',action:{type:'pause'}})}><DinerIcon name="pause"/></button>:<button className={css.iconButton} aria-label="Settings" onClick={()=>openPanel('settings')}><DinerIcon name="settings"/></button>}</div></header>
    {isTruck?<><aside className={css.location}><span className={css.tag}><DinerIcon name="truck" size={13}/>{run?.tutorial?'Your opening trip':isRally?'Equal equipment':run?.routeId.replace('_',' ')} · {node?`Stop ${node.row+1}`:'Between stops'}</span><h2>{smallServiceName}</h2><div className={css.recipePills}>{(service?.config.menu??run?.menu??[]).map(id=><button className={css.recipePill} key={id} onClick={()=>openPanel('help')}><ModelIcon kind="food" recipeId={id} label={RECIPE_BY_ID[id]?.name} size={30}/>{RECIPE_BY_ID[id]?.name}</button>)}</div></aside><div className={css.stats}><div className={css.strikes} aria-label={`${strikeCount} of ${strikeLimit} strikes`}>{Array.from({length:strikeLimit},(_,i)=><span className={`${css.strike} ${i<strikeCount?css.strikeLost:''}`} key={i}><DinerIcon name="plate" size={24}/></span>)}</div>{service&&<span className={css.progress}>{service.served} / {service.config.customers} served</span>}</div></>:<><aside className={css.location}><span className={css.tag}><DinerIcon name="leaf" size={13}/>{state.buzz.length?'The neighbourhood is talking':'Make it a little more yours'}</span><h2>Welcome home.</h2><p className={css.small}>Your crew has the cooking covered.</p></aside><div className={css.worldButton}><button className={css.tillButton} onClick={()=>openPanel('till')} aria-label={`${money(state.home.till.coins)} coins in your till`}><GameEmblem kind="coin" size={30}/><span><small>IN THE TILL</small><strong>{money(state.home.till.coins)}</strong></span><DinerIcon name="arrow" size={15}/></button></div></>}
    <div className={css.sceneControls}><button className={css.iconButton} aria-label="Rotate camera left" onClick={()=>setRotation((rotation+3)%4)}><DinerIcon name="rotate"/></button><button className={css.iconButton} aria-label="Rotate camera right" onClick={()=>setRotation((rotation+1)%4)}><DinerIcon name="rotate" style={{transform:'scaleX(-1)'}}/></button></div>
    {playing&&!panel&&!editing&&service&&selected&&!crate&&<div className={css.serviceFocus}><ServiceFocus service={service} selectedId={selected}/></div>}
    {run?.tutorial&&service&&setup&&!panel&&<aside className={css.coach}><span className={css.coachStep}>Your first little lunch</span><h3>Let&apos;s make a burger.</h3><p>Take ingredients, grill, assemble, and serve at the table outside. The sink gets each seat ready for the next guest.</p></aside>}
    {!isTruck&&!state.tutorial.finished&&!panel&&!editing&&<aside className={css.coach}><span className={css.coachStep}>Your first little lunch</span><h3>Ready when you are.</h3><p>Take the truck out to learn a dish. Your restaurant will be here when you return.</p><button className={css.primary} style={{marginTop:12}} onClick={()=>start('downtown')}>Begin my first lunch</button></aside>}
    {!isTruck&&state.tutorial.finished&&!state.home.layout.some(p=>p.equipmentId==='fryer')&&state.equipment.fryer?.homeCopies>0&&!editing&&!panel&&<aside className={css.coach}><span className={css.coachStep}>You brought something home</span><h3>Make room for fries.</h3><p>Your first fryer is waiting in storage. Place it and your diner can start serving fries.</p><button className={css.primary} style={{marginTop:12}} onClick={()=>place('fryer')}>Place your fryer</button></aside>}
    <footer className={css.bottom} style={run?.event?{display:'none'}:undefined}><div className={css.hint} role="status">{hint}</div>
      {editing?<div className={css.editorBar}><p>{placing?'Tap a clear floor tile.':selected?selectedFurnitureName:'Select a station or table.'}</p><button className={css.button} disabled={!selected} onClick={rotateItem}><DinerIcon name="rotate" size={17}/>Rotate</button><button className={css.button} disabled={!selected} onClick={storeItem}>Store</button><button className={css.button} onClick={()=>finishEdit(true)}>Cancel</button><button className={css.primary} onClick={()=>finishEdit()}>Done</button></div>:
      playing?<><div className={css.context}><div className={css.held}>{held?<ModelIcon kind="food" recipeId={held.recipeId} foodKind={held.kind} mastery={service?.config.recipeLevels[held.recipeId]??0} stage={held.stage} cold={held.cold} label={held.kind==='dirty'?'Dirty plate':recipe?.name??'Your ingredients'} size={44}/>:<DinerIcon name="hand" size={30}/>}<div><strong>{held?held.kind==='dirty'?'Dirty plate':held.kind==='burnt'?'Burnt food':held.kind==='dish'?recipe?.name:held.kind==='raw'?'Fresh ingredients':held.stage.replace(/_/g,' '):'Empty hands'}</strong><small>{held?held.kind==='dirty'?'Carry to the sink':held.kind==='burnt'?'Take this to the bin':held.kind==='dish'?'Bring it to the right table':nextStep?.label??'Ready for the next step':'Tap the crate or collect a ready dish'}</small></div></div>
        {activeJob&&(activeJob.action==='hold'||activeJob.action==='wash')?<HoldAction active={holding} label={`Hold to ${activeJob.action==='wash'?'wash':'prepare'} · ${Math.ceil(activeJob.remaining/20)}s`} onHold={active=>{setHolding(active);if(active)send({type:'service',action:{type:'hold',active:true}});else release();}}/>:held&&<button className={css.button} onClick={()=>{setSelected('bin');send({type:'service',action:{type:'interact',targetId:'bin'}});}}>Discard</button>}</div>
        {crate&&<div className={css.nav}>{service!.config.menu.map(id=><button key={id} onClick={()=>{send({type:'service',action:{type:'interact',targetId:'crate',recipeId:id}});setCrate(false);}}><ModelIcon kind="food" recipeId={id} label={RECIPE_BY_ID[id]?.name} size={30}/>{RECIPE_BY_ID[id]?.name}</button>)}<button aria-label="Close ingredients" onClick={()=>setCrate(false)}><DinerIcon name="close"/></button></div>}<span className={css.keyboardHint}>Click to move & interact · WASD to walk · E to work · Space to pause</span></>:
      isTruck?<><div className={css.actions}><button className={css.button} onClick={()=>isRally?send({type:'endRally'}):run?.practice?send({type:'endPractice'}):openPanel('map')}><DinerIcon name="arrow" size={18}/>{isRally?'End rally':run?.practice?'End practice':'The route'}</button>{setup&&!isRally&&<button className={css.button} onClick={beginEdit}><DinerIcon name="decorate" size={18}/>Arrange</button>}{!isRally&&<button className={css.button} onClick={()=>openPanel('garage')}><DinerIcon name="truck" size={18}/>My truck</button>}{setup&&<button className={css.primary} onClick={()=>{setSelected(null);send({type:'service',action:{type:'open'}});}}>Open for lunch <DinerIcon name="arrow" size={18}/></button>}{paused&&<button className={css.primary} onClick={()=>send({type:'service',action:{type:'resume'}})}>Resume service</button>}</div><button className={css.quietLink} onClick={()=>openPanel('help')}>How to cook</button></>:
      <><HomeInteraction state={state} selected={selected} send={send} open={openPanel} edit={()=>{const target=selected;beginEdit();setSelected(target);}} close={()=>{pauseWork();setSelected(null);}}/><nav className={css.homeDock} aria-label="Your restaurant"><button className={css.cook} onClick={()=>openPanel('map')}><GameEmblem kind="cook" size={60}/><span>Cook</span></button><button className={css.decorateButton} onClick={()=>openPanel('catalogue')}><GameEmblem kind="decorate" size={60}/><span>Decorate</span></button><button className={css.friendsButton} onClick={()=>openPanel('friends')}><GameEmblem kind="friends" size={60}/><span>Friends</span></button></nav></>}
    </footer>
    {run?.event&&!panel&&<RoadsideStop run={run} selected={selected} send={send} onContinue={()=>{if(run.event?.phase==='resolved')send({type:'leaveNode'});setPanel('map');}}/>}
    {isRally&&service&&(service.phase==='complete'||service.phase==='failed')&&!panel&&<DinerModal dismissible={false} title="A lunch to remember." eyebrow="Weekly rally · everyone starts equal" onClose={()=>send({type:'finishRally'})}><div className={css.summary}><DinerIcon name="star" size={48}/><p className={css.panelLead}>{service.paid} happy customers. Your best validated attempt counts.</p><button className={css.primary} onClick={()=>send({type:'finishRally'})}>Keep my result & go home</button></div></DinerModal>}
    {message&&<div className={`${css.toast} ${message.error?css.errorToast:''}`} role={message.error?'alert':'status'}>{message.text}</div>}
    {panel&&<DinerPanels key={panel} panel={panel} state={state} send={send} close={()=>setPanel(null)} open={openPanel} place={place} start={start} edit={beginEdit} sound={sound} setSound={setSound} paint={paint} setPaint={setPaint} onShare={share} syncStatus={syncStatus} serverEnabled={serverEnabled} connect={connect} read={read} social={social} acceptSession={acceptSession}/>}
    {paused&&!panel&&!editing&&<DinerModal dismissible={false} title="Take your time." eyebrow="Your service is safely paused" onClose={()=>send({type:'service',action:{type:'resume'}})}><div className={css.summary}><div className={css.summaryIcon}><DinerIcon name="pause" size={33}/></div><p className={css.panelLead}>Your customers, cooking, and carried dish will be right here when you return.</p><div className={css.actions}><button className={css.primary} onClick={()=>send({type:'service',action:{type:'resume'}})}>Back to cooking</button><button className={css.button} onClick={()=>openPanel('help')}>Cooking guide</button>{run?.practice&&<button className={css.button} onClick={()=>send({type:'endPractice'})}>Back home</button>}{isRally&&<button className={css.button} onClick={()=>send({type:'endRally'})}>End rally</button>}</div><p className={css.small} style={{marginTop:20}}>Close this tab whenever you need to. Go home and bank your haul from the map between stops.</p></div></DinerModal>}
    {run?.practice&&service?.phase==='failed'&&!panel&&<DinerModal dismissible={false} title="A little practice goes a long way." eyebrow="Nothing earned was lost" onClose={()=>send({type:'endPractice'})}><p className={css.panelLead}>Try again when you feel ready. Take one ingredient through every step, then clear and wash its plate.</p><button className={css.primary} onClick={()=>send({type:'endPractice'})}>Back home</button></DinerModal>}
    {service?.phase==='complete'&&!isRally&&!panel&&<DinerModal dismissible={false} title="That was a good lunch." eyebrow="Another stop, another story" onClose={()=>{if(send({type:'finishService'}))setPanel('map');}}><div className={css.summary}><div className={css.summaryIcon}><DinerIcon name="plate" size={38}/></div><p className={css.summaryAmount}>{money(service.coins)}</p><p className={css.small}>{run?.practice?'practice coins · no progress at risk':'coins added to your haul'} · {service.served} happy customers</p><button className={css.primary} onClick={()=>{if(send({type:'finishService'}))setPanel('map');}}>See what&apos;s up the road <DinerIcon name="arrow"/></button></div></DinerModal>}
    {run&&node&&!service&&!panel&&node.kind==='shop'&&<DinerModal dismissible={false} title="A good find on the road" eyebrow={`Roadside market · ${money(run.haul)} carried coins`} onClose={()=>send({type:'leaveNode'})} wide footer={<><button className={css.button} disabled={run.rerolled||run.haul<DINER_RULES.rerollCost} onClick={()=>send({type:'rerollShop'})}>New finds · {DINER_RULES.rerollCost}</button><button className={css.primary} onClick={()=>{if(send({type:'leaveNode'}))setPanel('map');}}>Back to the road</button></>}><p className={css.panelLead}>Everything you buy stays yours, even if the trip ends early. Your banked coins stay safely at home.</p><div className={css.grid}>{run.offers.map(offer=><article className={css.card} key={offer.id}><div className={css.cardArt}><ModelIcon kind={offer.kind==='recipe'?'food':offer.kind==='ingredients'?'crate':offer.target} recipeId={offer.kind==='recipe'?offer.target:undefined} label={RECIPE_BY_ID[offer.target]?.name??EQUIPMENT_BY_ID[offer.target]?.name??'Ingredient parcel'}/></div><div className={css.cardBody}><span className={css.badge}>{offer.kind}</span><h3>{RECIPE_BY_ID[offer.target]?.name??EQUIPMENT_BY_ID[offer.target]?.name??'A fresh ingredient'}</h3><button className={css.primary} disabled={offer.purchased||run.haul<offer.price} onClick={()=>send({type:'buyOffer',offerId:offer.id})}>{offer.purchased?'Yours to keep':`${money(offer.price)} haul coins`}</button></div></article>)}</div></DinerModal>}
    {run&&node&&!service&&!panel&&['bonus','ingredients'].includes(node.kind)&&<DinerModal title={node.kind==='ingredients'?'Fresh from the farm':'A little roadside kindness'} eyebrow="Choose one to take with you" onClose={()=>setPanel('map')}><div className={css.grid}>{([{id:'coins',name:'A little extra for the road',detail:'100 coins in your haul.',icon:'coin'},{id:'ingredients',name:'Something for the pantry',detail:run.qualified&&!run.ingredientClaimed&&state.daily.truckRuns.length<2?'One fresh ingredient, yours to keep.':'70 coins. Your next fresh ingredient comes with a qualifying trip.',icon:'leaf'},{id:'special',name:'A lucky little break',detail:'A daily special for the rest of this trip.',icon:'star'}] as const).map(choice=><article className={css.card} key={choice.id}><div className={css.cardArt}><DinerIcon name={choice.icon} size={49}/></div><div className={css.cardBody}><h3>{choice.name}</h3><p>{choice.detail}</p><button className={css.primary} disabled={choice.id==='special'&&run.specials.length>=3} onClick={()=>{if(send({type:'chooseGift',choice:choice.id}))setPanel('map');}}>Take this gift</button></div></article>)}</div></DinerModal>}
    {summary&&state.lastRun&&!panel&&<DinerModal title={state.lastRun.reason==='failed'?"Rough day. Let’s head home.":state.lastRun.reason==='won'?'The neighbourhood loved it.':'Home, with a little more to show.'} eyebrow="The good things came back with you" onClose={()=>setSummary(false)}><div className={css.summary}><div className={css.summaryIcon}><DinerIcon name="home" size={36}/></div><div className={css.summaryAmount}>+{money(state.lastRun.banked)}</div><p className={css.small}>coins safely banked{state.lastRun.lost>0?` · ${money(state.lastRun.lost)} carried coins lost`:''}</p><p className={css.panelLead}>Your equipment, recipes, ingredients, and memories are all yours to keep.</p>{state.tutorial.fryerGifted&&!state.home.layout.some(p=>p.equipmentId==='fryer')?<><ModelIcon kind="fryer" label="Your first fryer" size={126}/><p className={css.small}>A new fryer for your restaurant.</p><button className={css.primary} onClick={()=>place('fryer')}>Place your fryer <DinerIcon name="arrow"/></button></>:<button className={css.primary} onClick={()=>setSummary(false)}>Welcome home</button>}</div></DinerModal>}
  </main>;
}
