"use client";
import dynamic from "next/dynamic";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { createDkSfx, type DkSfx } from "./audio";
import { RoomEditor } from './RoomEditor';
import { moveRoomDraft, validateRoomDraft, type RoomDraft } from './room-editor';
import { roomModuleGeometry } from '@/lib/chef/diner/room-plan';
import { FixtureCare } from './FixtureCare';
import { RenovationPreview, type RenovationChoice } from './RenovationPreview';
import { RoomFinishPreview, type RoomFinishChoice } from './RoomFinishPreview';
import { getRenovationPreview } from '@/lib/chef/diner/renovation';
import { createHomeWorld } from '@/lib/chef/diner/home-simulation';
import { homeSimulationConfig } from '@/lib/chef/diner/progression';
import { createDinerMusic } from './music-player';
import { DECOR_BY_ID, ROOM_FINISH_DEFAULTS } from "@/lib/chef/diner/collections";
import { DINER_RULES, canCancelDinerRun, dinerPauseCommand, truckStorage, truckSetupError, type DinerCommand, type DinerState, type HomePlacement } from "@/lib/chef/diner/progression";
import { createService, serviceTargetIntent, serviceReadyError, serviceSupplyChoices, itemLabel } from "@/lib/chef/diner/service";
import { makeStation, makeTable, blockedCells, inServiceFloor, stationAccessPath } from "@/lib/chef/diner/geometry";
import { EQUIPMENT_BY_ID, INGREDIENT_BY_ID, RECIPE_BY_ID } from "@/lib/chef/diner/content";
import { recipeVessel, SERVING_VESSELS } from '@/lib/chef/diner/batch';
import type { ServiceState } from "@/lib/chef/diner/types";
import { useDiner } from "./useDiner";
import { useDinerAccess } from './DinerAccess';
import { betaStorageKeys } from './beta-access';
import { useHomeWorld, homeScene } from "./useHomeWorld";
import { serviceScene } from "./scene-adapter";
import type { DinerPerformance, DinerSceneProps, SceneAnchor } from "./scene-types";
import { DinerIcon } from "./DinerIcon";
import { DinerModal } from "./DinerModal";
import DinerPanels, { money, type PanelName } from "./DinerPanels";
import { ModelIcon } from "./ModelIcon";
import { RoadsideStop } from "./RoadsideStop";
import { RoadsideMarket } from './RecipeLearning';
import { HomeInteraction } from "./HomeInteraction";
import { StationAction } from "./StationAction";
import { FinishPreview, type FinishChoice } from './FinishPreview';
import { GameEmblem } from "./GameEmblem";
import { keyboardDirection,isTypingTarget,nearestTruckInteraction,firstLunchCoach } from './truck-controls';
import { TruckPacking } from './TruckPacking';
import { ServiceFocus } from './ServiceFocus';
import { aimHomeMount, createPlacementDraft, movePlacementDraft, previewPlacement, rotatePlacementDraft, type PlacementDraft } from './placement-preview';
import { homeGestureCommands, type HomeSceneGesture } from "@/lib/chef/diner/home-gesture";
import css from "./diner.module.css";

const DinerScene=dynamic(()=>import('./DinerScene'),{ssr:false,loading:()=> <div className={css.sceneLoading}>Setting the tables…</div>});
const manualService=(state:DinerState|null)=>state?.run?.service??state?.rally?.service??null;
const legacyPreferenceKey='street_eats_preview_preferences_v1';
type TruckLayout={stations:{id:string;kind:ServiceState['stations'][number]['kind'];x:number;y:number;facing:0|1|2|3}[];tables:{id:string;x:number;y:number;capacity:1|2|4;rotation:0|1|2|3}[]};
function truckLayout(service:ServiceState):TruckLayout{return {stations:service.stations.map(({id,kind,x,y,facing})=>({id,kind,x,y,facing})),tables:service.tables.map(({id,x,y,capacity,rotation})=>({id,x,y,capacity,rotation}))};}

export default function DinerClient(){
  const access=useDinerAccess();
  const preferenceKey=access?.mode==='beta'?betaStorageKeys(access.wallet).preferences:legacyPreferenceKey;
  const {state,send:dispatch,announce,message,syncStatus,serverEnabled,localSaveError,connect,read,social,acceptSession,signOut}=useDiner();
  const homeWorld=useHomeWorld(state);
  const [roomDraft,setRoomDraft]=useState<RoomDraft|null>(null),[roomSelected,setRoomSelected]=useState<string|null>(null);
  const [renovation,setRenovation]=useState<RenovationChoice|null>(null),[beforeRenovation,setBeforeRenovation]=useState(false);
  const [roomFinish,setRoomFinish]=useState<RoomFinishChoice|null>(null);
  const [finishPreview,setFinishPreview]=useState<FinishChoice|null>(null);
  const [panel,setPanel]=useState<PanelName|null>(null),[rotation,setRotation]=useState(0),[selected,setSelected]=useState<string|null>(null),[crate,setCrate]=useState(false),[supplyId,setSupplyId]=useState<string|null>(null);
  const [editing,setEditing]=useState<'home'|'truck'|null>(null),[placing,setPlacing]=useState<string|null>(null),[sound,setSound]=useState(true),[paint,setPaint]=useState('#b66751');
  const [placement,setPlacement]=useState<PlacementDraft|null>(null);
  const [musicOn,setMusicOn]=useState(true),[musicVolume,setMusicVolume]=useState(.35),[effectsVolume,setEffectsVolume]=useState(.7);
  const music=useRef<ReturnType<typeof createDinerMusic>|null>(null);
  const [summary,setSummary]=useState(false),[ready,setReady]=useState(false),[holding,setHolding]=useState(false),[performance,setPerformance]=useState<DinerPerformance|null>(null);
  const homeOriginal=useRef<HomePlacement[]|null>(null),truckOriginal=useRef<TruckLayout|null>(null),boot=useRef<string|null>(null),seenSummary=useRef<string|null>(null),sfx=useRef<DkSfx|null>(null),lastEvent=useRef(0);
  const stateRef=useRef(state);stateRef.current=state;
  const seenCareReceipts=useRef<Set<string>|null>(null);
  const [anchors,setAnchors]=useState<SceneAnchor[]>([]);
  const handleAnchors=useCallback((value:SceneAnchor[])=>setAnchors(value),[]);
  const [worldReward,setWorldReward]=useState<DinerSceneProps['worldReward']>(null);
  const seenParcel=useRef<{day:number;claimed:boolean;pantry:Record<string,number>}|null>(null);
  useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem(preferenceKey)||'{}');if(typeof saved.sound==='boolean')setSound(saved.sound);if(typeof saved.musicOn==='boolean')setMusicOn(saved.musicOn);else if(saved.sound===false)setMusicOn(false);if(typeof saved.musicVolume==='number')setMusicVolume(Math.max(0,Math.min(1,saved.musicVolume)));if(typeof saved.effectsVolume==='number')setEffectsVolume(Math.max(0,Math.min(1,saved.effectsVolume)));if(typeof saved.paint==='string'&&/^#[0-9a-f]{6}$/i.test(saved.paint))setPaint(saved.paint);}catch{}setReady(true);},[]);
  useEffect(()=>{if(ready)try{localStorage.setItem(preferenceKey,JSON.stringify({sound,paint,musicOn,musicVolume,effectsVolume}));}catch{}sfx.current?.setEffectsMuted(!sound);sfx.current?.setEffectsVolume(effectsVolume);music.current?.setEnabled(musicOn);music.current?.setVolume(musicVolume);},[sound,paint,ready,musicOn,musicVolume,effectsVolume]);
  useEffect(()=>{music.current=createDinerMusic();const activate=()=>void music.current?.activate(),hidden=()=>music.current?.setHidden(document.hidden);window.addEventListener('pointerdown',activate);window.addEventListener('keydown',activate);document.addEventListener('visibilitychange',hidden);return()=>{window.removeEventListener('pointerdown',activate);window.removeEventListener('keydown',activate);document.removeEventListener('visibilitychange',hidden);music.current?.destroy();sfx.current?.destroy();};},[]);
  const play=useCallback((name:Parameters<DkSfx['play']>[0])=>{if(!sound)return;if(!sfx.current){sfx.current=createDkSfx(true);sfx.current.setMusicMuted(true);}sfx.current.setEffectsVolume(effectsVolume);sfx.current.play(name);},[sound,effectsVolume]);
  const send=useCallback((command:DinerCommand)=>{const mapped=command.type==='service'&&stateRef.current?.rally?.service?{type:'rallyService' as const,action:command.action}:command;const okay=dispatch(mapped);if(okay&&['buyOffer','buyHomeEquipment','upgradeRecipe','collectTill','claimCrate','chooseGift'].includes(command.type))play(command.type==='upgradeRecipe'?'unlock':'kaching');return okay;},[dispatch,play]);
  useEffect(()=>{
    if(!state||boot.current===state.seed)return;boot.current=state.seed;setPanel(null);setSummary(false);
  },[state,send]);
  useEffect(()=>{if(state?.lastRun&&seenSummary.current!==state.lastRun.id){seenSummary.current=state.lastRun.id;try{const key=`${preferenceKey}_seen_${state.seed}`;if(localStorage.getItem(key)===state.lastRun.id)return;localStorage.setItem(key,state.lastRun.id);}catch{}setPanel(null);setSummary(true);setEditing(null);setPlacing(null);}},[state?.lastRun?.id,state?.seed]);
  useEffect(()=>{const run=state?.run;if(run?.tutorial&&!run.position&&!run.visited.length){const first=run.map.find(node=>node.row===0);if(first){send({type:'chooseNode',nodeId:first.id});setPanel(null);}}},[state?.run?.id,state?.run?.position,send]);
  const service=manualService(state);
  const musicContext=!state?.run&&!state?.rally?.service?'home':!service||!['playing','closing'].includes(service.phase)||state?.run?.practice?'truck-prep':(service.config.customers>=20?'truck-busy':'truck-service');
  useEffect(()=>{music.current?.setContext(musicContext);},[musicContext]);
  const guide=service&&state?.run?.tutorial?firstLunchCoach(service):null;
  useEffect(()=>{if(!service?.chef.holding)setHolding(false);},[service?.chef.holding]);
  useEffect(()=>{const events=service?.events??[];for(const event of events){if(event.id<=lastEvent.current)continue;lastEvent.current=event.id;if(event.type==='serve')play('serve');else if(event.type==='wash')play('bus');else if(event.type==='pay')play('kaching');else if(event.type==='arrive')play('doorbell');else if(event.type==='ready')play('heart');}},[service?.tick,play]);
  useEffect(()=>{lastEvent.current=0;setSelected(null);setCrate(false);setHolding(false);},[state?.run?.position,state?.run?.id]);
  const pauseWork=useCallback(()=>{const current=stateRef.current;if(current){const command=dinerPauseCommand(current);if(command)send(command);}},[send]);
  const openPanel=useCallback((name:PanelName)=>{setFinishPreview(null);setRoomFinish(null);setRenovation(null);setRoomDraft(null);pauseWork();setCrate(false);setPanel(name);},[pauseWork]);
  const release=useCallback(()=>{setHolding(false);if(manualService(stateRef.current)?.chef.holding)send({type:'service',action:{type:'hold',active:false}});},[send]);
  const interact=useCallback((id:string,seatId?:string,itemId?:string)=>{
    const s=manualService(stateRef.current);if(!s)return false;release();setSelected(id);
    const station=s.stations.find(station=>station.id===id),choices=serviceSupplyChoices(s,id);
    if(station?.kind==='pass'&&!itemId&&!s.chef.held&&station.slots.filter(slot=>slot.item).length>1){
      setCrate(false);const path=stationAccessPath(s.config.tier,s.stations,s.tables,s.chef,station);
      if(path===null){announce('Leave a clear side to reach this counter.');return false;}
      const target=path.at(-1)??{x:Math.round(s.chef.x),y:Math.round(s.chef.y)};send({type:'service',action:{type:'move',...target}});return false;
    }
    if(!s.chef.held&&(choices.length>1||(!s.config.physicalSupplies&&station?.kind==='crate'&&s.config.menu.length>1))){if(station){const path=stationAccessPath(s.config.tier,s.stations,s.tables,s.chef,station);if(path===null){announce('There is no clear route to those supplies.');return false;}const target=path.at(-1)??{x:Math.round(s.chef.x),y:Math.round(s.chef.y)};send({type:'service',action:{type:'move',...target}});}setSupplyId(id);setCrate(true);return false;}
    setCrate(false);return send({type:'service',action:{type:'interact',targetId:id,seatId,...(itemId?{itemId}:{}),...(choices.length===1?{recipeId:choices[0].recipeId,ingredientId:choices[0].ingredientId}:{})}});
  },[send,announce,release]);
  useEffect(()=>{
    const keys=new Set<string>();let workHeld=false;
    const available=()=>{const s=manualService(stateRef.current);return !panel&&!summary&&!editing&&s&&['preparing','playing','closing'].includes(s.phase)?s:null;};
    const step=(interrupt=false)=>{const s=available(),key=Array.from(keys).at(-1);if(!s||!key)return;const dir=keyboardDirection(key,rotation);if(!dir)return;
      const x=Math.round(s.chef.x),y=Math.round(s.chef.y);
      if(interrupt){send({type:'service',action:{type:'move',x,y}});setCrate(false);}
      else if(s.chef.path.length)return;
      const next={x:x+dir.x,y:y+dir.y};if(inServiceFloor(s.config.tier,next)&&!blockedCells(s.stations,s.tables).has(`${next.x},${next.y}`))send({type:'service',action:{type:'move',...next}});
    };
    const keyDown=(event:KeyboardEvent)=>{
      if(event.defaultPrevented||isTypingTarget(event.target as HTMLElement)||!available())return;
      if(event.code==='Space'){event.preventDefault();if(!event.repeat)send({type:'service',action:{type:'pause'}});return;}
      const key=event.key.toLowerCase();
      if(key==='e'){
        event.preventDefault();if(event.repeat)return;workHeld=true;
        const s=available()!,target=nearestTruckInteraction(s);if(target)workHeld=interact(target.targetId,target.seatId);return;
      }
      if(keyboardDirection(event.key,rotation)){event.preventDefault();if(event.repeat)return;keys.add(key);release();workHeld=false;step(true);}
    };
    const keyUp=(event:KeyboardEvent)=>{keys.delete(event.key.toLowerCase());if(event.key.toLowerCase()==='e'){workHeld=false;release();}};
    const clear=()=>{keys.clear();workHeld=false;release();};
    const hidden=()=>{if(document.hidden)clear();};
    const timer=window.setInterval(()=>{step();const s=available();if(workHeld&&s&&!s.chef.path.length&&!s.chef.holding){const job=s.stations.find(station=>station.id===s.chef.targetId)?.slots.find(slot=>slot.job&&!slot.job.ready)?.job;if(job?.action==='hold'||job?.action==='wash'){setHolding(true);send({type:'service',action:{type:'hold',active:true}});}}},40);
    window.addEventListener('keydown',keyDown);window.addEventListener('keyup',keyUp);window.addEventListener('blur',clear);document.addEventListener('visibilitychange',hidden);
    return()=>{window.clearInterval(timer);window.removeEventListener('keydown',keyDown);window.removeEventListener('keyup',keyUp);window.removeEventListener('blur',clear);document.removeEventListener('visibilitychange',hidden);clear();};
  },[panel,summary,editing,send,release,rotation,interact]);
  const beginEdit=()=>{if(!state)return;setRoomDraft(null);setRoomFinish(null);setRenovation(null);setFinishPreview(null);pauseWork();setPanel(null);setSelected(null);setPlacing(null);setPlacement(null);if(service){truckOriginal.current=truckLayout(service);setEditing('truck');}else{homeOriginal.current=structuredClone(state.home.layout);setEditing('home');}};
  const finishEdit=(cancel=false)=>{if(cancel){if(editing==='home'&&homeOriginal.current&&JSON.stringify(homeOriginal.current)!==JSON.stringify(stateRef.current?.home.layout)&&!send({type:'homeLayout',layout:homeOriginal.current}))return;const current=manualService(stateRef.current);if(editing==='truck'&&truckOriginal.current&&current&&JSON.stringify(truckOriginal.current)!==JSON.stringify(truckLayout(current))&&!send({type:'setupLayout',...truckOriginal.current}))return;}setEditing(null);setSelected(null);setPlacing(null);setPlacement(null);};
  const packItem=useCallback((equipmentId:string)=>{const current=stateRef.current,s=manualService(current);if(!current||current.rally?.service||!s||s.phase!=='setup'||!truckStorage(current).some(item=>item.equipmentId===equipmentId&&item.available>0))return;if(!editing)truckOriginal.current=truckLayout(s);setEditing('truck');setPanel(null);setSelected(null);setPlacing(equipmentId);setPlacement(createPlacementDraft(current,'truck',equipmentId,`truck-${crypto.randomUUID()}`));},[editing]);
  const onTarget=useCallback((id:string,seatId?:string)=>{
    const current=stateRef.current;if(!current)return;
    if(id.startsWith('trailer:')){packItem(id.slice(8));return;}
    if(editing&&placement?.mount&&current.home.roomPlan){const support=current.home.roomPlan.modules.find(m=>m.id===id);if(support){setPlacement(aimHomeMount(current,placement,support.x,support.y,true));return;}}
    if(editing){const currentService=manualService(current),item=editing==='home'?current.home.layout.find(item=>item.id===id):currentService?.stations.find(item=>item.id===id)??currentService?.tables.find(item=>item.id===id);if(item){const equipmentId='equipmentId'in item?item.equipmentId:'kind'in item?item.kind:`table_${item.capacity}`;setSelected(id);setPlacing(null);setPlacement(createPlacementDraft(current,editing,equipmentId,id,true));}return;}
    setSelected(id);
    if(!manualService(current)){if(current.run?.event?.phase==='challenge')return;if(current.run){openPanel('garage');return;}pauseWork();if(id.startsWith('incident:')){send({type:'beginHomeTask',incidentId:id});return;}if(id==='home-till')openPanel('till');else if(id==='home-binder')openPanel('recipes');else if(id==='home-collections')openPanel('collections');else if(id.startsWith('chef_')||id.startsWith('waiter_')||id.startsWith('cashier_'))openPanel('staff');return;}
    const s=manualService(current)!;if(s.phase==='setup'){if(current.rally?.service)return;const item=s.stations.find(item=>item.id===id)??s.tables.find(item=>item.id===id);if(item){truckOriginal.current=truckLayout(s);setEditing('truck');setPlacing(null);setPlacement(createPlacementDraft(current,'truck','kind'in item?item.kind:`table_${item.capacity}`,id,true));}return;}
    if(s.phase==='paused'||s.phase==='complete'||s.phase==='failed')return;
    interact(id,seatId);
  },[editing,placement,send,openPanel,pauseWork,packItem,interact]);
  const onHomeGesture=useCallback((gesture:HomeSceneGesture)=>{
    const current=stateRef.current;if(!current||editing||panel||summary||roomDraft||renovation||roomFinish||finishPreview||current.run||current.rally?.service)return;
    if(gesture.type==='begin'||gesture.type==='parcel')setSelected(gesture.incidentId);
    for(const command of homeGestureCommands(current,gesture)){if(!send(command))break;}
  },[editing,panel,summary,send,roomDraft,renovation,roomFinish,finishPreview]);
  useEffect(()=>{
    if(!state)return;
    const receipts=new Set(state.daily.incidentClaims),previous=seenCareReceipts.current;seenCareReceipts.current=receipts;
    const earned=previous&&[...receipts].find(id=>!previous.has(id));
    if(earned){play('heart');announce('Lovely. +30 coins');setWorldReward({id:earned,label:'+30 coins',receipt:earned});setSelected(null);}
  },[state?.daily.incidentClaims,play,announce]);
  useEffect(()=>{
    if(!state)return;const previous=seenParcel.current;seenParcel.current={day:state.daily.day,claimed:state.daily.crate,pantry:state.pantry};
    if(previous?.day===state.daily.day&&!previous.claimed&&state.daily.crate){
      const ingredients=Object.entries(state.pantry).filter(([id,count])=>count>(previous.pantry[id]??0)).map(([id,count])=>`${INGREDIENT_BY_ID[id]?.name??id} +${count-(previous.pantry[id]??0)}`);
      play('unlock');announce(`For your pantry: ${ingredients.join(' · ')}`);setWorldReward({id:'home-parcel',label:'Fresh for your pantry!',receipt:`crate:${state.daily.day}`});setSelected(null);
    }
  },[state?.daily.day,state?.daily.crate,state?.pantry,play,announce]);
  useEffect(()=>{if(!worldReward)return;const timer=setTimeout(()=>setWorldReward(null),3200);return()=>clearTimeout(timer);},[worldReward]);
  const onTile=useCallback((x:number,y:number)=>{
    const current=stateRef.current;if(!current)return;
    if(editing){setPlacement(draft=>draft?aimHomeMount(current,draft,x,y,true):draft);return;}
    if(manualService(current)&&['preparing','playing','closing'].includes(manualService(current)!.phase)){setCrate(false);send({type:'service',action:{type:'move',x,y}});}else if(!current.run){pauseWork();setSelected(null);}
  },[editing,send,pauseWork]);
  const onHoverTile=useCallback((x:number|null,y:number|null)=>{if(!editing||x===null||y===null)return;setPlacement(draft=>draft&&!draft.pinned&&(draft.x!==x||draft.y!==y)?stateRef.current?aimHomeMount(stateRef.current,draft,x,y):draft:draft);},[editing]);
  const rotateItem=()=>{if(!state||!editing)return;setPlacement(draft=>{if(draft)return rotatePlacementDraft(draft);const item=editing==='home'?state.home.layout.find(p=>p.id===selected):service?.stations.find(p=>p.id===selected)??service?.tables.find(p=>p.id===selected);if(!item)return null;return rotatePlacementDraft(createPlacementDraft(state,editing,'equipmentId'in item?item.equipmentId:'kind'in item?item.kind:`table_${item.capacity}`,item.id,true));});};
  const cancelPlacement=()=>{setPlacement(null);setSelected(null);setPlacing(null);};
  const confirmPlacement=()=>{const current=stateRef.current;if(!current||!placement)return;const preview=previewPlacement(current,placement);if(preview.error){announce(preview.error,true);return;}if(!send(preview.command))return;setSelected(null);setPlacing(null);setPlacement(null);play('unlock');if(placement.mode==='home'&&!placement.existing&&placement.equipmentId==='fryer'&&current.recipes.fries){const menu={...current.home.menu,starter:[...new Set([...current.home.menu.starter,'fries'])].slice(0,1)};send({type:'setHomeMenu',menu});}};
  const storeItem=()=>{if(!state||!selected)return;if(editing==='home'){if(send({type:'homeLayout',layout:state.home.layout.filter(p=>p.id!==selected)}))cancelPlacement();}else if(service){const layout=truckLayout(service);layout.stations=layout.stations.filter(p=>p.id!==selected);layout.tables=layout.tables.filter(p=>p.id!==selected);if(send({type:'setupLayout',...layout}))cancelPlacement();}};
  const place=(equipmentId:string)=>{if(!state)return;setRoomDraft(null);setRoomFinish(null);setRenovation(null);setFinishPreview(null);pauseWork();if(editing!=='home')homeOriginal.current=structuredClone(state.home.layout);setPanel(null);setSummary(false);setEditing('home');setPlacing(equipmentId);setSelected(null);setPlacement(createPlacementDraft(state,'home',equipmentId,`home-${crypto.randomUUID()}`));announce(`Preview your ${(EQUIPMENT_BY_ID[equipmentId]?.name??DECOR_BY_ID[equipmentId]?.name)?.toLowerCase()}, rotate it, then confirm.`);};
  const share=async()=>{const canvas=document.querySelector<HTMLCanvasElement>('[data-diner-canvas]')??document.querySelector<HTMLCanvasElement>(`.${css.scene} canvas`);if(!canvas){announce('The camera is still getting ready.',true);return;}try{const image=document.createElement('canvas');image.width=1200;image.height=900;const ctx=image.getContext('2d')!;ctx.fillStyle='#f6f1e4';ctx.fillRect(0,0,1200,900);const ratio=Math.min(1160/canvas.width,740/canvas.height);ctx.drawImage(canvas,(1200-canvas.width*ratio)/2,100,canvas.width*ratio,canvas.height*ratio);ctx.fillStyle='#456d58';ctx.textAlign='center';ctx.font='bold 34px Georgia';ctx.fillText(stateRef.current?.run?'A little adventure on the road':stateRef.current?.home.name??'My little diner',600,60);ctx.font='15px sans-serif';ctx.fillText('DOMAIN KITCHEN · made a little more mine',600,870);const a=document.createElement('a');a.href=image.toDataURL('image/png');a.download='domain-kitchen-postcard.png';a.click();announce('Your postcard is ready in Downloads.');}catch{announce('Your browser could not save this postcard.',true);}};
  const parked=useMemo(()=>{if(!state?.run||service)return null;const layout={stations:state.truckConfig.stations.map(p=>makeStation(p.id,p.kind,p.x,p.y,Math.min(3,state.equipment[p.kind]?.tier??1) as 1|2|3,p.facing)),tables:state.truckConfig.tables.map(p=>makeTable(p.id,p.x,p.y,p.capacity,1,p.rotation??0))};return createService({tier:state.truckTier,menu:state.run.menu,stations:layout.stations,tables:layout.tables});},[state?.run?.id,state?.run?.menu,state?.truckTier,state?.equipment,state?.truckConfig,service]);
  const placementPreview=useMemo(()=>state&&placement&&placement.mode===editing?previewPlacement(state,placement):null,[state,placement,editing]);
  const beginRoomEdit=()=>{if(!state?.home.roomPlan)return;pauseWork();setPanel(null);setEditing(null);setSelected(null);setRoomSelected(null);setRoomDraft({roomPlan:structuredClone(state.home.roomPlan),layout:structuredClone(state.home.layout)});};
  const roomDraftScene=useMemo(()=>{if(!state||!roomDraft)return null;const preview={...state,home:{...state.home,...roomDraft}};const value=homeScene(preview,createHomeWorld(homeSimulationConfig(preview)),roomSelected,paint),module=roomDraft.roomPlan.modules.find(m=>m.id===roomSelected),zone=roomDraft.roomPlan.zones.find(z=>`zone:${z.id}`===roomSelected),valid=!validateRoomDraft(state,roomDraft);value.people=[];value.tileHighlights=module?roomModuleGeometry(module).cells.map(p=>({...p,valid})):zone?Array.from({length:zone.w*zone.h},(_,i)=>({x:zone.x+i%zone.w,y:zone.y+Math.floor(i/zone.w),valid})):[];return value;},[state?.home.fixtureInventory,roomDraft,roomSelected,paint]);
  const renovationScene=useMemo(()=>{if(!state||!renovation)return null;const previewState={...state,cosmetics:renovation.cosmetics,home:{...state.home,w:renovation.roomPlan.w,h:renovation.roomPlan.h,layout:renovation.layout,roomPlan:renovation.roomPlan,staff:renovation.staff,finishes:renovation.finishes}};return homeScene(previewState,createHomeWorld(homeSimulationConfig(previewState)),null,paint);},[state?.seed,renovation,paint]);
  const scene=useMemo(()=>{
    if(!state)return null;
    const value=roomDraftScene??(renovationScene&&!beforeRenovation?{...renovationScene,objects:[...renovationScene.objects],tables:[...renovationScene.tables]}:service?serviceScene(service,selected,paint):parked?serviceScene(parked,selected,paint):homeScene(state,homeWorld,selected,paint));
    if(roomFinish&&!service&&!parked)value.roomFinishes={...ROOM_FINISH_DEFAULTS,...state.home.finishes,[roomFinish.slot]:roomFinish.id};
    if(finishPreview&&!service&&!parked)value[finishPreview.slot]=finishPreview.id;
    value.previewInset=roomDraft?270:renovation?245:finishPreview||roomFinish?190:undefined;value.uniform=state.cosmetics.uniform;value.wrap=state.cosmetics.wrap;value.guideTarget=service&&state.run?.tutorial?firstLunchCoach(service).targetId:null;
    if(service?.phase==='setup'&&!state.rally?.service)value.trailer=truckStorage(state).filter(item=>item.available>0).slice(0,6).map(item=>({id:item.equipmentId,kind:item.equipmentId,tier:item.tier}));
    if(placement&&placementPreview){value.objects=value.objects.filter(object=>object.id!==placement.id);value.tables=value.tables.filter(table=>table.id!==placement.id);value.placement={object:placementPreview.object,table:placementPreview.table,valid:!placementPreview.error};value.selectedId=null;}

    for(const task of state.run?.event?.tasks??[])if(task.progress<task.required)value.objects.push({id:`cleanup:${task.id}`,kind:'spill',x:task.x,y:task.y,state:'working',progress:task.progress/task.required});
    return value;
  },[state,service,parked,homeWorld,selected,paint,placement,placementPreview,finishPreview,roomFinish,renovationScene,beforeRenovation,roomDraftScene,roomDraft,renovation]);
  const performanceHandler=useCallback((next:DinerPerformance)=>setPerformance(next),[]);
  if(!state||!scene)return <main className={css.game}><div className={css.loading}><DinerIcon name="truck" size={55}/><strong>{message?.error?"Your diner could not open yet.":"Setting out the good plates…"}</strong><span className={css.small} role={message?.error?"alert":"status"}>{message?.text??"Your little diner is almost ready."}</span>{(message?.error||syncStatus==="offline")&&<button className={css.primary} onClick={()=>void connect()}>Reconnect account</button>}</div></main>;
  const run=state.run,node=run?.map.find(n=>n.id===run.position),isRally=!!state.rally?.service,isTruck=!!run||isRally,preparing=service?.phase==='preparing',playing=service&&['preparing','playing','closing'].includes(service.phase),paused=service?.phase==='paused',setup=service?.phase==='setup';
  const station=service?.stations.find(s=>s.id===service.chef.targetId),activeJob=station?.slots.find(slot=>slot.job&&!slot.job.ready)?.job,held=service?.chef.held,recipe=held?RECIPE_BY_ID[held.recipeId]:null;

  const nextStep=held&&recipe?recipe.steps[held.step]:null;
  const intent=service&&selected?serviceTargetIntent(service,selected):null;
  const selectedChore=scene.objects.find(object=>object.id===selected&&(object.id.startsWith('incident:')||object.id==='home-parcel'));
  const careHint=selectedChore?.kind==='spill'?'Wipe back and forth across the spill.':selectedChore?.kind==='parcel'?(selectedChore.progress??0)<1/3?'Peel the yellow tape.':(selectedChore.progress??0)<2/3?'Open the left flap.':'Open the right flap.':'Your place. Your pace.';
  const hint=finishPreview?'Try a color. Buy only when you love it.':editing?placement?'Tap a spot, rotate, then confirm.':'Choose a furnishing to move or rotate.':intent&&!intent.disabled?intent.label:service?.notice||careHint;
  const start=(route:string)=>{pauseWork();if(send({type:'startRun',routeId:route})){setPanel(state.tutorial.finished?'map':null);setSummary(false);}};
  const canGoBack=canCancelDinerRun(state);
  const backHome=()=>{if(send({type:'goHome'})){setPanel(null);setSummary(false);setEditing(null);setSelected(null);setCrate(false);setPlacement(null);setPlacing(null);}};
  const setupError=setup?(isRally?serviceReadyError(service):truckSetupError(state)):null;
  const missingStation=setup?service.config.menu.flatMap(id=>RECIPE_BY_ID[id].steps).map(step=>step.station).find(kind=>!service.stations.some(station=>station.kind===kind)):null;
  const smallServiceName=preparing?'Prep time':node?.name??(isRally?'Weekly truck rally':'Ready for the road');
  const strikeCount=run?.practice?service?.strikes??0:run?.strikes??service?.strikes??0,strikeLimit=isRally?service?.config.strikeLimit??3:run?.spices.includes('two_strikes')?2:state.settings.cosy?5:3;
  const progress=state.reputation-(DINER_RULES.reputationLevels[state.restaurantLevel-1]??0),needed=(DINER_RULES.reputationLevels[state.restaurantLevel]??state.reputation+100)-(DINER_RULES.reputationLevels[state.restaurantLevel-1]??0);
  const selectedFurnitureId=placement?.equipmentId??(editing==='home'?state.home.layout.find(p=>p.id===selected)?.equipmentId:service?.stations.find(p=>p.id===selected)?.kind??`table_${service?.tables.find(p=>p.id===selected)?.capacity??1}`);
  const selectedFurnitureName=(EQUIPMENT_BY_ID[selectedFurnitureId??'']??DECOR_BY_ID[selectedFurnitureId??''])?.name??'Selected furnishing';
  return <main className={css.game} data-service-phase={service?.phase} data-chef-position={service?`${service.chef.x.toFixed(2)},${service.chef.y.toFixed(2)}`:undefined} data-carried-item={held?`${held.recipeId}:${held.kind}:${held.stage}`:'empty'} data-diner-preview="v2" data-mode={isTruck?'truck':'home'} data-fps={performance?.fps.toFixed(1)}>
    <div className={css.scene}><DinerScene mode={isTruck?'truck':'home'} scene={scene} rotation={rotation} onRotate={setRotation} editing={!!editing||!!roomDraft} showWorldHints={!panel&&!summary&&!finishPreview&&!roomFinish&&!renovation&&!roomDraft&&!roomDraft} worldReward={worldReward} onTarget={roomDraft?id=>{if(roomDraft.roomPlan.modules.some(m=>m.id===id))setRoomSelected(id);}:renovation||roomFinish||finishPreview?()=>{}:onTarget} onTile={roomDraft?(x,y)=>setRoomDraft(moveRoomDraft(roomDraft,roomSelected,x,y)):renovation||roomFinish||finishPreview?()=>{}:onTile} onHoverTile={onHoverTile} onHomeGesture={onHomeGesture} onPerformance={performanceHandler} onAnchors={handleAnchors} onError={()=>{const pause=dinerPauseCommand(state);if(pause)send(pause);}}/></div>
    <header className={css.header}><div className={css.brand}><span className={css.brandIcon}><GameEmblem kind={isTruck?'cook':'chef'} size={62}/></span><div><div className={css.eyebrow}>{isTruck?'DOMAIN KITCHEN · ON THE ROAD':'DOMAIN KITCHEN'}</div><h1 className={css.title}>{isTruck?'The Little Lunch Truck':<button className={css.renameTitle} aria-label={`Name your diner: ${state.home.name}`} title="Name your diner" onClick={()=>openPanel('name')}>{state.home.name}<DinerIcon name="decorate" size={14}/></button>}</h1><p className={css.subtitle}>{isTruck?'A little adventure. A very good lunch.':'Made with love. Made by you.'}</p>{!isTruck&&<div className={css.level}><span className={css.levelBadge}>{state.restaurantLevel}</span><span className={css.levelBar}><span style={{width:`${Math.min(100,progress/needed*100)}%`}}/></span><span className={css.levelNumbers}>{Math.floor(progress)} / {needed}</span></div>}</div></div><div className={css.headerRight}><span className={css.chip}><GameEmblem kind="coin" size={36}/>{money(run?run.haul:isRally?service?.coins??0:state.coins)}{isTruck&&<span className={css.tiny}>{isRally?'rally':'haul'}</span>}</span>{playing?<button className={css.iconButton} aria-label="Pause service" onClick={()=>send({type:'service',action:{type:'pause'}})}><DinerIcon name="pause"/></button>:<button className={css.iconButton} aria-label="Settings" onClick={()=>openPanel('settings')}><DinerIcon name="settings"/></button>}</div></header>
    {isTruck?<><aside className={css.location}><span className={css.tag}><DinerIcon name="truck" size={13}/>{run?.tutorial?'Your opening trip':isRally?'Equal equipment':run?.routeId.replace('_',' ')} · {node?`Stop ${node.row+1}`:'Between stops'}</span><h2>{smallServiceName}</h2><div className={css.recipePills}>{(service?.config.menu??run?.menu??[]).map(id=><button className={css.recipePill} key={id} onClick={()=>openPanel('help')}><ModelIcon kind="food" recipeId={id} label={RECIPE_BY_ID[id]?.name} size={30}/>{RECIPE_BY_ID[id]?.name}</button>)}</div></aside><div className={css.stats}><div className={css.strikes} aria-label={`${strikeCount} of ${strikeLimit} strikes`}>{Array.from({length:strikeLimit},(_,i)=><span className={`${css.strike} ${i<strikeCount?css.strikeLost:''}`} key={i}><DinerIcon name="plate" size={24}/></span>)}</div>{service&&<><span className={css.progress}>{preparing?'Doors closed · take your time':`${service.served} / ${service.config.customers} served`}</span>{service.config.physicalSupplies&&service.config.plateCount>0&&<span className={css.progress} aria-label={`${service.cleanPlates} of ${service.config.plateCount} plates clean`}>{service.cleanPlates} / {service.config.plateCount} clean plates</span>}{service.config.physicalSupplies&&(service.config.bowlCount??0)>0&&<span className={css.progress} aria-label={`${service.cleanBowls??0} of ${service.config.bowlCount} bowls clean`}>{service.cleanBowls??0} / {service.config.bowlCount} clean bowls</span>}{service.config.physicalSupplies&&service.config.cupCount>0&&<span className={css.progress} aria-label={`${service.cleanCups} of ${service.config.cupCount} cups clean`}>{service.cleanCups} / {service.config.cupCount} clean cups</span>}</>}</div></>:<><aside className={css.location}><span className={css.tag}><DinerIcon name="leaf" size={13}/>{state.buzz.length?'The neighbourhood is talking':'Make it a little more yours'}</span><h2>Welcome home.</h2><p className={css.small}>Your crew has the cooking covered.</p></aside><div className={css.worldButton}><button className={css.tillButton} onClick={()=>openPanel('till')} aria-label={`${money(state.home.till.coins)} coins in your till`}><GameEmblem kind="coin" size={30}/><span><small>IN THE TILL</small><strong>{money(state.home.till.coins)}</strong></span><DinerIcon name="arrow" size={15}/></button></div></>}
    <div className={css.sceneControls}><button className={css.iconButton} aria-label="Rotate camera left" onClick={()=>setRotation((rotation+3)%4)}><DinerIcon name="rotate"/></button><button className={css.iconButton} aria-label="Rotate camera right" onClick={()=>setRotation((rotation+1)%4)}><DinerIcon name="rotate" style={{transform:'scaleX(-1)'}}/></button></div>
    {playing&&!panel&&!editing&&service&&selected&&!crate&&<div className={css.serviceFocus}><ServiceFocus service={service} selectedId={selected} onCounterItem={(id,itemId)=>interact(id,undefined,itemId)}/></div>}
    {run?.tutorial&&service&&setup&&!panel&&<aside className={css.coach}><span className={css.coachStep}>Your first little lunch</span><h3>{setupError?'Pack your little kitchen.':'Ready for one hungry guest.'}</h3><p>{setupError?missingStation?`Choose the ${EQUIPMENT_BY_ID[missingStation].name.toLowerCase()} in your trailer, then a glowing tile in the truck. No timer yet.`:setupError:'You have one table and one chair. Open when you’re ready; we’ll cook the first burger together.'}</p></aside>}
    {!isTruck&&!state.tutorial.finished&&!panel&&!editing&&!finishPreview&&!roomFinish&&!renovation&&!roomDraft&&<aside className={`${css.coach} ${css.homeCoach}`}><span className={css.coachStep}>Your first little lunch</span><h3>Ready when you are.</h3><p>Take the truck out to learn a dish. Your restaurant will be here when you return.</p><button className={css.primary} style={{marginTop:12}} onClick={()=>start('downtown')}>Begin my first lunch</button></aside>}
    {!isTruck&&state.tutorial.finished&&!state.home.layout.some(p=>p.equipmentId==='fryer')&&state.equipment.fryer?.homeCopies>0&&!editing&&!panel&&!finishPreview&&!roomFinish&&!renovation&&!roomDraft&&<aside className={`${css.coach} ${css.homeCoach}`}><span className={css.coachStep}>You brought something home</span><h3>Make room for fries.</h3><p>{state.recipes.fries?"Your first fryer is waiting in storage. Place it and your diner can start serving fries.":"Your first fryer is waiting in storage. Place it at home, then learn the fries recipe when you’re ready."}</p><button className={css.primary} style={{marginTop:12}} onClick={()=>place('fryer')}>Place your fryer</button></aside>}
    {playing&&!panel&&!editing&&station&&activeJob&&(activeJob.action==='hold'||activeJob.action==='wash')&&<StationAction anchor={anchors.find(anchor=>anchor.id===station.id)} active={holding} progress={1-activeJob.remaining/activeJob.total} label={service!.chef.path.length?'Walking over…':`Hold to ${activeJob.action==='wash'?'wash':'prepare'} · ${Math.ceil(activeJob.remaining/20)}s`} disabled={!!service!.chef.path.length} onHold={active=>{setHolding(active);if(active)send({type:'service',action:{type:'hold',active:true}});else release();}}/>}
    {!isTruck&&!panel&&!editing&&!roomDraft&&!finishPreview&&!roomFinish&&!renovation&&selected&&state.home.roomPlan?.modules.some(m=>m.id===selected&&['toilet','handwash_sink'].includes(m.kind))&&<FixtureCare key={selected} module={state.home.roomPlan.modules.find(m=>m.id===selected)!} anchor={anchors.find(a=>a.id===selected)} coins={state.coins} send={send}/>}
    <footer className={css.bottom} style={run?.event?{display:'none'}:undefined}><div className={css.hint} role="status">{setup&&!editing?(setupError??'All packed. Open whenever you’re ready.'):hint}</div>
      {setup&&!isRally&&<TruckPacking state={state} placing={placing} onChoose={packItem} onBuy={capacity=>send({type:'buyTruckTable',capacity})} send={send}/>}
      {roomDraft?<RoomEditor state={state} draft={roomDraft} selected={roomSelected} onSelect={setRoomSelected} onDraft={setRoomDraft} onCancel={()=>setRoomDraft(null)} onConfirm={()=>{if(send({type:'homeRoomPlan',...roomDraft})){setRoomDraft(null);play('unlock');}}} onBuy={kind=>{if(send({type:'buyHomeFixture',kind}))announce('Yours to keep. Choose it from In storage to place it.');}}/>:renovation?<RenovationPreview state={state} choice={renovation} before={beforeRenovation} setBefore={setBeforeRenovation} cancel={()=>setRenovation(null)} confirm={()=>{if(send({type:'renovateHome',stage:renovation.stage,previewToken:renovation.token})){setRenovation(null);play('unlock');}}}/>:roomFinish?<RoomFinishPreview state={state} choice={roomFinish} change={setRoomFinish} cancel={()=>setRoomFinish(null)} apply={()=>{if(send({type:'buyRoomFinish',...roomFinish}))setRoomFinish(null);}}/>:finishPreview?<FinishPreview state={state} choice={finishPreview} change={setFinishPreview} cancel={()=>setFinishPreview(null)} apply={()=>{if(send({type:'buyFinish',...finishPreview}))setFinishPreview(null);}}/>:editing?<div className={css.editorBar}><p role="status">{placement?`${selectedFurnitureName} · ${placement.rotation*90}°`:selected?selectedFurnitureName:'Select a station or table.'}{placementPreview?.error&&<span style={{display:'block',color:'#9c6046'}}>{placementPreview.error}</span>}</p>{placement?.mode==='home'&&state.home.roomPlan&&DECOR_BY_ID[placement.equipmentId]?.counter&&<button className={css.button} onClick={()=>setPlacement(draft=>draft?draft.mount?{...draft,mount:undefined,pinned:false}:aimHomeMount(state,{...draft,mount:{kind:'counter',targetId:'',slot:0},pinned:false},draft.x,draft.y):draft)}>{placement.mount?'Place on floor':'Place on counter'}</button>}<button className={css.button} disabled={!!placement?.mount||(!placement&&!selected)} onClick={rotateItem}><DinerIcon name="rotate" size={17}/>Rotate</button><button className={css.button} disabled={!selected||!!placing} onClick={storeItem}>Store</button>{placement&&<><button className={css.button} onClick={cancelPlacement}>Cancel move</button><button className={css.primary} disabled={!placementPreview||!!placementPreview.error} title={placementPreview?.error??'Save this placement'} onClick={confirmPlacement}>Confirm</button></>}<button className={css.button} onClick={()=>finishEdit(true)}>Cancel all</button><button className={placement?css.button:css.primary} disabled={!!placement} onClick={()=>finishEdit()}>Done</button></div>:
      playing?<>{preparing&&<><div className={css.actions}>{canGoBack&&<button className={css.button} onClick={backHome}><DinerIcon name="home" size={18}/>Back home</button>}<button className={css.primary} onClick={()=>send({type:'service',action:{type:'open'}})}>Open for lunch</button></div>{canGoBack&&<span className={css.small}>This trip only counts once you open for lunch.</span>}</>}{guide&&<div className={css.firstStep} role="status"><strong>{guide.heading}</strong><p>{guide.detail}</p></div>}<div className={css.context}><div className={css.held}>{held?<ModelIcon kind="food" recipeId={held.recipeId} foodKind={held.kind} mastery={service?.config.recipeLevels[held.recipeId]??0} ingredientId={held.ingredientId} vesselKind={held.vesselKind} stage={held.stage} cold={held.cold} label={itemLabel(held)} size={44}/>:<DinerIcon name="hand" size={30}/>}<div><strong>{itemLabel(held??null)}</strong><small>{held?held.kind==='dirty'?'Carry to the sink':held.kind==='plate'?'Bring it to prepared food at the counter':held.kind==='burnt'?'Take this to the bin':held.kind==='dish'?'Bring it to the right table':held.kind==='ingredient'&&held.ingredientId==='bun'?'Combine with the patty at the prep counter':nextStep?.label??`Set it on prep and fetch a clean ${SERVING_VESSELS[recipeVessel(held.recipeId)].name}`:'Choose an ingredient or collect ready food'}</small></div></div>
        {held&&<button className={css.button} onClick={()=>{const bin=service?.stations.find(station=>station.kind==='bin');if(bin){setSelected(bin.id);send({type:'service',action:{type:'interact',targetId:bin.id}});}}}>Discard</button>}</div>
        {crate&&supplyId&&<section className={css.supplyPicker} aria-label="Choose an ingredient"><strong>{service.stations.find(station=>station.id===supplyId)?.kind==='fridge'?'From the fridge':'From the pantry'}</strong><div>{service.config.physicalSupplies?serviceSupplyChoices(service,supplyId).map(choice=><button key={`${choice.recipeId}:${choice.ingredientId}`} onClick={()=>{send({type:'service',action:{type:'interact',targetId:supplyId,recipeId:choice.recipeId,ingredientId:choice.ingredientId}});setCrate(false);}}><ModelIcon kind="food" recipeId={choice.recipeId} foodKind="ingredient" ingredientId={choice.ingredientId} label={choice.name} size={46}/><span>{choice.name}<small>{RECIPE_BY_ID[choice.recipeId].name}</small></span></button>):service.config.menu.map(id=><button key={id} onClick={()=>{send({type:'service',action:{type:'interact',targetId:supplyId,recipeId:id}});setCrate(false);}}><ModelIcon kind="food" recipeId={id} label={RECIPE_BY_ID[id].name} size={40}/>{RECIPE_BY_ID[id].name}</button>)}</div><button className={css.quietLink} onClick={()=>setCrate(false)}>Close ingredients</button></section>}
        <span className={css.keyboardHint}>WASD / arrows to walk · E to pick up & use · Hold E to prepare · Space to pause</span></>:
      isTruck?<><div className={css.actions}>{!setup&&<button className={css.button} onClick={()=>isRally?send({type:'endRally'}):run?.practice?send({type:'endPractice'}):openPanel('map')}><DinerIcon name="arrow" size={18}/>{isRally?'End rally':run?.practice?'End practice':'The route'}</button>}{setup&&!isRally&&<button className={css.button} onClick={beginEdit}><DinerIcon name="decorate" size={18}/>Arrange</button>}{!isRally&&!setup&&<button className={css.button} onClick={()=>openPanel('garage')}><DinerIcon name="truck" size={18}/>My truck</button>}{setup&&<button className={css.button} disabled={!!setupError} onClick={()=>{setSelected(null);send({type:'service',action:{type:'prepare'}});}}>Prep ingredients</button>}{setup&&<button className={css.primary} disabled={!!setupError} title={setupError??'Your kitchen is ready'} onClick={()=>{setSelected(null);send({type:'service',action:{type:'open'}});}}>Open for lunch <DinerIcon name="arrow" size={18}/></button>}{paused&&<button className={css.primary} onClick={()=>send({type:'service',action:{type:'resume'}})}>Resume service</button>}</div>{setup&&!isRally?<>{canGoBack?<><button className={css.button} onClick={backHome}><DinerIcon name="home" size={18}/>Back home</button><span className={css.small}>This trip only counts once you open for lunch.</span></>:<button className={css.quietLink} onClick={()=>run?.practice?send({type:'endPractice'}):openPanel('map')}>{run?.practice?'Back home':'Back to the route'}</button>}</>:<button className={css.quietLink} onClick={()=>openPanel('help')}>How to cook</button>}</>:
      <><HomeInteraction state={state} selected={selected} send={send} open={openPanel} edit={()=>{const item=state.home.layout.find(p=>p.id===selected);beginEdit();if(item){setSelected(item.id);setPlacement(createPlacementDraft(state,'home',item.equipmentId,item.id,true));}}} close={()=>{pauseWork();setSelected(null);}}/><nav className={css.homeDock} aria-label="Your restaurant"><button className={css.cook} onClick={()=>openPanel('map')}><GameEmblem kind="cook" size={60}/><span>Cook</span></button><button className={css.decorateButton} onClick={()=>openPanel('catalogue')}><GameEmblem kind="decorate" size={60}/><span>Decorate</span></button><button className={css.friendsButton} onClick={()=>openPanel('friends')}><GameEmblem kind="friends" size={60}/><span>Friends</span></button></nav></>}
    </footer>
    {run?.event&&!panel&&<RoadsideStop run={run} selected={selected} send={send} onContinue={()=>{if(run.event?.phase==='resolved')send({type:'leaveNode'});setPanel('map');}}/>}
    {isRally&&service&&(service.phase==='complete'||service.phase==='failed')&&!panel&&<DinerModal dismissible={false} title="A lunch to remember." eyebrow="Weekly rally · everyone starts equal" onClose={()=>send({type:'finishRally'})}><div className={css.summary}><DinerIcon name="star" size={48}/><p className={css.panelLead}>{service.paid} happy customers. Your best validated attempt counts.</p><button className={css.primary} onClick={()=>send({type:'finishRally'})}>Keep my result & go home</button></div></DinerModal>}
    {(localSaveError||message)&&<div className={`${css.toast} ${localSaveError||message?.error?css.errorToast:''}`} role={localSaveError||message?.error?'alert':'status'}>{localSaveError??message?.text}</div>}
    {panel&&<DinerPanels key={panel} panel={panel} state={state} send={send} close={()=>setPanel(null)} open={openPanel} place={place} start={start} edit={beginEdit} sound={sound} setSound={setSound} musicOn={musicOn} setMusicOn={setMusicOn} musicVolume={musicVolume} setMusicVolume={setMusicVolume} effectsVolume={effectsVolume} setEffectsVolume={setEffectsVolume} paint={paint} setPaint={setPaint} onShare={share} syncStatus={syncStatus} localSaveError={localSaveError} serverEnabled={serverEnabled} connect={connect} read={read} social={social} acceptSession={acceptSession} signOut={signOut} editRoom={beginRoomEdit} previewRenovation={()=>{pauseWork();setPanel(null);setSelected(null);setBeforeRenovation(false);setRenovation(getRenovationPreview(state));}} previewRoomFinish={choice=>{pauseWork();setPanel(null);setSelected(null);setRoomFinish(choice);}} previewFinish={choice=>{pauseWork();setPanel(null);setSelected(null);setFinishPreview(choice);}}/>}
    {paused&&!panel&&!editing&&<DinerModal dismissible={false} title="Take your time." eyebrow="Your service is safely paused" onClose={()=>send({type:'service',action:{type:'resume'}})}><div className={css.summary}><div className={css.summaryIcon}><DinerIcon name="pause" size={33}/></div><p className={css.panelLead}>{canGoBack?'Your doors are still closed. Keep preparing, or head home without counting a run.':'Your customers, cooking, and carried dish will be right here when you return.'}</p><div className={css.actions}><button className={css.primary} onClick={()=>send({type:'service',action:{type:'resume'}})}>{canGoBack?'Keep preparing':'Back to cooking'}</button><button className={css.button} onClick={()=>openPanel('help')}>Cooking guide</button>{canGoBack&&<button className={css.button} onClick={backHome}><DinerIcon name="home" size={18}/>Back home</button>}{run?.practice&&<button className={css.button} onClick={()=>send({type:'endPractice'})}>Back home</button>}{isRally&&<button className={css.button} onClick={()=>send({type:'endRally'})}>End rally</button>}</div><p className={css.small} style={{marginTop:20}}>{canGoBack?'This trip only counts once you open for lunch.':'Close this tab whenever you need to. Go home and bank your haul from the map between stops.'}</p></div></DinerModal>}
    {run?.practice&&service?.phase==='failed'&&!panel&&<DinerModal dismissible={false} title="A little practice goes a long way." eyebrow="Nothing earned was lost" onClose={()=>send({type:'endPractice'})}><p className={css.panelLead}>Try again when you feel ready. Take one ingredient through every step, then clear and wash its plate.</p><button className={css.primary} onClick={()=>send({type:'endPractice'})}>Back home</button></DinerModal>}
    {service?.phase==='complete'&&!isRally&&!panel&&<DinerModal dismissible={false} title="That was a good lunch." eyebrow="Another stop, another story" onClose={()=>{if(send({type:'finishService'}))setPanel('map');}}><div className={css.summary}><div className={css.summaryIcon}><DinerIcon name="plate" size={38}/></div><p className={css.summaryAmount}>{money(service.coins)}</p><p className={css.small}>{run?.practice?'practice coins · no progress at risk':'coins added to your haul'} · {service.served} happy customers</p><button className={css.primary} onClick={()=>{if(send({type:'finishService'}))setPanel('map');}}>See what&apos;s up the road <DinerIcon name="arrow"/></button></div></DinerModal>}
    {run&&node&&!service&&!panel&&node.kind==='shop'&&<DinerModal dismissible={false} title="A good find on the road" eyebrow={`Roadside market · ${money(run.haul)} carried coins`} onClose={()=>send({type:'leaveNode'})} wide footer={<><button className={css.button} disabled={run.rerolled||run.haul<DINER_RULES.rerollCost} onClick={()=>send({type:'rerollShop'})}>New finds · {DINER_RULES.rerollCost}</button><button className={css.primary} onClick={()=>{if(send({type:'leaveNode'}))setPanel('map');}}>Back to the road</button></>}><RoadsideMarket state={state} send={send}/></DinerModal>}
    {run&&node&&!service&&!panel&&['bonus','ingredients'].includes(node.kind)&&<DinerModal title={node.kind==='ingredients'?'Fresh from the farm':'A little roadside kindness'} eyebrow="Choose one to take with you" onClose={()=>setPanel('map')}><div className={css.grid}>{([{id:'coins',name:'A little extra for the road',detail:'100 coins in your haul.',icon:'coin'},{id:'ingredients',name:'Something for the pantry',detail:run.qualified&&!run.ingredientClaimed&&state.daily.truckRuns.length<2?'One fresh ingredient, yours to keep.':'70 coins. Your next fresh ingredient comes with a qualifying trip.',icon:'leaf'},{id:'special',name:'A lucky little break',detail:'A daily special for the rest of this trip.',icon:'star'}] as const).map(choice=><article className={css.card} key={choice.id}><div className={css.cardArt}><DinerIcon name={choice.icon} size={49}/></div><div className={css.cardBody}><h3>{choice.name}</h3><p>{choice.detail}</p><button className={css.primary} disabled={choice.id==='special'&&run.specials.length>=3} onClick={()=>{if(send({type:'chooseGift',choice:choice.id}))setPanel('map');}}>Take this gift</button></div></article>)}</div></DinerModal>}
    {summary&&state.lastRun&&!panel&&<DinerModal title={state.lastRun.reason==='failed'?"Rough day. Let’s head home.":state.lastRun.reason==='won'?'The neighbourhood loved it.':'Home, with a little more to show.'} eyebrow="The good things came back with you" onClose={()=>setSummary(false)}><div className={css.summary}><div className={css.summaryIcon}><DinerIcon name="home" size={36}/></div><div className={css.summaryAmount}>+{money(state.lastRun.banked)}</div><p className={css.small}>coins safely banked{state.lastRun.lost>0?` · ${money(state.lastRun.lost)} carried coins lost`:''}</p><p className={css.panelLead}>Your equipment, recipes, ingredients, and memories are all yours to keep.</p>{state.tutorial.fryerGifted&&!state.home.layout.some(p=>p.equipmentId==='fryer')?<><ModelIcon kind="fryer" label="Your first fryer" size={126}/><p className={css.small}>A new fryer for your restaurant.</p><button className={css.primary} onClick={()=>place('fryer')}>Place your fryer <DinerIcon name="arrow"/></button></>:<button className={css.primary} onClick={()=>setSummary(false)}>Welcome home</button>}</div></DinerModal>}
  </main>;
}
