"use client";
import { useState } from "react";
import { DINER_RULES, canCancelDinerRun, dinerRates, equipmentTierCap, runStrikeLimit, staffSlots, truckMenuCapacity, recipeEquipmentNeeded, type DinerCommand, type DinerState } from "@/lib/chef/diner/progression";
import { TRUCK_EQUIPMENT, EQUIPMENT_BY_ID, INGREDIENT_BY_ID, ingredientSupply, RECIPES, RECIPE_BY_ID, ROUTES, TRUCK_TIERS } from "@/lib/chef/diner/content";
import { recipeVessel, SERVING_VESSELS } from '@/lib/chef/diner/batch';
import { COSMETICS } from "@/lib/chef/diner/collections";
import type { SyncStatus, DinerSession } from './diner-sync';
import type { DinerSocialCommand } from '@/lib/chef/diner/social';
import FriendsPanel from './FriendsPanel';
import { DinerModal } from "./DinerModal";
import { DinerIcon } from "./DinerIcon";
import { ModelIcon } from "./ModelIcon";
import { RouteMap } from "./RouteMap";
import { HomeFinishes, RegularBook, StaffRitual, TruckExtras, PassportBook } from "./CollectionPanels";
import { HomeGrowth } from './HomeGrowth';
import type { RoomFinishChoice } from './RoomFinishPreview';
import { renovationRequirements } from '@/lib/chef/diner/renovation';
import { STAGE_COPY } from './RenovationPreview';
import type { FinishChoice } from './FinishPreview';
import { FurnishingCatalog } from './FurnishingCatalog';
import { RecipeBook } from './RecipeBook';
import { equipmentUpgradeDescription, equipmentDisplayName, recipeEquipmentHint } from './RecipeLearning';
import { PantryShelf } from './PantryShelf';
import css from "./diner.module.css";

export type PanelName='recipes'|'pantry'|'catalogue'|'staff'|'collections'|'settings'|'till'|'map'|'garage'|'truckMenu'|'friends'|'help'|'finishes'|'grow'|'name';
export interface PanelProps {panel:PanelName;state:DinerState;send:(command:DinerCommand)=>boolean;close:()=>void;open:(name:PanelName)=>void;place:(equipmentId:string)=>void;start:(route:string)=>void;edit:()=>void;sound:boolean;setSound:(on:boolean)=>void;musicOn:boolean;setMusicOn:(on:boolean)=>void;musicVolume:number;setMusicVolume:(value:number)=>void;effectsVolume:number;setEffectsVolume:(value:number)=>void;paint:string;setPaint:(color:string)=>void;onShare:()=>void;syncStatus:SyncStatus;serverEnabled:boolean;connect:()=>Promise<boolean>;read:(path:string,body?:unknown)=>Promise<unknown>;social:(command:DinerSocialCommand)=>Promise<unknown>;acceptSession:(session:DinerSession)=>Promise<unknown>;signOut?:()=>Promise<boolean>;editRoom:()=>void;previewRenovation:()=>void;previewRoomFinish:(choice:RoomFinishChoice)=>void;previewFinish:(choice:FinishChoice)=>void;}
const wrapColors:Record<typeof COSMETICS.wraps[number],string>={tomato:'#bd6a50',buttercream:'#eacb85',sage:'#456d58',sky:'#8cabb8'};
export const money=(n:number)=>Math.floor(n).toLocaleString('en-US');
function SmallIcon({kind,label,tier=1}:{kind:string;label:string;tier?:number}){return <ModelIcon kind={kind} tier={tier} label={label} size={52}/>;}

export default function DinerPanels(props:PanelProps){
  const {panel,state,send,close,open,place,start,edit}=props;
  const [tab,setTab]=useState('all'),[name,setName]=useState(state.home.name),[helpRecipe,setHelpRecipe]=useState(state.run?.menu[0]??state.truckConfig.menu[0]??'classic_burger');
  if(panel==='friends')return <DinerModal title="Your little street" eyebrow="Good neighbours, good food" onClose={close} wide><FriendsPanel state={state} syncStatus={props.syncStatus} serverEnabled={props.serverEnabled} connect={props.connect} read={props.read} social={props.social} acceptSession={props.acceptSession} signOut={props.signOut} onNameDiner={()=>open('name')}/></DinerModal>;
  if(panel==='recipes')return <DinerModal title="Your cookbook" eyebrow="A little better with every ingredient" onClose={close} wide>
    <RecipeBook state={state} send={send} openPantry={()=>open('pantry')}/>
  </DinerModal>;
  if(panel==='pantry')return <DinerModal title="Your pantry" eyebrow="Small discoveries, lasting favourites" onClose={close} wide>
    <PantryShelf state={state} send={send} close={close} openRecipes={()=>open('recipes')}/>
  </DinerModal>;
  if(panel==='finishes')return <DinerModal title="The little things make it yours" eyebrow="Finishes & keepsakes" onClose={close} wide><HomeFinishes state={state} send={send} place={place} onPreviewFinish={(slot,id)=>props.previewFinish({slot,id})}/></DinerModal>;
  if(panel==='grow')return <DinerModal title="A little room to grow" eyebrow="Build a busier, better diner" onClose={close}><HomeGrowth state={state} send={send} open={open} preview={props.previewRenovation}/></DinerModal>;
  if(panel==='catalogue')return <DinerModal title="Make it yours" eyebrow="Your restaurant, your way" onClose={close} wide footer={<><button className={css.button} onClick={edit}><DinerIcon name="decorate"/>Move your furniture</button>{state.home.roomPlan&&<button className={css.button} onClick={props.editRoom}>Counters & bathroom</button>}<button className={css.primary} onClick={close}>Done</button></>}>
    <FurnishingCatalog state={state} send={send} place={place} moreStyle={()=>open('finishes')} onGrow={()=>open('grow')} onCook={()=>open('map')} onStaff={()=>open('staff')} onRecipes={()=>open('recipes')} onPreviewRoomFinish={props.previewRoomFinish} onPreviewFinish={(slot,id)=>props.previewFinish({slot,id})}/>
  </DinerModal>;
  if(panel==='staff')return <DinerModal title="The people who make it" eyebrow="Your diner crew" onClose={close}>
    <p className={css.panelLead}>Chefs cook. Cashiers take burger-shop orders. Servers deliver food and clear dishes. Nobody needs wages, feeding, or rest.</p><div className={css.gridTwo+' '+css.grid}>{(['chef','waiter'] as const).map(role=><article className={css.card} key={role}><div className={css.cardArt}><ModelIcon kind={role} label={role}/></div><div className={css.cardBody}><h3>{role==='chef'?'Kitchen crew':'Dining crew'}</h3><p>{state.home.staff[role==='chef'?'chefs':'waiters']} on your team</p><button className={css.button} disabled={(state.home.staff.chefs+state.home.staff.waiters+(state.home.staff.cashiers??0))>=staffSlots(state)||state.coins<500} onClick={()=>send({type:'hire',role})}>Hire · 500 coins</button></div></article>)}</div><p className={css.notice}>{(state.home.staff.chefs+state.home.staff.waiters+(state.home.staff.cashiers??0))} / {staffSlots(state)} crew slots used. Restaurant levels make room for more staff. Your truck&apos;s first helper seat opens at tier 2.</p><StaffRitual state={state} send={send}/>
  </DinerModal>;
  if(panel==='till'){const rates=dinerRates(state),next=renovationRequirements(state);return <DinerModal title="A good little business" eyebrow="The restaurant keeps going" onClose={close}>
    <div className={css.summary}><DinerIcon name="coin" size={35}/><p className={css.summaryAmount}>{money(state.home.till.coins)}</p><p className={css.small}>coins waiting in your till</p><button className={css.primary} disabled={state.home.till.coins<1&&state.home.till.reputation<1} onClick={()=>send({type:'collectTill'})}>Collect coins & reputation</button></div>
    <div className={css.split}><div className={css.statBox}><span className={css.eyebrow}>At your current layout</span><strong>{money(rates.coins)} / hour</strong><span className={css.small}>Your current bottleneck: {rates.bottleneck=== 'arrivals'?'finding more customers':rates.bottleneck==='kitchen'?'cooking capacity':rates.bottleneck==='waiters'?'serving capacity':'available seats'}.</span></div><div className={css.statBox}><span className={css.eyebrow}>While you&apos;re away</span><strong>{money(rates.coins*.6)} / hour</strong><span className={css.small}>Up to eight hours in the till. Facilities wear with use. A quick clean or repair restores service.</span></div></div>
    <h3 className={css.sectionTitle}>Room to grow</h3><div className={css.row}><DinerIcon name="home"/><div><h3>{state.home.w} × {state.home.h} diner</h3><p>{next.stage?`Next: ${STAGE_COPY[next.stage].name} · ${money(next.cost)} coins`:'Your full-size restaurant is open.'}</p></div><button className={css.button} onClick={()=>open('grow')}>Renovations</button></div>
  </DinerModal>;}
  if(panel==='map')return <DinerModal title="Where shall we go?" eyebrow={state.run?`${state.run.routeId.replace('_',' ')} · Carrying ${money(state.run.haul)} coins`:'The road is calling'} onClose={close} wide footer={state.run&&(!state.run.position||canCancelDinerRun(state))?<button className={css.primary} onClick={()=>{if(send({type:'goHome'}))close();}}><DinerIcon name="home"/>{canCancelDinerRun(state)?'Back home':`Go home & bank ${money(state.run.haul)}`}</button>:undefined}>
    {canCancelDinerRun(state)&&<p className={css.small}>Changed your mind? Head home. This trip only counts once you open for lunch.</p>}
    {!state.run&&<div className={css.actions} style={{marginBottom:18}}><button className={css.button} onClick={()=>{if(send({type:'startPractice'}))close();}}>A little practice</button><button className={css.button} onClick={()=>open('garage')}>Prepare my truck</button><button className={css.button} onClick={()=>{if(send({type:'startRally'}))close();}}>Weekly rally</button></div>}{state.run?<><RouteMap strikeLimit={runStrikeLimit(state)} run={state.run} choose={id=>{if(send({type:'chooseNode',nodeId:id}))close();}}/></>:ROUTES.map(route=><div className={css.routeCard} key={route.id}><DinerIcon name="truck" size={40}/><div><h3>{route.name}</h3><p>{route.recipeIds.filter(id=>state.recipes[id]).length} / {route.recipeIds.length} recipes found · {state.collections.routeWins.includes(route.id)?'Finale cleared':'A new story to tell'}</p></div><button className={css.primary} disabled={state.truckTier<route.tier} onClick={()=>start(route.id)}>{state.truckTier<route.tier?'Locked':'Take the truck'}</button></div>)}
  </DinerModal>;
  if(panel==='truckMenu')return <DinerModal title="What are we cooking?" eyebrow="A short menu, or a bigger challenge" onClose={close}>
    <p className={css.panelLead}>{(state.run?.menu??state.truckConfig.menu).length>truckMenuCapacity(state)?`Your existing ${(state.run?.menu??state.truckConfig.menu).length}-recipe menu is kept. New menus allow up to ${truckMenuCapacity(state)} recipes; grow your truck to add more.`:`Up to ${truckMenuCapacity(state)} recipes in this truck. More variety means more to juggle.`} Buying a recipe never selects it for you. Arrange its equipment and supplies before opening.</p><div className={css.grid}>{RECIPES.filter(r=>state.recipes[r.id]).map(recipe=>{
      const menu=state.run?.menu??state.truckConfig.menu,chosen=menu.includes(recipe.id),missing=recipeEquipmentNeeded(state,recipe.id),full=menu.length>=truckMenuCapacity(state),last=chosen&&menu.length===1;
      return <article className={css.card} key={recipe.id}><div className={css.cardArt}><ModelIcon kind="food" recipeId={recipe.id} label={recipe.name}/></div><div className={css.cardBody}><h3>{recipe.name}</h3><p>{recipe.steps.map(s=>s.label).join(' → ')}</p><p>{recipeEquipmentHint(state,recipe.id)}</p><button className={chosen?css.softButton:css.button} disabled={last||!chosen&&(missing.length>0||full)} onClick={()=>send({type:'setTruckMenu',recipeIds:chosen?menu.filter(id=>id!==recipe.id):[...menu,recipe.id]})}>{last?'On the menu · keep one dish':chosen?'Remove from menu':missing.length?'Get missing equipment':full?'Menu full':'Add to menu'}</button></div></article>;
    })}</div><p className={css.small}>Find more recipes at roadside markets from your second shop stop. You can keep a recipe while looking for its machine.</p>
  </DinerModal>;
  if(panel==='garage')return <DinerModal title="Your little adventure" eyebrow="The garage" onClose={close}>
    <div className={css.routeCard}><DinerIcon name="truck" size={47}/><div><h3>Tier {state.truckTier} food truck</h3><p>{TRUCK_TIERS[state.truckTier].w} × {TRUCK_TIERS[state.truckTier].h} kitchen · {state.truckConfig.tables.reduce((sum,table)=>sum+table.capacity,0)} seats arranged · {TRUCK_TIERS[state.truckTier].helpers} helpers</p></div></div><p className={css.small}>Clear a route’s finale to grow your truck. Collect only the recipes you want to cook.</p>
    <h3 className={css.sectionTitle}>A fresh coat of paint</h3><div className={css.swatches}>{COSMETICS.wraps.map(id=><button key={id} aria-label={`${id[0].toUpperCase()+id.slice(1)} truck wrap`} aria-pressed={state.cosmetics.wrap===id} title={id[0].toUpperCase()+id.slice(1)} className={`${css.swatch} ${state.cosmetics.wrap===id?css.swatchSelected:''}`} style={{background:wrapColors[id]}} onClick={()=>send({type:'setCosmetic',slot:'wrap',id})}/>)}</div>
    <h3 className={css.sectionTitle}>Your truck&apos;s hello</h3><div className={css.tabs} role="group" aria-label="Truck horn">{COSMETICS.horns.map(id=><button key={id} aria-pressed={state.cosmetics.horn===id} className={state.cosmetics.horn===id?css.tabActive:''} onClick={()=>send({type:'setCosmetic',slot:'horn',id})}>{id[0].toUpperCase()+id.slice(1)}</button>)}</div><p className={css.small}>Rex likes a friendly or jazzy welcome when his favourite burger is on the menu.</p>
    <div className={css.actions}><button className={css.button} onClick={()=>open('truckMenu')}><DinerIcon name="book"/>Truck menu</button><button className={css.button} onClick={props.onShare}><DinerIcon name="gift"/>Save a postcard</button></div>
    <h3 className={css.sectionTitle}>In your garage</h3><div className={css.list}>{TRUCK_EQUIPMENT.filter(e=>state.equipment[e.id]?.truckOwned).map(e=><div className={css.row} key={e.id}><SmallIcon kind={e.id} tier={state.equipment[e.id].tier} label={equipmentDisplayName(e.id,state.equipment[e.id].tier)}/><div><h3>{equipmentDisplayName(e.id,state.equipment[e.id].tier)}</h3><p>Tier {state.equipment[e.id].tier} · {equipmentUpgradeDescription(e.id,state.equipment[e.id].tier)}</p></div></div>)}</div><p className={css.tiny}>Preparation upgrades reach tier {equipmentTierCap(state)} at your restaurant level. Roadside markets can offer an early tier-two find.</p><TruckExtras state={state} send={send}/>
  </DinerModal>;
  if(panel==='collections')return <DinerModal title="Stories worth keeping" eyebrow="The collection cabinet" onClose={close}>
    <div className={css.tabs}>{['all','regulars','passport','trophies'].map(t=><button key={t} className={tab===t?css.tabActive:''} onClick={()=>setTab(t)}>{t==='all'?'Your favourites':t[0].toUpperCase()+t.slice(1)}</button>)}</div>
    {(tab==='all'||tab==='regulars')&&<RegularBook state={state} send={send} openRecipes={()=>open('recipes')} openDecor={()=>open('catalogue')} openCook={()=>open('map')}/>}
{(tab==='all'||tab==='passport')&&<PassportBook state={state} openRecipes={()=>open('recipes')} openCook={()=>open('map')}/>}
    {(tab==='all'||tab==='trophies')&&<><h3 className={css.sectionTitle}>A shelf for the good days</h3><div className={css.list}>{state.collections.trophies.map(t=><div className={css.row} key={t}><DinerIcon name="star" size={32}/><div><h3>{t.replace(/[:_]/g,' ')}</h3><p>Earned by playing. Always yours.</p></div></div>)}</div>{!state.collections.trophies.length&&<p className={css.small}>Master a recipe or clear a finale to earn something for this shelf.</p>}</>}
  </DinerModal>;
  if(panel==='name')return <DinerModal title="Name your diner" eyebrow="Make it yours" onClose={close} footer={<><button className={css.button} onClick={close}>Cancel</button><button className={css.primary} onClick={()=>{if(send({type:'settings',name}))close();}}>Save name</button></>}><label className={css.field}>Restaurant name<input autoFocus aria-label="Restaurant name" maxLength={24} value={name} onChange={event=>setName(event.target.value)} onKeyDown={event=>{if(event.key==='Enter'&&send({type:'settings',name}))close();}}/></label><p className={css.small}>Free to change anytime · up to 24 characters. Friends see this name when you publish your diner. Your friend code stays the same.</p></DinerModal>;
  if(panel==='settings')return <DinerModal title="Make yourself comfortable" eyebrow="A few little settings" onClose={close}>
    <div className={css.row}><DinerIcon name="home"/><div><h3>{props.syncStatus==='guest'?'Saved on this device':props.syncStatus==='offline'?'Waiting for a connection':props.syncStatus==='saving'?'Saving your diner…':'Your connected diner'}</h3><p>{props.syncStatus==='guest'?'This development sandbox is saved only in this browser.':'Your wallet is your account. Sign-in uses a message signature, with no transaction or gas fee.'}</p></div>{props.serverEnabled&&<button className={css.button} disabled={props.syncStatus==='connecting'||props.syncStatus==='saved'||props.syncStatus==='saving'} onClick={()=>void props.connect()}>{props.syncStatus==='offline'?'Retry':'Reconnect account'}</button>}</div>
    <label className={css.field}>Your diner&apos;s name<input maxLength={24} value={name} onChange={event=>setName(event.target.value)}/></label><button className={css.button} onClick={()=>send({type:'settings',name})}>Save name</button>
    <h3 className={css.sectionTitle}>Play your way</h3><div className={css.row}><DinerIcon name="heart"/><div><h3>Cosy mode</h3><p>More patience, five strikes, and 20% fewer truck coins. Choose before a trip.</p></div><button className={state.settings.cosy?css.softButton:css.button} disabled={!!state.run} onClick={()=>send({type:'settings',cosy:!state.settings.cosy})}>{state.settings.cosy?'On':'Off'}</button></div><div className={css.row}><DinerIcon name={props.sound?'sound':'mute'}/><div><h3>Kitchen sounds</h3><p>A little sizzle, a little celebration.</p></div><button className={css.button} onClick={()=>props.setSound(!props.sound)}>{props.sound?'On':'Off'}</button></div>
    <label className={css.field}>Sound effects · {Math.round(props.effectsVolume*100)}%<input aria-label="Sound effects volume" type="range" min="0" max="1" step="0.05" value={props.effectsVolume} onChange={event=>props.setEffectsVolume(Number(event.target.value))}/></label>
    <div className={css.row}><DinerIcon name={props.musicOn?'sound':'mute'}/><div><h3>A little music</h3><p>Café Swing at home. Sunlit Groove on the road.</p></div><button className={css.button} onClick={()=>props.setMusicOn(!props.musicOn)}>{props.musicOn?'On':'Off'}</button></div>
    <label className={css.field}>Music · {Math.round(props.musicVolume*100)}%<input aria-label="Music volume" type="range" min="0" max="1" step="0.05" value={props.musicVolume} onChange={event=>props.setMusicVolume(Number(event.target.value))}/></label>
    <button className={css.button} onClick={()=>open('help')}>Cooking guide</button>
  </DinerModal>;
  if(panel==='help')return <DinerModal title="Good food, one step at a time" eyebrow="Your pocket cooking guide" onClose={close}>
    <div className={css.tabs}>{RECIPES.filter(r=>state.run?.menu.includes(r.id)||state.recipes[r.id]).map(recipe=><button key={recipe.id} className={helpRecipe===recipe.id?css.tabActive:''} onClick={()=>setHelpRecipe(recipe.id)}>{recipe.name}</button>)}</div>
    <div className={css.summary}><ModelIcon kind="food" recipeId={helpRecipe} label={RECIPE_BY_ID[helpRecipe]?.name}/><h3>{RECIPE_BY_ID[helpRecipe]?.name}</h3></div><ol className={css.stepList}>
      <li>Take {INGREDIENT_BY_ID[RECIPE_BY_ID[helpRecipe]?.ingredients[0]]?.name.toLowerCase()??'ingredients'} from the {ingredientSupply(RECIPE_BY_ID[helpRecipe]?.ingredients[0])==='fridge'?'fridge':'pantry'}.</li>
      {RECIPE_BY_ID[helpRecipe]?.steps.map((step,i)=><li key={i}>{step.station==='prep'&&RECIPE_BY_ID[helpRecipe].assemblyIngredients?.length?`Leave the cooked food on the prep counter. Fetch ${RECIPE_BY_ID[helpRecipe].assemblyIngredients!.map(id=>`${INGREDIENT_BY_ID[id].name.toLowerCase()} from the ${ingredientSupply(id)==='fridge'?'fridge':'pantry'}`).join(' and ')} one at a time and combine them.`:`${step.label} at the ${EQUIPMENT_BY_ID[step.station]?.name.toLowerCase()}.`} {step.action==='hold'?'Hold the nearby work control or E.':'You can do another job while it cooks.'}{step.station==='boiler'&&' When ready, tap to lift and drain the basket. Tap again to take the noodles to prep.'}</li>)}
      {helpRecipe==='fries'?<><li>Tap the ready fryer to raise its basket. One batch makes three orders.</li><li>Take an empty fries box and bring it to the raised basket for one portion.</li></>:<li>Take a clean {SERVING_VESSELS[recipeVessel(helpRecipe)].name} from its stand and bring it to your finished food.</li>}
      <li>Pick up the order and tap the guest’s table.</li><li>{helpRecipe==='fries'?'Clear the used carton and take it to the bin.':'Clear the used dish. Wash it in the sink to refill your limited supply.'}</li>
    </ol><p className={css.small}>Prep ingredients before opening to get ahead. Click to walk and interact. WASD / arrows to walk; E to interact or hold. You can pause at any time. Switching away pauses your service.</p>
  </DinerModal>;
  return <DinerModal title="A place on the street" eyebrow="Good neighbours, good food" onClose={close}><div className={css.empty}><DinerIcon name="friends" size={42}/><p>Your diner is growing a neighbourhood.</p><p className={css.small}>Connected visits use their own diner accounts. Local preview saves stay on this device.</p></div><button className={css.button} onClick={props.onShare}><DinerIcon name="gift"/>Save a restaurant postcard</button></DinerModal>;
}
