"use client";
import {PICNIC,predictCommunity,arrangeCommunity,type CommunityAttempt} from '@/lib/chef/diner/community-feast';
import {ModelIcon} from './ModelIcon';
import {predictRanked} from '@/lib/chef/diner/ranked-rally';
import {useEffect,useRef,useState} from 'react';
import {useAccount,useSignMessage} from 'wagmi';
import {DinerSync,type DinerSession} from './diner-sync';
import {DinerModal} from './DinerModal';
import DinerScene from './DinerScene';
import {serviceScene} from './scene-adapter';
import {serviceTargetIntent,serviceSupplyChoices,serviceAssemblyChoices,itemLabel} from '@/lib/chef/diner/service';
import {rankedActive,arrangeRanked,type RankedAttempt,type RankedLayout} from '@/lib/chef/diner/ranked-rally';
import {HoldAction} from './HoldAction';
import {useControls} from './ControlPreferences';
import {manualWorkKey} from '@/lib/chef/diner/controls';
import {RankedSync} from './ranked-sync';
import type {ServiceState,ServiceAction} from '@/lib/chef/diner/types';
import {makeStation,makeTable,stationFootprint,tableFootprint} from '@/lib/chef/diner/geometry';
import {RECIPE_BY_ID} from '@/lib/chef/diner/content';
import css from './diner.module.css';
import styles from './ranked-rally.module.css';

type Attempt=RankedAttempt|CommunityAttempt;
export function RankedRally({close,onTrophy,mode='ranked',onPlace}:{close:()=>void;onTrophy?:(session:DinerSession)=>Promise<void>;mode?:'ranked'|'community';onPlace?:()=>void}){
 const community=mode==='community',summaryPath=community?'community/status':'ranked/standings';
 const {controls}=useControls();
 const {address,chainId}=useAccount(),{signMessageAsync}=useSignMessage(),wallet=address?.toLowerCase();
 const walletRef=useRef(wallet);walletRef.current=wallet;
 const session=useRef<DinerSession|null>(null),client=useRef<RankedSync<Attempt>|null>(null);
 const [board,setBoard]=useState<any>(null),[attempt,setAttempt]=useState<Attempt|null>(null),[service,setService]=useState<ServiceState|null>(null),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[signed,setSigned]=useState(false),[bests,setBests]=useState<{week_id:string;score:number}[]>([]);
 const [contribution,setContribution]=useState(0),[entitled,setEntitled]=useState(false);
 const [selected,setSelected]=useState<string|null>(null),[seat,setSeat]=useState<string|undefined>(),[rotation,setRotation]=useState(0),[draft,setDraft]=useState<RankedLayout|null>(null),[supplies,setSupplies]=useState<string|null>(null);
 const request=async(path:string,body?:unknown)=>{const token=session.current?.accessToken;const response=await fetch(`/api/chef/diner/${path}`,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},body:body===undefined?undefined:JSON.stringify(body),cache:'no-store'});const data=await response.json();if(!response.ok)throw Object.assign(new Error(data.error??'The rally could not be reached.'),{status:response.status,retryAfterMs:data.retryAfterMs});return data;};
 const adopt=(a:Attempt)=>{if(a.wallet!==walletRef.current)return;client.current?.stop();setAttempt(a);setService(a.service);client.current=new RankedSync<Attempt>(a,localStorage,request,(s,next,message)=>{if(next.wallet!==walletRef.current)return;setService({...s});setAttempt(next);setStatus(message);},{base:mode,predict:community?predictCommunity:predictRanked});void client.current.flush();};
 useEffect(()=>{let active=true;void request(summaryPath).then(v=>{if(active)setBoard(v);}).catch(e=>{if(active)setStatus(e.message);});return()=>{active=false;};},[]);
 useEffect(()=>{client.current?.stop();client.current=null;session.current=null;setSigned(false);setContribution(0);setEntitled(false);setService(null);setAttempt(null);setStatus('');},[wallet]);
 useEffect(()=>{const timer=setInterval(()=>{const c=client.current;if(!c||document.hidden||c.blocked)return;if(rankedActive(c.service))c.send({type:'service',action:{type:'tick',ticks:1}});},50);const flush=setInterval(()=>void client.current?.flush(),500);const pause=()=>client.current?.pause();const hidden=()=>{if(document.hidden)pause();};window.addEventListener('blur',pause);document.addEventListener('visibilitychange',hidden);return()=>{clearInterval(timer);clearInterval(flush);pause();client.current?.stop();window.removeEventListener('blur',pause);document.removeEventListener('visibilitychange',hidden);};},[]);
 const send=(action:ServiceAction)=>client.current?.send({type:'service',action});
 const workPrevious=useRef<string|null>(null),work=service?manualWorkKey(service):null;
 useEffect(()=>{if(service?.chef.holding&&workPrevious.current!==work)send({type:'hold',active:false});workPrevious.current=work;},[work,service?.chef.holding]);
 useEffect(()=>{const down=(e:KeyboardEvent)=>{if(e.target instanceof HTMLInputElement||e.target instanceof HTMLSelectElement||e.repeat)return;const c=client.current;if(!c)return;const s=c.service,key=e.key.toLowerCase();if(key==='e'){e.preventDefault();if(manualWorkKey(s))send({type:'hold',active:controls.work==='toggle'?!s.chef.holding:true});}if(key===' '){e.preventDefault();send({type:s.phase==='paused'?'resume':'pause'});}const dirs:Record<string,[number,number]>={w:[0,-1],arrowup:[0,-1],s:[0,1],arrowdown:[0,1],a:[-1,0],arrowleft:[-1,0],d:[1,0],arrowright:[1,0]};if(dirs[key]){e.preventDefault();send({type:'move',x:Math.round(s.chef.x)+dirs[key][0],y:Math.round(s.chef.y)+dirs[key][1]});}};const up=(e:KeyboardEvent)=>{if(e.key.toLowerCase()==='e'&&controls.work==='hold')send({type:'hold',active:false});};window.addEventListener('keydown',down);window.addEventListener('keyup',up);return()=>{window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);};},[controls.work]);
 async function connect(){if(!wallet||!address)return;setBusy(true);setStatus('');const expected=wallet;
  try{let saved:DinerSession|null=null;try{saved=JSON.parse(localStorage.getItem(DinerSync.sessionKey(wallet))??'null');}catch{}
   if(saved?.wallet===wallet&&saved.expiresAt*1000>Date.now()+60000)session.current=saved;else{const challenge=await request('wallet/challenge',{address,chainId:chainId??1});if(walletRef.current!==expected)return;const signature=await signMessageAsync({message:challenge.message,account:address});if(walletRef.current!==expected)return;saved=await request('wallet/verify',{nonce:challenge.nonce,message:challenge.message,signature});session.current=saved;}
   if(walletRef.current!==expected||session.current?.wallet!==expected)return;localStorage.setItem(DinerSync.sessionKey(expected),JSON.stringify(session.current));const current=await request(`${mode}/current`);if(walletRef.current!==expected)return;setSigned(true);setBests(current.bests??[]);setContribution(current.personal??0);setEntitled(!!current.entitled);if(current.attempt)adopt(current.attempt);if(current.trophy&&session.current)await onTrophy?.(session.current);
  }catch(e){session.current=null;setStatus(e instanceof Error?e.message:'Sign-in did not finish.');}finally{setBusy(false);}
 }
 async function start(){if(!session.current)return;setBusy(true);try{const key=`dk-${mode}-start-v1:${wallet}`,id=localStorage.getItem(key)??crypto.randomUUID();localStorage.setItem(key,id);const data=await request(`${mode}/start`,{id});if(data.attempt.wallet!==walletRef.current)return;localStorage.removeItem(key);adopt(data.attempt);}catch(e){setStatus((e as Error).message);}finally{setBusy(false);}}
 const target=(id:string,seatId?:string)=>{setSelected(id);setSeat(seatId);if(!service||service.phase==='setup')return;const st=service.stations.find(s=>s.id===id);if(st&&['crate','fridge'].includes(st.kind)){setSupplies(id);send({type:'interact',targetId:id});return;}setSupplies(null);send({type:'interact',targetId:id,seatId});};
 const moveLayout=(x:number,y:number,turn=false)=>{if(!service||!selected)return;const next=structuredClone(draft??{stations:service.stations.map(({id,kind,x,y,facing})=>({id,kind,x,y,facing})),tables:service.tables.map(({id,x,y,capacity,rotation})=>({id,x,y,capacity,rotation}))});const p=next.stations.find(s=>s.id===selected)??next.tables.find(t=>t.id===selected);if(p){if(turn){if('facing'in p)p.facing=((p.facing+1)%4) as 0|1|2|3;else p.rotation=((p.rotation+1)%4) as 0|1|2|3;}else{p.x=x;p.y=y;}setDraft(next);}};
 let layoutError:string|null=null,shown=service;if(draft&&service){try{shown=(community?arrangeCommunity:arrangeRanked)(service,draft);}catch(e){layoutError=(e as Error).message;shown={...service,stations:draft.stations.map(p=>makeStation(p.id,p.kind,p.x,p.y,1,p.facing)),tables:draft.tables.map(p=>makeTable(p.id,p.x,p.y,p.capacity,1,p.rotation))};}}
 const scene=shown?serviceScene(shown,selected,'#b66751'):null;if(scene){scene.truckSetup=true;scene.previewInset=0;if(draft&&shown){const st=shown.stations.find(p=>p.id===selected),table=shown.tables.find(p=>p.id===selected);scene.tileHighlights=(st?stationFootprint(st):table?tableFootprint(table):[]).map(p=>({...p,valid:!layoutError}));}}
 const intent=service&&selected?serviceTargetIntent(service,selected,seat):null;
 const exit=()=>{client.current?.pause();close();};
 return <DinerModal title={community?PICNIC.name:'Weekly cooking rankings'} eyebrow={community?'Community feast · everyone’s meals count':'Verified cooking · equal equipment · no collectible advantage'} onClose={exit} wide>
 {!service?<>{community?<><ModelIcon kind={PICNIC.reward} label="Picnic commemorative plaque" size={100}/><p>Cook burgers and fries for six neighbours in a supplied kitchen. Prepare as long as you like.</p><p className={css.notice}>{board?.total??0} / {PICNIC.goal} shared meals · You added {contribution}. Contribute three meals to earn the plaque once the shared goal is reached.</p><p className={css.small}>Meals count even if you end an attempt early. No coins, ingredients, mastery or rally score; your restaurant and trip stay untouched.</p>{signed&&(entitled||contribution>=3&&(board?.total??0)>=PICNIC.goal)&&<button className={css.button} onClick={async()=>{try{const result=await request('community/claim',{});if(result.entitled&&session.current){await onTrophy?.(session.current);setEntitled(true);onPlace?.();}}catch(e){setStatus((e as Error).message);}}}>{entitled?'Place picnic plaque':'Claim & place picnic plaque'}</button>}</>:<><p>Everyone gets this week’s seed, burgers, fries, lemonade and the same loaned kitchen. Arrange before opening. Your restaurant and carried trip money stay separate.</p><p className={css.notice}>Score = guests paid × 100 + service coins + final combo × 10 − strikes × 75 + 500 for completing. Each wallet’s best verified attempt counts; equal scores share a rank.</p><p className={css.small}>Weeks change Monday at 00:00 UTC. An existing attempt has 30 minutes to finish for the previous board.</p></>}
 {board?.enabled?signed?<button disabled={busy} className={css.primary} onClick={()=>void start()}>{community?'Cook for the picnic':'Start ranked attempt'}</button>:<button disabled={busy||!wallet} className={css.primary} onClick={()=>void connect()}>{busy?'Checking your signature…':community?'Sign in for community cooking':'Sign in for ranked cooking'}</button>:<p className={css.notice}>{community?'The picnic kitchen is being prepared.':'Verified rallies are being prepared. Local practice remains available in Cook.'}</p>}<p className={css.small}>A message signature only. No transaction, gas fee or asset-spending permission. Signing in here never imports or replaces your beta restaurant.</p></>:

 <><div className={styles.scene}>{scene&&<DinerScene mode="truck" scene={scene} rotation={rotation} onRotate={setRotation} editing={service.phase==='setup'} showWorldHints={false} onTarget={target} onTile={(x,y)=>service.phase==='setup'?moveLayout(x,y):send({type:'move',x,y})}/>}</div><p className={css.small}>{itemLabel(service.chef.held)} · {service.paid}/{service.config.customers} paid · {service.strikes}/3 strikes · {service.notice}</p>
 {service.phase==='setup'?<div className={css.actions}><button className={css.button} disabled={!selected} onClick={()=>moveLayout(0,0,true)}>Rotate selected</button>{draft&&<><button className={css.button} onClick={()=>setDraft(null)}>Cancel move</button><button className={css.primary} disabled={!!layoutError} onClick={()=>{if(client.current?.send({type:'layout',...draft}))setDraft(null);}}>Confirm layout</button></>}<button className={css.primary} disabled={!!draft} onClick={()=>send({type:'prepare'})}>Prepare ingredients</button><button className={css.primary} disabled={!!draft} onClick={()=>send({type:'open'})}>Open service</button></div>:<div className={css.actions}>{service.phase==='preparing'&&<button className={css.primary} onClick={()=>send({type:'open'})}>Open service</button>}{rankedActive(service)&&<button className={css.button} onClick={()=>send({type:'pause'})}>Pause</button>}{service.phase==='paused'&&<button className={css.primary} onClick={()=>send({type:'resume'})}>Resume same attempt</button>}{intent&&rankedActive(service)&&(intent.hold?<HoldAction active={service.chef.holding} label='Hold to work' disabled={intent.disabled} onHold={active=>send({type:'hold',active})}/>:<button className={css.primary} disabled={intent.disabled} onClick={()=>target(selected!,seat)}>{intent.label}</button>)}</div>}
 {layoutError&&<p className={css.notice}>{layoutError}</p>}{supplies&&rankedActive(service)&&<div className={css.actions}>{serviceSupplyChoices(service,supplies).map(c=><button key={c.ingredientId} className={css.button} onClick={()=>{send({type:'interact',targetId:supplies,ingredientId:c.ingredientId,recipeId:c.recipeId});setSupplies(null);}}>{c.name}</button>)}</div>}{selected&&serviceAssemblyChoices(service).length>1&&<div className={css.actions}>{serviceAssemblyChoices(service).map(id=><button key={id} className={css.button} onClick={()=>send({type:'interact',targetId:selected,recipeId:id})}>{RECIPE_BY_ID[id].name}</button>)}</div>}
 {attempt?.status==='active'&&['complete','failed'].includes(service.phase)&&<button className={css.primary} onClick={()=>{client.current?.send({type:'finish'});void client.current?.flush();}}>Verify this result</button> }{attempt?.status==='complete'&&<><p className={css.notice}>{community?`You added ${attempt.service.served} verified meals.`:'score' in attempt?`Verified score: ${attempt.score}. ${attempt.eligible?'Eligible for this week’s board.':'Personal result only.'}`:''}</p><button className={css.button} onClick={async()=>{if(!community&&session.current)void onTrophy?.(session.current).catch(e=>setStatus((e as Error).message));setService(null);setAttempt(null);try{setBoard(await request(summaryPath));if(community){const current=await request('community/current');setContribution(current.personal??0);setEntitled(!!current.entitled);}}catch(e){setStatus((e as Error).message);}}}>{community?'See picnic progress':'Back to rankings'}</button></>}{attempt?.status==='active'&&<button className={css.quietLink} onClick={()=>{client.current?.send({type:'abandon'});void client.current?.flush();}}>{community?'End attempt · keep verified meal contributions':'End this attempt without a result'}</button>}{attempt?.status==='abandoned'&&<><p>{community?`You added ${attempt.service.served} verified meals.`:''}</p><button className={css.button} onClick={async()=>{setService(null);setAttempt(null);try{setBoard(await request(summaryPath));if(community){const current=await request('community/current');setContribution(current.personal??0);setEntitled(!!current.entitled);}}catch(e){setStatus((e as Error).message);}}}>{community?'See picnic progress':'Back to rankings'}</button></>}
</>}
 {status&&<p role="status" className={css.notice}>{status}</p>}{client.current?.blocked&&<button className={css.button} onClick={()=>void client.current?.flush()}>Retry saved actions</button>}
 {!service&&!community&&<><h3 className={css.sectionTitle}>This week’s best verified attempts</h3><table className={styles.board}><thead><tr><th>Rank</th><th>Wallet</th><th>Score</th></tr></thead><tbody>{(board?.standings??[]).map((r:any,i:number)=><tr key={i}><td>{r.rank}</td><td>{r.wallet_label}</td><td>{r.score}</td></tr>)}</tbody></table>{board?.enabled&&!board.standings?.length&&<p>No verified attempts yet this week.</p>}{bests.length>0&&<p>Your verified bests: {bests.map(b=>`${b.week_id}: ${b.score}`).join(' · ')}</p>}</>}
 </DinerModal>;
}
