/**
 * BATTLE BOTS RIG POINTS. GENERATED by scripts/bots-bake-parts.mjs; do not
 * edit by hand. Re-run the bake to change a point, because the placeholder
 * art, the rig (rig.ts) and the art gate (scripts/bots-art-check.mts) must
 * all read the same numbers. All coordinates are @2x canvas pixels.
 *
 * THE CONCEPT CONTRACT (2026-09-04). Every canvas and every pivot below is
 * derived from FIGURE, the ratios measured off art-src/bots/concept/ scenes
 * 1, 3, 4 and 5. Pivots come from the band TARGETS, because where two parts
 * meet must be identical for every family and every tier. Canvases come from
 * the band MAXIMA plus a 8 px margin on every side, because a canvas
 * that holds the band max can hold any design the contract permits, and
 * because 25 of the 40 parts on the previous contract were clipped flat by
 * their own canvas.
 */

export type Pt = readonly [number, number];

/**
 * The figure contract: min / target / max as fractions of H, the assembled
 * height from the head dome apex to the lowest foot pixel. Measured on six
 * bots, about +/-1.3 percent of height. The art gate reads these, rather
 * than carrying its own copy, per the gates-must-import law.
 */
export const FIGURE = {
  H: 560,
  /** head art continues this far below its seat, torso art this far above its neck */
  skirt: 56,
  /**
   * The head's TARGET apex row inside its own canvas. The canvas carries the
   * margin plus the room a band-max head needs, so the drawn crown of an
   * on-target head starts here and not at row 0. Anything measuring the
   * figure's height has to subtract it, or it reads the empty headroom as
   * bot: rig.ts's RIG_HEIGHT measures to the head canvas's TOP, which is
   * 27 units of nothing.
   */
  headApexY: 27,
  /** the margin every canvas carries so no drawn pixel can reach an edge */
  margin: 8,
  /**
   * THE BRASS BUDGET. Exactly one brass piece per bot and it belongs to the
   * torso: the wind-up key. Nothing else on the figure is metal. Target under
   * 4 percent of a part's visible surface; for scale, the style anchor B1
   * measures 5.3 percent and the bots shipped before this bake measured 18.9
   * to 21.5. Seven gold rings on one bot is why it read as clockwork rather
   * than as a vinyl toy.
   */
  brassBudget: 0.04,
  /**
   * Saturation floor that separates METAL from the other two warm accents.
   * All three sit inside the paintable law's brass hue band, so hue cannot
   * tell them apart, and value cannot either once the ramp has run over them.
   * Saturation can, and it is the one channel a pure multiply leaves alone:
   * brass measures 0.70, the grille 0.50 and the eye lens 0.19, so a floor at
   * 0.60 has 0.10 of clearance on both sides and holds at every depth.
   */
  metalSatMin: 0.6,
  ratio: {
  headsTall: { min: 1.828, target: 1.944, max: 2.212 },
  headH: { min: 0.452, target: 0.515, max: 0.547 },
  headCoreW: { min: 0.529, target: 0.586, max: 0.694 },
  headFullW: { min: 0.529, target: 0.725, max: 0.78 },
  headCoreOverH: { min: 1.03, target: 1.185, max: 1.31 },
  headOverBody: { min: 1.267, target: 1.389, max: 1.583 },
  bodyH: { min: 0.242, target: 0.278, max: 0.333 },
  bodyW: { min: 0.379, target: 0.429, max: 0.474 },
  bodyWOverH: { min: 1.137, target: 1.565, max: 1.703 },
  legH: { min: 0.185, target: 0.21, max: 0.243 },
  footH: { min: 0.1, target: 0.174, max: 0.23 },
  footW: { min: 0.192, target: 0.271, max: 0.309 },
  stanceW: { min: 0.469, target: 0.53, max: 0.662 },
  armW: { min: 0.129, target: 0.15, max: 0.189 },
  armL: { min: 0.203, target: 0.216, max: 0.263 },
  armLOverW: { min: 1.071, target: 1.333, max: 1.818 },
  shoulderW: { min: 0.375, target: 0.594, max: 0.649 },
  shoulderY: { min: 0.379, target: 0.545, max: 0.576 },
  hipY: { min: 0.757, target: 0.79, max: 0.815 },
  },
} as const;

export const RIG = {
  head: { w: 456, h: 384, neck: [228, 315] },
  torso: { w: 288, h: 264, neck: [144, 64], shoulderL: [-23, 81], shoulderR: [311, 81], hipL: [94, 218], hipR: [194, 218], decal: [144, 148] },
  arm: { w: 128, h: 280, shoulder: [64, 63], hand: [64, 184] },
  leg: { w: 192, h: 280, hip: [70, 63], foot: [70, 181] },
  weapon: { w: 240, h: 136, grip: [38, 68] },
} as const;

/**
 * THE JOIN. THERE IS NO JOINT.
 *
 * Eight shoulders and hips cropped and enlarged from the concept scenes carry
 * the same thing every time: a plain rounded cap in the limb's own colour,
 * overlapped by the body group, one soft occlusion wash, and no hardware
 * anywhere. It works because the head is wider than the body, so the HEAD
 * hides the shoulder. Every ring, cup, collar, socket and bolt the previous
 * law drew is deleted from the art. A joint that needs hardware to read is a
 * joint drawn at the wrong size.
 *
 * Rendering only: the fight sim never reads any of it, and an art change that
 * moves a replay hash is a defect.
 */
export const JOIN = {
  /** the limb's end cap radius, x that limb's own width */
  capR: 0.5,
  /** the body silhouette buries the cap by this fraction of the limb's width */
  burialMin: 0.35,
  burial: 0.5,
  burialMax: 0.6,
  /** the wash value at the seam, back to 1.00 one limb width away */
  occlusion: 0.55,
  /** a shallow moulded cuff is the only decoration allowed at a joint */
  cuffMax: 0.12,
  /** a broken limb leaves a SCAR CHIP clamped to the body silhouette, never
   *  a black socket disc: body colour lightened and desaturated, with a one
   *  unit darker rim on its lower edge. */
  scarW: 0.6,
  scarH: 0.25,
  scarLighten: 0.15,
  scarDesat: 0.3,
  /** an unfitted slot on the build screen: the same chip, no rim */
  ghostAlpha: 0.4,
  /** limbs go BEHIND the body group and the head draws last, covering the caps */
  drawOrder: ["legL", "legR", "armL", "armR", "torso", "head", "weapon"],
} as const;

/**
 * THE LIGHT. One soft key from directly above. The ramp is applied once
 * across a whole part, never per shape, and it is purely vertical so it is
 * identical whatever family a part came from. Parts are rendered NEUTRAL: the
 * scene applies the warm grade, because baking it in turns eight paints into
 * eight muds.
 */
export const LIGHT = {
  /** 1.00 over the top quarter, falling to 0.48 at the form's base */
  rampTop: 1.0,
  rampBottom: 0.48,
  /** the torso's top band sits at this fraction of the head's base value,
   *  because the head shades it. The strongest one-body cue available. */
  headShadowOnTorso: 0.48,
  /** side to side, at most: the ramp must stay vertical or a mirrored limb
   *  flips its light */
  lateralMax: 1.25,
} as const;

/**
 * DEPRECATED, and kept only so src/app/bots/_view/rig.ts,
 * scripts/bots-gen-kit.mjs and scripts/bots-import-parts.py keep resolving
 * while the rig and generation lanes move to JOIN above. NOTHING IN THE ART
 * DRAWS ANY OF IT ANY MORE: the bake stopped drawing balls, cups, collars,
 * rings and bolts on 2026-09-04. Values are frozen at their last drawn
 * numbers so no consumer changes behaviour by accident; delete this block
 * once rig.ts stops drawing socket fittings.
 */
export const JOINT = {
  ballR: 25,
  ballDrop: 5,
  socketCoreR: 16,
  socketRingR: 31,
  neckCoreR: 12,
  neckRingR: 31,
  boltR: 9,
  pegW: 44,
  pegH: 32,
  armShaft: [34, 37, 40, 43],
  legShaft: [36, 39, 42, 45],
  footW: [58, 62, 67, 72],
} as const;

/** DEPRECATED with JOINT above: the torso draws no socket fittings any more. */
export const LIMB_SOCKETS = [
  { socket: "armL", at: RIG.torso.shoulderL },
  { socket: "armR", at: RIG.torso.shoulderR },
  { socket: "legL", at: RIG.torso.hipL },
  { socket: "legR", at: RIG.torso.hipR },
] as const;

export type ArtSlot = keyof typeof RIG;
export const ART_SLOTS: readonly ArtSlot[] = ["head", "torso", "arm", "leg", "weapon"];

/**
 * The torso's shoulder points fall OUTSIDE its canvas, because the arm centre
 * sits 0.08 H outboard of the torso edge and 0.065 H inboard of the head edge,
 * and that sandwich is what hides the cap. They are offsets, not pixels: the
 * art gate must not ask the torso PNG for ink at either of them.
 */
export const OFF_CANVAS: readonly string[] = ["shoulderL", "shoulderR"];

/** The scissor lift: two states on one canvas, bottom-aligned on the floor. */
export const LIFT = { w: 640, h: 420, topDown: 380, topRaised: 300, platformW: 600 } as const;

export const TIERS = [1, 2, 3, 4] as const;
export const DESIGNS = [1, 2] as const;

export const partFile = (slot: ArtSlot, tier: number, design: number): string =>
  `/bots-art/parts/${slot}/t${tier}-${design}.png`;
export const maskFile = (slot: ArtSlot, tier: number, design: number): string =>
  `/bots-art/parts/${slot}/t${tier}-${design}.mask.png`;
export const liftFile = (state: "down" | "raised"): string => `/bots-art/lift/${state}.png`;

/** Every rig point of a slot, named, for the gate. */
export function rigPointsNamed(slot: ArtSlot): { name: string; at: Pt }[] {
  const r = RIG[slot] as Record<string, unknown>;
  return Object.entries(r)
    .filter(([k]) => k !== "w" && k !== "h")
    .map(([name, v]) => ({ name, at: v as Pt }));
}

/** Every rig point of a slot, for the gate: each must land on opaque pixels. */
export function rigPoints(slot: ArtSlot): Pt[] {
  return rigPointsNamed(slot).map((p) => p.at);
}
