import {BODY_SOCKETS_V6,type SweepContactV6} from '@/lib/bots/v6/collision';
import {sweepRobotV7,sweepWeaponSegmentV7,earlierContactV7} from './collision';
import {canonicalRecordedV7} from './recording';
import {WEAPONS_V6} from '@/lib/bots/v6/weapons';
import {add,angle,clamp,cloneV6,hashV6,inverseQuatV6,length3,lerp,normalize,randomV6,rotateQuatV6,rotateY,scale,subtract,type Vec3} from '@/lib/bots/v6/math';
import {validBuildV7,RULES_VERSION_V7} from './build';
import {fighterPoseV7,actionPhaseV7} from './pose';
import {inversePointV7,markerV7,restNodesV7,worldNodesV7,transformPointV7} from './rig';
import type {ActionV7,AttackKindV7,BuildV7,EventV7,FighterPoseV7,FighterV7,FightOptionsV7,FootStateV7,PosedProxyV7,ResultV7,SideV7,SpecialCommandV7,SpecialReceiptV7,StateV7} from './types';
export const FPS_V7=60,MAX_FRAMES_V7=5400,AFTERMATH_FRAMES_V7=84;
export const RULES_V7=Object.freeze({rulesVersion:RULES_VERSION_V7,fps:FPS_V7,maxFrames:MAX_FRAMES_V7,aftermathFrames:AFTERMATH_FRAMES_V7,arenaRadius:6250,specialFrames:300,meterPerSecond:5,damageMeterPerCharge:40,stunFrames:24,knockdownFrames:72,protectionFrames:120,practiceOnly:true});
const other=(s:SideV7)=>(1-s) as SideV7,rootIdentity={x:0,z:0,yaw:0};
function emit(s:StateV7,event:Omit<EventV7,'id'|'frame'>):EventV7{const e=canonicalRecordedV7({...event,id:s.events.length,frame:s.frame});s.events.push(e);return e;}
const alive=(f:FighterV7,slot:number)=>f.armour[slot]>0;
const controlled=(s:StateV7,f:FighterV7)=>s.frame<f.stunnedUntil||s.frame<f.downUntil;
const specialActive=(s:StateV7,f:FighterV7,style:string)=>f.special?.style===style&&s.frame<f.special.until;
function emptyFoot():FootStateV7{return {plant:[0,0,0],from:[0,0,0],to:[0,0,0],started:0,until:0,lift:0,angle:0,planted:true};}
function initialFighter(build:BuildV7,side:SideV7,seed:number):FighterV7{return {x:side?3500:-3500,z:0,yaw:side?-1571:1571,moveX:0,moveZ:0,velocityX:0,velocityZ:0,turnVelocity:0,gait:0,random:((seed>>>0)^Math.imul(side+1,0x9e3779b9))>>>0||1,armour:[...build.stats.armour],guard:build.stats.guard,guardPose:0,heat:0,overheated:false,meter:0,damageMeter:0,action:null,special:null,nextAction:30,lastThreat:0,nextDodge:100,nextShove:0,nextMount:'right',stunnedUntil:0,downUntil:0,immuneUntil:0,slowUntil:0,dashUntil:0,dashX:0,dashZ:0,pushUntil:0,pushX:0,pushZ:0,reaction:null,feet:{left:emptyFoot(),right:emptyFoot()},nextFoot:'left',motionTrail:[],shots:0,dealt:0};}
export function createFightV7(builds:[BuildV7,BuildV7],seed:number,options:FightOptionsV7={}):StateV7 {
  if(!Number.isSafeInteger(seed)||builds.length!==2||!builds.every(validBuildV7))throw new Error('The saved remaster build does not match its installed rig and rules.');
  if(options.autoSpecial&&(!Array.isArray(options.autoSpecial)||options.autoSpecial.length!==2||options.autoSpecial.some(v=>typeof v!=='boolean'))||options.defensePlans&&(!Array.isArray(options.defensePlans)||options.defensePlans.length!==2||options.defensePlans.some(v=>!['early','balanced','last-stand'].includes(v))))throw new Error('Choose valid Special controls for both robots.');
  if(builds[0].rigVersion!==builds[1].rigVersion)throw new Error('Choose heroes from the same rig version.');
  const b=builds[0],s:StateV7={version:7,rulesVersion:RULES_VERSION_V7,rigVersion:b.rigVersion,motionVersion:b.motionVersion,collisionVersion:b.collisionVersion,presentationVersion:b.presentationVersion,seed:seed>>>0,frame:0,done:false,winner:null,builds:cloneV6(builds),stats:cloneV6([builds[0].stats,builds[1].stats]),fighters:[initialFighter(builds[0],0,seed),initialFighter(builds[1],1,seed)],events:[],commands:[],projectiles:[],burstBudgets:{},autoSpecial:options.autoSpecial??[false,true],defensePlans:options.defensePlans??['balanced','balanced'],attackSequence:0};
  for(const side of [0,1] as const){const f=s.fighters[side],rig=builds[side].rig,nodes=restNodesV7(rig);nodes.root.position=[f.x,0,f.z];nodes.root.quaternion=[0,Math.sin(f.yaw/2000),0,Math.cos(f.yaw/2000)];const world=worldNodesV7(rig,nodes);for(const suffix of ['L','R'] as const){const which=suffix==='L'?'left':'right',p=markerV7(rig,world,'sole'+suffix);f.feet[which]={...emptyFoot(),plant:p,from:[...p],to:[...p]};}}
  emit(s,{kind:'start',who:0,target:1});return s;
}
function startSpecial(s:StateV7,who:SideV7){const f=s.fighters[who],b=s.builds[who];f.meter=0;f.damageMeter=0;f.special={style:b.style,started:s.frame,until:s.frame+300,shieldLeft:s.stats[who].armour[1]*.35,finisherUsed:false,burstBudget:WEAPONS_V6.ap_rifle.damage*2*s.stats[who].power};emit(s,{kind:'special_start',who,target:other(who),ability:b.style});}
export function acceptSpecialV7(s:StateV7,command:SpecialCommandV7):SpecialReceiptV7{
  if(!command||typeof command.id!=='string'||!/^[a-zA-Z0-9_.:-]{1,100}$/.test(command.id)||![0,1].includes(command.who)||command.kind!=='special'||command.frame!==s.frame)return {accepted:false,reason:'This Special input does not match the current fight frame.'};
  const prior=s.commands.find(c=>c.id===command.id);if(prior)return JSON.stringify(prior)===JSON.stringify(command)?{accepted:true,command:cloneV6(prior)}:{accepted:false,reason:'That input ID is already used.'};
  const f=s.fighters[command.who];if(s.done)return {accepted:false,reason:'This fight has finished.'};if(controlled(s,f))return {accepted:false,reason:'Wait until your robot recovers.'};if(f.special)return {accepted:false,reason:'Your Special is already running.'};if(f.meter<100)return {accepted:false,reason:'Your Special is still charging.'};
  const saved=cloneV6(command);s.commands.push(saved);startSpecial(s,command.who);return {accepted:true,command:saved};
}
function chooseSpecial(s:StateV7,who:SideV7){const f=s.fighters[who];if(!s.autoSpecial[who]||f.special||f.meter<100||controlled(s,f))return;const plan=s.defensePlans[who],health=f.armour[1]/s.stats[who].armour[1],r=s.fighters[other(who)],distance=Math.hypot(r.x-f.x,r.z-f.z);if(plan==='early'||plan==='last-stand'&&health<.35||plan==='balanced'&&(health<.72||distance<1900))startSpecial(s,who);}
function cancelAction(s:StateV7,who:SideV7,sourcePose?:FighterPoseV7){const f=s.fighters[who];if(f.action){const p=sourcePose??fighterPoseV7(s,who),keys=['chest','head','shoulderL','shoulderR','elbowL','elbowR','wristL','wristR','handL','handR'];f.interruptedPose={started:s.frame,until:s.frame+14,rotations:Object.fromEntries(keys.map(key=>[key,[...p.nodes[key].quaternion]]))};emit(s,{kind:'interrupt',who,target:other(who),attackId:f.action.id,weapon:f.action.kind});f.action=null;f.nextAction=Math.max(f.nextAction,s.frame+14);}}
function detachPose(s:StateV7,target:SideV7,slot:string,pose:FighterPoseV7):EventV7['detachPose']{const branch=slot==='head'?'head':slot==='armL'?'shoulderL':slot==='armR'?'shoulderR':slot==='legL'?'hipL':slot==='legR'?'hipR':null;if(!branch)return undefined;const rig=s.builds[target].rig,nodes:Record<string,typeof pose.root>={};for(const [key,n] of Object.entries(pose.nodes)){let p:string|null=key;while(p){if(p===branch){nodes[key]=cloneV6(n);break;}p=rig.nodes[p]?.parent??null;}}return {node:branch,world:cloneV6(pose.worldNodes[branch]),nodes};}
function startAction(s:StateV7,who:SideV7,kind:AttackKindV7,special?:ActionV7['special']){
  const f=s.fighters[who],r=s.fighters[other(who)],b=s.builds[who],w=b.capabilities.weaponDefinition,rate=s.stats[who].attackRate*(specialActive(s,f,'speed')?1.2:1)*(specialActive(s,r,'ranged')?.7:1),mount=kind==='shoulder_cannon'?'shoulder':kind==='special_burst'||b.capabilities.paired?alive(f,f.nextMount==='right'?3:2)?f.nextMount:f.nextMount==='right'?'left':'right':alive(f,3)?'right':'left';
  if(mount!=='shoulder'&&!alive(f,mount==='right'?3:2))return;
  const short=kind==='punch'||kind==='shove',windup=short?14:kind==='backup_pistol'?18:kind==='special_burst'?22:kind==='special_charge'?35:kind==='special_flank'?24:Math.round(w.windup/rate),active=short?7:kind==='backup_pistol'?2:kind==='special_burst'?45:kind==='special_charge'?18:kind==='special_flank'?14:w.active,recovery=short?24:kind==='backup_pistol'?32:kind==='special_burst'?10:kind==='special_charge'?20:kind==='special_flank'?18:Math.round(w.recovery/rate),error=(randomV6(f,2001)-1000)/1000*s.stats[who].aimError;
  f.action={id:++s.attackSequence,kind,mount,started:s.frame,windup,active,recovery,released:false,hitTargets:[],aim:torsoAim(s,other(who)),aimError:[error,Math.round(error*.5),0],critical:randomV6(f,100)<Math.min(20,s.stats[who].luck),special,emissions:0,nextPulse:0,burstBudget:f.special?.burstBudget??0};if(kind==='special_burst')s.burstBudgets[String(f.action.id)]=f.action.burstBudget;f.nextMount=mount==='right'?'left':'right';emit(s,{kind:'windup',who,target:other(who),attackId:f.action.id,weapon:kind,mount});
}
function decisions(s:StateV7,who:SideV7){const f=s.fighters[who],r=s.fighters[other(who)],b=s.builds[who],dist=Math.hypot(r.x-f.x,r.z-f.z);if(f.action||s.frame<f.nextAction||controlled(s,f))return;
  const sp=f.special;if(sp&&!sp.finisherUsed&&s.frame>=sp.until-70){sp.finisherUsed=true;if(b.style==='tank'&&sp.shieldLeft>0&&alive(f,4)&&alive(f,5)){startAction(s,who,'special_charge','charge');return;}if(b.style==='speed'&&alive(f,4)&&alive(f,5)&&(alive(f,2)||alive(f,3))){startAction(s,who,'special_flank','flank');return;}if(b.style==='ranged'&&(alive(f,2)||alive(f,3))){startAction(s,who,'special_burst','burst');return;}}
  if(sp&&!sp.finisherUsed&&sp.until-s.frame<140)return;
  if(b.style==='ranged'){if(dist<1400&&s.frame>=f.nextShove&&(alive(f,2)||alive(f,3))){startAction(s,who,'shove');f.nextShove=s.frame+125;return;}if(dist<1900&&alive(f,3)){startAction(s,who,'backup_pistol');return;}if(!f.overheated&&dist<6000)startAction(s,who,'shoulder_cannon');return;}
  const armed=alive(f,3)||b.capabilities.paired&&alive(f,2);
  if(armed&&dist<1750)startAction(s,who,b.capabilities.weapon);else if(!armed&&alive(f,2)&&dist<1180)startAction(s,who,'punch');
}
function updateFeet(s:StateV7,who:SideV7){const f=s.fighters[who],rig=s.builds[who].rig,rest=worldNodesV7(rig,restNodesV7(rig)),speed=Math.hypot(f.velocityX,f.velocityZ),yaw=f.yaw;
  for(const suffix of ['L','R'] as const){const which=suffix==='L'?'left':'right',foot=f.feet[which],base=markerV7(rig,rest,'sole'+suffix),relative=rotateY(base,yaw),desired:Vec3=[f.x+relative[0],base[1],f.z+relative[2]];
    if(rig.legKind[which]==='wheel'){foot.angle+=Math.hypot(f.moveX,f.moveZ)/91*(f.velocityX*Math.sin(yaw/1000)+f.velocityZ*Math.cos(yaw/1000)>=0?1:-1);foot.plant=desired;foot.from=desired;foot.to=desired;foot.planted=true;continue;}
    if(!foot.planted&&s.frame>=foot.until){foot.planted=true;foot.plant=[...foot.to];emit(s,{kind:'land',who,target:who,slot:suffix==='L'?'legL':'legR',worldPoint:[...foot.plant]});}
    if(!alive(f,suffix==='L'?4:5)||controlled(s,f))continue;
    const distance=Math.hypot(desired[0]-foot.plant[0],desired[2]-foot.plant[2]),otherFoot=f.feet[which==='left'?'right':'left'];if(foot.planted&&(otherFoot.planted||distance>350)&&(distance>70||distance>30&&speed<3)&&(f.nextFoot===which||distance>220)){
      const duration=speed>12?6:9;foot.from=[...foot.plant];foot.to=[desired[0]+f.moveX*duration*1.5,base[1],desired[2]+f.moveZ*duration*1.5];foot.started=s.frame;foot.until=s.frame+duration;foot.lift=s.builds[who].style==='tank'?90:120;foot.planted=false;f.nextFoot=which==='left'?'right':'left';
    }
  }
}
function movingFoot(f:FighterV7){return !f.feet.left.planted||!f.feet.right.planted;}
function torsoAim(s:StateV7,who:SideV7):Vec3{const p=fighterPoseV7(s,who).proxies.find(p=>p.slot==='torso'&&p.node==='chest');return p?[...p.center]:[s.fighters[who].x,1300,s.fighters[who].z];}
function move(s:StateV7,who:SideV7){const f=s.fighters[who],r=s.fighters[other(who)],b=s.builds[who],dx=r.x-f.x,dz=r.z-f.z,dist=Math.max(1,Math.hypot(dx,dz)),dir:Vec3=[dx/dist,0,dz/dist],blocked=controlled(s,f),legs=(alive(f,4)?1:0)+(alive(f,5)?1:0),phase=actionPhaseV7(f.action,s.frame),ranged=b.style==='ranged';let desiredX=0,desiredZ=0;
  const threat=r.action;if(threat&&f.lastThreat!==threat.id&&s.frame>=threat.started+threat.windup-12){f.lastThreat=threat.id;if(!blocked&&legs===2&&s.frame>=f.nextDodge&&dist<2000&&(!f.action||phase.phase==='recover')&&randomV6(f,100)<Math.min(60,s.stats[who].evasion+(specialActive(s,f,'speed')?15:0))){const sign=randomV6(f,2)?1:-1;f.dashX=-dir[2]*sign;f.dashZ=dir[0]*sign;f.dashUntil=s.frame+10;f.nextDodge=s.frame+95;emit(s,{kind:'dodge',who,target:other(who)});}}
  const targetYaw=Math.atan2(dx,dz)*1000,turn=angle((targetYaw-f.yaw)/1000)*1000,maxTurn=s.stats[who].turnRate*(specialActive(s,r,'ranged')?.7:1)*(blocked?.12:1),wantedTurn=clamp(turn,-maxTurn,maxTurn);f.turnVelocity+=clamp(wantedTurn-f.turnVelocity,-12,12);f.yaw=Math.round(angle((f.yaw+f.turnVelocity)/1000)*1000);
  if(!blocked&&legs){const meleeStandoff=alive(f,3)||b.capabilities.paired&&alive(f,2)?1500:980;let forward=ranged?dist<2450?-1:dist>3600?1:0:dist>meleeStandoff?1:dist<850?-.6:0,strafe=0;
    if(ranged&&dist<2400)strafe=(who?1:-1)*.45;else if(b.style==='speed'&&dist<2200)strafe=Math.sin((s.frame+who*90)/105)*(specialActive(s,f,'speed')?.9:.35);
    if(f.action?.special==='flank'){forward=dist>1100?.5:0;strafe=(who?1:-1)*1.5;}if(f.action?.special==='charge'&&phase.phase==='contact')forward=2.5;
    const pace=s.stats[who].movement*(legs===1?.48:1)*(specialActive(s,f,'speed')?1.5:1)*(specialActive(s,r,'ranged')?.7:1),compactRetreat=ranged&&(f.action?.kind==='backup_pistol'||f.action?.kind==='shove'||f.action?.kind==='special_burst'),actionWeight=compactRetreat?1:phase.phase==='contact'&&f.action?.special!=='charge'?.12:phase.phase==='prepare'?ranged?.35:.45:1;
    desiredX=(dir[0]*forward-dir[2]*strafe)*pace*actionWeight;desiredZ=(dir[2]*forward+dir[0]*strafe)*pace*actionWeight;
    if(s.frame<f.dashUntil&&legs===2){desiredX=f.dashX*pace*1.5;desiredZ=f.dashZ*pace*1.5;}
  }
  const acceleration=blocked?7:b.style==='tank'?2.5:4;f.velocityX+=clamp(desiredX-f.velocityX,-acceleration,acceleration);f.velocityZ+=clamp(desiredZ-f.velocityZ,-acceleration,acceleration);
  const beforeX=f.x,beforeZ=f.z;f.x+=f.velocityX;f.z+=f.velocityZ;if(s.frame<f.pushUntil){f.x+=f.pushX;f.z+=f.pushZ;f.pushX*=.85;f.pushZ*=.85;}const radius=Math.hypot(f.x,f.z),limit=RULES_V7.arenaRadius-1000;if(radius>limit){f.x*=limit/radius;f.z*=limit/radius;f.velocityX*=.65;f.velocityZ*=.65;}
  f.x=Math.round(f.x);f.z=Math.round(f.z);f.velocityX=Math.round(f.velocityX*1000)/1000;f.velocityZ=Math.round(f.velocityZ*1000)/1000;f.moveX=f.x-beforeX;f.moveZ=f.z-beforeZ;f.gait+=Math.hypot(f.moveX,f.moveZ);
}
function separate(s:StateV7){const a=s.fighters[0],b=s.fighters[1],dx=b.x-a.x,dz=b.z-a.z,d=Math.hypot(dx,dz),min=900;if(d>=min)return;const nx=d?dx/d:1,nz=d?dz/d:0,push=(min-d)/2;a.x-=nx*push;a.z-=nz*push;b.x+=nx*push;b.z+=nz*push;}
interface ContactV7 {hit:SweepContactV6;proxy:PosedProxyV7}
function contact(s:StateV7,target:SideV7,old:FighterPoseV7,now:FighterPoseV7,from:Vec3,to:Vec3,radius:number,edgeFrom?:Vec3,edgeTo?:Vec3):ContactV7|null {let best:ContactV7|null=null;for(const p of now.proxies){if(!alive(s.fighters[target],BODY_SOCKETS_V6.indexOf(p.slot)))continue;const previous=old.proxies[p.proxyIndex]??p,hit=edgeFrom&&edgeTo?sweepWeaponSegmentV7(from,edgeFrom,to,edgeTo,rootIdentity,rootIdentity,[p],s.fighters[target].armour,radius,[previous]):sweepRobotV7(from,to,rootIdentity,rootIdentity,[p],s.fighters[target].armour,radius,[previous]);if(hit&&(!best||earlierContactV7(hit.t,best.hit.t)))best={hit,proxy:p};}return best;}
function applyHit(s:StateV7,who:SideV7,target:SideV7,c:ContactV7,pose:FighterPoseV7,attack:ActionV7|{id:number;kind:AttackKindV7;mount:'left'|'right'|'shoulder';critical?:boolean},baseDamage:number,impulse:number,bypass=0){const f=s.fighters[who],r=s.fighters[target],index=BODY_SOCKETS_V6.indexOf(c.hit.slot),stats=s.stats[target];if(!alive(r,index))return;
  let damage=baseDamage*s.stats[who].power*(specialActive(s,f,'speed')?1.25:1)*(attack.critical?1.35:1),absorbed=0;const shield=specialActive(s,r,'tank')?r.special:null;
  if(shield&&shield.shieldLeft>0){absorbed=Math.min(shield.shieldLeft,damage*.9);shield.shieldLeft-=absorbed;damage-=absorbed;if(shield.shieldLeft<=0&&r.action?.special==='charge')cancelAction(s,target);}else if(c.hit.slot==='armL'&&r.guardPose>.65&&r.guard>0&&!controlled(s,r)){absorbed=Math.min(r.guard,damage*.55);r.guard-=absorbed;damage-=absorbed;}
  damage*=1-stats.plating[index]*(1-bypass);damage=Math.min(r.armour[index],Math.max(1,Math.round(damage)));r.armour[index]-=damage;f.dealt+=damage;
  if(index===1&&!r.special){const gain=Math.min(40-r.damageMeter,damage/stats.armour[1]*100);r.damageMeter+=gain;r.meter=Math.min(100,r.meter+gain);}
  const normal=normalize(c.hit.normal),worldPoint=c.hit.point,node=c.proxy.node,localFrame=pose.worldNodes[node],direction=normalize([r.x-f.x,0,r.z-f.z]);r.reaction={kind:'hit',started:s.frame,direction,strength:clamp(damage/35,.25,1.3)};
  emit(s,{kind:absorbed?'block':'hit',who,target,attackId:attack.id,weapon:attack.kind,mount:attack.mount,slot:c.hit.slot,damage,absorbed,critical:attack.critical,node,point:inversePointV7(localFrame,worldPoint),normal:rotateQuatV6(normal,inverseQuatV6(localFrame.quaternion)),worldPoint,worldNormal:normal,impulse:scale(direction,impulse)});
  if(impulse>0){r.pushX=direction[0]*impulse*.08;r.pushZ=direction[2]*impulse*.08;r.pushUntil=s.frame+12;}
  if(attack.kind==='special_charge'&&s.frame>=r.immuneUntil){cancelAction(s,target,pose);r.downUntil=s.frame+72;r.immuneUntil=r.downUntil+120;r.reaction={kind:'knockdown',started:s.frame,direction,strength:1};emit(s,{kind:'knockdown',who:target,target:who,weapon:attack.kind,attackId:attack.id});}
  if(r.armour[index]<=0){emit(s,{kind:'break',who:target,target,slot:c.hit.slot,attackId:attack.id,weapon:attack.kind,node,worldPoint,worldNormal:normal,detachPose:detachPose(s,target,c.hit.slot,pose),impulse:scale(direction,Math.max(350,impulse))});if(r.action&&(index===2&&r.action.mount==='left'||index===3&&r.action.mount==='right'||index>=4&&r.action.special==='charge'))cancelAction(s,target);}
}
function fire(s:StateV7,who:SideV7,pose:FighterPoseV7,a:ActionV7){const f=s.fighters[who],w=s.builds[who].capabilities.weaponDefinition,m=pose.mounts[a.mount];if(!m?.aimable)return;const direction=m.forward,origin=m.muzzle,kind=a.kind,damage=kind==='backup_pistol'?18:kind==='special_burst'?11:w.damage,radius=kind==='shoulder_cannon'?w.projectileRadius:18;
  // The emitter must be outside every live opponent proxy; no arbitrary no-fire radius.
  const rivalPose=fighterPoseV7(s,other(who)),inside=contact(s,other(who),rivalPose,rivalPose,m.position,origin,radius);if(inside)return;
  const dir=normalize(direction),velocity=scale(dir,kind==='shoulder_cannon'?w.projectileSpeed:580);
  s.projectiles.push({id:a.id*100+a.emissions,attackId:a.id,who,weapon:kind,mount:a.mount,x:origin[0],y:origin[1],z:origin[2],vx:velocity[0],vy:velocity[1],vz:velocity[2],radius,ttl:35,damage,platingBypass:0,impulse:kind==='shoulder_cannon'?w.impulse:18});a.emissions++;if(a.kind==='special_burst'){a.shotsByMount??=[0,0];a.shotsByMount[a.mount==='left'?0:1]++;}f.shots++;f.heat+=kind==='shoulder_cannon'?w.heat:7;emit(s,{kind:'shot',who,target:other(who),attackId:a.id,weapon:kind,mount:a.mount,origin:[...origin],direction:dir});
}
function actions(s:StateV7,who:SideV7,prior:[FighterPoseV7,FighterPoseV7],poses:[FighterPoseV7,FighterPoseV7]){const f=s.fighters[who],a=f.action;if(!a)return;const age=s.frame-a.started,target=other(who),phase=actionPhaseV7(a,s.frame);if(age>=a.windup+a.active+a.recovery){f.action=null;f.nextAction=s.frame+4;return;}
  if(phase.phase==='prepare'){const r=s.fighters[target],chest=poses[target].proxies.find(p=>p.slot==='torso'&&p.node==='chest')?.center??[r.x,1300,r.z];a.aim=[chest[0]+r.velocityX*3,chest[1],chest[2]+r.velocityZ*3];return;}if(phase.phase!=='contact')return;
  if(a.kind==='shoulder_cannon'||a.kind==='backup_pistol'||a.kind==='special_burst'){if(!a.released||a.kind==='special_burst'&&s.frame>=a.nextPulse&&a.emissions<6){fire(s,who,poses[who],a);a.released=true;a.nextPulse=s.frame+7;if(a.kind==='special_burst'){const next=a.mount==='right'?'left':'right';if(alive(f,next==='right'?3:2)&&(a.shotsByMount?.[next==='left'?0:1]??0)<3)a.mount=next;else if((a.shotsByMount?.[a.mount==='left'?0:1]??0)>=3)a.nextPulse=MAX_FRAMES_V7+1;}}return;}
  if(a.hitTargets.length)return;const rig=s.builds[who].rig,suffix=a.mount==='left'?'L':'R',weaponNode='weapon'+suffix,oldPose=prior[who],newPose=poses[who];let from:Vec3,to:Vec3,oldEdge:Vec3|undefined,newEdge:Vec3|undefined,radius=rig.weapon.strikeRadius??100;
  if(a.kind==='punch'||a.kind==='shove'||a.kind==='special_charge'){const node=a.kind==='special_charge'?'chest':'hand'+suffix;from=oldPose.worldNodes[node].position;to=newPose.worldNodes[node].position;radius=a.kind==='special_charge'?460:115;}else if(rig.markers['weaponStrike'+suffix]&&newPose.worldNodes[weaponNode]){from=markerV7(rig,oldPose.worldNodes,'weaponStrike'+suffix);to=markerV7(rig,newPose.worldNodes,'weaponStrike'+suffix);if(a.kind!=='hammer'&&rig.markers['weaponHeel'+suffix]&&rig.markers['weaponTip'+suffix]){from=markerV7(rig,oldPose.worldNodes,'weaponHeel'+suffix);to=markerV7(rig,newPose.worldNodes,'weaponHeel'+suffix);oldEdge=markerV7(rig,oldPose.worldNodes,'weaponTip'+suffix);newEdge=markerV7(rig,newPose.worldNodes,'weaponTip'+suffix);}}else return;
  let c=contact(s,target,prior[target],poses[target],from,to,radius,oldEdge,newEdge);
  if(a.kind==='hammer'&&rig.weapon.strikeHalf){c=null;const marker=rig.markers['weaponStrike'+suffix],half=rig.weapon.strikeHalf,oldFrame=oldPose.worldNodes[marker.node],newFrame=newPose.worldNodes[marker.node],faceNormal=rotateQuatV6(marker.normal??[0,0,1],newFrame.quaternion),r=Math.min(half[2],half[1]/3);
    for(const row of [-1,-.5,0,.5,1]){const y=marker.position[1]+row*(half[1]-r),left:Vec3=[marker.position[0]-half[0]+r,y,marker.position[2]],right:Vec3=[marker.position[0]+half[0]-r,y,marker.position[2]],candidate=contact(s,target,prior[target],poses[target],transformPointV7(oldFrame,left),transformPointV7(newFrame,left),r,transformPointV7(oldFrame,right),transformPointV7(newFrame,right));if(candidate){const n=normalize(candidate.hit.normal);if(n[0]*faceNormal[0]+n[1]*faceNormal[1]+n[2]*faceNormal[2]<-.05&&(!c||earlierContactV7(candidate.hit.t,c.hit.t)))c=candidate;}}
  }
  if(!c)return;a.hitTargets.push(c.hit.slot);const w=s.builds[who].capabilities.weaponDefinition;let damage=a.kind==='shove'?6:a.kind==='punch'?15:a.kind==='special_charge'?34:a.kind==='special_flank'?w.damage*1.25:w.damage;const impulse=a.kind==='shove'?650:a.kind==='special_charge'?500:w.impulse;
  if(a.kind==='special_flank'){const victim=s.fighters[target],towards=normalize([f.x-victim.x,0,f.z-victim.z]),rear=towards[0]*Math.sin(victim.yaw/1000)+towards[2]*Math.cos(victim.yaw/1000)<-.4,index=BODY_SOCKETS_V6.indexOf(c.hit.slot);if(rear&&index>=2&&victim.armour[index]<s.stats[target].armour[index]*.25)damage=Math.max(damage,victim.armour[index]/Math.max(.01,s.stats[who].power*(specialActive(s,f,'speed')?1.25:1)*(1-s.stats[target].plating[index])));}
  applyHit(s,who,target,c,poses[target],a,damage,impulse);if(a.kind==='shove')emit(s,{kind:'shove',who,target,attackId:a.id,worldPoint:c.hit.point});
}
function projectiles(s:StateV7,prior:[FighterPoseV7,FighterPoseV7],poses:[FighterPoseV7,FighterPoseV7]){s.projectiles=s.projectiles.filter(p=>{const from:Vec3=[p.x,p.y,p.z],to:Vec3=[p.x+p.vx,p.y+p.vy,p.z+p.vz],target=other(p.who),c=contact(s,target,prior[target],poses[target],from,to,p.radius);if(c){const f=s.fighters[p.who],a=f.action,damage=p.weapon==='special_burst'?Math.min(p.damage,(s.burstBudgets[String(p.attackId)]??0)/Math.max(.1,s.stats[p.who].power)):p.damage;if(damage>0){applyHit(s,p.who,target,c,poses[target],{id:p.attackId,kind:p.weapon,mount:p.mount},damage,p.impulse,p.platingBypass);if(p.weapon==='special_burst')s.burstBudgets[String(p.attackId)]=Math.max(0,(s.burstBudgets[String(p.attackId)]??0)-damage*s.stats[p.who].power);}return false;}p.x=to[0];p.y=to[1];p.z=to[2];return --p.ttl>0&&Math.hypot(p.x,p.z)<8000;});}
function finish(s:StateV7){const losing=([0,1] as const).find(w=>{const f=s.fighters[w];return f.armour[1]<=0||f.armour[2]<=0&&f.armour[3]<=0&&s.builds[w].style!=='ranged';});if(losing!==undefined){const winner=other(losing),f=s.fighters[losing],r=s.fighters[winner];s.done=true;s.winner=winner;f.reaction={kind:'ko',started:s.frame,direction:normalize([f.x-r.x,0,f.z-r.z]),strength:1};emit(s,{kind:'ko',who:winner,target:losing,defeatReason:f.armour[1]<=0?'body':'disabled'});}else if(s.frame>=MAX_FRAMES_V7){s.done=true;s.winner=s.fighters[0].armour[1]/s.stats[0].armour[1]>=s.fighters[1].armour[1]/s.stats[1].armour[1]?0:1;emit(s,{kind:'timeout',who:s.winner,target:other(s.winner)});}}
export function stepFightV7(s:StateV7):StateV7{if(s.done)return s;const prior:[FighterPoseV7,FighterPoseV7]=[fighterPoseV7(s,0),fighterPoseV7(s,1)];s.frame++;
  for(const who of [0,1] as const){const f=s.fighters[who];if(f.special&&s.frame>=f.special.until){emit(s,{kind:'special_end',who,target:other(who),ability:f.special.style});f.special=null;}if(!f.special)f.meter=Math.min(100,f.meter+5/60);f.heat=Math.max(0,f.heat-s.stats[who].cooling);if(f.heat>=100&&!f.overheated){f.overheated=true;emit(s,{kind:'overheat',who,target:who});}if(f.overheated&&f.heat<35){f.overheated=false;emit(s,{kind:'cooled',who,target:who});}if(controlled(s,f))cancelAction(s,who);chooseSpecial(s,who);decisions(s,who);const available=alive(f,2)&&!s.builds[who].capabilities.paired&&!controlled(s,f)&&!(f.action?.mount==='left'),threat=s.fighters[other(who)].action,desiredGuard=available&&threat&&Math.hypot(f.x-s.fighters[other(who)].x,f.z-s.fighters[other(who)].z)<2200?1:0;f.guardPose+=clamp(desiredGuard-f.guardPose,-.06,.06);f.guard=Math.min(s.stats[who].guard,f.guard+.04);move(s,who);}
  separate(s);for(const who of [0,1] as const){const f=s.fighters[who];f.x=Math.round(f.x);f.z=Math.round(f.z);f.moveX=f.x-prior[who].root.position[0];f.moveZ=f.z-prior[who].root.position[2];if(s.frame%4===0){f.motionTrail.push({frame:s.frame,x:f.x,z:f.z});if(f.motionTrail.length>12)f.motionTrail.shift();}}updateFeet(s,0);updateFeet(s,1);const poses:[FighterPoseV7,FighterPoseV7]=[fighterPoseV7(s,0),fighterPoseV7(s,1)];actions(s,0,prior,poses);actions(s,1,prior,poses);projectiles(s,prior,poses);finish(s);return s;
}
export function advanceFightV7(s:StateV7,toFrame:number):StateV7{if(!Number.isSafeInteger(toFrame)||toFrame<s.frame)throw new Error('Advance to a later whole simulation frame.');while(!s.done&&s.frame<Math.min(MAX_FRAMES_V7,toFrame))stepFightV7(s);return s;}
export function resultV7(s:StateV7):ResultV7{if(!s.done||s.winner===null)throw new Error('The remaster fight is still running.');const result={version:7 as const,rulesVersion:s.rulesVersion,rigVersion:s.rigVersion,motionVersion:s.motionVersion,collisionVersion:s.collisionVersion,presentationVersion:s.presentationVersion,seed:s.seed,frames:s.frame,winner:s.winner,builds:cloneV6(s.builds),commands:cloneV6(s.commands),autoSpecial:cloneV6(s.autoSpecial),defensePlans:cloneV6(s.defensePlans),events:cloneV6(s.events)};return {...result,hash:hashV6(result)};}
export function replayV7(record:ResultV7):ResultV7{const {hash,...payload}=record;if(hashV6(payload)!==hash)throw new Error('The saved remaster result checksum is invalid.');const s=createFightV7(record.builds,record.seed,{autoSpecial:record.autoSpecial,defensePlans:record.defensePlans});let cursor=0;while(!s.done){while(record.commands[cursor]?.frame===s.frame){const receipt=acceptSpecialV7(s,record.commands[cursor++]);if(!receipt.accepted)throw new Error('The saved Special input cannot be replayed.');}stepFightV7(s);}const result=resultV7(s);if(result.hash!==record.hash)throw new Error('The remaster replay does not match its recorded result.');return result;}
