import type {StatsV6,DefensePlanV6,SpecialInfoV6,WeaponDefinitionV6,WeaponKindV6,AttackKindV6,EventKindV6} from '@/lib/bots/v6/types';
import type {Vec3,QuatV6} from '@/lib/bots/v6/math';
import type {BodySocketV6,HitProxyV6} from '@/lib/bots/v6/collision';
export type {Vec3};
export type QuatV7=QuatV6;export type SideV7=0|1;export type StyleV7='tank'|'speed'|'ranged';
export type BodySocketV7=BodySocketV6;export type StatsV7=StatsV6;export type DefensePlanV7=DefensePlanV6;export type AttackKindV7=AttackKindV6;
export interface NodeTransformV7 {position:Vec3;quaternion:QuatV7}
export interface RigNodeV7 extends NodeTransformV7 {parent:string|null}
export interface RigProxyV7 {slot:BodySocketV7;node:string;shape:'box'|'capsule';center:Vec3;half:Vec3;a?:Vec3;b?:Vec3;radius?:number}
export interface MarkerV7 {node:string;position:Vec3;normal?:Vec3}
export interface HeroRigV7 {id:string;style:StyleV7;modelUrl:string;nodes:Record<string,RigNodeV7>;proxies:RigProxyV7[];markers:Record<string,MarkerV7>;legKind:{left:'foot'|'spring'|'wheel';right:'foot'|'spring'|'wheel'};weapon:{kind:WeaponKindV6;node:string;leftNode?:string;strikeMarkers?:string[];strikeRadius?:number;strikeHalf?:Vec3;muzzleMarker?:string;backupNode?:string;backupMuzzleMarker?:string;backupLeftNode?:string;backupLeftMuzzleMarker?:string}}
export interface RigManifestV7 {version:string;motionVersion:string;collisionVersion:string;presentationVersion:string;units:'millimetres';heroes:Record<StyleV7,HeroRigV7>}
export interface BuildV7 {version:7;rulesVersion:'mk7-proof-3';rigVersion:string;motionVersion:string;collisionVersion:string;presentationVersion:string;manifestHash:string;style:StyleV7;tier:3;name:string;gp:350;stats:StatsV7;rig:HeroRigV7;capabilities:{special:SpecialInfoV6;tier3:true;weapon:WeaponKindV6;paired:boolean;mount:'right'|'shoulder';weaponDefinition:WeaponDefinitionV6}}
export interface FootStateV7 {plant:Vec3;from:Vec3;to:Vec3;started:number;until:number;lift:number;angle:number;planted:boolean}
export interface ReactionV7 {kind:'hit'|'stun'|'knockdown'|'ko';started:number;direction:Vec3;strength:number}
export interface ActionV7 {id:number;kind:AttackKindV7;mount:'left'|'right'|'shoulder';started:number;windup:number;active:number;recovery:number;released:boolean;hitTargets:BodySocketV7[];aim:Vec3;aimError:Vec3;critical:boolean;special?:'charge'|'flank'|'burst';emissions:number;shotsByMount?:[number,number];nextPulse:number;burstBudget:number}
export interface SpecialV7 {style:StyleV7;started:number;until:number;shieldLeft:number;finisherUsed:boolean;burstBudget:number}
export interface FighterV7 {x:number;z:number;yaw:number;moveX:number;moveZ:number;velocityX:number;velocityZ:number;turnVelocity:number;gait:number;random:number;armour:number[];guard:number;guardPose:number;heat:number;overheated:boolean;meter:number;damageMeter:number;action:ActionV7|null;special:SpecialV7|null;nextAction:number;lastThreat:number;nextDodge:number;nextShove:number;nextMount:'left'|'right';stunnedUntil:number;downUntil:number;immuneUntil:number;slowUntil:number;dashUntil:number;dashX:number;dashZ:number;pushUntil:number;pushX:number;pushZ:number;reaction:ReactionV7|null;interruptedPose?:{started:number;until:number;rotations:Record<string,QuatV7>};feet:{left:FootStateV7;right:FootStateV7};nextFoot:'left'|'right';motionTrail:{frame:number;x:number;z:number}[];shots:number;dealt:number}
export interface ProjectileV7 {id:number;attackId:number;who:SideV7;weapon:AttackKindV7;mount:'left'|'right'|'shoulder';x:number;y:number;z:number;vx:number;vy:number;vz:number;radius:number;ttl:number;damage:number;platingBypass:number;impulse:number}
export interface EventV7 {id:number;frame:number;kind:EventKindV6|'land';who:SideV7;target:SideV7;attackId?:number;weapon?:AttackKindV7;mount?:'left'|'right'|'shoulder';slot?:BodySocketV7;damage?:number;absorbed?:number;critical?:boolean;node?:string;detachPose?:{node:string;world:NodeTransformV7;nodes:Record<string,NodeTransformV7>};point?:Vec3;normal?:Vec3;worldPoint?:Vec3;worldNormal?:Vec3;origin?:Vec3;direction?:Vec3;impulse?:Vec3;ability?:StyleV7;defeatReason?:'body'|'disabled'}
export interface SpecialCommandV7 {id:string;who:SideV7;kind:'special';frame:number}
export interface SpecialReceiptV7 {accepted:boolean;reason?:string;command?:SpecialCommandV7}
export interface FightOptionsV7 {autoSpecial?:[boolean,boolean];defensePlans?:[DefensePlanV7,DefensePlanV7]}
export interface StateV7 {version:7;rulesVersion:'mk7-proof-3';rigVersion:string;motionVersion:string;collisionVersion:string;presentationVersion:string;seed:number;frame:number;done:boolean;winner:SideV7|null;builds:[BuildV7,BuildV7];stats:[StatsV7,StatsV7];fighters:[FighterV7,FighterV7];events:EventV7[];commands:SpecialCommandV7[];projectiles:ProjectileV7[];burstBudgets:Record<string,number>;autoSpecial:[boolean,boolean];defensePlans:[DefensePlanV7,DefensePlanV7];attackSequence:number}
export interface ResultV7 {version:7;rulesVersion:'mk7-proof-3';rigVersion:string;motionVersion:string;collisionVersion:string;presentationVersion:string;seed:number;frames:number;winner:SideV7;builds:[BuildV7,BuildV7];commands:SpecialCommandV7[];autoSpecial:[boolean,boolean];defensePlans:[DefensePlanV7,DefensePlanV7];hash:string;events:EventV7[]}
export interface PosedProxyV7 extends HitProxyV6 {node:string;proxyIndex:number}
export interface MountPoseV7 {node:string;position:Vec3;quaternion:QuatV7;muzzle:Vec3;forward:Vec3;aimable:boolean}
export interface FighterPoseV7 {nodes:Record<string,NodeTransformV7>;worldNodes:Record<string,NodeTransformV7>;proxies:PosedProxyV7[];mounts:Partial<Record<'left'|'right'|'shoulder',MountPoseV7>>;weapons:Partial<Record<'left'|'right'|'shoulder',NodeTransformV7>>;support:{feet:{left:Vec3;right:Vec3};planted:{left:boolean;right:boolean};maxReachError:number;reachErrors:Record<string,number>};root:NodeTransformV7;aftermath:number}
