'use client';
import {useEffect,useRef,useState,type CSSProperties,type PointerEvent as ReactPointer } from 'react';
import Link from 'next/link';
import {PitEngine } from '@/lib/bots/pit/engine';
import {verifyDrills } from '@/lib/bots/pit/drills';
import {fighter,loaner,rivalFor,moves } from '@/lib/bots/pit/moves';
import {DEFAULT_PREFERENCES,DEFAULT_BINDINGS,PREFERENCES_KEY,readPreferences,HeldInputs,keyName,keyboardBinding,bindCombatMouse,type PitPreferences,type Binding } from '@/lib/bots/pit/controls';
import {PIT_RULES,type Action,type Style,type Spec,type Options,type Packet } from '@/lib/bots/pit/types';
import {SAVE_KEY,readWorkshop,type Robot8 } from '@/lib/bots/workshop8/state';
import {ENTRY_MAP } from '@/lib/bots/workshop8/catalogue';
import type {createPitView,ViewSettings,MotionReview } from '@/lib/bots/pit/view';
import css from './reactor-pit.module.css';
type Match={fighters:[Spec,Spec];options:Options;key:number;replay?:Packet };
const STYLES:Style[]=['tank','speed','ranged'];
const NAMES={tank:'Heavy',speed:'Agile',ranged:'Ranged Tactician' };
const HELP={tank:'Hold your ground. Punish the opening.',speed:'Change the pace. Make every opening count.',ranged:'Own the distance. Make them come to you.' };
function Settings({value,onChange,onClose }:{value:PitPreferences;onChange(v:PitPreferences):void;onClose():void }){
 const [binding,setBinding]=useState<Binding|null>(null),[error,setError]=useState('');const dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{dialog.current?.showModal();return()=>dialog.current?.close() },[]);
 useEffect(()=>{if(!binding)return;const listen=(e:KeyboardEvent)=>{e.preventDefault();e.stopPropagation();if(e.code==='Escape'){setBinding(null);return; }const duplicate=(Object.keys(value.bindings) as Binding[]).find(k=>k!==binding&&value.bindings[k]===e.code);if(duplicate){setError(`Already used by ${duplicate }. Choose another key.`);return; }onChange({...value,bindings:{...value.bindings,[binding]:e.code } });setBinding(null);setError(''); };window.addEventListener('keydown',listen,true);return()=>window.removeEventListener('keydown',listen,true) },[binding,value,onChange]);
 const range=(key:'size'|'opacity'|'leftX'|'rightX'|'leftY'|'rightY'|'shake'|'musicVolume'|'effectsVolume',label:string,min:number,max:number,step:number)=><label>{label }<input type='range' aria-label={label } min={min } max={max } step={step } value={value[key] } onChange={e=>onChange({...value,[key]:Number(e.target.value) }) }/></label>;
 return <dialog ref={dialog } className={css.settings } onCancel={onClose }><header><h2>Your controls. Your pit.</h2><button onClick={onClose }>Done</button></header><div className={css.settingsGrid }><section><h3>Touch layout</h3><label><input type='checkbox' checked={value.touch } onChange={e=>onChange({...value,touch:e.target.checked }) }/>Always show touch controls</label><label><input type='checkbox' checked={value.dashButton } onChange={e=>onChange({...value,dashButton:e.target.checked }) }/>Dedicated dash button</label>{range('size','Button size',.8,1.25,.05) }{range('opacity','Button opacity',.35,1,.05) }{range('leftX','Movement horizontal position',-20,40,1) }{range('leftY','Movement vertical position',-20,40,1) }{range('rightX','Attack horizontal position',-20,40,1) }{range('rightY','Attack vertical position',-20,40,1) }</section><section><h3>Presentation</h3><label>Graphics<select value={value.quality } onChange={e=>onChange({...value,quality:e.target.value as PitPreferences['quality'] }) }><option value='auto'>Auto</option><option value='standard'>Standard</option><option value='low'>Low</option></select></label>{range('shake','Camera shake',0,1,.1) }{range('musicVolume','Music volume',0,1,.05) }{range('effectsVolume','Effects volume',0,1,.05) }<label><input type='checkbox' checked={value.reduced } onChange={e=>onChange({...value,reduced:e.target.checked }) }/>Reduced motion</label><label><input type='checkbox' checked={!value.flashes } onChange={e=>onChange({...value,flashes:!e.target.checked }) }/>Reduced flashes</label></section></div><details><summary>Remap keyboard</summary><p>{binding?`Press a key for ${binding }. Escape cancels.`:'Select an action, then press its new key.' }</p><div className={css.bindings }>{(Object.keys(value.bindings) as Binding[]).map(k=><button key={k } onClick={()=>setBinding(k) }>{k }<b>{keyName(value.bindings[k]) }</b></button>) }</div><p role='alert'>{error }</p></details><button onClick={()=>onChange(structuredClone(DEFAULT_PREFERENCES)) }>Reset settings</button></dialog>;
 }
export default function ReactorPit({ownedRobot,onClose }:{ownedRobot?:Robot8;onClose?:()=>void }){
 const [settings,setSettings]=useState(()=>structuredClone(DEFAULT_PREFERENCES)),[settingsOpen,setSettingsOpen]=useState(false),[style,setStyle]=useState<Style>('tank'),[rival,setRival]=useState<Style>('speed'),[difficulty,setDifficulty]=useState<Options['difficulty']>('normal'),[robots,setRobots]=useState<Robot8[]>(ownedRobot?[ownedRobot]:[]),[chosen,setChosen]=useState(ownedRobot?.id??''),[match,setMatch]=useState<Match|null>(null),[notice,setNotice]=useState('');
 useEffect(()=>{try{setSettings(readPreferences(JSON.parse(localStorage.getItem(PREFERENCES_KEY)||'null'))) }catch{ }if(ownedRobot)return;let alive=true;try{const saved=readWorkshop(localStorage.getItem(SAVE_KEY));if(saved)setRobots(saved.robots) }catch{ }
 const headers:Record<string,string>={ };try{const auth=JSON.parse(sessionStorage.getItem('mk8.wallet-session.v1')||'null');if(auth?.token)headers.Authorization='Bearer '+auth.token }catch{ }
 void fetch('/api/bots/workshop',{headers,cache:'no-store' }).then(r=>r.json()).then(v=>{if(alive&&v.ok&&v.state?.robots)setRobots(v.state.robots) }).catch(()=>{ });return()=>{alive=false }; },[ownedRobot]);
 const changeSettings=(v:PitPreferences)=>{setSettings(v);try{localStorage.setItem(PREFERENCES_KEY,JSON.stringify(v)) }catch{ } };
 function start(training=false){try{const own=robots.find(r=>r.id===chosen),a=own?fighter(own.name,own.choices,own.appearance):loaner(style),b=rivalFor(a,rival);setMatch({fighters:[a,b],options:{seed:crypto.getRandomValues(new Uint32Array(1))[0],difficulty,training,dummy:training?'idle':'ai',unlimited:training },key:Date.now() });setNotice(''); }catch(e){setNotice((e as Error).message) } }
 return <section className={css.root }><header className={css.top }><div><span>MODEL KOMBAT / UNDERGROUND LEAGUE</span><strong>REACTOR PIT</strong></div><nav><button onClick={()=>setSettingsOpen(true) }>Settings</button>{onClose?<button onClick={onClose }>Workshop</button>:<Link href='/bots/workshop?view=fight'>Workshop</Link> }</nav></header>{match?<PitMatch key={match.key } match={match } settings={settings } settingsOpen={settingsOpen } onSettings={()=>setSettingsOpen(true) } onBack={()=>setMatch(null) } onRematch={packet=>setMatch({...match,replay:packet,key:Date.now() }) }/>:<main className={css.selection }><div className={css.intro }><span>THREE WAYS TO OWN THE RING</span><h1>Built to fight.<br/><em>Ready when you are.</em></h1><p>Move. Read the opening. Make it hurt.</p><small>Free practice · No coins, repairs or prize points</small></div><div className={css.cards }>{STYLES.map(s=>{const spec=loaner(s),entry=ENTRY_MAP.get(spec.choices.torso)!;return <button className={`${css.card } ${!chosen&&s===style?css.selected:'' }` } aria-pressed={!chosen&&s===style } key={s } onClick={()=>{setChosen('');setStyle(s) } }><img src={`${entry.thumbnailRoot }/${entry.id }.whole.png` } alt={`${NAMES[s] } starter robot` }/><span>{NAMES[s] }</span><strong>{spec.name }</strong><p>{HELP[s] }</p><small>{spec.gp } GP · Free loaner</small></button> }) }</div><div className={css.setup }><label>Use my robot<select value={chosen } onChange={e=>setChosen(e.target.value) }><option value=''>Free loaner selected</option>{robots.map(r=><option key={r.id } value={r.id }>{r.name }</option>) }</select></label><label>Opponent<select value={rival } onChange={e=>setRival(e.target.value as Style) }>{STYLES.map(s=><option key={s } value={s }>{NAMES[s] }</option>) }</select></label><label>Difficulty<select value={difficulty } onChange={e=>setDifficulty(e.target.value as Options['difficulty']) }><option value='easy'>Easy · Find your feet</option><option value='normal'>Normal · Fight smart</option><option value='hard'>Hard · Make no promises</option></select></label><button className={css.primary } onClick={()=>start() }>Enter the pit →</button><button onClick={()=>start(true) }>Learn the moves</button></div><p className={css.note }>Your equipment matters. Opponents match your Gear Points. No wallet needed for loaners.</p>{notice&&<p role='alert'>{notice }</p> }</main> }{settingsOpen&&<Settings value={settings } onChange={changeSettings } onClose={()=>setSettingsOpen(false) }/> }</section>;
 }
function PitMatch({match,settings,settingsOpen,onSettings,onBack,onRematch }:{match:Match;settings:PitPreferences;settingsOpen:boolean;onSettings():void;onBack():void;onRematch(packet?:Packet):void }){
 const canvas=useRef<HTMLCanvasElement>(null),[simulation]=useState(()=>new PitEngine(match.fighters,match.options)),engine=useRef(simulation),view=useRef<Awaited<ReturnType<typeof createPitView>>|null>(null),preferences=useRef(settings),paused=useRef(true),settingsActive=useRef(settingsOpen),inputs=useRef<HeldInputs|null>(null),raf=useRef(0),last=useRef(0),accumulator=useRef(0),[loading,setLoading]=useState(0),[error,setError]=useState(''),[isPaused,setPaused]=useState(true),[started,setStarted]=useState(false),[touch,setTouch]=useState(false),[hud,setHud]=useState(0),[guide,setGuide]=useState(true),[showMoves,setShowMoves]=useState(false),[proof,setProof]=useState<ReturnType<typeof verifyDrills>[]>([]),[hitboxes,setHitboxes]=useState(false),[orientation,setOrientation]=useState(true),[lesson,setLesson]=useState(0);
 const [review,setReview]=useState<MotionReview|null>(null),reviewRef=useRef<MotionReview|null>(null);reviewRef.current=review;
 const [reviewPlaying,setReviewPlaying]=useState(false);
 useEffect(()=>{if(!reviewPlaying||!review||review.move==='guard')return;const timer=window.setInterval(()=>{if(document.hidden)return;setReview(current=>{if(!current||current.move==='guard')return current;const move=moves(match.fighters[0])[current.move];return {...current,frame:(current.frame+1)%(move.startup+move.active+move.recovery)};})},50);return()=>clearInterval(timer)},[reviewPlaying,review?.move]);
 const playbackRate=useRef(1),[slow,setSlow]=useState(false);
 const pressed=useRef<Partial<Record<Action,number>>>({});
 const dashHeld=useRef(false),moveDialog=useRef<HTMLDialogElement>(null);
 const hitboxesRef=useRef(hitboxes);hitboxesRef.current=hitboxes;preferences.current=settings;settingsActive.current=settingsOpen||showMoves;
 if(!inputs.current)inputs.current=new HeldInputs((action,down)=>{if(!match.replay&&(!paused.current||action==='clear')){if(down)pressed.current[action]=performance.now()+240;engine.current.input(0,action,down)} });
 const pause=()=>{setReviewPlaying(false);dashHeld.current=false;inputs.current?.clear();paused.current=true;setPaused(true);view.current?.pause();last.current=0;accumulator.current=0; };
 const resume=()=>{if(!view.current||settingsActive.current)return;setReview(null);setReviewPlaying(false);paused.current=false;setPaused(false);setStarted(true);canvas.current?.focus({preventScroll:true});view.current.unlock();last.current=0; };
 useEffect(()=>{if(settingsOpen)pause(); },[settingsOpen]);
 useEffect(()=>{if(showMoves)moveDialog.current?.showModal();return()=>moveDialog.current?.close() },[showMoves]);
 useEffect(()=>{window.scrollTo(0,0);setTouch(matchMedia('(pointer: coarse)').matches);if(match.replay)engine.current.replay=match.replay.commands;let alive=true,failed=false;
  const lost=(event:Event)=>{event.preventDefault();if(alive){failed=true;pause();setError('Graphics were interrupted. Retry this practice fight.')}};const surface=canvas.current!;surface.addEventListener('webglcontextlost',lost);
  void import('@/lib/bots/pit/view').then(m=>!alive?null:m.createPitView(canvas.current!,match.fighters,v=>{if(alive)setLoading(v) },()=>({...preferences.current,hitboxes:hitboxesRef.current }))).then(v=>{if(!v)return;if(!alive){v.dispose();return; }view.current=v;for(const side of [0,1] as const){engine.current.actors[side].spec.muzzle??=v.muzzles[side];engine.current.actors[side].spec.superMuzzle??=v.superMuzzles[side];engine.current.actors[side].spec.contacts??=v.contacts[side]; }setProof(match.fighters.map(verifyDrills));v.render(engine.current);setLoading(1); }).catch(e=>{if(alive)setError('The arena could not load. '+(e as Error).message) });
  let draws=0;const loop=(time:number)=>{if(!alive)return;raf.current=requestAnimationFrame(loop);if(!view.current||document.hidden||failed)return;
   if(!paused.current){if(last.current){const delta=Math.min(100,time-last.current);accumulator.current+=delta/1000*playbackRate.current; }last.current=time;while(accumulator.current>=1/60){engine.current.step();accumulator.current-=1/60;if(match.replay&&engine.current.tick>=match.replay.endTick){pause();break; } } }
   try{view.current.render(engine.current,reviewRef.current??undefined)}catch{failed=true;pause();setError('Graphics were interrupted. Retry this practice fight.');return;}if(++draws%4===0)setHud(n=>n+1);
   };raf.current=requestAnimationFrame(loop);let landscape=innerWidth>innerHeight;const resize=()=>{if(landscape!==(innerWidth>innerHeight)){landscape=innerWidth>innerHeight;pause(); }view.current?.resize() },hide=()=>{if(document.hidden)pause(); },rotate=()=>{pause();resize(); };window.addEventListener('resize',resize);window.addEventListener('blur',pause);window.addEventListener('orientationchange',rotate);document.addEventListener('visibilitychange',hide);
  return()=>{alive=false;surface.removeEventListener('webglcontextlost',lost);cancelAnimationFrame(raf.current);window.removeEventListener('resize',resize);window.removeEventListener('blur',pause);window.removeEventListener('orientationchange',rotate);document.removeEventListener('visibilitychange',hide);inputs.current?.clear();view.current?.dispose();view.current=null; };
  },[]);
 useEffect(()=>{view.current?.resize() },[settings.quality,settings.touch,touch]);
 useEffect(()=>bindCombatMouse(canvas.current!,window,inputs.current!,()=>!paused.current&&!settingsActive.current&&!match.replay,()=>{setTouch(false);canvas.current?.focus({preventScroll:true})}),[]);
 useEffect(()=>{const down=(e:KeyboardEvent)=>{if(settingsActive.current||(e.target instanceof HTMLInputElement&&!['checkbox','radio'].includes(e.target.type))||e.target instanceof HTMLSelectElement||e.target instanceof HTMLTextAreaElement)return;
  const binding=keyboardBinding(e.code,preferences.current.bindings);if(!binding)return;e.preventDefault();if(e.repeat)return;setTouch(false);
  if(binding==='pause'){if(paused.current)resume();else pause();return; }if(binding==='dash'){dashHeld.current=true;if(engine.current.actors[0].held.has('left')||engine.current.actors[0].held.has('right')){engine.current.input(0,'dash');engine.current.input(0,'dash',false); }return; }
  inputs.current!.set(e.code,[binding]);if((binding==='left'||binding==='right')&&(dashHeld.current)){engine.current.input(0,'dash');engine.current.input(0,'dash',false); }
  };const up=(e:KeyboardEvent)=>{if(e.code===preferences.current.bindings.dash)dashHeld.current=false;if(inputs.current!.owners.has(e.code)){e.preventDefault();inputs.current!.set(e.code,[]) } };window.addEventListener('keydown',down);window.addEventListener('keyup',up);return()=>{window.removeEventListener('keydown',down);window.removeEventListener('keyup',up) } },[]);
 const e=engine.current,a=e.actors[0],b=e.actors[1],controls=touch||settings.touch,active=e.phase==='fight',result=e.phase==='result',training=e.options.training,enhance=a.enhance;
 const send=(action:Action)=>{if(paused.current)return;engine.current.input(0,action);engine.current.input(0,action,false); };
 const pointer=(event:ReactPointer<HTMLElement>,actions:Action[])=>{event.preventDefault();event.currentTarget.setPointerCapture(event.pointerId);setTouch(event.pointerType!=='mouse');if(event.pointerType==='mouse')canvas.current?.focus({preventScroll:true});inputs.current!.set('p'+event.pointerId,actions); };
 const release=(event:ReactPointer<HTMLElement>)=>{inputs.current!.set('p'+event.pointerId,[]); };
 const pad=(event:ReactPointer<HTMLDivElement>)=>{const r=event.currentTarget.getBoundingClientRect(),x=(event.clientX-r.left)/r.width*2-1,y=(event.clientY-r.top)/r.height*2-1;const list:Action[]=[];if(x<-.25)list.push('left');if(x>.25)list.push('right');if(y<-.25)list.push('up');if(y>.25)list.push('down');inputs.current!.set('p'+event.pointerId,list); };
 const button=(action:Action,label:string,extra='')=><button className={`${css.control } ${extra }` } aria-label={label } onPointerDown={event=>pointer(event,[action]) } onPointerUp={release } onPointerCancel={event=>{release(event);pause() } } onLostPointerCapture={release }>{label }<small>{controls?'':keyName(settings.bindings[action as Binding]) }</small></button>;
 const desktopButton=(action:'light'|'heavy'|'guard'|'special',label:string,hint:string)=><button className={css.mouseAction} data-active={a.held.has(action)||(pressed.current[action]??0)>performance.now()} onPointerDown={event=>pointer(event,[action])} onPointerUp={release} onPointerCancel={event=>{release(event);pause()}} onLostPointerCapture={release} onClick={event=>{if(event.detail===0)send(action)}}><b>{label}</b><small>{hint}{hint?' · ':''}{keyName(settings.bindings[action])}</small></button>;
 const confirmed=a.attack?.hits.includes(1)&&a.attack.frame<=a.attack.move.startup+a.attack.move.active+8;
 const followup=confirmed?a.attack!.move.cancel.map(id=>({light:'Light',heavy:'Heavy',forwardSpecial:'Forward + Special',super:'Super',airLight:'Jump + Light',airHeavy:'Jump + Heavy' }[id as 'light']??id)).join(' / '):'';
 const jab=moves(a.spec).light,jabRange=Math.max(...(a.spec.contacts?.light?.map(p=>p[0])??[jab.reach]))+jab.radius+450+(jab.stepIn??0);
 const readyCue=a.y>0?'Air attack ready':Math.abs(a.x-b.x)>jabRange?'Close the gap · Forward + Light steps in':'In punching range';
 const readiness=a.down?'Getting up':a.throwHold?'Grabbed — press Throw to escape':a.stun?'Hitstun':a.blockstun?'Blocking impact':a.attack?`${(a.attack.stepScale??1)<0?'Retreating jab':a.attack.move.name} · ${a.attack.frame<a.attack.move.startup?'Preparing':a.attack.frame<a.attack.move.startup+a.attack.move.active?'Striking':'Recovering'}${a.buffer?' · next attack queued':''}`:a.dash?'Dashing':a.y>0?readyCue:a.held.has('guard')?(a.crouch?'Low guard':'Guarding · attacks lower your guard'):readyCue;
 const rejection=(a.reasonUntil??0)>e.clock?a.reason:'';
 const lessonDone=lesson===0?e.events.some(x=>x.kind==='hit'&&x.who===0&&(x.combo??0)>=3&&x.move===moves(a.spec).heavy.name):lesson===1?e.events.some(x=>x.kind==='block'&&x.target===0):lesson===2?e.events.some(x=>x.kind==='hit'&&x.who===0&&(x.combo??0)>=3&&x.move===moves(a.spec).airHeavy.name):lesson===3?e.events.some(x=>x.kind==='hit'&&x.who===0&&(x.combo??0)>=2&&x.move===moves(a.spec).forwardSpecial.name):e.events.some(x=>x.kind==='super'&&x.who===0);
 const nextLesson=()=>{const n=(lesson+1)%5;setLesson(n);inputs.current?.clear();e.options.dummy=n===1?'ai':'idle';e.resetTraining(); };
 const lessons=['Move into reach. Light → Light → Heavy. Press the next button when CONFIRMED appears.','Hold Guard against an attack. Down + Guard blocks lows.','Down + Heavy launches. Jump, then use Air Light → Air Heavy.','Land Heavy, then cancel into Forward + Special.','Arm Enhance, then use a Special. Use Super with two energy segments.'];
 return <div className={`${css.match } ${controls?css.touch:'' } ${training?css.trainingMatch:''} ${review?css.reviewMode:''}` } data-pit-drills={JSON.stringify(proof) } data-pit-tick={e.tick } data-pit-phase={e.phase } data-pit-controls={JSON.stringify({state:readiness,rejection,pressed:Object.entries(pressed.current).filter(([,until])=>until!>performance.now()).map(([key])=>key),held:[...a.held],height:a.y,distance:Math.round(Math.abs(a.x-b.x)),lastContacts:e.events.filter(v=>v.kind==='hit'||v.kind==='block').slice(-4),inputs:e.commands.filter(c=>c.side===0).slice(-12)})} data-pit-metrics={JSON.stringify(view.current?.metrics()??{ }) }>
 <div className={css.hud }>{[a,b].map((f,i)=><div key={i } className={css.health }><div><strong>{f.spec.name }</strong><span>{f.spec.gp } GP · {'●'.repeat(f.wins) }{'○'.repeat(2-f.wins) }</span></div><meter min={0 } max={f.spec.hp } value={f.hp } aria-label={`${f.spec.name } health` }/><div className={css.energy }>{[0,1,2].map(n=><span key={n } style={{background:`linear-gradient(90deg,#e7b65b ${Math.min(100,Math.max(0,f.energy-n*100)) }%,#28353b 0)` } }/>) }<small>{Math.floor(f.energy/100) } energy</small></div><small>Guard {Math.ceil(f.guard) } · {Math.max(0,f.hp) } HP</small></div>) }<div className={css.timer }><b>{training?'∞':Math.ceil(e.timer/60) }</b><span>ROUND {e.round }</span></div></div>
 <div className={`${css.surface} ${review?css.reviewSurface:""}`}><canvas ref={canvas } tabIndex={0} aria-label='Reactor Pit combat arena — left click Light, right hold Guard, wheel click Heavy'/><div className={css.surfaceTools }><button onClick={()=>paused.current?resume():pause() }>{isPaused?'Resume':'Pause' }</button><button onClick={()=>{pause();onSettings() } }>⚙ Settings</button><button onClick={()=>{pause();setShowMoves(true) } }>Moves</button></div>
 {loading<1&&!error&&<div className={css.centre }><h2>Warming the reactor</h2><progress max={1 } value={loading }/><p>Loading only these two fighters · {Math.round(loading*100) }%</p></div> }
 {error&&<div className={css.centre } role='alert'><p>{error }</p><button onClick={()=>onRematch() }>Retry</button><button onClick={onBack }>Fighters</button></div> }
 {loading===1&&!error&&isPaused&&!settingsOpen&&!showMoves&&!result&&!review&&<div className={css.centre }><span>NO COINS · NO REPAIRS · NO PRIZE POINTS</span><h2>{started?'Catch your breath.':'Enter the underground.' }</h2><p>{started?'The fight is paused. Resume when you are ready.':controls?'Move and jump with the pad. Tap Light or Heavy to strike. Hold Guard to block.':'A/D moves · Space jumps. Left click strikes, right hold guards, click the wheel for Heavy. U uses your weapon.' }</p><button className={css.primary } onClick={resume }>{started?'Resume fight':'Fight' }</button><button onClick={onBack }>Choose fighters</button></div> }
 {!isPaused&&e.phase==='intro'&&<div className={css.cue }><h2>{a.spec.name } <em>vs</em> {b.spec.name }</h2><button onClick={()=>e.skipIntro() }>Skip introduction</button></div> }
 {!isPaused&&e.phase==='ready'&&<div className={css.cue }><h2>{e.phaseFrame<45?`ROUND ${e.round }`:'FIGHT' }</h2></div> }
 {e.phase==='roundEnd'&&<div className={css.cue }><h2>{e.roundWinner===null?'DOUBLE DRAW':`${e.actors[e.roundWinner].spec.name } takes the round` }</h2></div> }
 {e.phase==='finishPrompt'&&<div className={css.cue }><h2>{e.winner===0?'FINISH THE MACHINE':'Rival wins' }</h2>{e.winner===0&&<button className={css.primary } onClick={()=>send('finish') }>Finish {controls?'':`[${keyName(settings.bindings.finish) }]` }</button> }</div> }
 {e.phase==='finisher'&&<div className={css.finisherTitle }>{e.winner===0?{tank:'HYDRAULIC CORE CRUSH',speed:'CIRCUIT SEVERED',ranged:'REACTOR OVERLOAD' }[a.spec.style]:'SYSTEM FAILURE' }</div> }
 {active&&<div className={css.feedback } aria-live='off'><strong>{b.combo>=2?`${b.combo } HITS · ${b.comboDamage } DAMAGE`:a.combo>=2?`RIVAL COMBO · ${a.combo } HITS`:'' }</strong><span>{followup?`CONFIRMED → ${followup }`:readiness }</span>{rejection&&<small className={css.inputNotice}>Input received: {rejection}</small>}{a.energy>=300&&a.combo>=2&&<button onClick={()=>send('escape') }>Escape combo · 3 energy</button> }</div> }
 </div>
 {!result&&<div className={css.bottom }><div className={css.controlLegend }>{!controls&&<div className={css.desktopControls}>{desktopButton('light','Light','Left mouse')}{desktopButton('guard','Guard','Hold right mouse')}{desktopButton('heavy','Heavy','Click wheel')}{desktopButton('special','Weapon','')}</div>}{!controls&&<span><b>{keyName(settings.bindings.left)} / {keyName(settings.bindings.right)} move · Space / {keyName(settings.bindings.up)} jump</b><br/>{keyName(settings.bindings.down)} crouch · {keyName(settings.bindings.throw)} throw · {keyName(settings.bindings.super)} super · {keyName(settings.bindings.pause)} pause</span>}<button aria-pressed={enhance } onClick={()=>send('enhance') }>{enhance?'ENHANCE ARMED':'Enhance next Special' } · 1 energy {controls?'':`[${keyName(settings.bindings.enhance) }]` }</button></div>
 {controls&&<div className={css.touchDeck } style={{'--button-scale':settings.size,'--button-opacity':settings.opacity } as CSSProperties }><div className={css.movement } style={{'--offset-x':`${settings.leftX}px`,'--offset-y':`${settings.leftY}px`} as CSSProperties}><div role='group' aria-label='Movement pad' className={css.pad } onPointerDown={event=>{pointer(event,[]);pad(event) } } onPointerMove={event=>{if(event.currentTarget.hasPointerCapture(event.pointerId))pad(event) } } onPointerUp={release } onLostPointerCapture={release } onPointerCancel={event=>{release(event);pause() } }><span>JUMP ↑</span><strong>←  •  →</strong><span>↓ CROUCH</span></div>{settings.dashButton&&button('dash','Dash') }</div><div className={css.attacks } style={{'--offset-x':`${settings.rightX}px`,'--offset-y':`${settings.rightY}px`} as CSSProperties}>{button('light','Light') }{button('heavy','Heavy',css.heavy) }{button('special','Special',css.special) }{button('guard','Guard',css.guard) }{button('throw','Throw') }{a.energy>=300&&a.combo>=2?button('escape','Escape'):button('super','Super',css.super) }</div></div> }
 {orientation&&controls&&<p className={css.orientation }>Landscape gives you more room. Portrait works too. <button onClick={()=>setOrientation(false) }>Dismiss</button></p> }
  {training&&<div className={css.training }><button onClick={()=>{pause();setReview(review?null:{move:'guard',frame:0,front:true})}}>{review?'Close movement review':'Review movements'}</button>{review&&<div className={css.poseReview}><button onClick={()=>{pause();setReview(null)}}>Back to practice</button><strong>{a.spec.name} · Movement review</strong><label>Movement<select value={review.move} onChange={event=>setReview({...review,move:event.target.value as MotionReview['move'],frame:0})}><option value='guard'>Guard</option><option value='light'>Jab</option><option value='heavy'>Heavy</option><option value='advance'>Step-in jab</option><option value='low'>Low kick</option><option value='launcher'>Uppercut</option><option value='overhead'>Overhead</option><option value='airLight'>Air kick</option></select></label><button onClick={()=>setReview({...review,front:!review.front})}>{review.front?'Side view':'Front view'}</button>{review.move!=='guard'&&<><button onClick={()=>setReviewPlaying(!reviewPlaying)}>{reviewPlaying?'Stop motion':'Play motion'}</button><label>Frame {review.frame}<input aria-label='Movement frame' type='range' min={0} max={(()=>{const m=moves(a.spec)[review.move as Exclude<MotionReview['move'],'guard'>];return m.startup+m.active+m.recovery-1})()} value={review.frame} onChange={event=>{setReviewPlaying(false);setReview({...review,frame:Number(event.target.value)})}}/></label><button onClick={()=>{setReviewPlaying(false);setReview({...review,frame:(()=>{const m=moves(a.spec)[review.move as Exclude<MotionReview['move'],'guard'>];return m.startup+m.active-1})()})}}>Contact pose</button></>}<small>Uses the actual fight animation. Return to practice to test timing and contact.</small></div>}<label>Dummy<select value={e.options.dummy } onChange={event=>{e.options.dummy=event.target.value as Options['dummy'];e.resetTraining() } }><option value='idle'>Idle</option><option value='block'>Always block</option><option value='ai'>Fight back</option></select></label><label><input type='checkbox' checked={e.options.unlimited } onChange={event=>{e.options.unlimited=event.target.checked;setHud(n=>n+1) } }/>Unlimited energy</label><label><input type='checkbox' checked={hitboxes } onChange={event=>setHitboxes(event.target.checked) }/>Show hitboxes</label><button onClick={()=>e.resetTraining() }>Instant reset</button><label><input type='checkbox' checked={slow} onChange={event=>{setSlow(event.target.checked);playbackRate.current=event.target.checked?.25:1}}/>Slow motion</label><p>{lessonDone?'✓ Completed. ':'' }{lessons[lesson] } <button onClick={nextLesson }>{lessonDone?'Next lesson →':'Skip lesson →' }</button></p><small>Inputs: {e.commands.filter(c=>c.side===0&&c.down&&c.action!=='clear').slice(-8).map(c=>c.action).join(' → ')||'Your inputs appear here' }</small></div> }
 </div> }
 {result&&<div className={css.results }><span>MATCH COMPLETE · UNREWARDED PRACTICE</span><h2>{e.winner===null?'An even match.':e.winner===0?'You own this round of steel.':'The rival takes the pit.' }</h2><p>{a.wins } — {b.wins } · {a.spec.name } vs {b.spec.name }</p><ul>{e.events.filter(x=>['guardBreak','tech','escape'].includes(x.kind)||x.kind==='hit'&&(x.combo??0)>=3).slice(-3).map(x=><li key={x.id }>{x.who===0?'You':'Rival' }: {x.kind==='hit'?`${x.combo }-hit combo with ${x.move }`:x.kind==='tech'?'escaped a throw':x.kind==='escape'?'spent three energy to escape a combo':'broke the guard' }.</li>) }</ul><p>{e.winner===1?'Try blocking the opening strike, then punish its recovery.':'Try another weapon kit or a tougher opponent.' }</p><button className={css.primary } onClick={()=>onRematch() }>Rematch</button><button onClick={onBack }>Choose fighters</button><button onClick={()=>onRematch(e.packet()) }>Watch replay</button></div> }
 {showMoves&&<dialog ref={moveDialog} className={css.movePanel } aria-label='Move list' onCancel={()=>setShowMoves(false)}><header><h2>{a.spec.name } · Moves</h2><button onClick={()=>setShowMoves(false) }>Close</button></header><p>Directions are relative to your opponent. Air attacks require a jump.</p><div>{Object.values(moves(a.spec)).map(m=><article key={m.id }><strong>{m.name }</strong><span>{({light:'Light',heavy:'Heavy',low:'Down + Light',launcher:'Down + Heavy',advance:'Forward + Light',overhead:'Forward + Heavy',airLight:'Air Light',airHeavy:'Air Heavy',special:'Special',forwardSpecial:'Forward + Special',bodySpecial:'Down + Special',throw:'Throw',super:'Super' })[m.id] }</span><small>{m.level } · {m.startup } frame startup{m.cost?` · ${m.cost/100 } energy`:'' }</small></article>) }</div><h3>Verified for this build</h3>{proof[0]?.string&&<p>Light → Light → Heavy · {proof[0].string.damage}% against equal equipment.</p>}{proof[0]?.air&&<p>Down + Heavy → Jump → Air Light → Air Heavy.</p>}{proof[0]?.signature&&<p>Heavy → Forward + Special.</p>}<p>Throw escapes: press Throw within ten frames. Block low with Down + Guard.</p></dialog> }
 </div>;
 }
