"use client";
import { useEffect, useState } from 'react';
import { ENTRY_MAP,SLOTS,SLOT_NAMES,defaultAppearance,type Slot } from '@/lib/bots/workshop8/catalogue';
import { PALETTES } from '@/lib/bots/workshop8/appearance';
import { readBanner,saveBanner,decodeBanner,cropBanner,bannerCanvasBlob } from '@/lib/bots/workshop8/banner-storage';
import type { Robot8 } from '@/lib/bots/workshop8/state';
import ConnectedModelRoom from './ConnectedModelRoom';
import EntryDialog from './EntryDialog';
import css from './workshop-journey.module.css';
export default function RobotPersonalization({robot,onSave,onClose}:{robot:Robot8;onSave:(robot:Robot8)=>Promise<boolean>;onClose:()=>void}){
 const [value,setValue]=useState(()=>structuredClone(robot)),[undo,setUndo]=useState<Robot8[]>([]),[slot,setSlot]=useState<Slot>('torso'),[light,setLight]=useState('workshop'),[error,setError]=useState(''),[saving,setSaving]=useState(false),[banner,setBanner]=useState('');
 const [crop,setCrop]=useState<ImageBitmap|null>(null),[zoom,setZoom]=useState(1),[x,setX]=useState(.5),[y,setY]=useState(.5);
 const change=(next:Robot8)=>{setUndo(old=>[...old.slice(-29),structuredClone(value)]);setValue(next)};
 useEffect(()=>{let live=true,url='';void (value.appearance.bannerId?readBanner(value.appearance.bannerId):Promise.resolve(null)).then(blob=>{if(blob&&live){url=URL.createObjectURL(blob);setBanner(url)}else if(live)setBanner('')}).catch(()=>setBanner(''));return()=>{live=false;if(url)URL.revokeObjectURL(url)}},[value.appearance.bannerId]);
 useEffect(()=>()=>crop?.close(),[crop]);
 const opposite=({armL:'armR',armR:'armL',legL:'legR',legR:'legL'} as Partial<Record<Slot,Slot>>)[slot];
 async function upload(file?:File){if(!file)return;try{const bitmap=await decodeBanner(file);setCrop(bitmap);setZoom(1);setX(.5);setY(.5);setError('')}catch(e){setError((e as Error).message)}}
 async function useCrop(){if(!crop)return;try{const id=await saveBanner(await bannerCanvasBlob(cropBanner(crop,zoom,x,y)));change({...value,appearance:{...value.appearance,banner:true,bannerId:id??undefined}});setCrop(null)}catch(e){setError((e as Error).message)}}
 return <EntryDialog title="Make it yours" onClose={onClose}><div className={css.customScroll}><label>Robot name<input value={value.name} maxLength={32} onChange={e=>setValue({...value,name:e.target.value})}/></label><div className={css.model}><ConnectedModelRoom title="Your painted robot" payload={{robots:[value],lighting:light}}/></div><div className={css.actions}><label>Lighting<select value={light} onChange={e=>setLight(e.target.value)}><option value="workshop">Workshop</option><option value="arena">Arena</option></select></label><label>Part<select value={slot} onChange={e=>setSlot(e.target.value as Slot)}>{SLOTS.map(s=><option key={s} value={s}>{SLOT_NAMES[s]}</option>)}</select></label></div><div className={css.paintGrid}>{(['primary','secondary','trim'] as const).map(channel=><label key={channel}>{channel}<input type="color" value={value.appearance.parts[slot][channel]} onChange={e=>{const next=structuredClone(value);next.appearance.parts[slot][channel]=e.target.value;change(next)}}/></label>)}</div><div className={css.actions}>{Object.entries(PALETTES).map(([name,paint])=><button className={css.palette} key={name} title={name} aria-label={`Apply ${name} palette`} style={{background:paint.primary,border:`3px solid ${paint.trim}`}} onClick={()=>change({...value,appearance:{...defaultAppearance(name),banner:value.appearance.banner,bannerId:value.appearance.bannerId}})}/>)}</div><div className={css.actions}>{opposite&&<button onClick={()=>{const next=structuredClone(value);next.appearance.parts[opposite]={...next.appearance.parts[slot]};change(next)}}>Mirror to {SLOT_NAMES[opposite].toLowerCase()}</button>}<button onClick={()=>{const next=structuredClone(value);for(const s of SLOTS)next.appearance.parts[s]={...next.appearance.parts[slot]};change(next)}}>Apply to whole robot</button><button disabled={!undo.length} onClick={()=>{setValue(undo[undo.length-1]);setUndo(old=>old.slice(0,-1))}}>Undo</button><button onClick={()=>change({...value,appearance:{...defaultAppearance(ENTRY_MAP.get(value.choices.torso)!.family),banner:value.appearance.banner,bannerId:value.appearance.bannerId}})}>Reset paint</button></div>
 <details><summary>My banner · Saved on this device</summary><p>PNG, JPEG or WebP. Up to 5 MB and 16 million pixels. Banners are not shared in public replays; other devices show a neutral emblem.</p><input aria-label="Upload banner" type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>void upload(e.target.files?.[0])}/>{banner&&<img className={css.bannerPreview} src={banner} alt="Your local banner"/>}<label><input type="checkbox" checked={value.appearance.banner} onChange={e=>change({...value,appearance:{...value.appearance,banner:e.target.checked}})}/> Show banner</label>{crop&&<><canvas className={css.bannerPreview} ref={node=>{if(node){const image=cropBanner(crop,zoom,x,y);node.width=512;node.height=768;node.getContext('2d')!.drawImage(image,0,0)}}}/>{([{name:'Zoom',min:1,max:3,value:zoom,set:setZoom},{name:'Horizontal position',min:0,max:1,value:x,set:setX},{name:'Vertical position',min:0,max:1,value:y,set:setY}]).map(c=><label key={c.name}>{c.name}<input type="range" min={c.min} max={c.max} step={.01} value={c.value} onChange={e=>c.set(Number(e.target.value))}/></label>)}<button onClick={()=>void useCrop()}>Use this crop</button><button onClick={()=>setCrop(null)}>Cancel upload</button></>}</details></div>{error&&<p role="alert">{error}</p>}<button className={css.primary} disabled={saving||!value.name.trim()} onClick={()=>void(async()=>{setSaving(true);if(await onSave(value))onClose();setSaving(false)})()}>{saving?'Saving…':'Save name & paint'}</button><small>Free to change. Equipment, metal edges and stats stay the same.</small></EntryDialog>;
}
