"use client";

import { useState } from "react";
import Link from "next/link";
import type { SeasonStateResponse } from "@/lib/bots/season/types";
import { fightRoomHref } from "@/lib/bots/fight-navigation";
import css from "./season-workshop.module.css";

export default function SeasonRecords({ view, canChallenge, busy, onChallenge }: { view: SeasonStateResponse; canChallenge: boolean; busy: boolean; onChallenge(id: string): void }) {
  const [tab, setTab] = useState<"history" | "rivals" | "scores">("history");
  return <section className={css.records} aria-label="Season battle records"><div className={css.sockets} role="group" aria-label="Choose battle records"><button aria-pressed={tab === "history"} onClick={() => setTab("history")}>My battles</button><button aria-pressed={tab === "rivals"} onClick={() => setTab("rivals")}>My rivalries</button><button aria-pressed={tab === "scores"} onClick={() => setTab("scores")}>Season scores</button></div>{tab === "history" ? <><p>Your fights and your robot’s saved defenses. A defense does not spend coins or send your robot for repairs.</p><div className={css.recordCards}>{(view.history ?? []).map(fight => <article key={fight.id}><div><small>{fight.viewerSide === 1 ? "Your robot defended" : "Your fight"} · {fight.mode === "ranked" ? "Ranked" : fight.mode === "direct" ? "Chosen rival" : fight.mode === "exhibition" ? "Friendly" : "House robot"}</small><strong>{fight.attackerName} vs {fight.defenderName}</strong><span>{fight.winner === null ? "Draw" : fight.winner === fight.viewerSide ? "Your robot won" : "Your robot lost"} · {new Date(fight.finishedAt).toLocaleDateString(undefined, { month: "short", day: "numeric" })}</span></div><Link href={fightRoomHref(6, { session: fight.id })}>Watch replay</Link>{fight.revengeBotId && <button disabled={busy || !canChallenge} onClick={() => onChallenge(fight.revengeBotId!)}>Rematch</button>}</article>)}</div>{!view.history?.length && <p>No finished fights yet. Your first one will appear here.</p>}</> : tab === "rivals" ? <><p>See how your rated fights add up against each rival. Your first two chosen challenges today may count for rank; the server checks the match first.</p><div className={css.recordCards}>{(view.rivalries ?? []).map(rival => <article key={rival.wallet}><div><strong>{rival.rivalName}</strong><span>{rival.wins} wins · {rival.losses} losses · {rival.draws} draws</span><small>{rival.ownAttacks} challenges · {rival.defenses} defenses</small></div><Link href={fightRoomHref(6, { session: rival.lastMatchId })}>Last fight</Link>{rival.rivalBotId && <button disabled={busy || !canChallenge} onClick={() => onChallenge(rival.rivalBotId!)}>Challenge</button>}</article>)}</div>{!view.rivalries?.length && <p>Your player rivalries start after a rated fight.</p>}</> : <><p>These scores belong to this season. House fights earn play coins but do not change rank.</p><div className={css.scoreRows}>{(view.standings ?? []).map(row => <div key={row.wallet}><b>#{row.rank}</b><span><strong>{row.botName}</strong><small>{row.wins} wins · {row.losses} losses{row.gp !== null ? ` · ${row.gp} GP` : ""}</small></span><strong>{row.rating}</strong></div>)}</div>{!view.standings?.length && <p>No season scores yet. The first player fights will set the board.</p>}</>}</section>;
}
