'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import dynamic from 'next/dynamic';
import EntryDialog from './EntryDialog';
import {emptyZoneView,REWARD_ZONES,ZONE_CATEGORIES,CATEGORY_LABELS,CATEGORY_WEIGHTS,unitsDecimal,type ZoneCategory,type ZoneView} from '@/lib/bots/token-zones';
import {PLAY_ENTRY_URL} from '@/lib/bots/workshop8/entry';
import css from './token-zone-board.module.css';
const Wallet=dynamic(()=>import('./WorkshopWalletConnect'),{ssr:false});
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
function PriceEstimate({view,symbol,quantity}:{view:ZoneView;symbol:string;quantity:string}){
 const asset=view.assets.find(a=>a.symbol===symbol),price=Number(asset?.priceUsd),at=asset?.priceAt;
 if(!asset||asset.priceUsd===null||!Number.isFinite(price)||price<=0||!at||!Number.isFinite(Date.parse(at)))return <span>Current value unavailable; token quantity unchanged.</span>;
 return <span>Estimated value {money(price*Number(quantity))} · price checked {new Date(at).toLocaleString()}{Date.now()-Date.parse(at)>5*3600000?' · stale price':''}</span>;
}
function headers():Record<string,string>{try{const s=JSON.parse(sessionStorage.getItem('mk8.wallet-session.v1')||'null');return s?.token?{Authorization:`Bearer ${s.token}`}:{}}catch{return {}}}
function Countdown({end}:{end:string}){const [now,setNow]=useState<number|null>(null);useEffect(()=>{setNow(Date.now());const id=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(id)},[]);const s=now===null?null:Math.max(0,Math.floor((Date.parse(end)-now)/1000));return <span className={css.clock}>{s===null?'28-day competition':`${Math.floor(s/86400)}d ${Math.floor(s/3600)%24}h ${Math.floor(s/60)%60}m ${s%60}s left`}</span>}
function ZoneChart({view}:{view:ZoneView}){
 const x=(day:number)=>66+Math.min(28,Math.max(0,day))/28*650,y=(volume:number)=>365-Math.min(750000,Math.max(0,volume))/750000*320;
 return <div className={css.chart}><svg viewBox='0 0 960 420' role='img' aria-labelledby='zone-chart-title zone-chart-desc'><title id='zone-chart-title'>28 days to climb nine reward zones</title><desc id='zone-chart-desc'>Cumulative verified community volume. Each horizontal threshold unlocks shared tokens. {view.state==='draft'?'Competition not started.':view.volumeUsd===null?'Volume unavailable.':`Verified volume ${money(Number(view.volumeUsd))}.`}</desc>
 <defs>{REWARD_ZONES.map((z,i)=><pattern key={z.symbol} id={`zone-pattern-${i}`} width={9+i*2} height={9+i*2} patternUnits='userSpaceOnUse'><path d={`M0 ${9+i*2} L${9+i*2} 0`} stroke={z.color} strokeOpacity='.12'/></pattern>)}</defs>
 {REWARD_ZONES.map((z,i)=>{const bottom=i?REWARD_ZONES[i-1].threshold:0;return <g key={z.symbol}><rect x='66' y={y(z.threshold)} width='650' height={y(bottom)-y(z.threshold)} fill={z.color} fillOpacity='.10'/><rect x='66' y={y(z.threshold)} width='650' height={y(bottom)-y(z.threshold)} fill={`url(#zone-pattern-${i})`}/><line x1='66' x2='716' y1={y(z.threshold)} y2={y(z.threshold)} stroke={z.color} strokeOpacity='.45'/></g>})}
 {[0,250000,500000,750000].map(v=><text key={v} x='56' y={y(v)+4} textAnchor='end' className={css.axis}>{v?`$${v/1000}k`:'$0'}</text>)}
 {[0,7,14,21,28].map(d=><g key={d}><line x1={x(d)} x2={x(d)} y1='45' y2='365' stroke='#ffffff12'/><text x={x(d)} y='389' textAnchor='middle' className={css.axis}>Day {d}</text></g>)}
 {REWARD_ZONES.map((z,i)=><g key={z.symbol}><circle cx='746' cy={350-i*38} r='4' fill={z.color}/><text x='760' y={354-i*38} className={css.legend}>{z.symbol}</text><text x='915' y={354-i*38} textAnchor='end' className={css.axis}>${z.threshold/1000}k</text></g>)}
 {!!view.history.length&&view.state!=='draft'&&<polyline points={view.history.map(p=>`${x(p.day)},${y(Number(p.volumeUsd))}`).join(' ')} fill='none' stroke='#fff1bc' strokeWidth='3.5' strokeLinejoin='round'/>}
 {(view.state==='draft'||view.volumeUsd===null)&&<><rect x='210' y='178' width='370' height='72' rx='12' fill='#152624' fillOpacity='.94'/><text x='395' y='209' textAnchor='middle' className={css.emptyChart}>{view.state==='draft'?'Your climb starts together.':'Waiting for verified tracking.'}</text><text x='395' y='232' textAnchor='middle' className={css.axis}>{view.state==='draft'?'Start date to be announced':'No invented progress. No estimated volume.'}</text></>}
 </svg></div>;
}
export default function TokenZoneBoard({compact=false}:{compact?:boolean}){
 const [view,setView]=useState<ZoneView>(emptyZoneView),[error,setError]=useState(''),[connect,setConnect]=useState(false),[busy,setBusy]=useState(false),[category,setCategory]=useState<ZoneCategory>('volume');
 const registered=useRef('');
 const refresh=useCallback(async()=>{try{const auth=headers();if(auth.Authorization&&registered.current!==auth.Authorization){const saved=await fetch('/api/bots/campaign/zones/register',{method:'POST',headers:auth});if(!saved.ok)throw Error('Wallet tracking could not be saved. Reconnect or retry.');registered.current=auth.Authorization;}const r=await fetch('/api/bots/campaign/zones',{headers:auth,cache:'no-store'});if(!r.ok)throw Error('Could not load rewards.');const v=await r.json();if(v.schemaVersion!==1)throw Error('Rewards format is unavailable.');setView(v);setError('');}catch(e){setError((e as Error).message);setView(emptyZoneView())}},[]);
 useEffect(()=>{void refresh();const id=setInterval(()=>{if(!document.hidden)void refresh()},60000);return()=>clearInterval(id)},[refresh]);
 const p=view.personal,volume=view.volumeUsd===null?null:Number(view.volumeUsd),unlocked=volume===null?[]:REWARD_ZONES.filter(z=>volume>=z.threshold),next=REWARD_ZONES.find(z=>(volume??0)<z.threshold),linked=p?.linkStatus==='linked';
 async function enter(){setBusy(true);try{const r=await fetch('/api/bots/campaign/zones',{method:'POST',headers:headers()}),v=await r.json();if(!r.ok)throw Error(v.error||'Could not enter.');setView(v.zones);}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const action=!p?'Connect wallet':view.state==='active'&&!p.entered&&linked?'Enter competition':linked?'Continue trading':'Set up trading';
 return <section className={`${css.root} ${compact?css.compact:''}`} aria-label='Model Kombat token rewards'>
 <header className={css.header}><a className={css.brand} href='/bots/leaderboard'>MODEL <b>KOMBAT</b><small>TRADE TOGETHER. CLIMB HIGHER.</small></a><nav aria-label='Competition navigation'><a href='/bots/start#steps'>Trading setup</a><a href='/bots/rules'>Rules</a><a href={PLAY_ENTRY_URL}>Play Model Kombat ↗</a></nav></header>
 <div className={css.hero}><div><p className={css.eyebrow}>28 DAYS · 9 TOKEN ZONES · ONE COMMUNITY</p><h1>Trade your way<br/>to the <em>next zone.</em></h1><p className={css.lead}>Unlock rewards initially valued at approximately <strong>$4,000.</strong></p><p className={css.subtle}>Eight domain tokens + USDC. Fixed token rewards. Dollar values can change.</p></div><div className={css.heroAside}>{view.state==='active'&&view.endsAt?<Countdown end={view.endsAt}/>:<span className={css.clock}>{view.state==='draft'?'Start date to be announced':view.state==='closed'?'Competition closed · reconciling':view.state==='frozen'?'Final results':'Competition setup being verified'}</span>}<button className={css.primary} disabled={busy} onClick={()=>!p?setConnect(true):action==='Enter competition'?void enter():window.location.assign('/bots/start#steps')}>{busy?'Entering…':action} →</button><small>Trading uses real funds and can lose money.</small></div></div>
 <div className={css.metrics}><div><span>Verified community volume</span><strong>{view.state==='draft'?'Not started':volume===null?'Not available':money(volume)}</strong></div><div><span>Unlocked reward basket</span><strong>{volume===null&&view.state!=='draft'?'Not confirmed':`${unlocked.length} / 9 zones`}</strong><small>{unlocked.length?`Reference value ${money(unlocked.reduce((n,z)=>n+z.referenceUsd,0))}`:'First 1,000 USDC unlocks at $5,000 volume'}</small></div><div><span>{next?'Next zone':'All zones unlocked'}</span><strong style={{color:next?.color}}>{next?.symbol??'SOFTWARE.ai reached'}</strong><small>{next?`${Number(next.quantity).toLocaleString('en-US',{maximumFractionDigits:2})} tokens · ${volume===null?'threshold '+money(next.threshold):money(Math.max(0,next.threshold-volume))+' volume to go'}`:'Final rewards remain subject to verification.'}</small></div></div>
 {!compact&&<><ZoneChart view={view}/><div className={css.chartCaption}><span>Any eligible domain-token trade advances these shared zones. You do not have to trade the reward token.</span><button onClick={()=>void refresh()}>Refresh</button></div><p className={css.subtle}>{view.confirmedThrough?`Verified through ${new Date(view.confirmedThrough).toLocaleString()}. Updates approximately every four hours.`:'Prelaunch trading does not count. The pool is conditional on reaching its volume thresholds.'}</p>
 {view.issues.length>0&&<p className={css.notice} role='status'>{view.issues.join(' ')}</p>}
 <div className={css.zones}>{REWARD_ZONES.map((z,i)=><article key={z.symbol} style={{borderTopColor:z.color}}><span>{String(i+1).padStart(2,'0')} · {volume!==null&&volume>=z.threshold?'UNLOCKED':view.state==='draft'?'LOCKED':volume===null?'UNCONFIRMED':'LOCKED'}</span><h3 style={{color:z.color}}>{z.symbol}</h3><strong>{Number(z.quantity).toLocaleString('en-US',{maximumFractionDigits:2})} tokens</strong><small>At {money(z.threshold)} volume</small><small>Reference allocation {money(z.referenceUsd)}</small></article>)}</div>
 <details className={css.details}><summary>Current token values · separate from fixed rewards</summary><ul>{REWARD_ZONES.map(z=><li key={z.symbol}><strong>{z.symbol}: </strong><PriceEstimate view={view} symbol={z.symbol} quantity={z.quantity}/></li>)}</ul><small>Price updates do not change the number of tokens allocated to a zone.</small></details>
 <section className={css.personal}><div><p className={css.eyebrow}>YOUR PLACE IN THE CLIMB</p><h2>{p?'Your progress':'Connect to see your progress.'}</h2><p>Trade on three distinct UTC days in any one competition week to qualify for all prize categories.</p>{p&&<p>Wallet connected · {linked?'Doma account linked':p.linkStatus==='unavailable'?'Wallet link unavailable':'Wallet link pending'} · {p.entered?'Competition entered':'Not entered'}</p>}</div>{p&&<div><div className={css.weekGrid}>{p.weeks.map((n,i)=><div key={i}><span>Week {i+1}</span><b>{n===null?'—':`${n}/3`}</b></div>)}</div><p>{p.qualified===null?'Qualification not confirmed.':p.qualified?'Qualified · final verification still applies.':'Complete one three-day week to qualify.'}</p><small>Your volume: {p.volumeUsd===null?'Not confirmed':money(Number(p.volumeUsd))} · Scored fights left today: {p.attemptsRemaining??'Not confirmed'}</small></div>}</section>
 {p&&<details className={css.details}><summary>Your estimated token rewards & achievements</summary>{p.awards.length?<ul>{p.awards.map(a=>{const asset=view.assets.find(x=>x.symbol===a.symbol);return <li key={a.symbol}>{asset?unitsDecimal(BigInt(a.units),asset.decimals):'Pending'} {a.symbol}</li>})}</ul>:<p>Token estimates will appear after qualification, funding and complete tracking are verified.</p>}<p>{p.challenges.join(' · ')||'Your verified trading milestones will appear here.'}</p><small>Estimates can change with ranks, corrections and newly unlocked zones. Tokens are paid after final reconciliation.</small></details>}
 <section className={css.standings}><div className={css.sectionHead}><h2>The leaderboards</h2><span>{p?.ranks[category]?`Your provisional rank: #${p.ranks[category]}`:view.state==="frozen"?"Finalized":"Provisional until finalized"}</span></div><div className={css.tabs} role='group' aria-label='Leaderboard category'>{ZONE_CATEGORIES.map(c=><button key={c} aria-pressed={c===category} onClick={()=>setCategory(c)}>{CATEGORY_LABELS[c]} <small>{CATEGORY_WEIGHTS[c]}%</small></button>)}</div><p>{category==='volume'?'40% of volume rewards goes to the top three; 60% is shared proportionally by other qualifiers. The groups are separate, so a lower rank can receive more.':'The top three split this category 50% / 30% / 20%.'}</p>{view.standings[category].length?<div className={css.table}><table><thead><tr><th>Rank</th><th>Trader</th><th>{CATEGORY_LABELS[category]}</th><th>Eligibility</th></tr></thead><tbody>{view.standings[category].map(r=><tr key={r.id}><td>#{r.rank}</td><td>{r.name}</td><td>{category==='roi'?`${Number(r.score).toFixed(2)}%`:category==='battles'?r.score:money(Number(r.score))}</td><td>{r.qualified?'Qualified*':'In progress'}</td></tr>)}</tbody></table></div>:<div className={css.empty}>{view.state==='draft'?'Be ready for the opening bell. Scoring has not started.':'No complete verified rankings are available yet.'}</div>}</section>
 <footer className={css.footer}><span>Game coins are separate from token prizes. No trading is needed to play.</span><a href={PLAY_ENTRY_URL}>Take a battle break →</a></footer></>}
 {compact&&<a className={css.primary} href='/bots/leaderboard'>See token zones & your rewards →</a>}
 {error&&<p role='alert'>{error}</p>}{connect&&<EntryDialog title='Connect your Doma wallet' onClose={()=>setConnect(false)}><Wallet onConnected={(token,address)=>{sessionStorage.setItem('mk8.wallet-session.v1',JSON.stringify({token,address}));setConnect(false);void refresh()}}/></EntryDialog>}
 </section>;
}
