'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import dynamic from 'next/dynamic';
import EntryDialog from './EntryDialog';
import QuickHelp from './QuickHelp';
import {emptyZoneView,REWARD_ZONES,ZONE_CATEGORIES,CATEGORY_LABELS,CATEGORY_WEIGHTS,unitsDecimal,type ZoneCategory,type ZoneView} from '@/lib/bots/token-zones';
import {PLAY_ENTRY_URL} from '@/lib/bots/workshop8/entry';
import css from './token-zone-board.module.css';
const Wallet=dynamic(()=>import('./WorkshopWalletConnect'),{ssr:false});
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
const volumeMoney=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',minimumFractionDigits:0,maximumFractionDigits:6}).format(n);
const awaiting='Awaiting verified update';
const validDate=(value:string|null)=>!!value&&Number.isFinite(Date.parse(value));
const verifiedVolume=(view:ZoneView)=>view.available&&['active','closed','frozen'].includes(view.state)&&view.complete&&typeof view.volumeUsd==='string'&&/^\d+(\.\d+)?$/.test(view.volumeUsd)&&Number.isFinite(Number(view.volumeUsd))?Number(view.volumeUsd):null;
const rewardAmount=(zone:typeof REWARD_ZONES[number])=>`${Number(zone.quantity).toLocaleString('en-US',{minimumFractionDigits:zone.quantity.split('.')[1]?.length??0,maximumFractionDigits:2})} ${zone.symbol}`;
function PriceEstimate({view,symbol,quantity}:{view:ZoneView;symbol:string;quantity:string}){
 const asset=view.assets.find(a=>a.symbol===symbol),price=Number(asset?.priceUsd),at=asset?.priceAt;
 if(!asset||asset.priceUsd===null||!Number.isFinite(price)||price<=0||!at||!Number.isFinite(Date.parse(at)))return <span>Current value unavailable; token quantity unchanged.</span>;
 return <span>Estimated value {money(price*Number(quantity))} · price checked {new Date(at).toLocaleString()}{Date.now()-Date.parse(at)>5*3600000?' · stale price':''}</span>;
}
function credential():string{try{const s=JSON.parse(sessionStorage.getItem('mk8.wallet-session.v1')||'null');return typeof s?.token==='string'?s.token:''}catch{return ''}}
function headers(token:string):Record<string,string>{return token?{Authorization:`Bearer ${token}`}:{}}
function issue(kind:'auth'|'identity'|'unavailable'){return Object.assign(new Error(),{kind})}
function issueText(error:unknown){const kind=(error as {kind?:string})?.kind;return kind==='auth'?'Sign in again to check your rewards.':kind==='identity'?'Your wallet changed. Refresh its status before continuing.':'Rewards could not be checked. Please retry.'}
function openingText(view:ZoneView){if(!view.available)return 'Competition status unavailable';return view.startsAt&&Number.isFinite(Date.parse(view.startsAt))?`Opens ${new Date(view.startsAt).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'})}`:'Start date to be announced'}
function Countdown({end}:{end:string}){const [now,setNow]=useState<number|null>(null);useEffect(()=>{setNow(Date.now());const id=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(id)},[]);const s=now===null?null:Math.max(0,Math.floor((Date.parse(end)-now)/1000));return <span className={css.countdown}>{s===null?'28-day competition':s===0?'Trading window ended':`${Math.floor(s/86400)}d ${Math.floor(s/3600)%24}h ${Math.floor(s/60)%60}m ${s%60}s left`}</span>}
export function ZoneOverview({view}:{view:ZoneView}){
 const volume=verifiedVolume(view),draft=view.available&&view.state==='draft',unlocked=volume===null?[]:REWARD_ZONES.filter(z=>volume>=z.threshold),next=volume===null?null:REWARD_ZONES.find(z=>volume<z.threshold),first=REWARD_ZONES[0],target=draft?first:next;
 const reference=unlocked.reduce((total,zone)=>total+zone.referenceUsd,0),remaining=volume!==null&&next?Math.max(0,next.threshold-volume):null,all=volume!==null&&!next;
 const date=draft?view.startsAt:view.endsAt,dateKnown=view.available&&validDate(date),confirmed=validDate(view.confirmedThrough),stateText=!view.available?awaiting:draft?'Not started':view.state==='frozen'?'Final results':view.state==='closed'?'Closed · reconciling':awaiting;
 return <div className={css.overview}>
  <div className={css.summary} aria-label='Competition at a glance'>
   <article className={css.summaryCard}><span className={css.metricLabel}>Group volume</span><strong className={volume===null?css.pending:css.metricNumber}>{volume===null?(draft?'Not started':awaiting):volumeMoney(volume)}</strong><small>{volume!==null&&!view.fresh?'Last verified total · update delayed':'Verified eligible domain-token trades'}</small></article>
   <article className={`${css.summaryCard} ${css.poolCard}`}><span className={css.metricLabel}>Pool unlocked</span><strong className={volume===null?css.pending:css.metricNumber}>{volume===null?(draft?'Not started':awaiting):`≈ ${money(reference)}`}</strong><small>{volume===null?'Fixed token rewards · dollar values vary':`${unlocked.length} / ${REWARD_ZONES.length} zones · approximate reference value`}</small></article>
   <article className={css.summaryCard}><span className={css.metricLabel}>{draft?'First unlock':'Next unlock'}</span><strong className={target?css.rewardNumber:all?css.metricNumber:css.pending} style={target?{color:target.color}:undefined}>{target?rewardAmount(target):all?'All 9 unlocked':awaiting}</strong><small>{remaining!==null?`${volumeMoney(remaining)} volume to go`:draft?`At ${money(first.threshold)} verified volume`:all?'Final payouts follow verification':`First target: ${rewardAmount(first)} at ${money(first.threshold)}`}</small></article>
   <article className={css.summaryCard}><span className={css.metricLabel}>{draft?'Cycle starts':'Cycle ends'}</span><strong className={dateKnown?css.metricNumber:css.pending}>{dateKnown?<time dateTime={date!}>{new Date(date!).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'})}</time>:draft?'To be announced':awaiting}</strong><small>{dateKnown?<>{new Date(date!).toLocaleTimeString('en-US',{hour:'2-digit',minute:'2-digit',hour12:false,timeZone:'UTC'})} UTC{view.state==='active'&&<Countdown end={date!}/>}</>:stateText}{dateKnown&&view.state==='closed'&&' · Closed · reconciling'}{dateKnown&&view.state==='frozen'&&' · Final results'}</small></article>
  </div>
  <div className={css.unlockPanel}>
   <div className={css.unlockHeading}><div><span className={css.metricLabel}>{all?'Every zone reached':target?(draft?'First target':'Next target'):'Reward unlock progress'}</span><strong>{target?`${rewardAmount(target)} at ${money(target.threshold)} volume`:all?'All nine reward zones unlocked':awaiting}</strong></div><span className={css.unlockStatus}>{remaining!==null?`${volumeMoney(remaining)} to go`:all?'9 / 9 zones':draft?'Opens with the competition':'Progress is not confirmed'}</span></div>
   <div className={css.unlockBar} role='progressbar' aria-label='Reward zones unlocked' aria-valuemin={0} aria-valuemax={9} aria-valuenow={volume===null?undefined:unlocked.length} aria-valuetext={volume===null?(draft?'Competition not started':awaiting):`${unlocked.length} of 9 zones unlocked${next?`; ${volumeMoney(remaining!)} volume to ${rewardAmount(next)}`:''}`}>
    {REWARD_ZONES.map((zone,index)=>{const previous=index?REWARD_ZONES[index-1].threshold:0,fill=volume===null?0:Math.min(100,Math.max(0,(volume-previous)/(zone.threshold-previous)*100));return <div className={css.unlockSegment} data-pending={volume===null&&!draft} key={zone.symbol} title={`${rewardAmount(zone)} at ${money(zone.threshold)} volume`}><span style={{width:`${fill}%`,background:zone.color}}/></div>})}
   </div>
   <div className={css.unlockLabels} aria-hidden='true'>{REWARD_ZONES.map(zone=><span key={zone.symbol}>${zone.threshold/1000}k</span>)}</div>
   <p className={css.unlockNote}>Each segment is one reward zone; its fill follows that zone’s volume threshold. Pool values are approximate reference amounts, not current token prices.</p>
  </div>
  <div className={css.updateLine}><span className={css.updateFrequency}><i data-fresh={view.complete&&view.fresh} aria-hidden='true'/>Updates about every 4 hours</span><span>{confirmed?`${view.complete?'Last confirmed':'Last reported'} through ${new Date(view.confirmedThrough!).toLocaleString()}${view.complete?'':' · awaiting verification'}`:draft?'Prelaunch trades do not count.':awaiting}</span><details><summary>Why the delay?</summary><p>The collector checks every 15 minutes. Wallet links and Strategy references refresh about every 4 hours. Totals appear only after coverage is verified.</p></details></div>
 </div>;
}
export function FinancialLeaders({view}:{view:ZoneView}){
 const roi=view.complete?view.standings.roi[0]:null,profits=view.complete?view.standings.profit.filter(r=>r.rank===1):[],tied=view.standings.roi.filter(r=>r.rank===1).length;
 const names=(rows:{name:string}[])=>rows.length>1?`${rows.length} traders tied`:rows[0]?.name;
 return <section className={css.leaders} aria-label='Verified trading results'>
  <div className={css.leaderCards}>
   <article><span className={css.metricLabel}>Best realized ROI</span><strong>{roi?.score!=null?`${Number(roi.score)>0?'+':''}${Number(roi.score).toFixed(2)}%`:'Verifying results'}</strong><small>{roi?(tied>1?`${tied} traders tied`:roi.name):'Appears after accounting is verified'}</small></article>
   <article><span className={css.metricLabel}>Realized-profit leader</span><strong>{profits.length?'#1':'Verifying results'}</strong><small>{profits.length?names(profits):'Rank only · profit amounts stay private'}</small></article>
  </div>
  <p>Closed-trade results from eligible Doma trading. {view.financials?`${view.financials.verified} of ${view.financials.total} trading accounts verified. `:''}{view.state==='frozen'?'Final results.':'Provisional; ranks can change as accounts are verified.'} Past results don’t guarantee future returns.</p>
 </section>;
}
function ZoneChart({view}:{view:ZoneView}){
 const volume=verifiedVolume(view),x=(day:number)=>66+Math.min(28,Math.max(0,day))/28*650,y=(volume:number)=>365-Math.min(750000,Math.max(0,volume))/750000*320;
 return <div className={css.chart}><svg viewBox='0 0 960 420' role='img' aria-labelledby='zone-chart-title zone-chart-desc'><title id='zone-chart-title'>28 days to climb nine reward zones</title><desc id='zone-chart-desc'>Cumulative verified community volume. Each horizontal threshold unlocks shared tokens. {!view.available?'Competition status unavailable.':view.state==='draft'?'Competition not started.':volume===null?'Awaiting verified update.':`Verified volume ${money(volume)}.`}</desc>
 <defs>{REWARD_ZONES.map((z,i)=><pattern key={z.symbol} id={`zone-pattern-${i}`} width={9+i*2} height={9+i*2} patternUnits='userSpaceOnUse'><path d={`M0 ${9+i*2} L${9+i*2} 0`} stroke={z.color} strokeOpacity='.12'/></pattern>)}</defs>
 {REWARD_ZONES.map((z,i)=>{const bottom=i?REWARD_ZONES[i-1].threshold:0;return <g key={z.symbol}><rect x='66' y={y(z.threshold)} width='650' height={y(bottom)-y(z.threshold)} fill={z.color} fillOpacity='.10'/><rect x='66' y={y(z.threshold)} width='650' height={y(bottom)-y(z.threshold)} fill={`url(#zone-pattern-${i})`}/><line x1='66' x2='716' y1={y(z.threshold)} y2={y(z.threshold)} stroke={z.color} strokeOpacity='.45'/></g>})}
 {[0,250000,500000,750000].map(v=><text key={v} x='56' y={y(v)+4} textAnchor='end' className={css.axis}>{v?`$${v/1000}k`:'$0'}</text>)}
 {[0,7,14,21,28].map(d=><g key={d}><line x1={x(d)} x2={x(d)} y1='45' y2='365' stroke='#ffffff12'/><text x={x(d)} y='389' textAnchor='middle' className={css.axis}>Day {d}</text></g>)}
 {REWARD_ZONES.map((z,i)=><g key={z.symbol}><circle cx='746' cy={350-i*38} r='4' fill={z.color}/><text x='760' y={354-i*38} className={css.legend}>{z.symbol}</text><text x='915' y={354-i*38} textAnchor='end' className={css.axis}>${z.threshold/1000}k</text></g>)}
 {volume!==null&&!!view.history.length&&<polyline points={view.history.map(p=>`${x(p.day)},${y(Number(p.volumeUsd))}`).join(' ')} fill='none' stroke='#fff1bc' strokeWidth='3.5' strokeLinejoin='round'/>}
 {(volume===null)&&<><rect x='210' y='178' width='370' height='72' rx='12' fill='#152624' fillOpacity='.94'/><text x='395' y='209' textAnchor='middle' className={css.emptyChart}>{!view.available?'Competition status unavailable':view.state==='draft'?'Your climb starts together.':awaiting}</text><text x='395' y='232' textAnchor='middle' className={css.axis}>{view.available&&view.state==='draft'?openingText(view):'Progress is not confirmed.'}</text></>}
 </svg></div>;
}
export default function TokenZoneBoard({compact=false}:{compact?:boolean}){
 const [view,setView]=useState<ZoneView>(emptyZoneView),[error,setError]=useState(''),[connect,setConnect]=useState(false),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[category,setCategory]=useState<ZoneCategory>('volume');
 const registered=useRef(''),requestId=useRef(0),alive=useRef(true),controller=useRef<AbortController|null>(null),identity=useRef<string|null>(null),confirmedIdentity=useRef<string|null>(null),entering=useRef(false);
 const clearPersonal=useCallback(()=>{confirmedIdentity.current=null;setView(v=>({...v,personal:null}))},[]);
 const refresh=useCallback(async()=>{
  const token=credential();if(entering.current&&identity.current===token)return;if(entering.current){entering.current=false;setBusy(false)}const id=++requestId.current;
  if(identity.current!==token){identity.current=token;clearPersonal()}
  controller.current?.abort();const c=new AbortController();controller.current=c;const timeout=setTimeout(()=>c.abort(),12000);setLoading(true);setError('');
  try{const auth=headers(token);if(token&&registered.current!==token){const saved=await fetch('/api/bots/campaign/zones/register',{method:'POST',headers:auth,signal:c.signal});if(!saved.ok)throw issue(saved.status===401?'auth':'unavailable');if(!alive.current||id!==requestId.current)return;if(credential()!==token)throw issue('identity');registered.current=token;}
   const r=await fetch('/api/bots/campaign/zones',{headers:auth,cache:'no-store',signal:c.signal});if(!r.ok)throw issue(r.status===401?'auth':'unavailable');const v=await r.json();if(v.schemaVersion!==1)throw issue('unavailable');
   if(!alive.current||id!==requestId.current)return;if(credential()!==token)throw issue('identity');if(token&&v.available&&!v.personal?.connected)throw issue('auth');
   confirmedIdentity.current=token;setView({...v,personal:token?v.personal:null});
  }catch(e){if(alive.current&&id===requestId.current){clearPersonal();setError(issueText(e));setView(emptyZoneView())}}
  finally{clearTimeout(timeout);if(alive.current&&id===requestId.current)setLoading(false)}
 },[clearPersonal]);
 useEffect(()=>{alive.current=true;void refresh();const id=setInterval(()=>{if(!document.hidden)void refresh()},60000),storage=(event:StorageEvent)=>{if(event.key==='mk8.wallet-session.v1')void refresh()};window.addEventListener('storage',storage);return()=>{alive.current=false;controller.current?.abort();clearInterval(id);window.removeEventListener('storage',storage)}},[refresh]);
 const p=view.available&&confirmedIdentity.current===credential()?view.personal:null,volume=verifiedVolume(view),linked=p?.linkStatus==='linked';
 async function enter(){
  if(entering.current||loading||error)return;const token=credential();if(!token||confirmedIdentity.current!==token){clearPersonal();setError('Your wallet changed. Refresh its status before continuing.');return;}
  if(!view.available||view.state!=='active'||!p?.connected||!linked||p.entered)return;
  entering.current=true;setBusy(true);setError('');const id=++requestId.current,c=new AbortController();controller.current?.abort();controller.current=c;const timeout=setTimeout(()=>c.abort(),12000);
  try{const r=await fetch('/api/bots/campaign/zones',{method:'POST',headers:headers(token),signal:c.signal}),v=await r.json();if(!r.ok||v.zones?.schemaVersion!==1)throw issue(r.status===401?'auth':'unavailable');if(!alive.current||id!==requestId.current)return;if(credential()!==token)throw issue('identity');if(!v.zones.personal?.connected)throw issue('auth');confirmedIdentity.current=token;setView(v.zones);
  }catch(e){if(alive.current&&id===requestId.current){clearPersonal();setError((e as {kind?:string})?.kind==='auth'||(e as {kind?:string})?.kind==='identity'?issueText(e):'Entry could not be confirmed. Refresh your status before trading for points.')}}
  finally{clearTimeout(timeout);if(alive.current&&id===requestId.current){entering.current=false;setBusy(false)}}
 }
 const action=!p?'Connect wallet':view.state==='active'&&!p.entered&&linked?'Enter competition':linked?'Continue trading':'Set up trading';
 return <section className={`${css.root} ${compact?css.compact:''}`} aria-label='Model Kombat token rewards'>
 <header className={css.header}><a className={css.brand} href='/bots/start'>MODEL <b>KOMBAT</b><small>TRADE TOGETHER. CLIMB HIGHER.</small></a><nav aria-label='Competition navigation'><a href='/bots/start?setup=1'>Trading setup</a><a href={PLAY_ENTRY_URL}>Play</a><QuickHelp topic='trading'/></nav></header>
 <div className={css.hero}><div><p className={css.eyebrow}>28 DAYS · 9 TOKEN ZONES · ONE COMMUNITY</p><h1>Your climb.<br/><em>Your rewards.</em></h1><p className={css.lead}>Unlock rewards initially valued at approximately <strong>$4,000.</strong></p><p className={css.subtle}>Eight domain tokens + USDC. Fixed token rewards. Dollar values can change.</p></div><div className={css.heroAside}>{view.available&&view.state==='active'?<span className={css.clock}>Competition live</span>:<span className={css.clock}>{!view.available?'Competition status unavailable':view.state==='draft'?openingText(view):view.state==='closed'?'Competition closed · reconciling':view.state==='frozen'?'Final results':'Competition setup being verified'}</span>}<button className={css.primary} disabled={busy||(loading&&action==='Enter competition')} onClick={()=>!p?setConnect(true):action==='Enter competition'?void enter():window.location.assign('/bots/start?setup=1')}>{busy?'Entering…':action} →</button><small>Trading uses real funds and can lose money.</small></div></div>
 <ZoneOverview view={view}/>
 {!compact&&<><FinancialLeaders view={view}/><ZoneChart view={view}/><div className={css.chartCaption}><span>Any eligible domain-token trade advances these shared zones. You do not have to trade the reward token.</span><button disabled={loading||busy} onClick={()=>void refresh()}>{loading?'Checking…':'Refresh'}</button></div>
 {view.issues.length>0&&<p className={css.notice} role='status'>{view.issues.join(' ')}</p>}
 <details className={css.details}><summary>All nine reward zones & token amounts</summary><div className={css.zones}>{REWARD_ZONES.map((z,i)=><article key={z.symbol} style={{borderTopColor:z.color}}><span>{String(i+1).padStart(2,'0')} · {!view.available?'UNCONFIRMED':volume!==null&&volume>=z.threshold?'UNLOCKED':view.state==='draft'?'LOCKED':volume===null?'UNCONFIRMED':'LOCKED'}</span><h3 style={{color:z.color}}>{z.symbol}</h3><strong>{Number(z.quantity).toLocaleString('en-US',{maximumFractionDigits:2})} tokens</strong><small>At {money(z.threshold)} volume</small><small>Reference allocation {money(z.referenceUsd)}</small></article>)}</div></details>
 <details className={css.details}><summary>Current token values · separate from fixed rewards</summary><ul>{REWARD_ZONES.map(z=><li key={z.symbol}><strong>{z.symbol}: </strong><PriceEstimate view={view} symbol={z.symbol} quantity={z.quantity}/></li>)}</ul><small>Price updates do not change the number of tokens allocated to a zone.</small></details>
 <section className={css.personal}><div><p className={css.eyebrow}>YOUR PLACE IN THE CLIMB</p><h2>{p?'Your progress':'Connect to see your progress.'}</h2><p>Trade on three distinct UTC days in any one competition week to qualify for all prize categories.</p>{p&&<p>Wallet connected · {linked?'Doma account linked':p.linkStatus==='unavailable'?'Wallet link unavailable':'Wallet link pending'} · {p.entered?'Competition entered':'Not entered'}</p>}</div>{p&&<div><div className={css.weekGrid}>{p.weeks.map((n,i)=><div key={i}><span>Week {i+1}</span><b>{n===null?'—':`${n}/3`}</b></div>)}</div><p>{p.qualified===null?'Qualification not confirmed.':p.qualified?'Qualified · final verification still applies.':'Complete one three-day week to qualify.'}</p><small>Your volume: {p.volumeUsd===null?'Not confirmed':money(Number(p.volumeUsd))} · Scored fights left today: {p.attemptsRemaining??'Not confirmed'}</small></div>}</section>
 {p&&<details className={css.details}><summary>Your estimated token rewards & achievements</summary>{p.awards.length?<ul>{p.awards.map(a=>{const asset=view.assets.find(x=>x.symbol===a.symbol);return <li key={a.symbol}>{asset?unitsDecimal(BigInt(a.units),asset.decimals):'Pending'} {a.symbol}</li>})}</ul>:<p>Token estimates will appear when qualification and complete tracking are verified.</p>}<p>{p.challenges.join(' · ')||'Your verified trading milestones will appear here.'}</p><small>Estimates can change with ranks, corrections and newly unlocked zones. Tokens are paid after final reconciliation.</small></details>}
 <section className={css.standings}><div className={css.sectionHead}><h2>The leaderboards</h2><span>{!view.available?"Rankings unavailable":p?.ranks[category]?`Your provisional rank: #${p.ranks[category]}`:view.state==="frozen"?"Finalized":"Provisional until finalized"}</span></div><div className={css.tabs} role='group' aria-label='Leaderboard category'>{ZONE_CATEGORIES.map(c=><button key={c} aria-pressed={c===category} onClick={()=>setCategory(c)}>{CATEGORY_LABELS[c]} <small>{CATEGORY_WEIGHTS[c]}%</small></button>)}</div><details className={css.details}><summary>How this category pays</summary><p>{category==='volume'?'40% of volume rewards goes to the top three; 60% is shared proportionally by other qualifiers. The groups are separate, so a lower rank can receive more.':'The top three split this category 50% / 30% / 20%.'}</p><a href='/bots/rules'>Full competition rules →</a></details>{view.available&&view.standings[category].length?<div className={css.table}><table><thead><tr><th>Rank</th><th>Trader</th><th>{CATEGORY_LABELS[category]}</th><th>Eligibility</th></tr></thead><tbody>{view.standings[category].map(r=><tr key={r.id}><td>#{r.rank}</td><td>{r.name}</td><td>{category==='profit'?'Amount private':r.score===null?'Pending':category==='roi'?`${Number(r.score).toFixed(2)}%`:category==='battles'?r.score:money(Number(r.score))}</td><td>{r.qualified?'Qualified*':'In progress'}</td></tr>)}</tbody></table></div>:<div className={css.empty}>{view.available&&view.state==='draft'?'Be ready for the opening bell. Scoring has not started.':'No complete verified rankings are available yet.'}</div>}</section>
 <footer className={css.footer}><span>Game coins are separate from token prizes. No trading is needed to play.</span><a href={PLAY_ENTRY_URL}>Take a battle break →</a></footer></>}
 {compact&&<a className={css.primary} href='/bots/leaderboard'>See token zones & your rewards →</a>}
 {error&&<p role='alert'>{error}</p>}{connect&&<EntryDialog title='Connect your Doma wallet' onClose={()=>setConnect(false)}><Wallet onConnected={(token,address)=>{try{sessionStorage.setItem('mk8.wallet-session.v1',JSON.stringify({token,address}));clearPersonal();setConnect(false);void refresh()}catch{setError('Your browser could not save the sign-in. Allow session storage and try again.')}}}/></EntryDialog>}
 </section>;
}
