"use client";
import { useEffect,useMemo,useState } from "react";
import ConnectedModelRoom from "./ConnectedModelRoom";
import { preset,defaultAppearance,ENTRY_MAP } from "@/lib/bots/workshop8/catalogue";
import type { Fight8 } from "@/lib/bots/workshop8/state";
import css from './workshop-community.module.css';

export default function WorkshopCommunity({onWatch,onPractice}:{onWatch(fight:Fight8):void;onPractice():void}){
 const [fights,setFights]=useState<Fight8[]>([]),[status,setStatus]=useState('loading'),[retry,setRetry]=useState(0);
 useEffect(()=>{let alive=true,controller:AbortController|null=null;const refresh=async()=>{if(document.hidden||controller)return;controller=new AbortController();const request=controller,timeout=setTimeout(()=>request.abort(),10000);try{const r=await fetch('/api/bots/workshop/fights',{signal:request.signal,cache:'no-store'}),v=await r.json();if(!r.ok||!v.ok)throw Error();if(alive){setFights(v.fights);setStatus('ready')}}catch{if(alive)setStatus('failed')}finally{clearTimeout(timeout);controller=null}};void refresh();const timer=setInterval(refresh,30000);document.addEventListener('visibilitychange',refresh);return()=>{alive=false;controller?.abort();clearInterval(timer);document.removeEventListener('visibilitychange',refresh)}},[retry]);
 const robots=useMemo(()=>{const first=fights[0];return first?[{id:'featured',name:first.name,choices:first.choices,appearance:first.appearance},{id:'rival',name:'House rival',choices:first.rival,appearance:defaultAppearance(ENTRY_MAP.get(first.rival.torso)!.family)},...['ranged','tank','speed'].map((style,i)=>({id:`practice-${i}`,name:'Practice robot',choices:preset(style as any),appearance:defaultAppearance()}))]:['tank','speed','ranged','tank','speed'].map((style,i)=>({id:`practice-${i}`,name:'Practice robot',choices:preset(style as any),appearance:defaultAppearance()}))},[fights]);
 return <section className={css.room} aria-label="Community room"><header><span>THE COMMUNITY WORKSHOP</span><h1>Pull up a seat.</h1><p>Watch real saved fights. Find your next robot idea.</p></header><div className={css.models}><ConnectedModelRoom title="Community robots" payload={{room:'garage',robots}}/></div><div className={css.invitation}>{fights[0]?<><span>JUST FOUGHT · {fights[0].mode==='training'?'TRAINING':'HOUSE FIGHT'}</span><strong>{fights[0].name} vs House rival</strong><button onClick={()=>onWatch(fights[0])}>Watch their fight ▶</button></>:<><span>PRACTICE ROBOTS</span><strong>Your next story starts in the arena.</strong><button onClick={onPractice}>Try a fight →</button></>}</div><div className={css.tickets}><div role="status">{status==='loading'?'Finding recent fights…':status==='failed'?'Recent fights could not load. Practice is ready.':fights.length?'Recorded fights, ready to watch.':'No published fights yet. These robots are practice examples.'}{status==='failed'&&<button onClick={()=>setRetry(n=>n+1)}>Try again</button>}</div><div className={css.list}>{fights.slice(0,6).map(f=><button key={f.id} onClick={()=>onWatch(f)}><strong>{f.name} · {f.winner===0?'Won':f.winner===null?'Drew':'Lost'}</strong><small>{f.mode==='training'?'Training':'House fight'} · {Math.round((f.ticks??0)/60)} seconds · Watch replay ↗</small></button>)}</div></div></section>;
}
