"use client";
import { useCallback, useEffect, useState } from 'react';
import { CAMPAIGN_PRIZES, type CampaignStanding } from '@/lib/bots/campaign-view';
import { COMPETITION_DRAFT_TEXT, emptyCompetition, type WorkshopCompetition } from '@/lib/bots/workshop8/competition';
import css from './workshop-competition.module.css';

export function useWorkshopCompetition(enabled:boolean,revision:number,connected:boolean){
 const [value,setValue]=useState<WorkshopCompetition>(()=>emptyCompetition(connected,enabled)),[error,setError]=useState(''),[loading,setLoading]=useState(false),[boards,setBoards]=useState<Record<'roi'|'profit'|'battles',CampaignStanding[]>>({roi:[],profit:[],battles:[]});
 const headers=()=>{try{const s=JSON.parse(sessionStorage.getItem('mk8.wallet-session.v1')||'null');return s?.token?{Authorization:`Bearer ${s.token}`} as Record<string,string>:{};}catch{return {}}};
 const refresh=useCallback(async()=>{if(!enabled)return;try{const r=await fetch('/api/bots/campaign?workshop=1',{headers:headers(),cache:'no-store'}),v=await r.json();if(!r.ok||!v.workshop)throw Error('Competition information could not load.');setValue(v.workshop);setBoards(v.standings??{roi:[],profit:[],battles:[]});setError('');}catch(e){setValue(emptyCompetition(connected));setBoards({roi:[],profit:[],battles:[]});setError((e as Error).message)}},[enabled,connected]);
 useEffect(()=>{void refresh();const timer=setInterval(()=>{if(!document.hidden)void refresh()},30000);return()=>clearInterval(timer)},[refresh,revision]);
 const enroll=async()=>{setLoading(true);try{const r=await fetch('/api/bots/campaign/enroll',{method:'POST',headers:headers()}),v=await r.json();if(!r.ok||!v.ok)throw Error(v.error||'Enrollment could not be confirmed.');setValue(v.competition);setError('');}catch(e){setError((e as Error).message)}finally{setLoading(false)}};
 return {value,error,loading,boards,refresh,enroll};
}

export function PrizeSummary(){return <><p><strong>Build your first robot free. Fight for game coins. Cash prizes are a separate competition.</strong></p><p>$800 for ROI · $800 for realized profit · $400 for battle points.</p><p>To qualify each week, complete at least one verified Doma Strategy trade on <strong>three distinct days that week</strong>. Qualify in both weeks for the final prizes. Trading uses real funds and can lose money.</p><details><summary>Battle points and eligibility</summary><p>Once the competition opens, enter with your wallet before fighting. A normal house win earns 1 battle point; a loss or draw earns 0. Only the first 12 normal house fights started per wallet each UTC day can count, shared across garages.</p><p>Training, loaners, extra fights and classic fights earn no competition points. Prelaunch activity will not count later.</p></details><details><summary>Prize breakdown · Rules version workshop-house-1</summary><div className={css.table}><table><thead><tr><th>Category</th><th>Each week · places 1–5</th><th>Final · places 1–5</th></tr></thead><tbody>{Object.entries(CAMPAIGN_PRIZES).map(([key,p])=><tr key={key}><th>{key==='roi'?'ROI':key==='profit'?'Realized profit':'Battle points'}</th><td>{p.weekly.map(n=>`$${n}`).join(' / ')}</td><td>{p.final.map(n=>`$${n}`).join(' / ')}</td></tr>)}</tbody></table></div><p>Two weekly rounds plus the final total $2,000. Game coins cannot be withdrawn and do not determine cash prizes. ROI, realized-profit and payout/tie rules remain unchanged.</p><p>A fight must start after opening and finish before closing. Points belong to the week when it finishes. The daily 12-fight limit uses the UTC day when it starts. Disconnecting does not return an attempt.</p><a href="/bots/rules/classic" target="_blank" rel="noreferrer">Historical classic rules (different combat and reward rules)</a></details></>}

export default function CompetitionPanel({model,onConnect,onPlay,compact=false,onOpen}:{model:ReturnType<typeof useWorkshopCompetition>;onConnect:()=>void;onPlay:()=>void;compact?:boolean;onOpen?:()=>void}){
 const [category,setCategory]=useState<'roi'|'profit'|'battles'>('battles');
 const v=model.value,draft=v.state==='draft',unavailable=!v.available;
 return <section className={css.panel} aria-label="Your competition status"><header><span>$2,000 COMPETITION</span><h2>{draft?'Coming soon':unavailable?'Checking competition status':'Your competition status'}</h2></header>
 {draft?<p>{COMPETITION_DRAFT_TEXT}</p>:unavailable?<p>Competition data is unavailable. No activity or qualification is confirmed here.</p>:<p>{v.state==='active'?'Competition open':v.state==='frozen'?'Competition finished':'Competition closed'} · {v.connected?'Wallet connected':'Wallet not connected'} · {v.enrollment==='entered'?'Entered':v.enrollment==='not_entered'?'Not entered':'Enrollment unavailable'}</p>}
 {compact?<button onClick={onOpen}>How prizes work →</button>:<>
 <PrizeSummary/>
 {!draft&&<><dl className={css.stats}><div><dt>Battle points</dt><dd>{v.points??'Not confirmed'}</dd></div><div><dt>Scored starts left today</dt><dd>{v.attemptsRemaining??'Not confirmed'}</dd></div>{v.weeks.map((week,i)=><div key={i}><dt>Week {i+1} · Strategy days</dt><dd>{week.days===null?week.status==='upcoming'?'Not started':'Data unavailable':`${week.days}/3 · ${week.status.replaceAll('_',' ')}`}</dd></div>)}</dl><p>Final eligibility: {v.finalQualified===null?'Not confirmed':v.finalQualified?'Both weeks qualified':'Both weeks required'}</p><div className={css.stats}>{(['roi','profit','battles'] as const).map(k=><div key={k}><strong>{k==='roi'?'ROI':k==='profit'?'Realized profit':'Battle points'}</strong><p>{v.categories[k].rank===null?'Rank not confirmed':`${v.categories[k].provisional?'Provisional ':''}rank ${v.categories[k].rank}`}</p></div>)}</div></>}
 {!draft&&<details><summary>Overall provisional standings</summary><label>Category<select value={category} onChange={e=>setCategory(e.target.value as typeof category)}><option value="battles">Battle points</option><option value="roi">ROI</option><option value="profit">Realized profit</option></select></label>{model.boards[category].length?<ol>{model.boards[category].slice(0,5).map((r,i)=><li key={i}>{r.rank}. {r.name} · {r.score}{category==='roi'?'%':category==='profit'?' USD':' points'}</li>)}</ol>:<p>No verified standings available yet.</p>}<small>Ranks may change after qualification and corrections are checked. These are not final prize awards.</small></details>}{draft&&<p><strong>Not entered yet.</strong> Wallet connection does not enter you. Enrollment and qualifying days begin only after opening.</p>}
 <button disabled={model.loading} onClick={()=>v.nextAction==='connect'?onConnect():v.nextAction==='enroll'?void model.enroll():v.nextAction==='check'?void model.refresh():onPlay()}>{model.loading?'Entering…':v.nextAction==='connect'?'Connect wallet':v.nextAction==='enroll'?'Enter competition':v.nextAction==='check'?'Retry status':'Play now'}</button>
 {v.updatedAt&&<small>Last checked {new Date(v.updatedAt).toLocaleTimeString()}. Trading verification is reported separately from game rewards.</small>}
 </>}{model.error&&<p role="alert">{model.error}</p>}</section>;
}
