"use client";
import { useState } from 'react';
import { ENTRY_MAP, ITEMS, SLOTS, SLOT_NAMES, STYLE_NAMES, SPECIAL_NAMES, preset, defaultAppearance, legalChoices, dailyItems, type Choices, type Item, type Slot } from '@/lib/bots/workshop8/catalogue';
import { careerOf, compareBuilds, MILESTONES, plannedParts } from '@/lib/bots/workshop8/journey';
import { type Action8, type Draft8, type Fight8, type Robot8, type Workshop8 } from '@/lib/bots/workshop8/state';
import { readPresentation, type PresentationSettings as PresentationPreferences } from '@/lib/bots/workshop8/presentation';
import ConnectedModelRoom from './ConnectedModelRoom';
import EntryDialog from './EntryDialog';
import WorkshopItemPages from './WorkshopItemPages';
import css from './workshop-journey.module.css';

type Act=(action:Action8)=>Promise<boolean>;
export function FightResults({fight,replay=false,onMoment,onAgain,onGarage,onPin,onShare}:{fight:Fight8;replay?:boolean;onMoment:(start:number,end?:number)=>void;onAgain:()=>void;onGarage:()=>void;onPin?:()=>void;onShare?:()=>void}){
 const report=fight.report;
 return <section className={css.results} aria-label="Fight result"><div><strong>{fight.winner===0?'You won!':fight.winner===1?'The rival won.':'An even match.'}</strong><span> {fight.coins===undefined?(replay?'Recorded coin reward unavailable':'Saving result…'):`${replay?'Recorded reward: ': '+'}${fight.coins} game coins`}{fight.mode==='training'?' · Training · No repairs':''}</span><span>{fight.competition?.status==='reserved'?'Saving competition points…':fight.competition?`${fight.competition.points??0} competition points · ${fight.competition.reason}`:'This fight was not entered for competition scoring.'}</span></div>
 {replay&&<small>Replay only. Watching does not award coins or competition points.</small>}
 {!replay&&(fight.coins??0)>0&&<p>Spend your game coins on better parts or your next robot.</p>}
 {report?.milestones.map(id=><strong className={css.earned} key={id}>✦ {MILESTONES[id].title} earned</strong>)}
 <div className={css.actions}><button className={css.primary} onClick={onAgain}>Fight again →</button>{report&&<button onClick={()=>onMoment(report.highlight.start,report.highlight.end)}>Watch best moment</button>}<button onClick={()=>onMoment(0)}>Full replay</button><button onClick={onGarage}>Garage</button>{onPin&&<button onClick={onPin}>Pin this fight</button>}{onShare&&<button onClick={onShare}>Share fight</button>}</div>
 {report&&<details><summary>What happened?</summary>{report.moments.map((m,i)=><button className={css.fact} key={i} onClick={()=>onMoment(Math.max(0,m.tick-180))}>{m.text} <small>Watch {Math.floor(m.tick/60)}s ↗</small></button>)}<p>{report.suggestion}</p></details>}
 </section>;
}

export function RobotCareer({robot,state,act,onWatch,onClose}:{robot:Robot8;state:Workshop8;act:Act;onWatch:(f:Fight8)=>void;onClose:()=>void}){
 const c=careerOf(robot),favorite=Object.entries(c.weapons).sort((a,b)=>b[1]-a[1])[0]?.[0];
 const watch=(id?:string)=>{const f=state.history.find(f=>f.id===id)??(id?state.journey?.retained[id]:undefined);if(f)onWatch(f)};
 return <EntryDialog title={`${robot.name} · Career`} onClose={onClose}><p>{c.verified?'Verified fight record':'Local record'} · {c.wins} house wins · {c.losses} house losses</p><p>Favourite weapon: {favorite?ENTRY_MAP.get(favorite)?.name:'A story still to write'}</p><div className={css.actions}>{c.firstFight&&<button onClick={()=>watch(c.firstFight)}>First fight</button>}{c.firstVictory&&<button onClick={()=>watch(c.firstVictory)}>First victory</button>}{c.pinnedReplay&&<button onClick={()=>watch(c.pinnedReplay)}>Pinned fight</button>}</div>
 <div className={css.milestones}>{Object.entries(MILESTONES).map(([id,m])=><article key={id} data-earned={!!c.milestones[id as keyof typeof MILESTONES]}><strong>{c.milestones[id as keyof typeof MILESTONES]?'✦':'◇'} {m.title}</strong><p>{m.explanation}</p>{c.milestones[id as keyof typeof MILESTONES]&&<button onClick={()=>watch(c.milestones[id as keyof typeof MILESTONES])}>Watch how you earned it</button>}</article>)}</div>
 <label>Show a title<select value={c.title??''} onChange={e=>void act({kind:'career',id:robot.id,title:e.target.value as keyof typeof MILESTONES|''})}><option value="">No title</option>{Object.keys(c.milestones).map(id=><option value={id} key={id}>{MILESTONES[id as keyof typeof MILESTONES].title}</option>)}</select></label>
 <label>Nameplate emblem<select value={c.emblem??'none'} onChange={e=>void act({kind:'career',id:robot.id,emblem:e.target.value as 'none'|'spark'|'star'|'shield'|'bolt'})}><option value="none">No emblem</option>{Object.keys(c.milestones).map(id=><option key={id} value={MILESTONES[id as keyof typeof MILESTONES].emblem}>{MILESTONES[id as keyof typeof MILESTONES].title}</option>)}</select></label>
 <label>Victory pose<select value={c.pose??'proud'} onChange={e=>void act({kind:'career',id:robot.id,pose:e.target.value as 'proud'|'salute'|'fist'})}><option value="proud">Proud stance</option><option value="salute">Salute</option><option value="fist">Raised fist</option></select></label><small>Your robot uses a proud stance when its equipment needs both hands.</small>
 <label><input type="checkbox" checked={c.showMarks??false} onChange={e=>void act({kind:'career',id:robot.id,showMarks:e.target.checked})}/> Keep up to five battle marks</label><button disabled={!c.marks.length} onClick={()=>void act({kind:'career',id:robot.id,clearMarks:true})}>Remove battle marks</button><p>Titles, poses and marks are free. They never change stats.</p></EntryDialog>;
}

export function BuildPlan({state,act,onTry,onBuild,onClose}:{state:Workshop8;act:Act;onTry:(draft:Draft8)=>void;onBuild:(draft:Draft8)=>Promise<void>;onClose:()=>void}){
 const [draft,setDraft]=useState<Draft8>(()=>structuredClone(state.journey?.plan??{name:'My next robot',choices:preset('tank'),appearance:defaultAppearance()}));
 const [slot,setSlot]=useState<Slot|null>(null),[tier,setTier]=useState('1'),[style,setStyle]=useState('all'),[saved,setSaved]=useState(false),[replace,setReplace]=useState(false);
 const plan=plannedParts(state,draft),today=new Set(dailyItems(new Date().toISOString().slice(0,10)).map(i=>i.id));
 const update=(next:Draft8)=>{setDraft(next);setSaved(false)};
 return <EntryDialog title="Your next robot" onClose={onClose}><div className={css.planScroll}><div className={css.planLayout}><div className={css.model}>{!slot&&legalChoices(draft.choices)&&<ConnectedModelRoom title="Your planned robot" payload={{robots:[{id:'plan',...draft}]}}/>}</div><div><label>Plan name<input value={draft.name} maxLength={32} onChange={e=>update({...draft,name:e.target.value})}/></label><p><strong>{plan.cost} coins left to spend</strong> · {plan.parts.filter(p=>p.owned).length}/7 owned spares</p><small>Planning is free. A spare part can fill only one slot.</small><div className={css.planParts}>{plan.parts.map(p=><button key={p.slot} onClick={()=>setSlot(p.slot)}><span>{SLOT_NAMES[p.slot]}</span><strong>{p.item.entry.name}</strong><small>{p.owned?'Owned spare':`${p.cost} coins · ${today.has(p.item.id)?p.cost>state.coins?'In today’s shipment · Not enough coins':'In today’s shipment':'Not in today’s shipment'}`}</small></button>)}</div></div></div>
 {slot&&<><div className={css.actions}><strong>Choose {SLOT_NAMES[slot]}</strong><select aria-label="Plan tier" value={tier} onChange={e=>setTier(e.target.value)}>{[1,2,3,4].map(t=><option key={t} value={t}>Tier {t}</option>)}</select><select aria-label="Plan style" value={style} onChange={e=>setStyle(e.target.value)}><option value="all">All styles</option>{Object.entries(STYLE_NAMES).map(([s,l])=><option key={s} value={s}>{l}</option>)}</select><button onClick={()=>setSlot(null)}>Done choosing</button></div><div className={css.planGrid}><WorkshopItemPages compact items={ITEMS.filter(i=>i.slot===slot&&i.entry.tier===Number(tier)&&(style==='all'||i.entry.style===style))} resetKey={`${slot}:${tier}:${style}`} render={item=><button className={css.part} onClick={()=>{update({...draft,choices:{...draft.choices,[slot]:item.entry.id}});setSlot(null)}}><img src={item.image} alt=""/><strong>{item.entry.name}</strong><small>{item.price} coins</small></button>}/></div></>}
 </div><div className={css.actions}><button className={css.primary} onClick={()=>void act({kind:'journey',plan:draft}).then(ok=>setSaved(ok))}>{saved?'Plan saved ✓':'Pin this plan'}</button><button disabled={!plan.complete} onClick={()=>onTry(draft)}>Try this build</button><button disabled={!plan.complete||state.robots.length>=5} onClick={()=>state.draft?setReplace(true):void onBuild(draft)}>Build this robot</button></div><small>Trying a plan is unrewarded practice. Build copies it into your draft; Finish is when coins and spare parts are used.</small>{replace&&<div role="alert"><p>You already have a draft. Replace it with this plan?</p><button onClick={()=>void onBuild(draft)}>Replace draft</button><button onClick={()=>setReplace(false)}>Keep current draft</button></div>}</EntryDialog>;
}

export function PartDemonstration({before,item,appearance,onClose}:{before:Choices;item:Item;appearance:Robot8['appearance'];onClose:()=>void}){
 const [candidate,setCandidate]=useState(false),[run,setRun]=useState(0),after={...before,[item.slot]:item.entry.id},comparison=compareBuilds(before,after),valid=legalChoices(after);
 const choices=candidate&&valid?after:before;
 return <EntryDialog title="See what this changes" onClose={onClose}><p>{comparison.benefit?`More ${comparison.benefit.label}.`:'No increase in overall stats.'} {comparison.cost?`Less ${comparison.cost.label}.`:'No reduction in these overall stats.'}</p><div className={css.actions}><button aria-pressed={!candidate} onClick={()=>{setCandidate(false);setRun(n=>n+1)}}>Current build</button><button disabled={!valid} aria-pressed={candidate} onClick={()=>{setCandidate(true);setRun(n=>n+1)}}>With this part</button></div><small>Same opponent, seed and automatic Special policy. Watch one example at a time. No rewards; this does not predict a win.</small>{!valid&&<p>This part needs compatible equipment before it can be demonstrated.</p>}<div className={css.demo}><ConnectedModelRoom view="practice" title="Part comparison combat example" payload={{id:`compare-${candidate}-${run}`,choices,rival:before,appearance,seed:75,arena:'spaceship',name:candidate?'Proposed build':'Current build',demo:true}}/></div><details><summary>Overall numbers</summary><dl>{comparison.changes.map(c=><div key={c.key}><dt>{c.label}</dt><dd>{c.from.toFixed(2)} → {c.to.toFixed(2)}</dd></div>)}</dl><p>Special: {SPECIAL_NAMES[ENTRY_MAP.get(choices.torso)!.style]} · {ENTRY_MAP.get(choices.torso)!.tier>=3?'Ending unlocked':'No ending yet'}</p><p>Weapon: {ENTRY_MAP.get(choices.weapon)?.name}</p></details></EntryDialog>;
}

export function PresentationSettings({onClose,onApply}:{onClose:()=>void;onApply:()=>void}){
 const [value,setValue]=useState<PresentationPreferences>(()=>(()=>{try{return readPresentation(JSON.parse(localStorage.getItem('mk8.presentation.1')||'null'))}catch{return readPresentation(null)}})());
 return <EntryDialog title="Settings" onClose={onClose}><label>Graphics<select value={value.quality} onChange={e=>setValue({...value,quality:e.target.value as PresentationPreferences['quality']})}><option value="auto">Auto</option><option value="standard">Standard</option><option value="low">Low</option></select></label><p>Low uses fewer effects and simpler shadows. The fight result stays the same.</p><label><input type="checkbox" checked={value.reducedMotion} onChange={e=>setValue({...value,reducedMotion:e.target.checked})}/> Reduce motion</label><label><input type="checkbox" checked={value.steadyCamera} onChange={e=>setValue({...value,steadyCamera:e.target.checked})}/> Steady camera</label><button className={css.primary} onClick={()=>{localStorage.setItem('mk8.presentation.1',JSON.stringify(value));window.dispatchEvent(new Event('mk8-presentation-change'));onApply();onClose()}}>Apply settings</button><details><summary>Classic collection</summary><p>A separate historical collection, with its own robots, balances and rules.</p><a href="/bots?collection=classic">Open classic collection</a></details></EntryDialog>;
}
