import {REWARD_ZONES} from '@/lib/bots/token-zones';
export function TokenPrizeSummary(){return <>
 <p><strong>Unlock fixed token rewards initially valued at approximately $4,000.</strong> No reward allocation unlocks until verified community volume reaches $5,000. Token prices can change.</p>
 <p>28 days. Eligible domain-token trades against USDC or ETH count through verified Strategies or your linked agent wallet. ETH/USDC trades, transfers, approvals, failures and duplicated route hops do not count. No daily volume cap applies.</p>
 <p>Qualify for all prize categories by trading on three distinct UTC days within any one of four competition weeks. Connect, link your Doma account and enter before activity counts. Prelaunch trades and fights do not count.</p>
 <p>Each unlocked token: <strong>60% volume · 15% ROI · 15% realized profit · 10% battles.</strong> Top-three awards use 50% / 30% / 20%. Players can win multiple categories.</p>
 <p>Volume awards have two separate groups: 40% of the volume allocation goes to its top-three award recipients; 60% is shared proportionally among the other qualifiers. A lower-ranked participant can consequently receive more than a top-three winner.</p>
 <p>Only the first 12 eligible normal house fights started per participant per UTC day can score, across linked wallets and garages. A win earns one point. Arcade practice, training, loaners, classic fights and manual practice earn none. Disconnecting does not restore a scored start.</p>
 <p>Fixed quantities, not dollar promises. Prices and provisional payouts can change. Actual token transfers occur after reconciliation; this game does not automatically transfer funds. Game coins cannot be withdrawn.</p>
 </>}
export default function TokenZoneRules(){return <main style={{maxWidth:1000,margin:'0 auto',padding:'32px 24px',lineHeight:1.75}}><a href='/bots/leaderboard'>← Token zones & leaderboard</a><h1>Model Kombat token-zone rules</h1><p>Rules version mk-token-zones-1 · See Rewards for the current server-confirmed dates and status.</p><p>Independent community hobby game run by @sdmike. Doma does not operate this competition. Questions or disputes: <a href="https://discord.gg/doma" target="_blank" rel="noopener noreferrer">@sdmike in Discord</a>.</p><TokenPrizeSummary/>
 <h2>Nine community unlocks</h2><div style={{overflowX:'auto'}}><table style={{width:'100%',textAlign:'left'}}><thead><tr><th>Volume</th><th>Reward</th><th>Fixed tokens</th><th>Reference value</th></tr></thead><tbody>{REWARD_ZONES.map(z=><tr key={z.symbol}><td>${z.threshold.toLocaleString()}</td><td>{z.symbol}</td><td>{z.quantity}</td><td>${z.referenceUsd}</td></tr>)}</tbody></table></div>
 <h2>Scoring and verification</h2><p>The four weeks are measured from the authoritative opening time. Completed eligible trades must occur after enrollment, at or after opening, and before closing. Qualifying days use UTC. Delayed wallet discovery can recover eligible post-enrollment activity; it does not credit prelaunch activity.</p><p>Any eligible domain trade advances shared zones; trading a zone’s reward token is not required. Linked wallets belong to one participant. Rankings use unrounded scores and the existing reviewed ROI/profit methodology. Internal transfers are not profit, and wallet ROI percentages are never added together.</p><p>Every economic fill counts once, excluding routing duplication. Uncapped repeated legitimate trading can increase volume. Verified volume does not prove unique capital or trading intent. False attribution, duplicate fills and corrected/revoked transactions do not retain credit.</p>
 <h2>Ties, small rewards and closing</h2><p>Exact ties share occupied-position awards. Top-three volume award recipients do not share its remainder pot. Vacant top-three awards are redistributed among eligible winners using their relative weights. If the volume remainder group is empty, its allocation goes to the volume winners. Categories without qualifiers remain unawarded.</p><p>Rewards are computed in integer token units with deterministic remainder allocation. Small proportional shares are not promises of meaningful cash value. Eligibility and displayed unlocks remain provisional while evidence is checked.</p><p>Allow 48 hours after closing for reconciliation. Incomplete coverage or unresolved disputes delay finalization. Corrections can change scores and unlocked zones before awards freeze. Token values can change independently of the fixed quantities.</p><p>Trading uses real funds and can lose money, including more than any reward. Participation does not guarantee a prize. Pool reserve figures are not a promise of a particular selling price.</p><p><a href='/bots/terms'>Terms</a> · <a href='/bots/privacy'>Privacy</a> · <a href='/bots/disclaimer'>Trading risks</a></p><a href='/bots/rules/classic'>Historical classic rules</a></main>}
