import { InfoPage } from '../_components/InfoPage';
import { CAMPAIGN_PRIZES } from '@/lib/bots/campaign-view';
import css from '../info.module.css';
export default function WorkshopRules(){return <InfoPage eyebrow="Workshop competition · rules workshop-house-1" title="$2,000. Three ways to place." intro="Build and play for free. Cash prizes have separate entry requirements. Check Progress in your workshop for the competition’s opening status." art="/bots-art/plates/arena-evening.png">
 <p><a href="/bots/workshop?view=earn">Back to your workshop and competition status →</a></p>
 <h2>Opening and entry</h2><p>The competition stays in draft until a start date is announced and enrollment opens. No countdown or scoring runs before opening. Prelaunch fights and trades will not count later.</p><p>Connecting a wallet saves your garage; it does not enter the competition. Enter separately when enrollment opens. Use the same wallet for the competition and your Doma Strategy activity.</p>
 <h2>Game coins are not cash prizes</h2><p>Your 250 starter game coins build one Tier 1 robot. Each of the first 12 rewarded fight completions each UTC day earns 75 game coins, win or lose. The sixth adds 100, up to 1,000 daily. Linked garages share that allowance. Introductory training earns its normal completion reward once and causes no repairs. Repeating training earns nothing.</p><p>Coins buy spare parts and faster repairs. Finished robots keep their parts. Workshop coins and historical trading balances stay separate. Game coins have no cash value and cannot be withdrawn.</p>
 <h2>Who qualifies?</h2><p>Complete at least one verified Doma Strategy trade on three distinct days in a week for that week’s prizes. Meet that requirement in both weeks for the final. Multiple trades on one day still count as one day. Only verified activity within the competition dates counts. Trading uses real funds and can lose money.</p><p>Missing or corrected evidence can change eligibility. A pending check is not confirmed qualification. Trading volume does not determine any cash prize.</p>
 <h2>Battle points</h2><p>Only verified normal house fights in the new workshop count: 1 point for a win, 0 for a loss or draw. Your first 12 normal house fights started per wallet per UTC day can score, shared across all garages. This is a separate counter from coin rewards.</p><p>Sign in and enroll before the scored fight starts. An attempt is reserved when the arena is ready and the server starts the match. Disconnecting continues that match and does not return the attempt. Guest, prelaunch, training, loaner, extra and classic-game fights earn no competition points. Replay viewing never earns rewards.</p><p>A scored fight must start after opening and finish before closing. Its points belong to the week when the server says it finished. The daily limit uses the UTC date when it started.</p>
 <h2>ROI and realized profit</h2><p>ROI shows profit from eligible sold tokens as a percentage of recorded starting funds plus eligible added funds. Starting funds must be verified before a confirmed rank can be shown. Realized profit is the dollar profit from eligible tokens sold during the competition. Unsold price increases do not count toward either cash-prize score. Existing verified ROI and realized-profit calculations are unchanged.</p>
 <h2>Prize pool</h2><p>$800 ROI + $800 realized profit + $400 battle points = $2,000.</p>{Object.entries(CAMPAIGN_PRIZES).map(([category,p])=><div key={category} className={css.tableWrap}><table className={css.table}><caption>{category==='roi'?'ROI':category==='profit'?'Realized profit':'Battle points'}</caption><thead><tr><th>Period</th>{[1,2,3,4,5].map(n=><th key={n}>Place {n}</th>)}</tr></thead><tbody><tr><td>Each week</td>{p.weekly.map((n,i)=><td key={i}>${n}</td>)}</tr><tr><td>Final</td>{p.final.map((n,i)=><td key={i}>${n}</td>)}</tr></tbody></table></div>)}
 <h2>Results and ties</h2><p>Live ranks are provisional. Final results require checked trades, starting balances, fights and eligibility. Tied players share equally the combined prizes for the places their tie occupies. Fractions may be rounded to the nearest cent. There are 45 scheduled prize places across two weekly rounds and the final; a player can place in multiple categories.</p><p>Manipulated, duplicated, self-dealing, automated-abuse or unverifiable activity may be excluded. Incomplete data can pause or correct standings. Material rule or date changes will be published before they take effect whenever reasonably possible.</p>
 <h2>Participation</h2><p>You must be at least 18 and legally allowed to participate where you live. Void where prohibited. You are responsible for taxes, wallet access and information reasonably needed to verify eligibility and deliver a prize. In-game equipment, cosmetics and coins have no cash value.</p><p><a href="/bots/rules/classic">Historical classic rules — different game and scoring version</a></p>
 </InfoPage>}
