/** Descriptions of the repainted launch catalogue. These are presentation
 * words only: the frozen engine catalogue still owns every part's identity,
 * stats, price and factory paint. */
export const ART_PART_LORE: Readonly<Record<string, string>> = {
  "starter.scrapCap": "A little flat cap with two bright eyes and a very small smile.",
  "starter.scrapCan": "A little barrel body with a small square panel on its tummy.",
  "starter.scrapMitts": "A soft round mitten with one little thumb.",
  "starter.scrapPegs": "A small work boot with a long toe and a soft sole.",
  "starter.scrapSpanner": "A curved wrench with a big open mouth and a soft handle.",
  "head.sprocketCap": "A little flat cap with two bright eyes and a very small smile.",
  "head.peeperEye": "A bell-shaped head with two warm eyes and a wavy edge.",
  "head.kettleDome": "A round kettle head with big eyes and two round ears.",
  "head.lanternLens": "A tall lantern face that looks pleased to see you.",
  "head.hornetScope": "A pointed little head with a small smile at the bottom.",
  "head.pistonVisor": "A wide, low face with two bright eyes tucked inside.",
  "head.bulldozerHelm": "A big soft helmet over a little smiling face.",
  "head.anvilMask": "A square head with round corners and two curious eyes.",

  "torso.sprocketCan": "A little barrel body with a small square panel on its tummy.",
  "torso.peeperBox": "A pear-shaped body with a big round tummy.",
  "torso.kettleChest": "A body like a spool, wide at both ends and small in the middle.",
  "torso.lanternDrum": "A tall little box with a tidy panel on its front.",
  "torso.hornetFrame": "Wide shoulders and a small waist make a funny little body.",
  "torso.pistonShell": "A round drum body with a round panel, ready for your sticker.",
  "torso.bulldozerHull": "A broad little brick of a body with a tiny pair of hips.",
  "torso.anvilCore": "A body shaped like a shield, with a little badge in the middle.",

  "arms.sprocketMitts": "A soft round mitten with one little thumb.",
  "arms.peeperHooks": "A big curved claw with a gap for holding things.",
  "arms.kettleGrips": "A square fist with round corners and little finger lines.",
  "arms.lanternClamps": "A slim arm with a shiny rod and a small round hand.",
  "arms.hornetFists": "Two curved fingers curl beneath a little round palm.",
  "arms.pistonLevers": "A curly spring joins a round hand to its shoulder.",
  "arms.bulldozerFists": "A wide arm with a shield-shaped front and a little hand.",
  "arms.anvilGrips": "A wide round fist sits below two short bars.",

  "legs.sprocketPegs": "A small work boot with a long toe and a soft sole.",
  "legs.peeperStilts": "A little wheel wears a curved cover like a hat.",
  "legs.kettleShins": "A curly spring stands on a little boot.",
  "legs.lanternStruts": "A thin shiny rod stands above a long, flat shoe.",
  "legs.hornetBoots": "A curved leg leaves a big open space above its shoe.",
  "legs.pistonTreads": "A wide little track has three round wheels tucked inside.",
  "legs.bulldozerHooves": "Two short bars make an open leg above a chunky shoe.",
  "legs.anvilSprings": "A boot that gets wider at the bottom, with three soft pads.",

  "weapon.rustySpanner": "A curved wrench with a big open mouth and a soft handle.",
  "weapon.tinMallet": "A smooth little club with a round end and a soft handle.",
  "weapon.ironWrench": "A broad toy axe with a flared head and a little brass bolt.",
  "weapon.sparkDrill": "A small drill with a pointed brass nose and a button on top.",
  "weapon.steelSaw": "A round saw with chunky teeth and a brass dot in the middle.",
  "weapon.brassPike": "A long pointed tool with a tiny spring behind its tip.",
  "weapon.pistonHammer": "A square hammer with rounded black pads on both ends.",
  "weapon.anvilCleaver": "A curved blade sweeps up from a short, chunky handle.",
};
