/** Serializable simulation contracts. Positions use one shared truck/pavement grid. */
import type { BoilBasket, FryBatch, VesselKind } from './batch';
export type Point = { x: number; y: number };
export type DinerTier = 1 | 2 | 3 | 4;
export type Course = 'starter' | 'main' | 'drink' | 'dessert';
export type StationKind = 'crate' | 'fridge' | 'plates' | 'cups' | 'boxes' | 'bowls' | 'grill' | 'prep' | 'fryer' | 'boiler' | 'sink' | 'bin' | 'oven' | 'blender' | 'coffee' | 'drinks' | 'waffle' | 'pass';
export type CookingAction = 'instant' | 'hold' | 'timed' | 'risk';
export type RecipeStep = { station: StationKind; action: CookingAction; ticks: number; burnTicks?: number; label: string; output: string };
export type RecipeDef = { id: string; name: string; course: Course; ingredients: string[]; steps: RecipeStep[]; basePrice: number; reputation: number; route: 'starter' | 'downtown' | 'boardwalk' | 'night_market' | 'secret'; secret?: boolean; assemblyIngredients?:string[] };
export type IngredientDef = { id: string; name: string; rarity: 'common' | 'uncommon' | 'rare' };
export type EquipmentDef = { id: string; name: string; family: string; footprint: [number, number]; tiers: { tier: number; price: number; capacity: number; speed: number; noBurn?: boolean; warm?: boolean; automatic?: boolean }[] };
export type MealReference = { tableId: string; seatId: string; mealId: string };
export type ServiceItem = { id: string; kind: 'ingredient' | 'plate' | 'raw' | 'processed' | 'dish' | 'burnt' | 'dirty'; recipeId: string; step: number; stage: string; createdTick: number; finishedTick?: number; cold: boolean; meal?: MealReference; physical?:boolean; ingredientId?:string; components?:{id:string;ingredientId:string}[];plateId?:string;vesselKind?:VesselKind };
export type ServiceJob = { action: CookingAction | 'wash'; remaining: number; total: number; burnRemaining: number | null; ready: boolean };
export type StationSlot = { item: ServiceItem | null; job: ServiceJob | null;batch?:FryBatch|null;boil?:BoilBasket|null };
export type ServiceStation = Point & { id: string; kind: StationKind; facing: 0 | 1 | 2 | 3; tier: 1 | 2 | 3; slots: StationSlot[] };
export type SeatStatus = 'clean' | 'reserved' | 'occupied' | 'eating' | 'dirty' | 'awaitingWash';
/** Occupancy and dish are independent: an occupied seat can still hold the previous meal’s dirty vessel. */
export type ServiceSeat = Point & { id: string; status: SeatStatus; customerId: string | null; mealId: string | null; item: ServiceItem | null };
export type ServiceTable = Point & { id: string; capacity: 1 | 2 | 4; tier: 1 | 2; rotation: 0 | 1 | 2 | 3; seats: ServiceSeat[] };
export type CustomerType = 'walk_in' | 'office' | 'kid' | 'family' | 'critic' | 'influencer' | 'regular';
export type ServiceCustomer = Point & { id: string; groupId: string | null; type: CustomerType; phase: 'queue' | 'walking' | 'seated' | 'eating' | 'leaving' | 'gone'; path: Point[]; recipeId: string; patience: number; maxPatience: number; queuePatience: number; tableId: string | null; seatId: string | null; mealId: string | null; eatRemaining: number; payment: number; tip: number; servedCold: boolean; servedTick: number | null;washed?:boolean };
export type ServiceChef = Point & { path: Point[]; held: ServiceItem | null; targetId: string | null; targetSeatId: string | null; targetRecipeId: string | null; targetIngredientId?:string|null; targetItemId?:string|null; holding: boolean };
export type ServiceHelperConfig = { id:string;role:'washer'|'runner'|'prep';look?:number };
export type ServiceHelper = ServiceChef & ServiceHelperConfig & { task:{kind:'wash'|'deliver'|'prep';itemId:string|null;stationId:string|null;tableId:string|null;seatId:string|null;phase:'take'|'deliver'|'work'}|null };
export type ServicePhase = 'setup' | 'preparing' | 'playing' | 'closing' | 'paused' | 'complete' | 'failed';
export type ServiceConfig = { seed: string; tier: DinerTier; menu: string[]; recipeLevels: Record<string, number>; customers: number; arrivalTicks: number; queuePatienceTicks: number; tablePatienceTicks: number; cosy: boolean; practice: boolean; strikeLimit: number; tutorialFailure: boolean; customerTypes: CustomerType[]; specials: string[]; spices: string[];helpers:ServiceHelperConfig[];tipMultiplier:number;tutorialLearning:boolean;physicalSupplies:boolean;plateCount:number;cupCount:number;bowlCount:number;batchVersion:0|1;counterVersion:1 };
export type ServiceState = { version: 1; contentVersion: number; phase: ServicePhase; pausedPhase: 'preparing' | 'playing' | 'closing' | null; tick: number; rng: number; nextId: number; chef: ServiceChef;helpers:ServiceHelper[]; stations: ServiceStation[]; tables: ServiceTable[]; customers: ServiceCustomer[]; config: ServiceConfig; cleanPlates:number;plateStock:string[];cleanCups:number;cupStock:string[];cleanBowls:number;bowlStock:string[];spawned: number; nextArrival: number; coins: number; reputation: number; strikes: number; combo: number; served: number; paid: number; missed: number; burnt: number; washed: number; notice: string; events: ServiceEvent[]; influenceRemaining: number };
export type ServiceEvent = { id: number; tick: number; type: 'arrive' | 'sit' | 'ready' | 'burn' | 'serve' | 'pay' | 'strike' | 'wash' | 'complete'; targetId: string; amount?: number };
export type CreateServiceOptions = Partial<Omit<ServiceConfig, 'seed'>> & { seed?: string; stations?: ServiceStation[]; tables?: ServiceTable[] };
export type ServiceAction = { type: 'prepare' | 'open' | 'pause' | 'resume' | 'discard' } | { type: 'tick'; ticks: number } | { type: 'move'; x: number; y: number } | { type: 'interact'; targetId: string; recipeId?: string; seatId?: string; ingredientId?:string;itemId?:string } | { type: 'hold'; active: boolean };
export type ServiceResult = { coins: number; reputation: number; strikes: number; completed: boolean; failed: boolean; served: number; missed: number; practice: boolean };
