'use client';
import {useEffect,useRef,useState,type CSSProperties,type ReactNode} from 'react';
import dynamic from 'next/dynamic';
import {DOMAIN_IDS,DOMAIN_WORLDS,DOMAIN_COLLECTIBLE_BY_ID,DOMAIN_PACK_PRICES,type DomainId} from '@/lib/chef/diner/domain-worlds';
import type {PackKind} from '@/lib/chef/diner/collectible-packs-v1';
import {hasDomainArtStudy} from '@/lib/chef/diner/domain-art-studies';
import {beginPackPreview,emptyPackPreview,experiencePackItems,finishPackPreview,PACK_PREVIEW_KEY,placementCopy,previewDiscoveries,RARITY_PRESENTATION,restorePackPreview,revealPhase,type PackPreviewSession,type PreviewOpening,type RevealPhase} from '@/lib/chef/diner/pack-experience';
import {createDkSfx,type DkSfx} from '../diner-preview/audio';
import PackEmblem from './PackEmblem';
import css from './pack-experience.module.css';
import CollectibleThumbnail from './CollectibleThumbnail';
import CinematicOpening from './CinematicOpening';
const Stage=dynamic(()=>import('./CollectibleStage'),{ssr:false,loading:()=> <div className={css.stageLoading}>Setting the spotlight…</div>});
const Room=dynamic(()=>import('../domain-review/DomainRoomReview'),{ssr:false,loading:()=> <p>Opening the room preview…</p>});

function Sheet({title,children,onClose,cinema=false}:{title:string;children:ReactNode;onClose:()=>void;cinema?:boolean}){
 const panel=useRef<HTMLDivElement>(null),close=useRef(onClose);close.current=onClose;
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null,overflow=document.body.style.overflow;document.body.style.overflow='hidden';panel.current?.focus();
 const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();close.current();}if(e.key==='Tab'&&panel.current){const nodes=Array.from(panel.current.querySelectorAll<HTMLElement>('button:not(:disabled),a[href],summary,[tabindex="0"]')).filter(n=>n.getClientRects().length);const first=nodes[0],last=nodes[nodes.length-1];if(!first){e.preventDefault();return;}if(e.shiftKey&&(document.activeElement===first||document.activeElement===panel.current)){e.preventDefault();last.focus();}else if(!e.shiftKey&&(document.activeElement===last||document.activeElement===panel.current)){e.preventDefault();first.focus();}}};document.addEventListener('keydown',key);return()=>{document.body.style.overflow=overflow;document.removeEventListener('keydown',key);previous?.focus();};},[]);
 return <div className={css.backdrop} onClick={e=>{if(!cinema&&e.target===e.currentTarget)onClose();}}><div ref={panel} className={cinema?css.cinema:css.sheet} role="dialog" aria-modal="true" aria-label={title} tabIndex={-1}>{children}{!cinema&&<button className={css.close} aria-label={`Close ${title}`} onClick={onClose}>×</button>}</div></div>;
}
function FoilPack({domain,pack}:{domain:DomainId;pack:PackKind}){
 return <div className={css.parcel} data-pack={pack} aria-hidden="true"><div className={css.packShadow}/><div className={css.packBody}><div className={css.packSide}/><div className={css.packFront}><span className={css.foilBrand}>{DOMAIN_WORLDS[domain].name}</span><PackEmblem domain={domain}/><strong>{pack==='super'?'SUPER':'REGULAR'}</strong><span className={css.foilEdition}>THE RESTAURANT COLLECTION</span><div className={css.packSeal}>DK</div></div><div className={css.packLid}><span>OPEN SOMETHING EXTRAORDINARY</span></div></div></div>;
}
const themes:Record<DomainId,{title:string;accent:string;dark:string;line:string}>={gochujang:{title:'A little heat.\nA lot of character.',accent:'#ab372b',dark:'#321d1d',line:'Red lacquer. Midnight ramyeon. A tiny Fireant world.'},smoothie:{title:'A little sunshine.\nEntirely yours.',accent:'#277763',dark:'#153e36',line:'Tropical fruit. Sculpted glass. A brighter kind of bar.'},wines:{title:'Good taste.\nGreat company.',accent:'#78374d',dark:'#30212d',line:'Walnut, warm brass and extraordinary little vintages.'}};

export default function PackExperience({initialDomain,verifiedCollectionReview=false}:{initialDomain?:DomainId;verifiedCollectionReview?:boolean}){
 const [domain,setDomain]=useState<DomainId>(initialDomain??'gochujang'),[view,setView]=useState<'welcome'|'packs'|'collection'|'leaderboard'>(initialDomain?'packs':'welcome'),[pack,setPack]=useState<PackKind>('regular');
 const [session,setSession]=useState<PackPreviewSession>(emptyPackPreview),[hydrated,setHydrated]=useState(false),[storageWarning,setStorageWarning]=useState(false);
 const [receipt,setReceipt]=useState<PreviewOpening|null>(null),[phase,setPhase]=useState<RevealPhase>('arrival'),[playback,setPlayback]=useState(0),[recovered,setRecovered]=useState(false),[roomItem,setRoomItem]=useState<string|null>(null),[inspect,setInspect]=useState<string|null>(null),[sheet,setSheet]=useState<'odds'|'help'|'terms'|null>(null),[reduced,setReduced]=useState(false),[sound,setSound]=useState(false),[turn,setTurn]=useState(0),[cinematic,setCinematic]=useState(true);
 const activeLock=useRef(false),sfx=useRef<DkSfx|null>(null),soundRef=useRef(false),finishRef=useRef(()=>{});
 useEffect(()=>{window.scrollTo(0,0);},[view,domain]);
 useEffect(()=>{try{const saved=restorePackPreview(sessionStorage.getItem(PACK_PREVIEW_KEY));setSession(saved);if(saved.pending){setReceipt(saved.pending);setDomain(saved.pending.domain);setPack(saved.pending.pack);setView('packs');setRecovered(true);setPhase('revealed');setSession(finishPackPreview(saved));}}catch{setStorageWarning(true);}setHydrated(true);
 const mq=matchMedia('(prefers-reduced-motion: reduce)'),change=()=>setReduced(mq.matches);change();mq.addEventListener('change',change);return()=>{mq.removeEventListener('change',change);sfx.current?.destroy();};},[]);
 useEffect(()=>{if(!hydrated)return;try{sessionStorage.setItem(PACK_PREVIEW_KEY,JSON.stringify(session));}catch{setStorageWarning(true);}},[session,hydrated]);
 finishRef.current=()=>{setPhase('revealed');setSession(s=>finishPackPreview(s));activeLock.current=false;};
 useEffect(()=>{if(!receipt||recovered||(cinematic&&!reduced))return;setPhase('arrival');setTurn(0);let elapsed=0,prior=0,frame=0,last:RevealPhase='arrival',ended=false;const item=DOMAIN_COLLECTIBLE_BY_ID[receipt.itemId];
 const tick=(now:number)=>{if(ended)return;if(document.hidden){prior=now;frame=requestAnimationFrame(tick);return;}elapsed+=prior?Math.min(80,now-prior):0;prior=now;const next=revealPhase(elapsed,item.rarity,reduced);if(next!==last){last=next;setPhase(next);}if(next==='revealed'){ended=true;finishRef.current();}else frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);return()=>{ended=true;cancelAnimationFrame(frame);};},[receipt?.id,playback,recovered,reduced,cinematic]);
 useEffect(()=>{if(receipt&&soundRef.current&&phase!=='arrival')sfx.current?.play(phase==='hint'?'hustle':phase==='unseal'?'bus':'unlock');},[phase,receipt?.id]);
 const world=DOMAIN_WORLDS[domain],theme=themes[domain],items=experiencePackItems(domain,pack),discoveries=previewDiscoveries(session,domain),result=receipt?DOMAIN_COLLECTIBLE_BY_ID[receipt.itemId]:null;
 const style={'--accent':theme.accent,'--world-dark':theme.dark} as CSSProperties;
 function openPreview(){if(!hydrated||activeLock.current||session.pending)return;const next=beginPackPreview(session,domain,pack);if(!next.pending)return;activeLock.current=true;setCinematic(true);setTurn(0);setRecovered(false);setPhase('arrival');setSession(next);setReceipt(next.pending);setPlayback(n=>n+1);if(sound)sfx.current?.play('doorbell');}
 function closeReveal(){finishRef.current();setReceipt(null);setRecovered(false);}
 function chooseDomain(id:DomainId){setDomain(id);setView('packs');setPack('regular');}
 function toggleSound(){const enabled=!sound;setSound(enabled);soundRef.current=enabled;if(!sfx.current){sfx.current=createDkSfx(enabled);sfx.current.setMusicMuted(true);}else sfx.current.setMuted(!enabled);if(enabled)sfx.current.play('serve');}
 function roomPreview(id:string){closeReveal();setRoomItem(id);}
 return <main className={css.page} style={style} data-domain={domain}>
  <header className={css.header}><a href="/chef/diner-preview" className={css.brand}><img src="/chef/kitchen-icon.svg" alt="" width="34" height="34"/>DOMAIN KITCHEN</a><div><button onClick={()=>setSheet('help')}>How it works</button><a href="/chef/diner-preview">My restaurant ↗</a></div></header>
  <div className={css.previewBar}><span className={css.previewDot}/>PRIVATE PREVIEW<span>Samples only. No payments or NFTs.</span></div>
  {view==='welcome'?<>
   <section className={css.welcome}><span className={css.eyebrow}>THE COLLECTORS’ TABLE</span><h1>Little worlds.<br/><em>Big personality.</em></h1><p>Find extraordinary pieces for your restaurant.<br/>Choose a world to start exploring.</p></section>
   <div className={css.worlds}>{DOMAIN_IDS.map(id=><button key={id} className={css.worldCard} onClick={()=>chooseDomain(id)} style={{'--accent':themes[id].accent} as CSSProperties}><div className={css.roomImage}><img src={`/api/chef/pack-preview-image/${id}`} alt={`${DOMAIN_WORLDS[id].room} themed restaurant`}/></div><div className={css.worldCopy}><small>{DOMAIN_WORLDS[id].name}</small><h2>{DOMAIN_WORLDS[id].room}</h2><p>{themes[id].line}</p><span>Explore collection <b>↗</b></span></div></button>)}</div>
   <section className={css.startLoop}><div><span className={css.eyebrow}>NEW TO DOMAIN KITCHEN?</span><h2>Cook on the road.<br/>Make yourself at home.</h2></div><p>Run your food truck to discover recipes and equipment. Come home to upgrade dishes and build a restaurant that feels like you.</p><a className={css.primary} href="/chef/diner-preview">Start my restaurant ↗</a></section>
  </>:<>
   <div className={css.domainNav}><button className={css.back} onClick={()=>setView('welcome')}>← All worlds</button><div className={css.worldTabs} aria-label="Domain collection">{DOMAIN_IDS.map(id=><button key={id} aria-pressed={id===domain} onClick={()=>chooseDomain(id)}>{DOMAIN_WORLDS[id].name}</button>)}</div></div>
   <nav className={css.tabs} aria-label="Collection pages">{(['packs','collection','leaderboard'] as const).map(v=><button key={v} aria-current={view===v?'page':undefined} onClick={()=>setView(v)}>{v==='packs'?'Packs':v==='collection'?<>My preview collection <span>{discoveries.size}/24</span></>:'Leaderboard'}</button>)}</nav>
   {view==='packs'?<>
    <section className={css.packHero}>
     <div className={css.packIntro}><span className={css.eyebrow}>{world.name} · COLLECTION 01</span><h1>{theme.title.split('\n').map((l,i)=><span key={l}>{i?<em>{l}</em>:l}</span>)}</h1><p>{theme.line}</p><div className={css.packChooser} aria-label="Choose pack">{(['regular','super'] as const).map(p=><button key={p} aria-pressed={p===pack} onClick={()=>setPack(p)}><strong>{p==='regular'?'Regular':'Super'}</strong><span>{DOMAIN_PACK_PRICES[p]/1e6} USDC*</span></button>)}</div><p className={css.small}>12 designs per pack · One collectible per opening</p></div>
     <div className={css.packDisplay}><div className={css.displayRing}/><FoilPack domain={domain} pack={pack}/><span className={css.displayCaption}>{pack==='regular'?'THE EVERYDAY EXTRAORDINARY':'AFTER HOURS. ABOVE ORDINARY.'}</span></div>
     <div className={css.openBar}><div><strong>Collect it. Place it. Make it yours.</strong><span>Decorations & equipment appearances. No gameplay advantage.</span></div><button className={css.primary} disabled={!hydrated} onClick={openPreview}>Preview {pack==='regular'?'Regular':'Super'} opening <span>↗</span></button><p>Curated reveal demo, not a paid draw. <button className={css.textButton} onClick={()=>setSheet('odds')}>See all 12 & exact launch odds</button></p></div>
    </section>
    <section className={css.collectionGoal}><div className={css.goalImage}><img src={`/api/chef/pack-preview-image/${domain}`} alt={world.room}/></div><div><span className={css.eyebrow}>THE COMPLETE-COLLECTION RESTAURANT</span><h2>Make the whole world yours.</h2><p>Discover all 24 different pieces across both packs to unlock this restaurant. Each counts forever, even after selling or redeeming it.</p><div className={css.collectionMeter} aria-label={`${discoveries.size} of 24 items discovered in preview`}>{Array.from({length:24},(_,i)=><span key={i} data-filled={i<discoveries.size}/>)}</div><div className={css.goalFoot}><small>{discoveries.size}/24 in this preview · No real unlocks</small><button className={css.textButton} onClick={()=>setView('collection')}>View collection →</button></div></div></section>
    <p className={css.launchNote}>*Proposed prices. Purchasing and redemption are closed. <button className={css.textButton} onClick={()=>setSheet('terms')}>Token backing & launch terms</button></p>
   </>:view==='collection'?<section className={css.collection}><div className={css.sectionHeading}><div><span className={css.eyebrow}>{world.name}</span><h1>A home for every find.</h1><p>{discoveries.size} of 24 different designs seen in this preview. Samples don’t unlock the real restaurant.</p></div><button className={css.secondary} onClick={()=>setView('packs')}>Back to packs</button></div><div className={css.collectionGrid}>{(['regular','super'] as const).flatMap(p=>experiencePackItems(domain,p).map(item=><button key={item.id} className={css.itemCard} data-discovered={discoveries.has(item.id)} disabled={!hasDomainArtStudy(item.id)} onClick={()=>setInspect(item.id)}><div className={css.itemImage}>{hasDomainArtStudy(item.id)?<CollectibleThumbnail id={item.id}/>:<PackEmblem domain={domain}/>}</div><span className={css.itemMeta}>{item.rarity} · {p}</span><strong>{item.name}</strong><small>{!hasDomainArtStudy(item.id)?'Artwork in production':discoveries.has(item.id)?'✓ Seen in preview':'Inspect piece'}</small></button>))}</div></section>:<section className={css.board}><span className={css.eyebrow}>{world.name} · OPENING LEADERBOARD</span><h1>A place at the table.</h1><div className={css.packChooser}>{(['regular','super'] as const).map(p=><button key={p} aria-pressed={pack===p} onClick={()=>setPack(p)}>{p==='regular'?'Regular':'Super'} openings</button>)}</div><div className={css.boardEmpty}><PackEmblem domain={domain}/><h2>The season hasn’t started.</h2><p>Verified {pack} openings will count here. Dates and any funded prizes will appear when approved.</p></div><p className={css.small}>Equal counts share a rank. Rarity adds no points. Redeeming a pull keeps its opening credit. Samples never count.</p></section>}
  </>}
  {storageWarning&&<p className={css.storageWarning} role="status">This browser can’t save the preview. You can still explore; sample progress may disappear on reload.</p>}
  <footer className={css.footer}>{verifiedCollectionReview&&<a href={`/chef/collection-review?domain=${domain}`}>Check my verified restaurant reward ↗</a>}<span>DOMAIN KITCHEN</span><p>A little place. Entirely yours.</p><a href="/chef/domain-review">Private art workshop ↗</a></footer>
  {sheet&&<Sheet title={sheet==='odds'?'Pack contents and odds':sheet==='help'?'How Domain Kitchen works':'Launch terms'} onClose={()=>setSheet(null)}>
   {sheet==='odds'?<><span className={css.eyebrow}>{world.name} · {pack.toUpperCase()} PACK</span><h2>Know what’s inside.</h2><p>One collectible. Exact proposed odds per item, totaling 100%.</p><div className={css.oddsList}>{items.map(item=><div key={item.id}><span>{item.name}<small>{item.rarity}</small></span><strong>{item.weight/100}%</strong></div>)}</div><p className={css.small}>Independent openings. Duplicates are possible. No pity, guarantees or changing probabilities.</p><p className={css.small}>The free screen demo tours selected finished artwork. It does not sample these probabilities.</p></>:sheet==='help'?<><span className={css.eyebrow}>WELCOME TO DOMAIN KITCHEN</span><h2>Your restaurant.<br/>Your kind of fun.</h2><ol className={css.steps}><li><strong>Cook & grow</strong><p>Take the truck out to discover recipes and equipment. Bring them home to your restaurant.</p></li><li><strong>Collect & decorate</strong><p>Open a domain pack, keep its NFT and place the piece, or redeem its published token backing once live.</p></li><li><strong>Complete a world</strong><p>Discover its 24 different pieces at least once to earn the full restaurant theme. You don’t have to keep holding them.</p></li></ol><button className={css.primary} onClick={()=>setSheet(null)}>Got it. Let’s explore.</button></>:<><span className={css.eyebrow}>PURCHASES ARE CLOSED</span><h2>A clear choice, before you open.</h2><p>Regular and Super packs have proposed prices of 5 and 10 USDC. Actual contracts, fees, token backing and settlement still require developer verification.</p><p>At launch, keep and place your collectible NFT, or redeem its backing in that domain’s token. The exact token amount and fees must be visible before you confirm.</p><p>No fixed USDC return, prize pool or financial return is promised. This preview cannot purchase, mint, redeem or grant collection credit.</p></>}
  </Sheet>}
  {inspect&&<Sheet title="Collectible details" onClose={()=>setInspect(null)}><span className={css.eyebrow}>{DOMAIN_COLLECTIBLE_BY_ID[inspect].rarity} · ART PREVIEW</span><h2>{DOMAIN_COLLECTIBLE_BY_ID[inspect].name}</h2><div className={css.inspectStage}><Stage id={inspect} reduced={reduced}/></div><p>{DOMAIN_COLLECTIBLE_BY_ID[inspect].description}</p><p className={css.small}>{placementCopy(DOMAIN_COLLECTIBLE_BY_ID[inspect])}</p><button className={css.primary} onClick={()=>{setRoomItem(inspect);setInspect(null);}}>Try it in a room →</button></Sheet>}
  {roomItem&&<Sheet title="Try the collectible in a restaurant" onClose={()=>setRoomItem(null)}><span className={css.eyebrow}>ISOLATED ROOM PREVIEW</span><h2>Give it a place.</h2><p>This shows the piece in its themed room. Your restaurant and inventory stay untouched.</p><Room key={roomItem} domain={DOMAIN_COLLECTIBLE_BY_ID[roomItem].domain} initialItem={roomItem}/><button className={css.primary} onClick={()=>{setRoomItem(null);setView('collection');}}>Back to my preview collection</button></Sheet>}
  {receipt&&result&&<Sheet cinema title="Pack opening" onClose={()=>{if(phase==='revealed')closeReveal();else{setRecovered(true);finishRef.current();}}}>
   <div className={css.cinemaInner} style={{...style,'--rarity':RARITY_PRESENTATION[result.rarity].color} as CSSProperties} data-phase={phase} data-rarity={result.rarity} data-reduced={reduced} data-cinematic={cinematic&&!reduced&&!recovered}>
    <div className={css.cinemaTop}><span>{world.name} · {receipt.pack.toUpperCase()} PREVIEW</span><div><button onClick={toggleSound} aria-pressed={sound}>{sound?'Sound on':'Sound off'}</button><button onClick={()=>{if(phase==='revealed')closeReveal();else{setRecovered(true);finishRef.current();}}}>{phase==='revealed'?'Close':'Skip animation'}</button></div></div>
    {cinematic&&!reduced&&!recovered&&phase!=='revealed'&&<CinematicOpening key={`${receipt.id}:${playback}`} domain={receipt.domain} rarity={result.rarity} onPhase={setPhase} onFinish={()=>finishRef.current()} onFallback={()=>{setCinematic(false);setPhase('arrival');}}/>}<div className={css.deliveryLights} aria-hidden="true"/><div className={css.revealRings} aria-hidden="true"/>
    <div className={css.revealHeading} aria-live="polite"><span className={css.eyebrow}>{phase==='arrival'?'SPECIAL DELIVERY':phase==='revealed'?`${result.rarity} · ${discoveries.has(result.id)&&session.openings.filter(r=>r.itemId===result.id).length>1?'DUPLICATE PREVIEW':'COLLECTION FIND'}`:result.rarity}</span><p>{phase==='arrival'?'A little world is on its way.':phase==='revealed'?'Collect it. Place it. Make it yours.':RARITY_PRESENTATION[result.rarity].hint}</p></div>
    <div className={css.revealArt}><div className={css.arrivingParcel}><FoilPack domain={receipt.domain} pack={receipt.pack}/></div><div className={css.rarityMarks} aria-hidden="true">{'✦'.repeat(RARITY_PRESENTATION[result.rarity].marks)}</div><div className={css.revealedModel} aria-hidden={phase!=='revealed'}><Stage id={result.id} reduced={reduced} turn={turn}/></div></div>
    {phase==='revealed'&&<div className={css.resultCopy}><h1>{result.name}</h1><p>{placementCopy(result)}</p><div className={css.resultActions}><button className={css.primary} onClick={()=>roomPreview(result.id)}>Try it in a room →</button><button className={css.secondary} onClick={()=>{closeReveal();setView('collection');}}>View preview collection</button></div><div className={css.resultTools}><button onClick={()=>setTurn(n=>n+1)}>Turn the piece ↻</button><button onClick={()=>{setCinematic(true);setTurn(0);setRecovered(false);setPhase('arrival');setPlayback(n=>n+1);}}>Replay reveal</button></div><small>Sample only. No NFT, leaderboard credit or restaurant unlock. Redemption is unavailable.</small></div>}
   </div>
  </Sheet>}
 </main>;
}
