/**
 * BATTLE BOTS RIG POINTS. GENERATED by scripts/bots-bake-parts.mjs; do not
 * edit by hand. Re-run the bake to change a point, because the placeholder
 * art, the rig (rig.ts) and the art gate (scripts/bots-art-check.mts) must
 * all read the same numbers. All coordinates are @2x canvas pixels
 * (screens doc 2.4).
 */

export type Pt = readonly [number, number];

export const RIG = {
  head: { w: 160, h: 160, neck: [80, 150] },
  torso: { w: 200, h: 240, neck: [100, 10], shoulderL: [22, 60], shoulderR: [178, 60], hipL: [62, 228], hipR: [138, 228], decal: [100, 120] },
  arm: { w: 90, h: 200, shoulder: [45, 20], hand: [45, 180] },
  leg: { w: 90, h: 200, hip: [45, 20], foot: [45, 195] },
  weapon: { w: 220, h: 120, grip: [30, 60] },
} as const;

export type ArtSlot = keyof typeof RIG;
export const ART_SLOTS: readonly ArtSlot[] = ["head", "torso", "arm", "leg", "weapon"];

/** The scissor lift: two states on one canvas, bottom-aligned on the floor. */
export const LIFT = { w: 640, h: 420, topDown: 380, topRaised: 300, platformW: 600 } as const;

export const TIERS = [1, 2, 3, 4] as const;
export const DESIGNS = [1, 2] as const;

export const partFile = (slot: ArtSlot, tier: number, design: number): string =>
  `/bots-art/parts/${slot}/t${tier}-${design}.png`;
export const maskFile = (slot: ArtSlot, tier: number, design: number): string =>
  `/bots-art/parts/${slot}/t${tier}-${design}.mask.png`;
export const liftFile = (state: "down" | "raised"): string => `/bots-art/lift/${state}.png`;

/** Every rig point of a slot, for the gate: each must land on opaque pixels. */
export function rigPoints(slot: ArtSlot): Pt[] {
  const r = RIG[slot] as Record<string, unknown>;
  return Object.entries(r)
    .filter(([k]) => k !== "w" && k !== "h")
    .map(([, v]) => v as Pt);
}
