/**
 * Season 1 — Results & Proof.
 *
 *   /launch-wars/proof
 *
 * A public, shareable record of every captain who took part in Launch Wars
 * Season 1: their fleet points, their boss contribution, and where they
 * finished. Built so no one can claim they did a lot and got nothing.
 *
 * Deliberately shows NO payout amounts and NO wallet addresses. It proves
 * participation and points, not prizes. Data is a frozen snapshot generated by
 * doma-reporter/scripts/s1_proof.js from settled, on-chain-verified results.
 *
 * Design language matches /launch-wars (EPL meets Bloomberg). Copy is plain,
 * no contractions, translation-friendly. Server component; the table itself is
 * the one small client component (sorting + name filter).
 */
import proof from "@/data/s1-proof.json";
import ProofTable, { type ProofRow } from "./ProofTable";
import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Launch Wars Season 1 — Results & Proof",
  description:
    "Every captain in Launch Wars Season 1: their fleet points, their boss contribution, and where they finished. Public proof of participation. No payout amounts, no wallet addresses.",
  openGraph: {
    title: "Launch Wars Season 1 — Results & Proof",
    description:
      "Every captain, their points, and where they finished. Public proof of participation in Launch Wars Season 1 on Doma.",
    type: "website",
    url: "https://web3guides.com/launch-wars/proof",
  },
  twitter: { card: "summary_large_image", title: "Launch Wars Season 1 — Results & Proof" },
};

const T = {
  bg: "#0a0d14",
  panel: "#10141d",
  panel2: "#0c1018",
  line: "rgba(255,255,255,0.07)",
  line2: "rgba(255,255,255,0.14)",
  text: "#e9edf5",
  mut: "#97a0b5",
  dim: "#626b82",
  violet: "#8b7cff",
  green: "#34d399",
  rose: "#fb6f84",
  amber: "#fbbf24",
  cyan: "#38bdf8",
};
const MAXW = 1140;
const MONO = "ui-monospace, 'SF Mono', 'Cascadia Mono', Menlo, Consolas, monospace";
const NUM: React.CSSProperties = { fontFamily: MONO, fontVariantNumeric: "tabular-nums" };

const LEGEND: { label: string; color: string; note: string }[] = [
  { label: "Paid", color: T.green, note: "Earned a share of the prize, on the winning fleet or by dealing at least $10 of held boss damage." },
  { label: "Fleet did not place", color: T.mut, note: "Earned fleet points, but their fleet was not the season winner. Season 1 paid the winning fleet only." },
  { label: "Sold before the end", color: T.rose, note: "Left their fleet, or sold a boss token before the event ended." },
  { label: "Under the $10 boss minimum", color: T.amber, note: "Bought a boss but held less than the $10 needed to share its reward." },
  { label: "Boss did not bond", color: T.cyan, note: "Took part on a boss that did not reach bonding, so no one was paid on it." },
  { label: "Participated", color: T.dim, note: "Joined and took part, with no scored fleet or boss activity recorded." },
];

function StatTile({ value, label }: { value: string; label: string }) {
  return (
    <div style={{ flex: "1 1 150px", background: T.panel, border: `1px solid ${T.line}`, borderRadius: 12, padding: "16px 18px" }}>
      <div style={{ ...NUM, fontSize: 28, fontWeight: 700, color: T.text }}>{value}</div>
      <div style={{ fontSize: 12, letterSpacing: 0.4, textTransform: "uppercase", color: T.mut, marginTop: 4 }}>{label}</div>
    </div>
  );
}

export default function Page() {
  const rows = proof.rows as ProofRow[];
  const t = proof.totals;
  const generated = new Date(proof.generatedAt).toISOString().slice(0, 10);

  return (
    <main style={{ background: T.bg, color: T.text, minHeight: "100vh", fontFamily: "ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, sans-serif" }}>
      <div style={{ maxWidth: MAXW, margin: "0 auto", padding: "48px 20px 80px" }}>
        <div style={{ fontSize: 12, letterSpacing: 1, textTransform: "uppercase", color: T.violet, fontWeight: 600 }}>Launch Wars · Season 1</div>
        <h1 style={{ fontSize: 34, lineHeight: 1.15, fontWeight: 800, margin: "10px 0 0" }}>Results and proof</h1>
        <p style={{ fontSize: 16, lineHeight: 1.6, color: T.mut, maxWidth: 720, marginTop: 12 }}>
          Every captain who took part in Season 1, what they earned, and where they finished. This page is the public record, so no one can claim they did a lot and walked away with nothing.
        </p>
        <p style={{ fontSize: 14, lineHeight: 1.6, color: T.dim, maxWidth: 720, marginTop: 10 }}>
          It shows fleet points and boss contribution. It does not show payout amounts or wallet addresses. It proves participation and points, not prizes.
        </p>

        <div style={{ display: "flex", flexWrap: "wrap", gap: 12, marginTop: 28 }}>
          <StatTile value={String(t.participants)} label="Captains" />
          <StatTile value={String(t.winners)} label="Paid winners" />
          <StatTile value={proof.winningFleet || "—"} label="Winning fleet" />
        </div>

        <section style={{ marginTop: 28, background: T.panel2, border: `1px solid ${T.line}`, borderRadius: 12, padding: "18px 20px" }}>
          <div style={{ fontSize: 12, letterSpacing: 0.5, textTransform: "uppercase", color: T.mut, marginBottom: 12 }}>What each result means</div>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))", gap: "10px 24px" }}>
            {LEGEND.map((l) => (
              <div key={l.label} style={{ display: "flex", gap: 10, alignItems: "flex-start" }}>
                <span style={{ marginTop: 2, flex: "0 0 auto", width: 9, height: 9, borderRadius: 3, background: l.color }} />
                <div>
                  <span style={{ color: l.color, fontWeight: 600, fontSize: 13.5 }}>{l.label}</span>
                  <span style={{ color: T.dim, fontSize: 13, lineHeight: 1.5 }}> — {l.note}</span>
                </div>
              </div>
            ))}
          </div>
        </section>

        <div style={{ marginTop: 32 }}>
          <ProofTable rows={rows} />
        </div>

        <footer style={{ marginTop: 36, paddingTop: 18, borderTop: `1px solid ${T.line}`, fontSize: 12.5, color: T.dim, lineHeight: 1.6 }}>
          <p>
            Fleet points are the final Launch Wars score on each captain&apos;s registered wallet. A score of zero means they did not play the fleet game on that wallet. Boss contribution is the net dollars held into a boss at settlement, verified on-chain. &quot;Sold before the end&quot; is read from the chain and counts only sells dated before the event ended.
          </p>
          <p style={{ marginTop: 8 }}>
            Frozen snapshot generated {generated}. <Link href="/launch-wars" style={{ color: T.violet }}>Back to Launch Wars</Link>.
          </p>
        </footer>
      </div>
    </main>
  );
}
