"""BATTLE BOTS: INSTALL THE BODY RULERS AS A SHAPE TABLE (lane T, 2026-09-05).

    python scripts/sd/bots-sd-shape-install-bodies.py           # install and verify
    python scripts/sd/bots-sd-shape-install-bodies.py --check   # verify only, write nothing

WHY IT EXISTS. scripts/sd/rank-part.py measures a candidate against the ruler
for ITS OWN shape when a shape table names one, and against the SHIP ruler
when it does not. All eight shipped torso rulers are one barrel, so a teapot
judged with no teapot row would be marked down for failing to be a barrel: the
judge would be correct and useless at the same time. That is the seam section
4a of the judge exists to close, and a table that closes it for the heads and
the legs but not for the body would be a judge that bends for one slot.

WHERE IT INSTALLS. Into .bots-preview/sd-shapes2, WAVE TWO'S SHARED TRAY: the
head lane installs its looks into parts/head of the same tree, so the table
here is MERGED and never overwritten. Every row this file does not own is read
back and written out untouched, in its original order, and a re-run is
idempotent. That is not politeness: the judge resolves a candidate's ruler out
of this file, so a row dropped by someone else's installer is a candidate
silently measured against the ship ruler, which for the torso is one barrel
eight times. NOTHING HERE SHIPS: public/bots-art/parts is the live catalogue
and is never read, never written and never staged by this file.

THE ID IS `<slot>-<shape>`, not `<shape>`. The renderer writes every candidate
under out/stage7-bodies/<slot>-<shape>/cut/, so `torso-teapot` is a whole path
segment and resolves with no guess. A bare `teapot` would be fine today but a
bare `tube` would also match the token `tube` in any filename that carries it,
and two rows for one candidate is an ambiguity refusal from the judge.

EVERY ROW IS VERIFIED BY THE JUDGE'S OWN READER, imported rather than copied:
rank_part.shape_ruler runs the canvas, ink, pivot and proportion-band guards on
the PNG, and rank_part.infer_shape proves a real candidate path resolves to
exactly one row. A check that re-implemented either would reproduce this
file's own assumptions and pass (lesson_gates_must_import_not_reimplement).
"""
from __future__ import annotations

import argparse
import importlib.util
import json
import os
import shutil
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
sys.path.insert(0, HERE)

V3 = os.path.join(ROOT, "public", "bots-art", "_raw", "parts", "placeholders-v3")
PREVIEW = os.path.join(ROOT, ".bots-preview", "sd-shapes2")
PARTS = os.path.join(PREVIEW, "parts")
TABLE = os.path.join(PREVIEW, "shape-table.json")
MANIFEST = {"torso": "manifest-torso.json", "arm": "manifest-arm.json"}
STEM = {"torso": "torso", "arm": "arms"}

HEADER = [
    "THE BODY SHAPE TABLE, as scripts/sd/rank-part.py reads it. GENERATED by",
    "scripts/sd/bots-sd-shape-install-bodies.py from the v3 bake's own manifests; do",
    "not edit by hand. The authored table is scripts/bots-shapes.json (bodies) and",
    "the drawing is bots-bake-parts.mjs --out v3 --only torso,arm.",
    "",
    "Every ruler here is on the contract canvas at the contract's pivots and is what",
    "a candidate of that shape is measured against, so that a teapot is not judged",
    "for failing to be a barrel. No judge rule and no bar moves for any of them:",
    "every torso keeps the contract's proportion bands, the buried skirt, clay under",
    "the neck, both hips and the decal anchor, and the wind-up key at the importer's",
    "own anchor; every arm keeps burial 0.50, ink under the hand pivot and its own",
    "three bands. Each of those is checked on the rendered pixels at bake time and",
    "each row here is re-checked by the judge's own reader on install.",
    "",
    "Nothing here ships. public/bots-art/parts is the live catalogue and this tree",
    "is a preview.",
]


def die(msg: str) -> None:
    raise SystemExit("bots-sd-shape-install-bodies REFUSES: " + msg)


def load_judge():
    """rank-part.py by path. Importing the judge is the whole point: a check
    that re-implements its reader reproduces its author's assumptions."""
    p = os.path.join(HERE, "rank-part.py")
    spec = importlib.util.spec_from_file_location("rank_part", p)
    mod = importlib.util.module_from_spec(spec)
    sys.modules["rank_part"] = mod
    spec.loader.exec_module(mod)
    return mod


def rows() -> list[dict]:
    out = []
    for slot in ("torso", "arm"):
        p = os.path.join(V3, MANIFEST[slot])
        if not os.path.exists(p):
            die(f"no {p}. Run `node scripts/bots-bake-parts.mjs --out v3 --only torso,arm` first.")
        man = json.load(open(p, encoding="utf-8"))
        if man["slot"] != slot:
            die(f"{p} declares slot {man['slot']!r}, not {slot!r}")
        for r in man["shapeRows"]:
            src = os.path.join(V3, "target", f"{STEM[slot]}-{r['shape']}.png")
            if not os.path.exists(src):
                die(f"{MANIFEST[slot]} lists {r['shape']} but {src} is not on disk")
            out.append({
                "id": f"{slot}-{r['shape']}", "slot": slot, "shape": r["shape"], "src": src,
                "name": r["name"], "prompt": r["prompt"], "notes": r["notes"],
                "live": bool(r.get("live")), "ratios": r["ratios"],
            })
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="verify only, write nothing")
    args = ap.parse_args()

    body = rows()
    if args.check and not os.path.exists(TABLE):
        die(f"no shape table at {TABLE}; run this file without --check first")

    if not args.check:
        for r in body:
            d = os.path.join(PARTS, r["slot"])
            os.makedirs(d, exist_ok=True)
            shutil.copyfile(r["src"], os.path.join(d, r["id"] + ".png"))
        mine = [{
            "id": r["id"], "slot": r["slot"],
            "ruler": f"parts/{r['slot']}/{r['id']}.png",
            "name": r["name"], "shape": r["shape"],
            "prompt": r["prompt"], "notes": r["notes"],
            "live": r["live"], "ratios": r["ratios"],
        } for r in body]
        # MERGE, NEVER OVERWRITE. sd-shapes2 is wave two's SHARED tray: the
        # head lane installs its looks into parts/head of this same tree. Rows
        # this lane does not own keep their place and their order, and only
        # this lane's ids are replaced, so a re-run is idempotent and nobody
        # else's rows can go missing. The judge resolves a candidate's ruler
        # out of this file, so a dropped row is a candidate silently measured
        # against the ship ruler, which for the torso is one barrel eight times.
        old_table, kept = {}, []
        if os.path.exists(TABLE):
            old_table = json.load(open(TABLE, encoding="utf-8"))
            ids = {r["id"] for r in mine}
            kept = [r for r in old_table.get("shapes", []) if r.get("id") not in ids]
        table = dict(old_table)
        table.setdefault("_", HEADER)
        table["_bodies"] = HEADER
        table["shapes"] = kept + mine
        print(f"  merged: kept {len(kept)} rows from other lanes, wrote {len(mine)} body rows")
        os.makedirs(PREVIEW, exist_ok=True)
        with open(TABLE, "w", encoding="utf-8", newline="\n") as fh:
            json.dump(table, fh, indent=1, ensure_ascii=False)
            fh.write("\n")

    # ── the judge's own reader, on every row ─────────────────────────────
    J = load_judge()
    for r in body:
        a = J.shape_ruler(r["slot"], r["id"], TABLE)          # canvas, ink, pivot and band guards
        got = J.infer_shape(os.path.join("out", "stage7-bodies", r["id"], "cut",
                                         f"c_s0.85_e0.80_seed1000_ip0.30_x_v3.png"), TABLE)
        if got != r["id"]:
            die(f"a candidate path for {r['id']} resolves to {got!r}; the judge would measure it "
                f"against the wrong ruler or refuse it as ambiguous")
        print(f"  {r['id']:<15} {a.shape[1]}x{a.shape[0]}  verified by the judge's own reader"
              + ("   (the live outline)" if r["live"] else ""))
    print(f"{'checked' if args.check else 'installed'} {len(body)} body shapes -> "
          f"{os.path.relpath(TABLE, ROOT)}")
    print(f"  nothing was written under public/bots-art/parts")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
