"""BATTLE BOTS / stable-diffusion: THE SHAPE TABLE'S SLOTS IN THE MATRIX.

    python scripts/sd/bots-sd-shape-slots.py --check   # is the matrix current? (exit 1 if not)
    python scripts/sd/bots-sd-shape-slots.py --write   # bring it up to date

WHY THIS EXISTS (lane R, 2026-09-05). scripts/sd/bots-sd-render.py refuses a
job whose prompt it cannot rebuild:

    want = P.build_prompt(m, j["slot"], tier, plate, variant)
    if j["prompt"] != want: "prompt differs from what the matrix assembles today"

That check is the runner's whole reason to be trusted with money, so it does
not bend. But the head shape jobs were emitted with slot "head" carrying a
SPLICED prompt (the dome crown swapped for a bear crown, the grille swapped
for a smile), so the runner rebuilt the dome prompt, saw a difference and
refused all 384. Measured, not guessed: `--dry-run` said
"384 of 384 jobs are not safe to render".

THE FIX IS THE ONE LANE B ALREADY PROVED ON THE LEGS. A leg shape is not a
spliced `leg`; it is its own slot in the matrix (`leg-wheels`), so the runner
rebuilds its prompt from the matrix like any other slot and the 96 leg jobs
pass untouched. This file does the same for the eighteen head looks, with one
difference that matters: the leg slots were authored by hand, and these are
GENERATED from scripts/bots-shapes.json, so the shape table stays the single
author of what a shape says and the matrix cannot drift away from it.

WHAT A GENERATED SLOT IS. Exactly the head's own entry with the two documented
substitutions applied, and nothing else:

    subject   the head's, unchanged
    form      the head's, crownPhrase replaced by this shape's crown clause
    features  the head's, mouthPhrase replaced by this look's mouth clause
    forehead  the head's, unchanged (the blank forehead law)

and, so the slot behaves like a head everywhere else in the matrix:

    negative.slot[key]          a copy of the head's groups, so the negative
                                string is byte-identical to today's
    skeleton.subjectShort[key]  the head's, for the terse variant

A substring that is not found exactly once is a REFUSAL, never a fallback,
for the reason bots-sd-shape-jobs.py gives: a shape prompt that silently keeps
the dome is the defect the shape table exists to end.
"""
from __future__ import annotations

import argparse
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
sys.path.insert(0, HERE)

SHAPES_JSON = os.path.join(ROOT, "scripts", "bots-shapes.json")
MATRIX_JSON = os.path.join(HERE, "bots-sd-prompts.json")
V3_RULERS = os.path.join(ROOT, "public", "bots-art", "_raw", "parts", "placeholders-v3")

NOTE = ("GENERATED by scripts/sd/bots-sd-shape-slots.py from scripts/bots-shapes.json. "
        "Do not hand-edit: edit the shape table and re-run --write. This is the head's own "
        "entry with the crown clause and the mouth clause replaced, so the runner can rebuild "
        "this prompt from the matrix and check_job passes.")


def die(msg: str) -> None:
    raise SystemExit("bots-sd-shape-slots REFUSES: " + msg)


def load_matrix_raw() -> dict:
    with open(MATRIX_JSON, encoding="utf-8") as fh:
        return json.load(fh)


def looks() -> list[dict]:
    """Every look the v3 head bake actually drew. The manifest is the authority
    on what exists; the shape table is the authority on what it says."""
    mp = os.path.join(V3_RULERS, "manifest-head.json")
    if not os.path.exists(mp):
        die(f"no {mp}. Run `node scripts/bots-bake-parts.mjs --out v3 --only head` first.")
    with open(mp, encoding="utf-8") as fh:
        man = json.load(fh)
    return list(man["looks"])


def splice(head: dict, crown: str, mouth: str, look: dict) -> dict:
    """The head's entry with this look's two clauses in it. Both substrings
    must be found exactly once."""
    nform = head["form"].count(crown)
    if nform != 1:
        die(f"the matrix head `form` contains the crown phrase {nform} times, expected once "
            f"(crownPhrase {crown!r}). Fix one or the other: a shape prompt that silently keeps "
            f"the dome is the defect the shape table exists to end.")
    nfeat = head["features"].count(mouth)
    if nfeat != 1:
        die(f"the matrix head `features` contains the mouth phrase {nfeat} times, expected once "
            f"(mouthPhrase {mouth!r}).")
    out = {
        "_": NOTE,
        "subject": head["subject"],
        "form": head["form"].replace(crown, look["prompt"]),
        "features": head["features"].replace(mouth, look["mouthPrompt"]),
    }
    if head.get("forehead"):
        out["forehead"] = head["forehead"]
    return out


def desired(m: dict) -> tuple[dict, dict, dict]:
    """(subject rows, negative.slot rows, subjectShort rows) the shape table asks for."""
    with open(SHAPES_JSON, encoding="utf-8") as fh:
        table = json.load(fh)
    crown, mouth = table["crownPhrase"], table["mouthPhrase"]
    head = m["subject"]["head"]
    subj, neg, short = {}, {}, {}
    for lk in looks():
        k = lk["key"]
        if not k.startswith("head-"):
            die(f"look key {k!r} does not start with head-; the slot name would collide")
        subj[k] = splice(head, crown, mouth, lk)
        neg[k] = list(m["negative"]["slot"]["head"])
        short[k] = m["skeleton"]["subjectShort"]["head"]
    return subj, neg, short


def apply(m: dict, subj: dict, neg: dict, short: dict) -> dict:
    for k, v in subj.items():
        m["subject"][k] = v
    for k, v in neg.items():
        m["negative"]["slot"][k] = v
    for k, v in short.items():
        m["skeleton"]["subjectShort"][k] = v
    return m


def stale(m: dict, subj: dict, neg: dict, short: dict) -> list[str]:
    out = []
    for k, v in subj.items():
        if m["subject"].get(k) != v:
            out.append(f"subject.{k}")
    for k, v in neg.items():
        if m["negative"]["slot"].get(k) != v:
            out.append(f"negative.slot.{k}")
    for k, v in short.items():
        if m["skeleton"]["subjectShort"].get(k) != v:
            out.append(f"skeleton.subjectShort.{k}")
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="exit 1 if the matrix is not current")
    ap.add_argument("--write", action="store_true", help="bring the matrix up to date")
    args = ap.parse_args()
    if args.check == args.write:
        die("pass exactly one of --check or --write")

    m = load_matrix_raw()
    subj, neg, short = desired(m)
    bad = stale(m, subj, neg, short)

    if args.check:
        if bad:
            print(f"the matrix is NOT current: {len(bad)} rows differ")
            for b in bad[:12]:
                print("  " + b)
            return 1
        print(f"the matrix is current: {len(subj)} head look slots match the shape table")
        return 0

    if not bad:
        print(f"nothing to do: {len(subj)} head look slots already match the shape table")
        return 0
    # indent=1 plus a trailing newline is what this file already is on disk:
    # a load/dump round trip of the untouched matrix reproduces it byte for
    # byte (checked), so the only lines this ever changes are the rows above.
    m = apply(m, subj, neg, short)
    with open(MATRIX_JSON, "w", encoding="utf-8", newline="\n") as fh:
        json.dump(m, fh, indent=1, ensure_ascii=False)
        fh.write("\n")
    print(f"wrote {len(subj)} head look slots into {os.path.relpath(MATRIX_JSON, ROOT)} "
          f"({len(bad)} rows were stale)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
