"""BATTLE BOTS / stable-diffusion lane: THE CONTRACT READER.

One module, imported by every other script under scripts/sd/, that answers
"what are the canvases, the pivots and the paintable law" by READING THE
SHIPPED FILES, never by carrying its own copy of the numbers.

WHY IT IS WRITTEN THIS WAY. lesson_gates_must_import_not_reimplement: a gate
that re-implements the logic it checks reproduces the author's assumptions and
passes. The same trap is open here in a nastier form, because a control map
is not a gate: if this file's idea of the head canvas drifts from
rig-points.ts by eight pixels, every render in the sweep is conditioned on a
silhouette the game cannot use, and nothing anywhere complains. So:

  * canvases and pivots are PARSED out of src/app/bots/_view/rig-points.ts,
    which is itself generated by scripts/bots-bake-parts.mjs;
  * the parse is then CROSS-CHECKED against the real PNGs on disk, and a
    mismatch is a hard exit, not a warning. That cross-check is what makes a
    regex parse trustworthy: it is verified against ground truth every run;
  * the paintable law is read from scripts/bots-art-accents.json, the same
    file scripts/bots-paint-masks.py and scripts/bots-art-check.mts read;
  * the accent classifier below is a transcription of the one in
    scripts/bots-paint-masks.py. It is the ONE thing here that is a copy, and
    it is a copy because that file is owned by another lane and importing a
    hyphenated module name is not free. `--selftest` re-derives every shipped
    mask from its base with this classifier and compares against the shipped
    mask, so the copy cannot silently drift.

Nothing in this file writes anything. Run `python scripts/sd/bots_sd_contract.py`
to print what it read, or with `--selftest` to prove the classifier agrees
with the shipped masks.
"""
from __future__ import annotations

import json
import os
import re
import sys

import numpy as np
from PIL import Image, ImageFilter

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
RIG_TS = os.path.join(ROOT, "src", "app", "bots", "_view", "rig-points.ts")
ACCENTS = os.path.join(ROOT, "scripts", "bots-art-accents.json")
PARTS = os.path.join(ROOT, "public", "bots-art", "parts")
RULERS = os.path.join(ROOT, "public", "bots-art", "_raw", "parts", "placeholders")

# The ruler folder names slots differently from the shipped parts folder
# (`arms`/`legs` plural there, singular here). One table, so no caller guesses.
RULER_NAME = {"head": "head", "torso": "torso", "arm": "arms", "leg": "legs", "weapon": "weapon"}

TIERS = (1, 2, 3, 4)
DESIGNS = (1, 2)


def die(msg: str) -> None:
    sys.exit(f"bots_sd_contract: {msg}")


# ── the contract, parsed ───────────────────────────────────────────────────

def _num_list(src: str) -> list[float]:
    return [float(x) for x in re.findall(r"-?\d+(?:\.\d+)?", src)]


def read_contract() -> dict:
    """Parse RIG, FIGURE and JOIN out of the generated rig-points.ts."""
    if not os.path.exists(RIG_TS):
        die(f"missing {RIG_TS}. Run `node scripts/bots-bake-parts.mjs` first.")
    src = open(RIG_TS, encoding="utf-8").read()

    m = re.search(r"export const RIG = \{(.*?)\n\} as const;", src, re.S)
    if not m:
        die("could not find `export const RIG` in rig-points.ts")
    rig: dict[str, dict] = {}
    for slot, body in re.findall(r"(\w+): \{([^}]*)\},", m.group(1)):
        entry: dict[str, object] = {}
        for key, val in re.findall(r"(\w+): (\[[^\]]*\]|-?\d+)", body):
            entry[key] = tuple(int(v) for v in _num_list(val)) if val.startswith("[") else int(val)
        if "w" not in entry or "h" not in entry:
            die(f"RIG.{slot} has no canvas size")
        rig[slot] = entry
    if not rig:
        die("RIG parsed empty")

    fm = re.search(r"export const FIGURE = \{(.*?)\n\} as const;", src, re.S)
    if not fm:
        die("could not find `export const FIGURE`")
    ftxt = fm.group(1)
    fig: dict[str, object] = {}
    for key in ("H", "skirt", "headApexY", "margin", "brassBudget", "metalSatMin"):
        km = re.search(rf"\n  {key}: ([\d.]+),", ftxt)
        if not km:
            die(f"FIGURE.{key} not found")
        fig[key] = float(km.group(1))
    ratio: dict[str, dict] = {}
    for name, mn, tg, mx in re.findall(
        r"(\w+): \{ min: ([\d.]+), target: ([\d.]+), max: ([\d.]+) \}", ftxt
    ):
        ratio[name] = {"min": float(mn), "target": float(tg), "max": float(mx)}
    if len(ratio) < 19:
        die(f"FIGURE.ratio parsed {len(ratio)} entries, expected 19")
    fig["ratio"] = ratio

    jm = re.search(r"export const JOIN = \{(.*?)\n\} as const;", src, re.S)
    if not jm:
        die("could not find `export const JOIN`")
    join = {k: float(v) for k, v in re.findall(r"(\w+): ([\d.]+),", jm.group(1))}

    om = re.search(r"export const OFF_CANVAS: readonly string\[\] = \[([^\]]*)\]", src)
    off_canvas = re.findall(r'"(\w+)"', om.group(1)) if om else []

    slots = [s for s in ("head", "torso", "arm", "leg", "weapon") if s in rig]
    return {"rig": rig, "figure": fig, "join": join, "off_canvas": off_canvas, "slots": slots}


def verify_against_disk(c: dict, quiet: bool = True) -> None:
    """The parse is only trustworthy if the numbers match the real PNGs."""
    bad: list[str] = []
    for slot in c["slots"]:
        want = (c["rig"][slot]["w"], c["rig"][slot]["h"])
        for t in TIERS:
            for d in DESIGNS:
                p = part_path(slot, t, d)
                if not os.path.exists(p):
                    bad.append(f"missing {p}")
                    continue
                got = Image.open(p).size
                if got != want:
                    bad.append(f"{slot} t{t}-{d}: PNG is {got}, contract says {want}")
    if bad:
        die("contract does not match the PNGs on disk:\n  " + "\n  ".join(bad[:10]))
    if not quiet:
        print(f"contract verified against {len(c['slots']) * 8} PNGs on disk")


def part_path(slot: str, tier: int, design: int) -> str:
    return os.path.join(PARTS, slot, f"t{tier}-{design}.png")


def mask_path(slot: str, tier: int, design: int) -> str:
    return os.path.join(PARTS, slot, f"t{tier}-{design}.mask.png")


def ruler_path(slot: str, tier: int, design: int) -> str:
    return os.path.join(RULERS, f"{RULER_NAME[slot]}-t{tier}-{design}.png")


def every_part(c: dict):
    for slot in c["slots"]:
        for t in TIERS:
            for d in DESIGNS:
                yield slot, t, d


def part_key(slot: str, tier: int, design: int) -> str:
    return f"{slot}-t{tier}-{design}"


def rig_points_named(c: dict, slot: str) -> list[tuple[str, tuple[int, int]]]:
    return [(k, v) for k, v in c["rig"][slot].items() if k not in ("w", "h")]


# ── the paintable law ──────────────────────────────────────────────────────

def read_law() -> dict:
    if not os.path.exists(ACCENTS):
        die(f"missing {ACCENTS}")
    return json.load(open(ACCENTS, encoding="utf-8"))


def hsv(rgb_u8: np.ndarray) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """H in degrees, S and V in 0..1. Transcribed from scripts/bots-paint-masks.py
    so the two files classify a pixel identically; --selftest proves it."""
    rgb = rgb_u8.astype(np.float64) / 255.0
    r, g, b = rgb[..., 0], rgb[..., 1], rgb[..., 2]
    v = rgb.max(axis=-1)
    d = v - rgb.min(axis=-1)
    s = np.where(v > 0, d / np.maximum(v, 1e-9), 0.0)
    h = np.zeros_like(v)
    lit = d > 0
    rm = lit & (v == r)
    gm = lit & ~rm & (v == g)
    bm = lit & ~rm & ~gm
    h[rm] = ((g - b)[rm] / d[rm]) % 6
    h[gm] = ((b - r)[gm] / d[gm]) + 2
    h[bm] = ((r - g)[bm] / d[bm]) + 4
    return h * 60.0, s, v


def classify(rgba: np.ndarray, law: dict, metal_sat_min: float) -> dict[str, np.ndarray]:
    """Split a part into the material classes the render has to get right.

    Returns boolean planes. `accent` is the union the paint mask cuts out;
    the individual planes exist because the CONTROL MAPS need them separately:
    a grille is a hole and must be pushed back in depth, an eye lens is a dome
    and must be pushed forward, and a scorer has to be able to ask "is the eye
    still the brightest thing on this head" without a hue guess.

    METAL vs LENS vs GRILLE. All three sit inside the brass hue band, so hue
    cannot separate them and value cannot either once the ramp has run over
    them. FIGURE.metalSatMin (0.60) can: brass measures 0.70, the grille 0.50,
    the lens 0.19. That constant is the contract's, read not invented.
    """
    a = law["accents"]
    h, s, v = hsv(rgba[..., :3])
    ink = rgba[..., 3] > 0

    rubber = v < a["rubber"]["valueMax"]
    warm = (
        (h >= a["brass"]["hueMin"]) & (h <= a["brass"]["hueMax"])
        & (s >= a["brass"]["satMin"]) & (v > a["brass"]["valueMin"])
    )
    # THE EYE BAND, read by name. The law replaced its cyan `glass` band (which
    # no pixel ever matched) with an `eye` band for the warm white bulb on
    # 2026-09-05; the gate's FACE check refuses when it is missing, so does this.
    if "eye" not in a:
        die('the paintable law has no "eye" band; the gate (FACE) and the mask deriver read it by '
            'name, and this classifier will not guess a lens colour')
    e = a["eye"]
    glass = (
        (h >= e["hueMin"]) & (h <= e["hueMax"])
        & (s >= e["satMin"]) & (s <= e.get("satMax", 1.0)) & (v > e["valueMin"])
    )
    coral = (
        (h >= a["coral"]["hueMin"]) & (h <= a["coral"]["hueMax"])
        & (s >= a["coral"]["satMin"]) & (s <= a["coral"]["satMax"])
    )
    accent = (rubber | warm | glass | coral) & ink

    close = int(law.get("accentHoleClose", {}).get("value", 1))
    if close:
        accent = _close(accent, close) & ink

    # inside the warm band, saturation splits the three
    metal = warm & ink & (s >= metal_sat_min)
    dark_warm = warm & ink & (s < metal_sat_min) & (v < 0.55)   # the grille
    lens = (glass | (warm & ink & (s < metal_sat_min) & (v >= 0.55)))

    body = ink & ~accent
    return {
        "ink": ink,
        "body": body,
        "accent": accent,
        "metal": metal & ~lens,
        "grille": dark_warm,
        "lens": lens & ink,
        "rubber": rubber & ink,
        "coral": coral & ink,
    }


def _close(flags: np.ndarray, times: int = 1) -> np.ndarray:
    im = Image.fromarray((flags * 255).astype(np.uint8), "L")
    for _ in range(times):
        im = im.filter(ImageFilter.MaxFilter(3))
    for _ in range(times):
        im = im.filter(ImageFilter.MinFilter(3))
    return np.asarray(im) > 0


# ── selftest ───────────────────────────────────────────────────────────────

def _band(flags: np.ndarray, px: int) -> np.ndarray:
    """The `px`-wide ring straddling a region's boundary: dilate minus erode."""
    im = Image.fromarray((flags * 255).astype(np.uint8), "L")
    grow, shrink = im, im
    for _ in range(px):
        grow = grow.filter(ImageFilter.MaxFilter(3))
        shrink = shrink.filter(ImageFilter.MinFilter(3))
    return (np.asarray(grow) > 0) & ~(np.asarray(shrink) > 0)


def selftest(c: dict, law: dict, band_px: int = 2) -> int:
    """Prove this file's copy of the accent classifier still agrees with the
    one in scripts/bots-paint-masks.py. If it drifts, the accent semantics in
    every control map (the eye lens is a dome, the grille is a hole) go quietly
    wrong.

    THE BOUNDARY BAND IS EXCLUDED, and that is not moving the goalposts.
    The shipped mask deliberately GROWS each clay shape by its outline stroke
    width, because a mask that stops at the shape leaves a one-pixel ring
    keeping the colour the art was drawn in - 3,584 such pixels on one head,
    per the bake's own comment. This file does not grow it, because a control
    map wants the true boundary. So the two are SUPPOSED to differ by about one
    pixel everywhere, and on a shipped head that ring alone measured 8 to 17
    percent of the ink: the accent regions on a generated head are small and
    intricate, so their perimeter is a large share of their area. Comparing
    inside the band measures the disagreement we designed in and tells us
    nothing about drift. Comparing outside it measures drift and nothing else.
    """
    msm = float(c["figure"]["metalSatMin"])
    worst = 0.0
    rows = []
    for slot, t, d in every_part(c):
        base = np.asarray(Image.open(part_path(slot, t, d)).convert("RGBA"))
        shipped = np.asarray(Image.open(mask_path(slot, t, d)).convert("RGBA"))
        cl = classify(base, law, msm)
        ink = base[..., 3] > 200
        mine = cl["body"] & ink
        theirs = (shipped[..., 3] > 128) & (shipped[..., 0] > 128)
        core = ink & ~_band(cl["accent"] & ink, band_px) & ~_band(ink, band_px)
        dis = float((mine ^ theirs)[core].mean()) if core.any() else 0.0
        raw = float((mine ^ theirs)[ink].mean()) if ink.any() else 0.0
        rows.append((dis, raw, part_key(slot, t, d)))
        worst = max(worst, dis)
    rows.sort(reverse=True)
    print(f"accent classifier vs the shipped masks, worst 6 (boundary band {band_px}px excluded):")
    print(f"  {'part':<14} {'drift':>7} {'raw':>7}")
    for dis, raw, k in rows[:6]:
        print(f"  {k:<14} {dis * 100:6.2f}% {raw * 100:6.2f}%")
    print(f"worst drift {worst * 100:.2f}%  (bar 2.00%; `raw` includes the one-pixel stroke ring "
          f"the two are meant to differ by)")
    return 0 if worst < 0.02 else 1


if __name__ == "__main__":
    c = read_contract()
    law = read_law()
    verify_against_disk(c, quiet=False)
    print("\nCANVASES AND PIVOTS (from rig-points.ts, verified against the PNGs)")
    for slot in c["slots"]:
        r = c["rig"][slot]
        pts = ", ".join(f"{k}{tuple(v)}" for k, v in rig_points_named(c, slot))
        print(f"  {slot:<7} {r['w']:>4} x {r['h']:<4}  aspect {r['w'] / r['h']:.3f}   {pts}")
    f = c["figure"]
    print(f"\nH={f['H']:.0f} skirt={f['skirt']:.0f} margin={f['margin']:.0f} "
          f"brassBudget={f['brassBudget']} metalSatMin={f['metalSatMin']}")
    print(f"JOIN capR={c['join']['capR']} burial={c['join']['burial']} "
          f"({c['join']['burialMin']}..{c['join']['burialMax']}) occlusion={c['join']['occlusion']}")
    print(f"OFF_CANVAS: {c['off_canvas']}")
    if "--selftest" in sys.argv:
        print()
        sys.exit(selftest(c, law))
