"""BATTLE BOTS / stable-diffusion: THE BODY SHAPES' SLOTS IN THE MATRIX.

    python scripts/sd/bots-sd-body-slots.py --check   # is the matrix current? (exit 1 if not)
    python scripts/sd/bots-sd-body-slots.py --write   # bring it up to date

WHY THIS EXISTS (lane T, 2026-09-05). scripts/sd/bots-sd-render.py refuses a
job whose prompt it cannot rebuild:

    want = P.build_prompt(m, j["slot"], tier, plate, variant)
    if j["prompt"] != want: "prompt differs from what the matrix assembles today"

That check is the runner's whole reason to be trusted with money, so it does
not bend. A body shape emitted as slot `torso` carrying a SPLICED prompt would
be rebuilt as the barrel, and every job would be refused: lane R measured
exactly that on the head looks, 384 of 384.

So a body shape is its own slot in the matrix (`torso-teapot`, `arm-pincers`),
exactly as lane B's leg shapes are (`leg-wheels`) and lane A's head looks are
(`head-bear-smile`). The difference from lane B, and it is the one worth
keeping, is that these are GENERATED from scripts/bots-shapes.json rather than
authored by hand, so the shape table stays the single author of what a shape
says and the matrix cannot drift away from it. This file is
scripts/sd/bots-sd-shape-slots.py's own method applied to the body's one
shape-dependent clause.

WHAT A GENERATED SLOT IS. Exactly the slot's own entry with ONE documented
substitution applied, and nothing else:

    subject   the slot's, unchanged
    form      the slot's, formPhrase replaced by this shape's form clause
    features  the slot's, unchanged (the key on a torso, the smooth surface on
              an arm: both are true of every shape in the table)

and, so the shape behaves like its slot everywhere else in the matrix:

    negative.slot[key]          a copy of the slot's groups, so the negative
                                string is byte-identical to today's
    skeleton.subjectShort[key]  the slot's, for the terse variant

A substring that is not found exactly once is a REFUSAL, never a fallback: a
teapot that silently keeps the barrel's prompt is the exact defect the shape
table exists to end, and it is the one failure that would look like success
right up until the contact sheet.

WHAT IT DOES NOT TOUCH. Every row it did not generate, head and leg lanes'
included: it loads the matrix, sets its own keys and writes the whole file
back at indent=1, which a load and dump round trip of the untouched matrix
reproduces byte for byte (checked by --check on a clean tree).
"""
from __future__ import annotations

import argparse
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
sys.path.insert(0, HERE)

SHAPES_JSON = os.path.join(ROOT, "scripts", "bots-shapes.json")
MATRIX_JSON = os.path.join(HERE, "bots-sd-prompts.json")
V3_RULERS = os.path.join(ROOT, "public", "bots-art", "_raw", "parts", "placeholders-v3")
MANIFESTS = {"torso": "manifest-torso.json", "arm": "manifest-arm.json"}

NOTE = ("GENERATED by scripts/sd/bots-sd-body-slots.py from scripts/bots-shapes.json (bodies). "
        "Do not hand-edit: edit the shape table and re-run --write. This is the slot's own entry "
        "with the form clause replaced by this shape's, so the runner can rebuild this prompt from "
        "the matrix and check_job passes.")


def die(msg: str) -> None:
    raise SystemExit("bots-sd-body-slots REFUSES: " + msg)


def shapes_on_disk(slot: str) -> list[str]:
    """The shapes the v3 bake actually drew. The manifest is the authority on
    what exists on disk; the shape table is the authority on what each one
    says. A row with no ruler is a hard stop, because a matrix slot with no
    control map is a job that dies after it has been paid for."""
    p = os.path.join(V3_RULERS, MANIFESTS[slot])
    if not os.path.exists(p):
        die(f"no {p}. Run `node scripts/bots-bake-parts.mjs --out v3 --only torso,arm` first.")
    man = json.load(open(p, encoding="utf-8"))
    stem = {"torso": "torso", "arm": "arms"}[slot]
    out = []
    for row in man["shapeRows"]:
        png = os.path.join(V3_RULERS, "target", f"{stem}-{row['shape']}.png")
        if not os.path.exists(png):
            die(f"the {slot} manifest lists {row['shape']} but {png} is not on disk")
        out.append(row["shape"])
    return out


def splice(base: dict, phrase: str, form: str, slot: str, shape: str) -> dict:
    n = base["form"].count(phrase)
    if n != 1:
        die(f"the matrix {slot} `form` contains the form phrase {n} times, expected once "
            f"(bodies.{slot}.formPhrase is {phrase!r}). Fix one or the other: a shape prompt that "
            f"silently keeps the barrel is the defect the shape table exists to end.")
    out = {"_": NOTE, "subject": base["subject"], "form": base["form"].replace(phrase, form)}
    for k in ("features", "forehead"):
        if base.get(k):
            out[k] = base[k]
    return out


def desired(m: dict) -> tuple[dict, dict, dict]:
    """(subject rows, negative.slot rows, subjectShort rows) the shape table asks for."""
    table = json.load(open(SHAPES_JSON, encoding="utf-8"))
    if not table.get("bodies"):
        die("scripts/bots-shapes.json carries no `bodies` section")
    subj, neg, short = {}, {}, {}
    for slot in ("torso", "arm"):
        sect = table["bodies"][slot]
        phrase = sect["formPhrase"]
        rows = {r["shape"]: r for r in sect["shapes"]}
        drawn = shapes_on_disk(slot)
        missing = [s for s in drawn if s not in rows]
        if missing:
            die(f"the {slot} bake drew {missing} but the shape table has no row for them")
        for shape in drawn:
            key = f"{slot}-{shape}"
            if key in ("torso", "arm"):
                die(f"slot name {key!r} would collide with the base slot")
            subj[key] = splice(m["subject"][slot], phrase, rows[shape]["prompt"], slot, shape)
            neg[key] = list(m["negative"]["slot"][slot])
            short[key] = m["skeleton"]["subjectShort"][slot]
    return subj, neg, short


def apply(m: dict, subj: dict, neg: dict, short: dict) -> dict:
    for k, v in subj.items():
        m["subject"][k] = v
    for k, v in neg.items():
        m["negative"]["slot"][k] = v
    for k, v in short.items():
        m["skeleton"]["subjectShort"][k] = v
    return m


def stale(m: dict, subj: dict, neg: dict, short: dict) -> list[str]:
    out = []
    for k, v in subj.items():
        if m["subject"].get(k) != v:
            out.append(f"subject.{k}")
    for k, v in neg.items():
        if m["negative"]["slot"].get(k) != v:
            out.append(f"negative.slot.{k}")
    for k, v in short.items():
        if m["skeleton"]["subjectShort"].get(k) != v:
            out.append(f"skeleton.subjectShort.{k}")
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="exit 1 if the matrix is not current")
    ap.add_argument("--write", action="store_true", help="bring the matrix up to date")
    args = ap.parse_args()
    if args.check == args.write:
        die("pass exactly one of --check or --write")

    m = json.load(open(MATRIX_JSON, encoding="utf-8"))
    subj, neg, short = desired(m)
    bad = stale(m, subj, neg, short)

    if args.check:
        if bad:
            print(f"the matrix is NOT current: {len(bad)} rows differ")
            for b in bad[:12]:
                print("  " + b)
            return 1
        print(f"the matrix is current: {len(subj)} body shape slots match the shape table")
        return 0

    if not bad:
        print(f"nothing to do: {len(subj)} body shape slots already match the shape table")
        return 0
    m = apply(m, subj, neg, short)
    with open(MATRIX_JSON, "w", encoding="utf-8", newline="\n") as fh:
        json.dump(m, fh, indent=1, ensure_ascii=False)
        fh.write("\n")
    print(f"wrote {len(subj)} body shape slots into {os.path.relpath(MATRIX_JSON, ROOT)} "
          f"({len(bad)} rows were stale)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
