"""BATTLE BOTS: INSTALL THE SHAPE TABLE WHERE THE JUDGE READS IT.

    python scripts/sd/bots-sd-shape-install.py           # install and verify
    python scripts/sd/bots-sd-shape-install.py --check   # verify what is there, write nothing

scripts/sd/rank-part.py judges a shape candidate against THE DRAWING THAT IS
THAT SHAPE rather than against the dome, and it finds that drawing through a
shape table it looks for at .bots-preview/sd-shapes/shape-table.json. This
file is what puts one there:

  * it copies the sixteen head rulers `node scripts/bots-bake-parts.mjs
    --out v3 --only head` drew into .bots-preview/sd-shapes/parts/head/, the
    preview install target, because nothing about the shape lane ships and
    public/bots-art/parts is the live catalogue;
  * it writes the table beside them, in the judge's own schema: one entry per
    look with its id, its slot and its ruler, plus the shape, the mouth and
    the clauses, which the judge ignores and a person reads;
  * and it then VERIFIES every entry BY IMPORTING THE JUDGE'S OWN READER,
    never by re-implementing it. rank-part.shape_ruler runs the canvas check,
    the ink check, the pivot check and the proportion-band check on each PNG,
    so a ruler that would mis-measure every candidate judged against it is
    refused here, at install time, and not discovered in a report.

THE ID IS THE WHOLE LOOK KEY (head-bear-smile), not the shape word. The judge
matches an id as a whole path segment or a whole filename token, and the
renderer writes every candidate under <out>/<part>/cut/, where <part> is that
same key: one whole segment, one shape, no guess. A bare `bear` would also
match the token `bear` inside `head-bear-o`, which is two rulers for one
candidate and an ambiguity refusal.
"""
from __future__ import annotations

import argparse
import importlib.util
import json
import os
import shutil
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
sys.path.insert(0, HERE)

V3 = os.path.join(ROOT, "public", "bots-art", "_raw", "parts", "placeholders-v3")
PREVIEW = os.path.join(ROOT, ".bots-preview", "sd-shapes")
PARTS = os.path.join(PREVIEW, "parts")
TABLE = os.path.join(PREVIEW, "shape-table.json")
MANIFESTS = ("manifest-head.json", "manifest-leg.json")


def die(msg: str) -> None:
    raise SystemExit("bots-sd-shape-install REFUSES: " + msg)


def load_judge():
    """rank-part.py by path: its name is hyphenated, and importing it is the
    whole point (a check that re-implements the judge's reader reproduces its
    author's assumptions and passes)."""
    p = os.path.join(HERE, "rank-part.py")
    spec = importlib.util.spec_from_file_location("rank_part", p)
    mod = importlib.util.module_from_spec(spec)
    sys.modules["rank_part"] = mod
    spec.loader.exec_module(mod)
    return mod


def rows() -> list[dict]:
    """Every look the v3 bake declares, head lane and leg lane alike, in table
    order. Read off the manifests on disk: a look with no ruler cannot exist."""
    out = []
    for name in MANIFESTS:
        p = os.path.join(V3, name)
        if not os.path.exists(p):
            continue
        man = json.load(open(p, encoding="utf-8"))
        slot = man["slot"]
        if not man.get("looks"):
            # LOUD, NEVER SILENT: a lane whose manifest carries no `looks`
            # list cannot be installed here, and a shape table quietly missing
            # half the table is a judge quietly measuring against the dome.
            print(f"note: {name} declares no `looks` list, so its {slot} rulers are NOT in the shape "
                  f"table. Each entry needs a `key` naming its ruler PNG under target/.")
            continue
        for lk in man["looks"]:
            src = os.path.join(V3, "target", lk["key"] + ".png")
            if not os.path.exists(src):
                die(f"{name} lists {lk['key']} but {src} is not on disk. "
                    f"Run `node scripts/bots-bake-parts.mjs --out v3` first.")
            out.append({**lk, "slot": slot, "src": src})
    if not out:
        die(f"no v3 manifest under {V3}. Run `node scripts/bots-bake-parts.mjs --out v3` first.")
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="verify what is installed, write nothing")
    args = ap.parse_args()

    looks = rows()
    if not args.check:
        for lk in looks:
            dst_dir = os.path.join(PARTS, lk["slot"])
            os.makedirs(dst_dir, exist_ok=True)
            shutil.copy2(lk["src"], os.path.join(dst_dir, lk["key"] + ".png"))
        table = {
            "_": [
                "THE SHAPE TABLE, as scripts/sd/rank-part.py reads it. GENERATED by",
                "scripts/sd/bots-sd-shape-install.py from the v3 bake's own manifests; do not",
                "edit by hand. The authored table is scripts/bots-shapes.json and the drawing",
                "is bots-bake-parts.mjs --out v3.",
                "",
                "Every ruler here is on the contract canvas at the contract's pivots and is",
                "what a candidate of that look is measured against, so that a bear is not",
                "judged for failing to be a dome. No judge rule and no bar moves for any of",
                "them: they all keep two lamp eyes on the design-one eye row at the design-one",
                "radius band, a blank forehead, the crease lugs, the dome underside and their",
                "ink inside the full head width.",
                "",
                "Nothing here ships. public/bots-art/parts is the live catalogue and this tree",
                "is a preview.",
            ],
            "shapes": [
                {
                    "id": lk["key"],
                    "slot": lk["slot"],
                    "ruler": f"parts/{lk['slot']}/{lk['key']}.png",
                    "name": lk.get("name"),
                    "shape": lk.get("shape"),
                    "mouth": lk.get("mouth"),
                    "prompt": lk.get("prompt"),
                    "mouthPrompt": lk.get("mouthPrompt"),
                    "notes": lk.get("notes"),
                }
                for lk in looks
            ],
        }
        os.makedirs(PREVIEW, exist_ok=True)
        with open(TABLE, "w", encoding="utf-8", newline="\n") as fh:
            json.dump(table, fh, indent=1, ensure_ascii=False)
            fh.write("\n")

    # THE JUDGE'S OWN READER IS THE CHECK.
    judge = load_judge()
    t = judge.shape_table(TABLE)
    bad = []
    for lk in looks:
        try:
            judge.shape_ruler(lk["slot"], lk["key"], TABLE)
        except SystemExit as e:
            bad.append(f"{lk['key']}: {e}")
    # and the id must resolve to exactly one shape from a real candidate path
    for lk in looks:
        p = os.path.join("out", "stage6-heads", lk["key"], "cut", "seed1000.png")
        got = judge.infer_shape(p, TABLE)
        if got != lk["key"]:
            bad.append(f"{lk['key']}: a candidate under {p} infers shape {got!r}")
    if bad:
        die("the judge refused installed rulers:\n  " + "\n  ".join(bad))
    per_slot: dict = {}
    for lk in looks:
        per_slot[lk["slot"]] = per_slot.get(lk["slot"], 0) + 1
    print(f"shape table at {os.path.relpath(TABLE, ROOT)}: {len(t['byKey'])} looks "
          + ", ".join(f"{n} {s}" for s, n in sorted(per_slot.items())))
    print(f"every ruler passed rank-part's own verify_shape_ruler (canvas, ink, pivots, "
          f"proportion bands) and infers its own shape from a candidate path")
    return 0


if __name__ == "__main__":
    sys.exit(main())
