import * as T from 'three';
import {KITS} from './weapon-actions';
import type {Practice8,Side,Event8} from './v8-engine';
const V=(x=0,y=0,z=0)=>new T.Vector3(x,y,z);
export function combatEffects(scene:T.Scene){
 const groups=[new T.Group(),new T.Group()],owned:T.Material[]=[],geometries:T.BufferGeometry[]=[];
 const material=(color:string,opacity:number)=>{const m=new T.MeshBasicMaterial({color,transparent:true,opacity,depthWrite:false,side:T.DoubleSide});owned.push(m);return m};
 const shields=groups.map(group=>{scene.add(group);const patches:T.Mesh[]=[];for(let i=0;i<8;i++){const geometry=new T.SphereGeometry(2.15,8,8,i*Math.PI/4+.025,Math.PI/4-.05,.25,Math.PI-.50);geometries.push(geometry);const m=new T.Mesh(geometry,material('#efba55',.13));m.scale.set(1,.98,1);group.add(m);patches.push(m)}return patches});
 const fields=groups.map(()=>{const g=new T.Group();scene.add(g);for(let i=0;i<3;i++){const geometry=new T.RingGeometry(1.5+i*.30,1.53+i*.30,64);geometries.push(geometry);const m=new T.Mesh(geometry,material('#b992ff',.55));m.rotation.x=-Math.PI/2;m.position.y=.018+i*.005;g.add(m)}return g});
 const trails=groups.map(()=>{const geometry=new T.BufferGeometry();geometry.setAttribute('position',new T.Float32BufferAttribute(new Float32Array(32*3),3));geometries.push(geometry);const m=new T.LineBasicMaterial({color:'#55e5f8',transparent:true,opacity:.65});owned.push(m);const line=new T.Line(geometry,m);scene.add(line);return {line,points:[] as T.Vector3[],last:-1}});
 const feet=groups.map(()=>{const g=new T.Group();scene.add(g);for(let i=0;i<2;i++){const geometry=new T.TorusGeometry(.19,.022,6,18);geometries.push(geometry);g.add(new T.Mesh(geometry,material('#66efff',.9)))}return g});
 const dropped=new Set<number>();
 const debris:{group:T.Object3D;start:number;p:T.Vector3;q:T.Quaternion;velocity:T.Vector3;axis:T.Vector3;radius:number;settle:T.Quaternion}[]=[];
 function broken(engine:Practice8,event:Event8){if(event.target===undefined||!event.slot)return;const a=engine.actors[event.target],node=a.assembly.model.getObjectByName(({armL:'shoulderL',armR:'shoulderR',legL:'hipL',legR:'hipR',head:'head'} as Record<string,string>)[event.slot]??'');if(!['armL','armR','legL','legR','head'].includes(event.slot)||!node||!node.visible)return;const clone=node.clone(true);clone.position.copy(node.getWorldPosition(V()));clone.quaternion.copy(node.getWorldQuaternion(new T.Quaternion()));scene.add(clone);node.visible=false;
  const box=new T.Box3().setFromObject(clone),size=box.getSize(V()),local=new T.Box3(),inverse=clone.matrixWorld.clone().invert();clone.traverse(o=>{const mesh=o as T.Mesh;if(mesh.isMesh){mesh.geometry.computeBoundingBox();local.union(mesh.geometry.boundingBox!.clone().applyMatrix4(inverse.clone().multiply(mesh.matrixWorld)));}});const extent=local.getSize(V()),normal=extent.x<extent.y&&extent.x<extent.z?V(1,0,0):extent.y<extent.z?V(0,1,0):V(0,0,1),direction=V().fromArray(event.direction??[1,0,0]),settle=new T.Quaternion().setFromAxisAngle(V(0,1,0),Math.atan2(direction.x,direction.z)).multiply(new T.Quaternion().setFromUnitVectors(normal,V(0,1,0)));debris.push({group:clone,start:engine.tick,p:clone.position.clone(),q:clone.quaternion.clone(),velocity:V().fromArray(event.direction??[1,0,0]).multiplyScalar(2).add(V(0,2.1,0)),axis:V(.7,.4,.2).normalize(),radius:Math.min(size.x,size.y,size.z)*.4,settle});
 }
 function pose(engine:Practice8,reduced:boolean,aftermath=0){
  for(const who of [0,1] as Side[]){const a=engine.actors[who];
   if(KITS[a.build.weapon].hands===2&&(a.hp.armL<=0||a.hp.armR<=0)&&!dropped.has(who)){
    dropped.add(who);const weapon=a.assembly.model.getObjectByName('weaponR');
    if(weapon){if(a.hp.armR>0){const clone=weapon.clone(true);clone.position.copy(weapon.getWorldPosition(V()));clone.quaternion.copy(weapon.getWorldQuaternion(new T.Quaternion()));clone.scale.copy(weapon.getWorldScale(V()));scene.add(clone);clone.updateMatrixWorld(true);const size=new T.Box3().setFromObject(clone).getSize(V()),localBox=new T.Box3(),inverse=clone.matrixWorld.clone().invert();clone.traverse(o=>{const m=o as T.Mesh;if(m.isMesh){m.geometry.computeBoundingBox();localBox.union(m.geometry.boundingBox!.clone().applyMatrix4(inverse.clone().multiply(m.matrixWorld)))}});const extent=localBox.getSize(V()),up=extent.x<extent.y&&extent.x<extent.z?V(1,0,0):extent.y<extent.z?V(0,1,0):V(0,0,1);debris.push({group:clone,start:engine.tick,p:clone.position.clone(),q:clone.quaternion.clone(),velocity:V(Math.cos(a.yaw)*1.4,.5,-Math.sin(a.yaw)*1.4),axis:V(.6,.3,.7).normalize(),radius:Math.min(size.x,size.y,size.z)*.25,settle:new T.Quaternion().setFromAxisAngle(V(0,1,0),a.yaw).multiply(new T.Quaternion().setFromUnitVectors(up,V(0,1,0)))});}weapon.visible=false;}
   }
   const b=engine.actors[(1-who) as Side],active=a.specialUntil>engine.tick&&!engine.done;groups[who].visible=active&&a.build.style==='tank'&&a.shield>0;groups[who].position.copy(a.position).add(V(0,2,0));for(const m of shields[who])(m.material as T.MeshBasicMaterial).opacity=.035+.11*clamp(a.shield/(a.initial.torso*.35));
   fields[who].visible=active&&a.build.style==='ranged';fields[who].position.copy(b.position);fields[who].scale.setScalar(reduced?1:1+.05*Math.sin(engine.tick*.10));
   const speed=active&&a.build.style==='speed';feet[who].visible=speed;feet[who].children.forEach((child,i)=>{const ankle=a.assembly.model.getObjectByName('ankle'+(i?'R':'L'))!;child.position.copy(ankle.getWorldPosition(V())).add(V(0,.08,0));child.rotation.x=Math.PI/2});
   const trail=trails[who];trail.line.visible=speed&&!reduced;if(trail.last!==engine.tick){trail.last=engine.tick;if(speed){trail.points.push(a.position.clone().add(V(0,.17,0)));if(trail.points.length>32)trail.points.shift()}else trail.points=[];}const attribute=trail.line.geometry.attributes.position;for(let i=0;i<32;i++){const p=trail.points[i]??trail.points[trail.points.length-1]??a.position;attribute.setXYZ(i,p.x,p.y,p.z)}attribute.needsUpdate=true;trail.line.geometry.setDrawRange(0,trail.points.length);
   if(engine.done&&a.deadAt!==null){const t=clamp(aftermath/1.20),ease=t*t*(3-2*t);const impact=[...engine.events].reverse().find(e=>e.kind==='hit'&&e.target===who&&e.direction),direction=V().fromArray(impact?.direction??[who?1:-1,0,0]).setY(0).normalize(),axis=new T.Vector3().crossVectors(V(0,1,0),direction).normalize();a.root.quaternion.setFromAxisAngle(axis,1.50*ease).multiply(new T.Quaternion().setFromAxisAngle(V(0,1,0),a.yaw));a.root.position.copy(a.position);a.root.position.y=0;a.root.updateMatrixWorld(true);const box=new T.Box3();a.root.traverse(o=>{const mesh=o as T.Mesh;let shown=true;for(let n:T.Object3D|null=o;n;n=n.parent)shown&&=n.visible;if(mesh.isMesh&&shown){mesh.geometry.computeBoundingBox();box.union(mesh.geometry.boundingBox!.clone().applyMatrix4(mesh.matrixWorld));}});a.root.position.y-=box.min.y-.025;const center=box.getCenter(V()).setY(0),radius=Math.max(...[box.min.x,box.max.x].flatMap(x=>[box.min.z,box.max.z].map(z=>Math.hypot(x,z))));if(radius>7.8)a.root.position.addScaledVector(center.normalize(),-(radius-7.8));}
  }
  for(const part of debris){const t=Math.max(0,(engine.tick-part.start)/60+aftermath),floor=part.radius+.03,landing=(part.velocity.y+Math.sqrt(Math.max(0,part.velocity.y**2+19.6*(part.p.y-floor))))/9.8,settled=T.MathUtils.smoothstep(t-landing,0,.55);part.group.position.copy(part.p).addScaledVector(part.velocity,(1-Math.exp(-t*2.8))/2.8);let y=part.p.y+part.velocity.y*t-4.9*t*t;if(y<floor){const landing=(part.velocity.y+Math.sqrt(part.velocity.y**2+19.6*(part.p.y-floor)))/9.8,after=Math.max(0,t-landing);y=floor+Math.max(0,Math.sin(after*7))*Math.exp(-after*5)*.18}part.group.position.y=Math.max(floor,y);part.group.quaternion.copy(part.q).multiply(new T.Quaternion().setFromAxisAngle(part.axis,(1-Math.exp(-t*2))*4.2));part.group.quaternion.slerp(part.settle,settled);part.group.updateMatrixWorld(true);const bounds=new T.Box3().setFromObject(part.group);if(settled>=1||bounds.min.y<.025)part.group.position.y+=.025-bounds.min.y;const r=Math.hypot(part.group.position.x,part.group.position.z);if(r>7.7){part.group.position.x*=7.7/r;part.group.position.z*=7.7/r;}}
 }
 const clamp=(v:number)=>T.MathUtils.clamp(v,0,1);
 return {broken,pose,inspect:()=>debris.map(p=>({name:p.group.name,position:p.group.position.toArray()})),reset(){dropped.clear();for(const p of debris)p.group.removeFromParent();debris.length=0;for(const t of trails){t.points=[];t.last=-1}},dispose(){for(const p of debris)p.group.removeFromParent();for(const g of [...groups,...fields,...feet])g.removeFromParent();for(const t of trails)t.line.removeFromParent();geometries.forEach(g=>g.dispose());owned.forEach(m=>m.dispose())}};
}
