import * as T from 'three';
import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js';
import {GLTFLoader} from 'three/examples/jsm/loaders/GLTFLoader.js';
import {RoomEnvironment} from 'three/examples/jsm/environments/RoomEnvironment.js';
import {createExchange,EXCHANGE_DURATION,EXCHANGE_VERSION} from './exchange';

export async function startExchange(){
 const $=(id:string)=>document.getElementById(id)!;
 const canvas=$('model-canvas') as HTMLCanvasElement,play=$('play-strike') as HTMLButtonElement,slider=$('motion-time') as HTMLInputElement,phase=$('motion-phase') as HTMLOutputElement;
 document.querySelector('.model-title h1')!.textContent='Tank sparring';document.querySelector('.model-title p')!.textContent='Dodge. Counter. Recover.';
 document.querySelector('.eyebrow')!.textContent='WARDEN / CONTACT PROOF';
 $('joint-controls').hidden=true;$('motion-controls').hidden=false;
 document.querySelectorAll<HTMLButtonElement>('[data-mode]').forEach(b=>{b.setAttribute('aria-pressed','false');b.onclick=()=>location.href='/?revision=reference-hammer-2'+(b.dataset.mode==='inspect'?'&inspect=1':'')});
 $('exchange-mode').setAttribute('aria-pressed','true');$('reload-model').onclick=()=>location.reload();
 slider.setAttribute('aria-label','Sparring exchange position');canvas.setAttribute('aria-label','Tank sparring. Drag or use arrow keys to turn. Space plays or pauses.');
 const labels=['Warden','Rival'].map(name=>{const label=document.createElement('span');label.className='fighter-label';label.textContent=name;canvas.parentElement!.append(label);return label});
 const inspectDamage=document.createElement('button');inspectDamage.className='damage-inspect';inspectDamage.textContent='Inspect last hit';inspectDamage.disabled=true;canvas.parentElement!.append(inspectDamage);
 const renderer=new T.WebGLRenderer({canvas,antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.AgXToneMapping;renderer.toneMappingExposure=.90;
 renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.shadowMap.autoUpdate=false;
 const scene=new T.Scene();scene.background=new T.Color('#242723');scene.fog=new T.Fog('#242723',28,60);
 const camera=new T.PerspectiveCamera(35,1,.05,100);camera.position.set(-14,8,14);
 const reduced=matchMedia('(prefers-reduced-motion: reduce)'),controls=new OrbitControls(camera,canvas);controls.enablePan=false;controls.enableDamping=!reduced.matches;controls.target.set(0,2,0);controls.minDistance=4;controls.maxDistance=45;controls.maxPolarAngle=Math.PI*.49;
 const env=new RoomEnvironment(),pmrem=new T.PMREMGenerator(renderer),environment=pmrem.fromScene(env,.045);scene.environment=environment.texture;env.dispose();pmrem.dispose();
 scene.add(new T.HemisphereLight('#e5e0d4','#24231e',.42));
 const key=new T.DirectionalLight('#ffe8c9',2);key.position.set(-4,9,6);key.castShadow=true;key.shadow.mapSize.set(1024,1024);Object.assign(key.shadow.camera,{left:-8,right:8,top:8,bottom:-8,near:.1,far:30});key.shadow.bias=-.00015;key.shadow.normalBias=.028;scene.add(key);
 const rim=new T.DirectionalLight('#d7e0e2',1.25);rim.position.set(5,6,-7);scene.add(rim);const fill=new T.DirectionalLight('#e9dfcc',.35);fill.position.set(5,3,7);scene.add(fill);
 const floor=new T.Mesh(new T.PlaneGeometry(160,160),new T.MeshStandardMaterial({color:'#282925',roughness:.9,metalness:.02}));floor.rotation.x=-Math.PI/2;floor.position.y=.024;floor.receiveShadow=true;scene.add(floor);
 const ring=new T.Mesh(new T.RingGeometry(6.8,6.82,96),new T.MeshBasicMaterial({color:'#747057',transparent:true,opacity:.24,depthWrite:false}));ring.rotation.x=-Math.PI/2;ring.position.y=.027;scene.add(ring);
 let ready=false,playing=false,alive=true,raf=0,last:number|null=null,time=0,draws=0,controller:ReturnType<typeof createExchange>|null=null,audio:AudioContext|null=null;
 let source:T.Group|null=null,support:T.Group|null=null,activeView='three-quarter';
 const request=()=>{if(alive&&!document.hidden&&!raf)raf=requestAnimationFrame(draw)};
 function sound(){if(!audio||audio.state!=='running')return;const now=audio.currentTime,osc=audio.createOscillator(),gain=audio.createGain();osc.frequency.setValueAtTime(100,now);osc.frequency.exponentialRampToValueAtTime(32,now+.25);gain.gain.setValueAtTime(.19,now);gain.gain.exponentialRampToValueAtTime(.0001,now+.35);osc.connect(gain).connect(audio.destination);osc.start();osc.stop(now+.36);osc.onended=()=>{osc.disconnect();gain.disconnect()}}
 function sample(t:number){time=T.MathUtils.clamp(t,0,EXCHANGE_DURATION);const state=controller?.pose(time);slider.value=String(time);phase.value=state?.phase??'Loading';inspectDamage.disabled=!controller?.contacts.some(h=>h.time<=time);renderer.shadowMap.needsUpdate=true;return state}
 function placeLabels(){controller?.actors.forEach((a,i)=>{const p=a.root.localToWorld(V(0,.1,0)).project(camera),label=labels[i];label.hidden=p.z>1||Math.abs(p.x)>.96||Math.abs(p.y)>.92;label.style.left=`${(p.x*.5+.5)*canvas.clientWidth}px`;label.style.top=`${(-p.y*.5+.5)*canvas.clientHeight+12}px`})}
 function draw(now:number){raf=0;if(!alive||document.hidden)return;if(playing){const before=time;sample(time+(last===null?0:Math.min(.05,(now-last)/1000)));last=now;if(controller?.contacts.some(h=>h.time>before&&h.time<=time))sound();if(time>=EXCHANGE_DURATION){playing=false;last=null;play.textContent='Replay exchange'}}controls.update();renderer.render(scene,camera);placeLabels();draws++;if(playing)request()}
 controls.addEventListener('change',request);
 const bounds=new T.Box3(V(-4,0,-5),V(4,5.3,5));
 function V(x=0,y=0,z=0){return new T.Vector3(x,y,z)}
 function view(name:string){activeView=name;const direction=(name==='side'?V(-1,.17,0):name==='front'?V(0,.2,1):name==='back'?V(0,.2,-1):V(-1,.40,.72)).normalize();const target=bounds.getCenter(V(0,0,0)),right=new T.Vector3().crossVectors(V(0,1,0),direction).normalize(),up=new T.Vector3().crossVectors(direction,right).normalize(),tan=Math.tan(T.MathUtils.degToRad(camera.fov/2));let distance=0;
  for(const x of [bounds.min.x,bounds.max.x])for(const y of [bounds.min.y,bounds.max.y])for(const z of [bounds.min.z,bounds.max.z]){const p=V(x,y,z).sub(target),depth=p.dot(direction);distance=Math.max(distance,depth+Math.abs(p.dot(right))/(tan*camera.aspect),depth+Math.abs(p.dot(up))/tan)}
  controls.target.copy(target);camera.position.copy(target).addScaledVector(direction,distance*1.08);camera.lookAt(target);controls.update();document.querySelectorAll<HTMLButtonElement>('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===name)));request();
 }
 function resize(){const box=canvas.parentElement!.getBoundingClientRect();renderer.setSize(box.width,box.height,false);camera.aspect=box.width/box.height;camera.updateProjectionMatrix();view(activeView)}
 const observer=new ResizeObserver(resize);observer.observe(canvas.parentElement!);
 inspectDamage.onclick=()=>{const hit=controller&&[...controller.contacts].reverse().find(h=>h.time<=time);if(!controller||!hit)return;playing=false;last=null;play.textContent='Continue exchange';const mesh=controller.actors[hit.defender].meshes[hit.mesh],point=mesh.localToWorld(V().fromArray(hit.localPoint)),normal=V().fromArray(hit.localNormal).applyMatrix3(new T.Matrix3().getNormalMatrix(mesh.matrixWorld)).normalize();controls.minDistance=1;controls.target.copy(point);camera.position.copy(point).addScaledVector(normal,2.2).add(V(0,.5,.15));camera.lookAt(point);controls.update();document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed','false'));phase.value='Armour dent · drag to inspect';request()};
 document.querySelectorAll<HTMLButtonElement>('[data-view]').forEach(b=>b.onclick=()=>view(b.dataset.view!));
 play.onclick=()=>{if(!ready)return;if(!audio)audio=new AudioContext();void audio.resume();if(controls.minDistance===1){controls.minDistance=4;view(activeView)}if(time>=EXCHANGE_DURATION)sample(0);playing=!playing;last=null;play.textContent=playing?'Pause exchange':'Continue exchange';request()};
 slider.oninput=()=>{playing=false;last=null;sample(Number(slider.value));play.textContent=time>=EXCHANGE_DURATION?'Replay exchange':'Continue exchange';request()};
 const hidden=()=>{if(document.hidden){cancelAnimationFrame(raf);raf=0;last=null}else request()};document.addEventListener('visibilitychange',hidden);
 const preference=()=>{controls.enableDamping=!reduced.matches;request()};reduced.addEventListener('change',preference);
 $('concept-toggle').onclick=()=>{$('concept-panel').hidden=!$('concept-panel').hidden;$('concept-toggle').setAttribute('aria-expanded',String(!$('concept-panel').hidden));if(!$('concept-panel').hidden)$('concept-close').focus()};$('concept-close').onclick=()=>{$('concept-panel').hidden=true;$('concept-toggle').setAttribute('aria-expanded','false');$('concept-toggle').focus()};
 const keyboard=(event:KeyboardEvent)=>{if(event.key==='Escape'&&!$('concept-panel').hidden){$('concept-close').click();return}if(event.target!==canvas)return;if(event.key===' '){event.preventDefault();play.click()}if(event.key==='Home'){event.preventDefault();view('three-quarter')}if(['ArrowLeft','ArrowRight'].includes(event.key)){event.preventDefault();const offset=camera.position.clone().sub(controls.target).applyAxisAngle(V(0,1,0),event.key==='ArrowLeft'?-.12:.12);camera.position.copy(controls.target).add(offset);controls.update();request()}};document.addEventListener('keydown',keyboard);
 function disposeObjects(roots:T.Object3D[]){const geometry=new Set<T.BufferGeometry>(),materials=new Set<T.Material>(),textures=new Set<T.Texture>();roots.forEach(root=>root.traverse(o=>{const m=o as T.Mesh;if(!m.isMesh)return;geometry.add(m.geometry);for(const mat of Array.isArray(m.material)?m.material:[m.material]){materials.add(mat);Object.values(mat).forEach(t=>{if(t?.isTexture)textures.add(t)})}}));geometry.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());textures.forEach(t=>t.dispose())}
 function dispose(){if(!alive)return;alive=false;cancelAnimationFrame(raf);observer.disconnect();document.removeEventListener('visibilitychange',hidden);document.removeEventListener('keydown',keyboard);reduced.removeEventListener('change',preference);controller?.dispose();controls.dispose();disposeObjects([source,support,floor,ring].filter(Boolean) as T.Object3D[]);environment.dispose();key.shadow.map?.dispose();renderer.dispose();void audio?.close()}
 window.addEventListener('pagehide',dispose,{once:true});
 (window as any).tankExchange={get ready(){return ready},seek:(t:number)=>{if(!Number.isFinite(t))return;playing=false;last=null;sample(t);play.textContent=time===0?'Watch exchange':time>=EXCHANGE_DURATION?'Replay exchange':'Continue exchange';request()},setView:view,inspect:()=>({version:EXCHANGE_VERSION,time,duration:EXCHANGE_DURATION,playing,contacts:controller?.contacts,attacks:controller?.attacks,state:controller?.pose(time),draws,memory:renderer.info.memory,render:renderer.info.render,canvasCount:document.querySelectorAll('canvas').length,damage:[...(controller?.damageMeshes.entries()??[])].map(([key,d])=>{let maxDepth=0,hash=2166136261;const data=d.geometry.attributes.position.array;for(let i=0;i<data.length;i++){maxDepth=Math.max(maxDepth,Math.abs(data[i]-d.base[i]));hash=Math.imul(hash^Math.round(data[i]*1e6),16777619)}return {key,vertices:d.geometry.attributes.position.count,maxDepth,hash:hash>>>0}})}),render:()=>{renderer.render(scene,camera)},dispose};
 try{
  const loader=new GLTFLoader();const [model,hand]=await Promise.all([loader.loadAsync('/assets/tank-t3-warden-hammer-motion-2.glb'),loader.loadAsync('/assets/warden-support-hand.glb')]);source=model.scene;support=hand.scene;if(!alive){disposeObjects([source,support]);return}
  const materials=new Map<string,T.Material>();source.traverse(o=>{const mesh=o as T.Mesh;if(!mesh.isMesh)return;mesh.castShadow=true;mesh.receiveShadow=true;for(const mat of Array.isArray(mesh.material)?mesh.material:[mesh.material]){materials.set(mat.name,mat);if((mat as T.MeshStandardMaterial).isMeshStandardMaterial)(mat as T.MeshStandardMaterial).envMapIntensity=.68}});
  support.traverse(o=>{const mesh=o as T.Mesh;if(!mesh.isMesh)return;mesh.castShadow=true;mesh.receiveShadow=true;mesh.material=(Array.isArray(mesh.material)?mesh.material:[mesh.material]).map(m=>{const replacement=materials.get(m.name);if(replacement){m.dispose();return replacement}return m})});
  $('load-status').textContent='Preparing the sparring exchange…';await new Promise(resolve=>requestAnimationFrame(resolve));controller=createExchange(source,support,scene);
  bounds.makeEmpty();for(let t=0;t<=EXCHANGE_DURATION;t+=.16){controller.pose(t);for(const a of controller.actors)bounds.expandByObject(a.model,true)}sample(0);ready=true;slider.disabled=false;slider.max=String(EXCHANGE_DURATION);slider.step='.01';play.disabled=false;play.textContent='Watch exchange';$('load-status').classList.add('empty');resize();request();
 }catch(error){$('load-status').textContent='The sparring preview could not load. Reload to try again.';console.error(error)}
}

