import * as T from 'three';
import {GLTFLoader} from 'three/examples/jsm/loaders/GLTFLoader.js';
import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js';
import {RoomEnvironment} from 'three/examples/jsm/environments/RoomEnvironment.js';
import {assemble,prepareLibrary,SLOTS,type Choices,type Entry} from './parts-assembly';
import {paintAssembly,parseAppearance,defaultAppearance} from './paint';
import {gameBridge} from './game-bridge';
import {createBanner,readBanner} from './banner';
import {presentationSettings} from './presentation-settings';

type DisplayRobot={id:string;name?:string;choices:Choices;appearance?:any;career?:any;repairUntil?:number};
type Instance={robot:DisplayRobot;signature:string;assembly:ReturnType<typeof assemble>;painter:ReturnType<typeof paintAssembly>;banner:ReturnType<typeof createBanner>;bannerId?:string;bannerRevision:number;marks:T.Mesh[];dead:boolean};

/** Instances own paint/banner/marks. Immutable mesh donors remain owned by this room. */
export async function startGameDisplay(){
 const connection=gameBridge();if(!connection)throw Error('Open this room from your garage.');const bridge=connection;
 document.querySelector('.studio')!.innerHTML='<canvas id="game-model" aria-label="Your robot. Drag to turn the view."></canvas><p id="game-model-status" role="status">Opening your workshop…</p>';
 document.body.classList.add('game-display');document.documentElement.style.colorScheme='light';
 const payload=await bridge.initial,canvas=document.getElementById('game-model') as HTMLCanvasElement,status=document.getElementById('game-model-status')!;
 let queuedPayload=payload;const stopQueue=bridge.subscribe(next=>{queuedPayload=next});
 const manifests=await Promise.all(['/assets/catalogue-2/manifest.json','/assets/weapon-kits-1/manifest.json'].map(async url=>{const r=await fetch(url);if(!r.ok)throw Error('Parts could not load');return r.json()}));
 const entries=new Map<string,Entry>(manifests.flatMap(m=>m.entries).map((e:Entry)=>[e.id,e]));
 const preferences=presentationSettings(),garage=payload.room==='garage';
 let currentPayload=payload,selectionTime=0,alive=true,frame=0,generation=0,loaded=false;
 const renderer=new T.WebGLRenderer({canvas,antialias:!preferences.low,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,preferences.low?1:1.5));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;renderer.shadowMap.enabled=!preferences.low;renderer.shadowMap.type=T.PCFSoftShadowMap;
 const scene=new T.Scene(),camera:T.PerspectiveCamera|T.OrthographicCamera=garage?new T.OrthographicCamera(-15,15,6,-6,.1,160):new T.PerspectiveCamera(35,1,.1,160),controls=new OrbitControls(camera,canvas);
 controls.enablePan=false;controls.enableDamping=true;controls.minPolarAngle=.7;controls.maxPolarAngle=1.48;controls.minDistance=6;controls.maxDistance=garage?36:18;controls.enabled=!garage;
 const studio=new RoomEnvironment(),pmrem=new T.PMREMGenerator(renderer),environment=pmrem.fromScene(studio,.08);scene.environment=environment.texture;scene.environmentIntensity=.45;pmrem.dispose();studio.dispose();renderer.setClearColor(0x000000,0);
 scene.add(new T.HemisphereLight(0xffead0,0x514332,1.2));
 const key=new T.DirectionalLight(0xffe2bb,3.5);key.position.set(5,14,10);key.castShadow=true;key.shadow.mapSize.set(1024,1024);Object.assign(key.shadow.camera,{left:-14,right:14,top:12,bottom:-8,near:1,far:45});key.shadow.normalBias=.025;scene.add(key);
 const rim=new T.DirectionalLight(0xa8c9da,1.1);rim.position.set(-6,8,-4);scene.add(rim);
 const library=new Map<string,T.Group>(),loading=new Map<string,Promise<void>>(),loader=new GLTFLoader(),instances:(Instance|undefined)[]=[],stands:T.Group[]=[],retries:(HTMLButtonElement|undefined)[]=[],placeholders:(T.Mesh|undefined)[]=[];
 const reduced=matchMedia('(prefers-reduced-motion: reduce)');
 const ground=new T.Mesh(new T.PlaneGeometry(80,80),new T.ShadowMaterial({opacity:.27}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);
 function disposeResources(root:T.Object3D){const geometry=new Set<T.BufferGeometry>(),materials=new Set<T.Material>(),textures=new Set<T.Texture>();root.traverse(o=>{const m=o as T.Mesh;if(m.isMesh){geometry.add(m.geometry);for(const mat of Array.isArray(m.material)?m.material:[m.material]){materials.add(mat);for(const v of Object.values(mat))if(v?.isTexture)textures.add(v)}}});geometry.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());textures.forEach(t=>t.dispose())}
 for(let i=0;i<(garage?5:1);i++){const group=new T.Group();scene.add(group);stands.push(group);const deck=new T.Mesh(new T.CylinderGeometry(2.5,2.65,.25,48),new T.MeshStandardMaterial({color:0x716351,metalness:.35,roughness:.6}));deck.position.y=.34;deck.castShadow=true;deck.receiveShadow=true;group.add(deck);for(const dx of [-1.6,1.6])for(const dz of [-1.2,1.2]){const wheel=new T.Mesh(new T.CylinderGeometry(.24,.24,.20,12),new T.MeshStandardMaterial({color:0x252a2b,roughness:.8}));wheel.rotation.z=Math.PI/2;wheel.position.set(dx,.18,dz);group.add(wheel)}}
 async function loadPart(id:string){if(library.has(id))return;const existing=loading.get(id);if(existing)return existing;
  const job=(async()=>{const model=(await loader.loadAsync(id==='__support'?'/assets/warden-support-hand.glb':entries.get(id)!.url)).scene;if(!alive){disposeResources(model);return;}if(id!=='__support'){model.userData.weaponKind=entries.get(id)!.weapon;model.userData.weaponHands=entries.get(id)!.hands;prepareLibrary(model);}library.set(id,model)})();loading.set(id,job);try{await job}finally{loading.delete(id);trimLibrary()}
 }
 function trimLibrary(){const robots:DisplayRobot[]=Array.isArray(currentPayload.robots)?currentPayload.robots.slice(0,stands.length):[];const retained=new Set(['__support',...robots.flatMap(r=>r.choices?Object.values(r.choices):[]),...instances.flatMap(i=>i?Object.values(i.robot.choices):[])]);for(const [id,model]of library){if(library.size<=36)break;if(!retained.has(id)&&!loading.has(id)){library.delete(id);disposeResources(model)}}}
 function destroyInstance(instance:Instance){if(instance.dead)return;instance.dead=true;instance.bannerRevision++;instance.assembly.model.removeFromParent();instance.painter.dispose();instance.banner.dispose();instance.marks.forEach(m=>{m.removeFromParent();disposeResources(m)});/* Shared donor geometry/materials are not disposed here. */}
 function appearance(instance:Instance,robot:DisplayRobot){instance.robot=robot;const value=parseAppearance(robot.appearance)??defaultAppearance(entries.get(robot.choices.torso)!.family);instance.painter.apply(value);instance.banner.visible(value.banner);if(instance.bannerId!==value.bannerId){instance.bannerId=value.bannerId;const revision=++instance.bannerRevision;void (value.bannerId?readBanner(value.bannerId):Promise.resolve(null)).then(blob=>{if(alive&&!instance.dead&&revision===instance.bannerRevision)return instance.banner.load(blob)}).catch(()=>{})}}
 function build(robot:DisplayRobot,signature:string,next:any):Instance{const a=assemble(robot.choices,library);a.model.traverse(o=>{const m=o as T.Mesh;if(m.isMesh){m.castShadow=true;m.receiveShadow=true}});a.articulate(0);
  const weapon=entries.get(robot.choices.weapon)!;
  if(weapon.hands===1&&!['sword_shield','spear_shield','rifle','precision_rifle','rotary','dual_blades'].includes(weapon.weapon??'')&&(robot.repairUntil??0)<Date.now()){const shoulder=a.model.getObjectByName('shoulderL'),elbow=a.model.getObjectByName('elbowL');if(shoulder&&robot.career?.pose==='fist'){shoulder.rotation.x=-1.25;if(elbow)elbow.rotation.x=-.8}if(shoulder&&robot.career?.pose==='salute'){shoulder.rotation.z=-.5;shoulder.rotation.x=-.9;if(elbow)elbow.rotation.x=-1.1}}
  if(Array.isArray(next.visibleSlots))for(const slot of SLOTS)if(!next.visibleSlots.includes(slot))for(const node of a.installed[slot]??[])node.visible=false;
  a.model.position.y+=.48;const instance:Instance={robot,signature,assembly:a,painter:paintAssembly(a.model,a.installed),banner:createBanner(),bannerId:undefined,bannerRevision:0,marks:[],dead:false};instance.banner.garage.position.set(-1.9,.5,-1.2);instance.banner.pose(0,true);appearance(instance,robot);
  if(robot.career?.showMarks)for(const mark of (robot.career.marks??[]).slice(-5)){const target=a.model.getObjectByName(mark.node);if(!target||!Array.isArray(mark.local)||mark.local.length!==3)continue;const chip=new T.Mesh(new T.CircleGeometry(.045,7),new T.MeshStandardMaterial({color:0x39332e,roughness:1,side:T.DoubleSide,polygonOffset:true,polygonOffsetFactor:-2}));chip.position.fromArray(mark.local);const normal=chip.position.clone().normalize();chip.position.addScaledVector(normal,.005);chip.quaternion.setFromUnitVectors(new T.Vector3(0,0,1),normal.lengthSq()?normal:new T.Vector3(0,0,1));target.add(chip);instance.marks.push(chip)}return instance;
 }
 function clearFailure(i:number){retries[i]?.remove();retries[i]=undefined;if(placeholders[i]){placeholders[i]!.removeFromParent();disposeResources(placeholders[i]!);placeholders[i]=undefined}}
 function failure(i:number,robot:DisplayRobot){clearFailure(i);if(!instances[i]){const mesh=new T.Mesh(new T.IcosahedronGeometry(.65,0),new T.MeshStandardMaterial({color:0x78878c,wireframe:true}));mesh.position.y=2;stands[i].add(mesh);placeholders[i]=mesh}const retry=document.createElement('button');retry.textContent=`Retry ${robot.name||'robot'} preview`;retry.style.cssText=`position:absolute;bottom:${10+i*40}px;left:12px;z-index:8`;retry.onclick=()=>void update(currentPayload);document.querySelector('.studio')!.append(retry);retries[i]=retry}
 async function update(next:any){const ownGeneration=++generation;if(next.selected!==currentPayload.selected)selectionTime=performance.now();currentPayload=next;key.color.set(next.lighting==='arena'?0xe2f3ff:0xffe2bb);renderer.toneMappingExposure=next.lighting==='arena'?.94:1.12;
  const robots:DisplayRobot[]=(Array.isArray(next.robots)?next.robots:[]).slice(0,stands.length);
  const desired=robots.map(robot=>JSON.stringify([robot?.id,robot?.choices,robot?.career?.pose,robot?.career?.showMarks?robot.career.marks:null,robot?.repairUntil,next.visibleSlots]));
  const changes=await Promise.all(stands.map(async(_,i)=>{const robot=robots[i];if(!robot)return {i,robot,instance:undefined};if(instances[i]?.signature===desired[i])return {i,robot,unchanged:true};try{if(!robot.choices||!SLOTS.every(s=>entries.get(robot.choices[s])?.slots.includes(s)))throw Error('Unavailable part');status.hidden=false;status.textContent='Updating your robot…';await Promise.all([...new Set([...SLOTS.map(s=>robot.choices[s]),'__support'])].map(loadPart));if(!alive||generation!==ownGeneration)return {i,robot};return {i,robot,instance:build(robot,desired[i],next)}}catch{return {i,robot,failed:true}}}));
  if(!alive||generation!==ownGeneration){changes.forEach(c=>{if(c.instance)destroyInstance(c.instance)});return;}
  for(const change of changes){const {i,robot}=change;if(change.failed){failure(i,robot!);continue;}clearFailure(i);if(change.unchanged){appearance(instances[i]!,robot!);continue;}if(instances[i])destroyInstance(instances[i]!);instances[i]=change.instance;if(change.instance){stands[i].add(change.instance.assembly.model,change.instance.banner.garage)}}
  stands.forEach((s,i)=>(s.children[0] as T.Mesh<T.CylinderGeometry,T.MeshStandardMaterial>).material.color.set(robots[i]?.id===next.selected?0xbd9957:0x716351));
  trimLibrary();
  const failed=changes.some(c=>c.failed);status.hidden=!failed;status.textContent=failed?'A preview could not update. Your parts are saved.':'';canvas.dataset.equipment=JSON.stringify(instances.map(i=>i?.robot.choices??null));canvas.dataset.ready='true';draw();if(!loaded){layout();loaded=true;bridge.send('loaded')}bridge.send('updated',{generation:ownGeneration,failed});
 }
 function layout(){const width=canvas.clientWidth,height=canvas.clientHeight;if(!width||!height)return;renderer.setSize(width,height,false);const aspect=width/height,mobile=width<650;if(camera instanceof T.PerspectiveCamera)camera.aspect=aspect;else{const span=Math.max(mobile?12:9,(mobile?17:28)/aspect);camera.left=-span*aspect/2;camera.right=span*aspect/2;camera.top=span/2;camera.bottom=-span/2;}camera.updateProjectionMatrix();if(garage){stands.forEach((s,i)=>s.position.set(mobile?(i<3?(i-1)*5.1:(i-3.5)*5.4):(i-2)*5.1,0,mobile?(i<3?-3.2:3.1):0));camera.position.set(mobile?0:1,mobile?14:9,24);controls.target.set(0,3.2,0);camera.lookAt(controls.target)}else if(!loaded){camera.position.set(7.4,4.9,9.6);controls.target.set(0,2.7,0);controls.update();}draw()}
 function draw(){if(alive)renderer.render(scene,camera)}
 function animate(time:number){frame=0;if(!alive||document.hidden)return;if(!preferences.reduced()){instances.forEach((instance,i)=>{if(!instance)return;const robot=instance.robot,head=instance.assembly.model.getObjectByName('head'),ack=robot.id===currentPayload.selected?Math.max(0,1-(time-selectionTime)/1100):0;if(head)head.rotation.y=Math.sin(time*.00028+i)*.035+ack*.09;instance.assembly.model.rotation.y=Math.sin(time*.00017+i)*.018+(currentPayload.returning===robot.id ? .04 : 0);instance.banner.pose(time/1000,false)});controls.update();}draw();if(!preferences.reduced())frame=requestAnimationFrame(animate)}
 const visibility=()=>{cancelAnimationFrame(frame);frame=0;if(!document.hidden)frame=requestAnimationFrame(animate)};
 const observer=new ResizeObserver(layout);observer.observe(canvas);stopQueue();const unsubscribe=bridge.subscribe(next=>void update(next));
 function dispose(){if(!alive)return;alive=false;generation++;unsubscribe();cancelAnimationFrame(frame);observer.disconnect();document.removeEventListener('visibilitychange',visibility);reduced.removeEventListener('change',visibility);controls.dispose();instances.forEach(i=>i&&destroyInstance(i));stands.forEach((_,i)=>clearFailure(i));disposeResources(scene);library.forEach(disposeResources);library.clear();environment.dispose();key.shadow.map?.dispose();renderer.dispose()}
 window.addEventListener('pagehide',dispose,{once:true});document.addEventListener('visibilitychange',visibility);reduced.addEventListener('change',visibility);controls.addEventListener('change',draw);
 layout();await update(queuedPayload);if(alive)frame=requestAnimationFrame(animate);
}
