import * as T from 'three';
import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js';
import {GLTFLoader} from 'three/examples/jsm/loaders/GLTFLoader.js';
import {RoomEnvironment} from 'three/examples/jsm/environments/RoomEnvironment.js';
import {createHeroMotion,HERO_DURATION,HeroStyle} from './hero-motion';
const V=(x=0,y=0,z=0)=>new T.Vector3(x,y,z);
type Selection='lineup'|'tank'|HeroStyle;
export async function startHeroes(){
 const $=(id:string)=>document.getElementById(id)!,canvas=$('model-canvas') as HTMLCanvasElement,play=$('play-strike') as HTMLButtonElement,slider=$('motion-time') as HTMLInputElement,phase=$('motion-phase') as HTMLOutputElement;
 document.title='Three fighting styles — Model Kombat';document.querySelector('.review-label')!.textContent='Three approved models';document.querySelector('.eyebrow')!.textContent='ART BIBLE / TIER 03';
 $('joint-controls').hidden=true;$('motion-controls').hidden=false;document.querySelector('.mode-switch')!.innerHTML='<button data-hero="lineup">All three</button><button data-hero="tank">Tank</button><button data-hero="speed">Speed</button><button data-hero="ranged">Ranged</button>';
 $('reload-model').textContent='Tank combat proof';$('reload-model').onclick=()=>location.href='/?view=exchange&revision=tank-exchange-1';slider.setAttribute('aria-label','Weapon demonstration position');
 const note=document.createElement('p');note.className='hero-note';canvas.parentElement!.append(note);
 const renderer=new T.WebGLRenderer({canvas,antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.AgXToneMapping;renderer.toneMappingExposure=.9;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.shadowMap.autoUpdate=false;
 const scene=new T.Scene();scene.background=new T.Color('#242723');scene.fog=new T.Fog('#242723',28,60);const camera=new T.PerspectiveCamera(35,1,.05,100);camera.position.set(-9,6,12);
 const controls=new OrbitControls(camera,canvas),reduced=matchMedia('(prefers-reduced-motion: reduce)');controls.enablePan=false;controls.enableDamping=!reduced.matches;controls.minDistance=3;controls.maxDistance=40;controls.maxPolarAngle=Math.PI*.49;
 const env=new RoomEnvironment(),pmrem=new T.PMREMGenerator(renderer),environment=pmrem.fromScene(env,.045);scene.environment=environment.texture;env.dispose();pmrem.dispose();
 scene.add(new T.HemisphereLight('#e5e0d4','#24231e',.42));const key=new T.DirectionalLight('#ffe8c9',2);key.position.set(-4,9,6);key.castShadow=true;key.shadow.mapSize.set(1024,1024);Object.assign(key.shadow.camera,{left:-10,right:10,top:9,bottom:-9,near:.1,far:30});key.shadow.bias=-.00015;key.shadow.normalBias=.028;scene.add(key);
 for(const [color,power,pos]of [['#d7e0e2',1.25,[5,6,-7]],['#e9dfcc',.35,[5,3,7]]] as const){const light=new T.DirectionalLight(color,power);light.position.set(pos[0],pos[1],pos[2]);scene.add(light)}
 const floor=new T.Mesh(new T.PlaneGeometry(160,160),new T.MeshStandardMaterial({color:'#282925',roughness:.9,metalness:.02}));floor.rotation.x=-Math.PI/2;floor.position.y=.024;floor.receiveShadow=true;scene.add(floor);
 let selected:Selection='lineup',drill=false,playing=false,time=0,ready=false,alive=true,raf=0,last:number|null=null,draws=0,activeView='three-quarter',audio:AudioContext|null=null;
 const models=new Map<Selection,T.Group>(),motions=new Map<HeroStyle,ReturnType<typeof createHeroMotion>>(),bounds=new T.Box3(),labels=new Map<Selection,HTMLSpanElement>(),objects:T.Object3D[]=[floor];
 const steel=new T.MeshStandardMaterial({color:'#4e5b5a',metalness:.8,roughness:.38}),padmat=new T.MeshStandardMaterial({color:'#887754',metalness:.25,roughness:.7});
 const target=new T.Group();scene.add(target);objects.push(target);const pad=new T.Mesh(new T.BoxGeometry(.65,.65,.10),padmat);target.add(pad);pad.position.y=2.8;pad.castShadow=true;pad.receiveShadow=true;const stem=new T.Mesh(new T.BoxGeometry(.10,2.6,.13),steel);stem.position.y=1.35;target.add(stem);const foot=new T.Mesh(new T.BoxGeometry(.62,.10,.48),steel);foot.position.y=.075;target.add(foot);target.visible=false;
 const flash=new T.Mesh(new T.ConeGeometry(.105,.38,7),new T.MeshBasicMaterial({color:'#ffe0a0',transparent:true,opacity:.95,depthWrite:false}));flash.rotation.x=Math.PI/2;scene.add(flash);objects.push(flash);flash.visible=false;
 const tracer=new T.Mesh(new T.CylinderGeometry(.017,.017,1,8),new T.MeshBasicMaterial({color:'#ffd18a'}));scene.add(tracer);objects.push(tracer);tracer.visible=false;
 const chips=new T.InstancedMesh(new T.BoxGeometry(.024,.025,.07),new T.MeshBasicMaterial({color:'#e9ba71'}),12);scene.add(chips);objects.push(chips);chips.visible=false;chips.frustumCulled=false;const dummy=new T.Object3D(),firelight=new T.PointLight('#ffd29a',0,3,2);scene.add(firelight);let events:any[]=[];
 const request=()=>{if(alive&&!document.hidden&&!raf)raf=requestAnimationFrame(draw)};
 function sound(rifle:boolean){if(!audio||audio.state!=='running')return;const now=audio.currentTime,osc=audio.createOscillator(),gain=audio.createGain();osc.type=rifle?'sawtooth':'triangle';osc.frequency.setValueAtTime(rifle?155:100,now);osc.frequency.exponentialRampToValueAtTime(35,now+.15);gain.gain.setValueAtTime(.08,now);gain.gain.exponentialRampToValueAtTime(.0001,now+.20);osc.connect(gain).connect(audio.destination);osc.start();osc.stop(now+.22);osc.onended=()=>{osc.disconnect();gain.disconnect()}}
 function pose(t:number){time=T.MathUtils.clamp(t,0,HERO_DURATION);slider.value=String(time);flash.visible=tracer.visible=chips.visible=false;firelight.intensity=0;
  if(selected==='speed'||selected==='ranged'){
   const state=motions.get(selected)?.pose(time);if(state)phase.value=state.phase;const impacts=events.filter(e=>e.impact<=time),latest=impacts[impacts.length-1],age=latest?time-latest.impact:100;
   if(latest&&age<.3){chips.visible=true;for(let i=0;i<12;i++){const a=i*2.39996;dummy.position.fromArray(latest.point).add(V(Math.cos(a)*age*1.5,Math.sin(a)*age*1.8-4*age*age,-age*(.9+(i%3)*.25)));dummy.scale.setScalar(1-age/.3);dummy.rotation.set(a,age*5,a);dummy.updateMatrix();chips.setMatrixAt(i,dummy.matrix)}chips.instanceMatrix.needsUpdate=true}pad.position.z=-Math.sin(Math.min(1,Math.max(0,age)/.28)*Math.PI)*.05;
   if(selected==='ranged')for(const e of events){const age=time-e.release;if(age>=0&&age<.085){flash.visible=true;flash.position.fromArray(state?.endpoint??e.origin).add(V(0,0,.15));flash.scale.setScalar(1-age/.11);firelight.position.fromArray(state?.endpoint??e.origin);firelight.intensity=2.5*(1-age/.085)}if(age>=0&&time<e.impact){const p=V().fromArray(e.origin),end=V().fromArray(e.point),dir=end.clone().sub(p).normalize(),distance=Math.min(end.distanceTo(p),age*18);tracer.visible=true;tracer.scale.set(1,Math.min(.65,distance+.04),1);tracer.position.copy(p).addScaledVector(dir,Math.max(0,distance-tracer.scale.y*.5));tracer.quaternion.setFromUnitVectors(V(0,1,0),dir)}}
  }else phase.value=selected==='lineup'?'Tank · Speed · Ranged':'Approved Tank model';renderer.shadowMap.needsUpdate=true;
 }
 function placeLabels(){models.forEach((m,style)=>{const label=labels.get(style)!;label.hidden=selected!=='lineup';if(label.hidden)return;const p=m.localToWorld(V(0,.1,0)).project(camera);label.style.left=`${(p.x*.5+.5)*canvas.clientWidth}px`;label.style.top=`${(-p.y*.5+.5)*canvas.clientHeight+12}px`})}
 function draw(now:number){raf=0;if(!alive||document.hidden)return;if(playing){const previous=time;pose(time+(last===null?0:Math.min(.05,(now-last)/1000)));last=now;for(const e of events)if(e.release>previous&&e.release<=time)sound(selected==='ranged');if(time>=HERO_DURATION){playing=false;last=null;play.textContent='Replay demonstration'}}controls.update();renderer.render(scene,camera);placeLabels();draws++;if(playing)request()}
 function view(name:string){activeView=name;const dir=(name==='front'?V(0,.17,1):name==='side'?V(-1,.18,0):name==='back'?V(0,.17,-1):selected==='lineup'?V(-.20,.20,1):V(-.62,.24,1)).normalize(),center=bounds.isEmpty()?V(0,2.4,0):bounds.getCenter(V()),right=new T.Vector3().crossVectors(V(0,1,0),dir).normalize(),up=new T.Vector3().crossVectors(dir,right).normalize(),tan=Math.tan(T.MathUtils.degToRad(camera.fov/2));let distance=7;
  if(!bounds.isEmpty())for(const x of [bounds.min.x,bounds.max.x])for(const y of [bounds.min.y,bounds.max.y])for(const z of [bounds.min.z,bounds.max.z]){const p=V(x,y,z).sub(center),d=p.dot(dir);distance=Math.max(distance,d+Math.abs(p.dot(right))/(tan*camera.aspect),d+Math.abs(p.dot(up))/tan)}controls.target.copy(center);camera.position.copy(center).addScaledVector(dir,distance*1.08);camera.lookAt(center);controls.update();document.querySelectorAll<HTMLButtonElement>('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===name)));request();
 }
 function select(style:Selection){selected=style;drill=false;playing=false;last=null;events=[];models.forEach((m,s)=>{m.visible=style==='lineup'||style===s;m.position.set(0,0,0);m.quaternion.identity()});for(const m of motions.values())m.pose(0);if(style==='lineup'){motions.get('speed')!.rest();models.forEach((m,s)=>{m.position.x=s==='tank'?-3.4:s==='speed'?0:3.4;if(s==='ranged')m.rotation.y=.75})}
  target.visible=style==='speed'||style==='ranged';target.position.set(0,0,0);pad.position.z=0;
  if(style==='speed'){const controller=motions.get(style)!,end=V().fromArray(controller.pose(1.17).endpoint);target.position.set(end.x,0,end.z+.05);pad.position.y=end.y;stem.scale.y=(end.y-.2)/2.6;stem.position.y=(end.y-.2)/2;events=[{release:1.17,impact:1.17,point:end.toArray()}];controller.pose(0)}
  else if(style==='ranged'){const controller=motions.get(style)!;for(const release of [1.24,2.4]){const origin=V().fromArray(controller.pose(release).endpoint),point=origin.clone();point.z=5.15;events.push({release,impact:release+origin.distanceTo(point)/18,origin:origin.toArray(),point:point.toArray()})}target.position.set(events[0].point[0],0,5.20);pad.position.y=events[0].point[1];stem.scale.y=(pad.position.y-.2)/2.6;stem.position.y=(pad.position.y-.2)/2;controller.pose(0)}
  pose(0);if(style==='speed'||style==='lineup')motions.get('speed')!.rest();target.visible=false;bounds.makeEmpty();models.forEach(m=>{if(m.visible)bounds.expandByObject(m,true)});
  document.querySelector('.model-title h1')!.textContent=style==='lineup'?'Three ways to fight.':style==='tank'?'Bastion Warden':style==='speed'?'Phalanx Duelist':'Ghost Tracker';document.querySelector('.model-title p')!.textContent=style==='lineup'?'One world. Three distinct silhouettes.':style==='tank'?'Tank · heavy armour, two-handed hammer':style==='speed'?'Speed · lean armour, spear and shield':'Ranged · exposed frame, precision rifle';
  note.textContent=style==='lineup'?'Choose a class below to inspect its movement.':style==='tank'?'Approved model · open the Tank combat proof to watch it fight.':'Approved model · isolated weapon drill';play.disabled=style==='lineup'||style==='tank';slider.disabled=play.disabled;play.textContent=style==='speed'?'Watch spear drill':style==='ranged'?'Watch rifle drill':'Choose Speed or Ranged';document.querySelectorAll<HTMLButtonElement>('[data-hero]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.hero===style)));$('concept-toggle').textContent=style==='lineup'?'Tank reference':'View reference';view(activeView);request();
 }
 function resize(){const box=canvas.parentElement!.getBoundingClientRect();renderer.setSize(box.width,box.height,false);camera.aspect=box.width/box.height;camera.updateProjectionMatrix();view(activeView)}
 const observer=new ResizeObserver(resize);observer.observe(canvas.parentElement!);controls.addEventListener('change',request);document.querySelectorAll<HTMLButtonElement>('[data-view]').forEach(b=>b.onclick=()=>view(b.dataset.view!));document.querySelectorAll<HTMLButtonElement>('[data-hero]').forEach(b=>b.onclick=()=>{if(ready)select(b.dataset.hero as Selection)});
 function startDrill(){if(drill||!(selected==='speed'||selected==='ranged'))return;drill=true;target.visible=true;bounds.makeEmpty();for(let t=0;t<=HERO_DURATION;t+=.12){motions.get(selected)!.pose(t);bounds.expandByObject(models.get(selected)!,true)}bounds.expandByObject(target,true);pose(time);view(activeView)}
 play.onclick=()=>{if(!ready||play.disabled)return;startDrill();if(!audio)audio=new AudioContext();void audio.resume();if(time>=HERO_DURATION)pose(0);playing=!playing;last=null;play.textContent=playing?'Pause demonstration':'Continue demonstration';request()};slider.oninput=()=>{startDrill();playing=false;last=null;pose(Number(slider.value));play.textContent='Continue demonstration';request()};
 function concept(open:boolean){$('concept-panel').hidden=!open;$('concept-toggle').setAttribute('aria-expanded',String(open));if(open){const img=$('concept-panel').querySelector('img')!;img.src=selected==='speed'?'/assets/speed-t3-duelist-v1-concept.png':selected==='ranged'?'/assets/ranged-t3-tracker-v1-concept.png':'/concept.png';img.alt=selected==='speed'?'Speed spear-and-shield design reference':selected==='ranged'?'Ranged skeletal marksman design reference':'Approved Tank design';$('concept-panel').querySelector('h2')!.textContent=selected==='speed'?'Speed reference':selected==='ranged'?'Ranged reference':'Approved Tank';$('concept-panel').querySelector('p')!.textContent='Design reference. Review the actual 3D model and movement separately.';$('concept-close').focus()}else $('concept-toggle').focus()}
 $('concept-toggle').onclick=()=>concept($('concept-panel').hidden);$('concept-close').onclick=()=>concept(false);
 const keydown=(e:KeyboardEvent)=>{if(e.key==='Escape'&&!$('concept-panel').hidden){concept(false);return}if(e.target!==canvas)return;if(e.key===' '){e.preventDefault();play.click()}if(e.key==='Home'){e.preventDefault();view('three-quarter')}if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();const offset=camera.position.clone().sub(controls.target).applyAxisAngle(V(0,1,0),e.key==='ArrowLeft'?-.12:.12);camera.position.copy(controls.target).add(offset);controls.update();request()}};document.addEventListener('keydown',keydown);
 const hidden=()=>{if(document.hidden){cancelAnimationFrame(raf);raf=0;last=null}else request()},preference=()=>{controls.enableDamping=!reduced.matches;request()};document.addEventListener('visibilitychange',hidden);reduced.addEventListener('change',preference);
 function disposeRoots(roots:T.Object3D[]){const geo=new Set<T.BufferGeometry>(),mats=new Set<T.Material>(),textures=new Set<T.Texture>();roots.forEach(r=>r.traverse(o=>{const m=o as T.Mesh;if(!m.isMesh)return;geo.add(m.geometry);for(const mat of Array.isArray(m.material)?m.material:[m.material]){mats.add(mat);Object.values(mat).forEach(t=>{if(t?.isTexture)textures.add(t)})}}));geo.forEach(g=>g.dispose());mats.forEach(m=>m.dispose());textures.forEach(t=>t.dispose())}
 function dispose(){if(!alive)return;alive=false;cancelAnimationFrame(raf);observer.disconnect();controls.dispose();document.removeEventListener('keydown',keydown);document.removeEventListener('visibilitychange',hidden);reduced.removeEventListener('change',preference);disposeRoots([...objects,...models.values()]);environment.dispose();key.shadow.map?.dispose();renderer.dispose();void audio?.close()}window.addEventListener('pagehide',dispose,{once:true});
 (window as any).heroStudio={get ready(){return ready},select,seek:(t:number)=>{if(!Number.isFinite(t))return;startDrill();playing=false;last=null;pose(t);request()},setView:view,inspect:()=>({selected,drill,time,playing,events,draws,memory:renderer.info.memory,render:renderer.info.render,canvasCount:document.querySelectorAll('canvas').length,motion:motions.get(selected as HeroStyle)?.inspect(),models:[...models].map(([name,m])=>({name,visible:m.visible,position:m.position.toArray()}))}),render:()=>renderer.render(scene,camera),dispose};
 try{const loader=new GLTFLoader();for(const [style,file] of [['tank','tank-t3-warden-v1'],['speed','speed-t3-duelist-v1'],['ranged','ranged-t3-tracker-v1']] as const){const gltf=await loader.loadAsync('/assets/'+file+'.glb');if(!alive){disposeRoots([gltf.scene]);return}const m=gltf.scene;m.traverse(o=>{const mesh=o as T.Mesh;if(mesh.isMesh){mesh.castShadow=true;mesh.receiveShadow=true;for(const mat of Array.isArray(mesh.material)?mesh.material:[mesh.material])if((mat as T.MeshStandardMaterial).isMeshStandardMaterial)(mat as T.MeshStandardMaterial).envMapIntensity=.68}});scene.add(m);models.set(style,m);if(style!=='tank')motions.set(style,createHeroMotion(m,style));const label=document.createElement('span');label.className='fighter-label';label.textContent=style==='tank'?'TANK · Warden':style==='speed'?'SPEED · Duelist':'RANGED · Tracker';canvas.parentElement!.append(label);labels.set(style,label)}
  $('load-status').textContent='Preparing the character materials…';flash.visible=tracer.visible=chips.visible=target.visible=true;firelight.intensity=1;await renderer.compileAsync(scene,camera);if(!alive)return;flash.visible=tracer.visible=chips.visible=target.visible=false;firelight.intensity=0;
  ready=true;slider.max=String(HERO_DURATION);slider.step='.005';$('load-status').classList.add('empty');const style=new URLSearchParams(location.search).get('style');select(style==='speed'||style==='ranged'||style==='tank'?style:'lineup');resize();request();
 }catch(error){$('load-status').textContent='The class preview could not load. Reload to retry.';console.error(error)}
}




