import {ManualPractice9,MANUAL_ACTIONS,type ControlKind,type ManualCommand} from './manual-engine';
import {KITS} from './weapon-actions';

type Options={engine:()=>ManualPractice9|null;playing:()=>boolean;play:(value:boolean)=>void;restart:(lesson:boolean,commands?:ManualCommand[],seek?:number)=>void;change:()=>void};
const LESSONS=[['Move & jump','A/D or ←/→ move left/right. Space or W / ↑ jumps. Tank hops low, Ranged jumps higher, Speed leaps highest.'],['Attack & combo','Left-click over the arena or press J to strike immediately. After a hit, press again for the second strike, then the finisher. Middle-click or K uses a heavy attack.'],['Defend','Hold right-click over the arena or L to absorb hits while stamina recovers. A well-timed block or parry earns a faster counter.'],['Dodge','Press U with a movement direction as the rival prepares. Making that strike miss earns a faster counter.'],['Punish recovery','Backstep or jump clear of an attack, then step in and strike during recovery.'],['Special','Press O or Special. In the lesson only, it starts ready.']];

export function manualControls(host:HTMLElement,options:Options){
 const root=document.createElement('section');root.className='manual-panel';root.setAttribute('aria-label','Manual fight controls');
 root.innerHTML=`<div class="manual-top"><strong>TAKE CONTROL · PRACTICE</strong><span>No coins, repairs or competition points</span><button data-op="pause" title="Esc · Pause or resume">Pause · Esc</button></div><div class="manual-readiness"><span data-readiness></span><label>Guard <progress data-guard max="1" value="1"></progress></label><label>Stamina <progress data-stamina max="100" value="100"></progress></label><span data-special></span></div><div class="manual-lane-map" aria-label="Arena position"><span>LEFT EDGE</span><div><i data-lane-player></i><i data-lane-rival></i></div><span>RIGHT EDGE</span></div><p data-threat></p><p data-notice role="status"></p><div class="manual-movement" aria-label="Movement"><span>Move · A/D · Jump Space</span>${[['left','Left','A / ←'],['right','Right','D / →'],['jump','Jump','Space / W / ↑']].map(([kind,name,key])=>`<button data-control="${kind}" aria-label="${name}" type="button"><strong>${name}</strong><small>${key}</small></button>`).join('')}</div><div class="manual-buttons">${[['attack','Attack','LMB / J'],['heavy','Heavy','MMB / K'],['defend','Defend','RMB / L · hold'],['dodge','Dodge','U'],['shove','Shove','I'],['special','Special','O']].map(([kind,name,key])=>`<button data-control="${kind}" aria-label="${name}" type="button"><strong>${name}</strong><small>${key}</small></button>`).join('')}</div><div class="manual-lesson" hidden><strong data-lesson-title></strong><span data-lesson-copy></span><button data-op="lesson-next">Skip step</button><button data-op="lesson-skip">Skip lesson · start fight</button></div><div class="manual-cover"><h2>Make the calls.</h2><p>Face off in one lane. A/D or ←/→ move left and right. Space or W / ↑ jumps. Hold a direction to leap in or out. Your robot stays facing the rival.</p><p>Attack starts on press. Land a hit, then press again to link up to three strikes. Jump and press Attack for a descending strike. Left-click attacks, hold right-click to block, and middle-click for Heavy. J / L / K also work. Back away during their attack, then step in during recovery. Attacks spend stamina. Time a defence or dodge for a faster counter; jump over low strikes or retreat from heavy ones.</p><button data-op="lesson" disabled>Learn the controls</button><button data-op="start" disabled>Start fight</button></div><div class="manual-results" hidden><h2 data-result></h2><p>Practice result · no rewards or repairs</p><div data-moments></div><button data-op="rematch">Rematch · same rival</button><button data-op="change">Change opponent</button><button data-op="replay">Watch full fight</button><button data-op="download">Save practice replay</button></div>`;
 host.append(root);const announcement=document.createElement('div');announcement.className='manual-announcement';announcement.setAttribute('aria-live','polite');announcement.hidden=true;host.append(announcement);document.body.classList.add('manual-fight');
 const $=<E extends HTMLElement=HTMLElement>(s:string)=>root.querySelector<E>(s)!;
 const cover=$('.manual-cover'),results=$('.manual-results'),lessonPanel=$('.manual-lesson');
 const pointers=new Map<number,ControlKind>(),held=new Set<ControlKind>(),sources=new Map<string,ControlKind>();let disposed=false,lesson=-1,lastResult:ReturnType<ManualPractice9['snapshot']>|null=null,seenEnd=false,lastMessage='',pauseReason='';
 const keys:Record<string,ControlKind>={KeyJ:'attack',KeyK:'heavy',KeyL:'defend',KeyU:'dodge',KeyI:'shove',KeyO:'special',Space:'jump',KeyW:'jump',ArrowUp:'jump',KeyA:'left',ArrowLeft:'left',KeyD:'right',ArrowRight:'right'};
 function press(kind:ControlKind,source:string=kind){if(!options.playing()||sources.has(source)||options.engine()?.replayManual)return;sources.set(source,kind);if(held.has(kind))return;held.add(kind);options.engine()?.command(kind);}
 function release(kind:ControlKind,source:string=kind){sources.delete(source);if([...sources.values()].includes(kind)||!held.delete(kind))return;if(kind==='attack'||kind==='defend'||['forward','back','left','right'].includes(kind))options.engine()?.command(kind,'release');}
 function clear(){held.clear();sources.clear();pointers.clear();options.engine()?.clearControls();}
 function pause(reason='Paused'){clear();options.play(false);pauseReason=reason;$('[data-op="pause"]').textContent='Resume · Esc';$('[data-notice]').textContent=`${reason}. Press Resume to continue.`;}
 function start(inLesson=false){if(!options.engine()){ $('[data-notice]').textContent='Loading fighters…';return;}clear();lesson=inLesson?0:-1;lastResult=null;seenEnd=false;cover.hidden=true;results.hidden=true;lessonPanel.hidden=!inLesson;options.restart(inLesson);options.play(true);pauseReason='';lastMessage='';$('[data-notice]').textContent='';$('[data-op="pause"]').textContent='Pause · Esc';lessonText();}
 function lessonText(){if(lesson<0)return;if(lesson>=LESSONS.length){lessonPanel.hidden=true;pause('Lesson complete');cover.hidden=false;cover.querySelector('h2')!.textContent='Now fight for real.';return;}$('[data-lesson-title]').textContent=`${lesson+1}/${LESSONS.length} · ${LESSONS[lesson][0]}`;$('[data-lesson-copy]').textContent=LESSONS[lesson][1];}
 for(const button of Array.from(root.querySelectorAll<HTMLButtonElement>('[data-control]'))){
  button.addEventListener('pointerdown',e=>{if(e.button!==0)return;e.preventDefault();const kind=button.dataset.control as ControlKind;if(held.has(kind))return;button.setPointerCapture(e.pointerId);pointers.set(e.pointerId,kind);press(kind);});
  button.addEventListener('pointerup',e=>{e.preventDefault();const kind=pointers.get(e.pointerId);pointers.delete(e.pointerId);if(kind)release(kind);});
  button.addEventListener('pointercancel',()=>pause('Touch interrupted'));
  button.addEventListener('lostpointercapture',e=>{if(pointers.has(e.pointerId))pause('Touch interrupted');});
  // Native keyboard/screen-reader activation remains available without pointer synthesis.
  button.addEventListener('click',e=>{if(e.detail!==0)return;const kind=button.dataset.control as ControlKind;if(kind==='defend'&&held.has(kind))release(kind);else{press(kind);if(kind!=='defend')release(kind);}});
 }
 // Use mouse events: pointerdown only fires for the first button in a chord.
 // Own presses on the arena only; release on document even after dragging away.
 const arena=host.querySelector<HTMLCanvasElement>('#fight-canvas');
 const mouseKeys:Record<number,ControlKind>={0:'attack',2:'defend',1:'heavy'};
 const mouseDown=(e:MouseEvent)=>{const kind=mouseKeys[e.button];if(!kind||!options.playing()||document.querySelector('dialog[open]'))return;e.preventDefault();press(kind,`mouse-${e.button}`);};
 const mouseUp=(e:MouseEvent)=>{const kind=mouseKeys[e.button];if(kind&&sources.has(`mouse-${e.button}`)){e.preventDefault();release(kind,`mouse-${e.button}`);}};
 const mouseMove=(e:MouseEvent)=>{for(const [button,mask]of [[0,1],[2,2],[1,4]])if(sources.has(`mouse-${button}`)&&!(e.buttons&mask))release(mouseKeys[button],`mouse-${button}`);};
 const mouseDefault=(e:MouseEvent)=>e.preventDefault();
 arena?.addEventListener('mousedown',mouseDown);arena?.addEventListener('contextmenu',mouseDefault);arena?.addEventListener('auxclick',mouseDefault);
 document.addEventListener('mouseup',mouseUp);document.addEventListener('mousemove',mouseMove);
 const down=(e:KeyboardEvent)=>{if(['INPUT','TEXTAREA','SELECT'].includes((e.target as HTMLElement)?.tagName)||document.querySelector('dialog[open]'))return;if(e.code==='Escape'){e.preventDefault();if(!e.repeat)$('[data-op="pause"]').click();return;}if(!keys[e.code])return;e.preventDefault();if(!e.repeat)press(keys[e.code]);};
 const up=(e:KeyboardEvent)=>{if(keys[e.code]){e.preventDefault();release(keys[e.code]);}};
 const blur=()=>{if(options.playing())pause('Paused when focus left the fight');},hidden=()=>{if(document.hidden)pause('Paused while hidden');};
 const parentPause=(e:MessageEvent)=>{if(e.source===parent&&e.origin===location.origin&&e.data?.type==='manual-pause')pause('Paused when focus left the game');};
 document.addEventListener('keydown',down);document.addEventListener('keyup',up);window.addEventListener('blur',blur);document.addEventListener('visibilitychange',hidden);window.addEventListener('message',parentPause);
 root.addEventListener('click',e=>{const op=(e.target as HTMLElement).closest<HTMLElement>('[data-op]')?.dataset.op;if(!op)return;
  if(op==='start'||op==='rematch'||op==='lesson-skip')start();if(op==='lesson')start(true);
  if(op==='lesson-next'){lesson++;lessonText();}
  if(op==='change'){clear();options.change();}
  if(op==='pause'){if(options.engine()?.done)return;if(options.playing())pause();else if(cover.hidden){options.play(true);pauseReason='';lastMessage='';$('[data-op="pause"]').textContent='Pause · Esc';}}
  if(op==='replay'&&lastResult){results.hidden=true;options.restart(lastResult.manualLesson,lastResult.commands);options.play(true);seenEnd=false;}
  if(op==='download'&&lastResult){const safe={...lastResult,builds:lastResult.builds.map(b=>({...b,appearance:{...b.appearance,banner:false,bannerId:undefined}}))};const url=URL.createObjectURL(new Blob([JSON.stringify(safe)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='model-kombat-practice-replay.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 });
 function update(){if(disposed)return;const e=options.engine();for(const button of Array.from(root.querySelectorAll<HTMLButtonElement>('[data-op=lesson],[data-op=start]')))button.disabled=!e;if(!e)return;const a=e.actors[0],kit=KITS[a.build.weapon],map=MANUAL_ACTIONS[a.build.weapon];
  const activation=[...e.events].reverse().find(v=>v.kind==='special');const shown=!!activation&&e.tick-activation.tick<80;announcement.hidden=!shown;if(activation&&shown){const actor=e.actors[activation.who];announcement.dataset.style=actor.build.style;announcement.textContent=`${activation.who===0?'YOUR':'RIVAL'} ${actor.build.style==='tank'?'ENERGY SHIELD':actor.build.style==='speed'?'OVERDRIVE':'SLOW FIELD'}`;}
  $('[data-lane-player]').style.left=`${(a.position.x+6.8)/13.6*100}%`;$('[data-lane-rival]').style.left=`${(e.actors[1].position.x+6.8)/13.6*100}%`;
  $<HTMLProgressElement>('[data-guard]').value=a.guard/e.guardMax;
  $<HTMLProgressElement>('[data-stamina]').value=e.stamina[0];$('[data-stamina]').setAttribute('aria-label',`Stamina ${Math.floor(e.stamina[0])} of 100`);
  $('[data-readiness]').textContent=e.counterUntil>e.tick?'Counter ready — faster next attack':e.replayManual?'Watching recorded inputs':e.buffer?'Attack buffered':e.comboReady?`${e.comboHits} HIT${e.comboHits===1?'':'S'} · ATTACK TO LINK ${e.comboStep+1}/3`:e.guardRequested&&!e.defending?'Guard queued':e.followUp?`Opening: ${e.followUp.name}`:a.action?.def.name??e.attackStatus;
  $('[data-control=attack] strong').textContent=e.jumpHeight(0)>.05?'Air strike':'Attack';
  const enemy=e.actors[1],threat=$('[data-threat]');threat.textContent=enemy.downUntil>e.tick?'Rival knocked down — reposition for the get-up':enemy.guardUntil>e.tick?'Rival guarding — bait a strike, then punish':e.rivalOpening?'Rival recovering — step in and punish':enemy.action&&enemy.action.elapsed<enemy.action.prepare?'Rival preparing — guard, dash or jump':'Find your distance. Bait an attack.';threat.dataset.open=String(e.rivalOpening);
  $('[data-special]').textContent=a.specialUntil>e.tick?`${a.build.style==='tank'?'ENERGY SHIELD':a.build.style==='speed'?'OVERDRIVE':'SLOW FIELD'} · ${Math.ceil((a.specialUntil-e.tick)/60)}s`:`Special ${Math.floor(a.meter)}%`;
  root.dataset.special=a.specialUntil>e.tick?a.build.style:'';root.dataset.ready=String(a.meter>=100);
  if(e.message!==lastMessage&&!pauseReason){lastMessage=e.message;$('[data-notice]').textContent=e.message;}
  for(const b of Array.from(root.querySelectorAll<HTMLButtonElement>('[data-control]'))){b.disabled=!options.playing()||e.done||!!e.replayManual;b.setAttribute('aria-pressed',String(held.has(b.dataset.control as ControlKind)));}
  if(lesson>=0&&lesson<LESSONS.length){const done=lesson===0?e.movementTicks>=30:lesson===1?e.events.some(v=>v.kind==='prepare'&&v.who===0):lesson===2?e.receipts.some(v=>v.accepted&&v.reason==='Guarding'):lesson===3?e.events.some(v=>v.who===0&&v.kind==='movement'&&v.reason==='player dodge'):lesson===4?e.events.some(v=>v.who===0&&v.kind==='hit'&&v.reason==='caught recovery'):e.events.some(v=>v.who===0&&v.kind==='special');if(done){lesson++;lessonText();}}
  if(e.done&&!seenEnd){seenEnd=true;options.play(false);if(!e.replayManual)lastResult=e.snapshot();results.hidden=false;$('[data-result]').textContent=e.winner===0?'You won':e.winner===1?'Rival won':'Draw';const container=$('[data-moments]');container.replaceChildren();
   const moments=e.events.filter(v=>['break','parry','guard_break'].includes(v.kind)||v.kind==='hit'&&v.reason==='caught recovery').slice(-3);
   for(const event of moments){const button=document.createElement('button');button.textContent=`${(event.tick/60).toFixed(1)}s · ${event.kind==='hit'?'Caught an exposed recovery':event.kind==='break'?`${event.target===0?'Your':'Rival’s'} ${event.slot} broke`:event.kind==='parry'?'A strike was parried':'Guard broke'} ↗`;button.onclick=()=>{if(!lastResult)return;results.hidden=true;options.restart(lastResult.manualLesson,lastResult.commands,Math.max(0,event.tick-120));options.play(true);seenEnd=false;};container.append(button);}
  }
 }
 return {element:root,update,pause,dispose(){disposed=true;clear();arena?.removeEventListener('mousedown',mouseDown);arena?.removeEventListener('contextmenu',mouseDefault);arena?.removeEventListener('auxclick',mouseDefault);document.removeEventListener('mouseup',mouseUp);document.removeEventListener('mousemove',mouseMove);document.removeEventListener('keydown',down);document.removeEventListener('keyup',up);window.removeEventListener('blur',blur);document.removeEventListener('visibilitychange',hidden);window.removeEventListener('message',parentPause);announcement.remove();root.remove();}};
}
