import {renderBuildStats,renderPartStats} from './equipment-stats-ui';
import * as T from 'three';
import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js';
import {GLTFLoader} from 'three/examples/jsm/loaders/GLTFLoader.js';
import {RoomEnvironment} from 'three/examples/jsm/environments/RoomEnvironment.js';
import {assemble,prepareLibrary,SLOTS,Slot,Entry,Choices} from './parts-assembly';
import {PALETTES,defaultAppearance,parseAppearance,paintAssembly,type Appearance} from './paint';
import {createBanner,readBanner,saveBanner,decodeBanner,cropBanner,bannerCanvasBlob} from './banner';
import {KITS,type WeaponKind} from './weapon-actions';
import {build8} from './v8-engine';
const PAINT_STORE='mk-bible-paint-1';
const LABEL:Record<Slot,string>={head:'Head',torso:'Body',armL:'Left arm',armR:'Right arm',legL:'Left leg',legR:'Right leg',weapon:'Weapon kit'};
const STORE='mk-bible-parts-workbench-1';
export async function startParts(){
 document.title='Parts workbench — Model Kombat';document.body.classList.add('parts-studio');
 document.querySelector('.studio')!.innerHTML=`<header class="topbar"><a class="brand" href="/?view=heroes"><span class="brand-mark">MK</span><span>MODEL KOMBAT<small>PARTS WORKBENCH</small></span></a><div class="header-actions"><a class="class-link" href="/?view=heroes">Approved models</a><a class="class-link" href="/?view=practice&saved=1">Try this robot</a></div></header>
 <section class="parts-stage"><canvas id="parts-canvas" tabindex="0" aria-label="Robot preview. Drag to turn. Arrow keys rotate the view."></canvas><div class="model-title"><span class="eyebrow">NINE FAMILIES / FOUR TIERS</span><h1 id="build-name">Your parts. Your robot.</h1><p id="build-note">Choose a complete design or mix individual parts.</p><span id="weapon-label" class="weapon-label"></span></div><details open id="robot-stat-panel" class="robot-stat-panel"><summary>Robot stats</summary><div id="live-build-stats"></div></details><div class="parts-stage-tools"><button id="isolate" aria-pressed="false">View this part</button><button id="joint-play" aria-pressed="false">Check grip</button><button id="front">▤ Front</button><button id="angle">◩ Three-quarter</button><button id="side">◧ Side</button><button id="back">▣ Back</button></div><p id="parts-loading" class="load-status" role="status">Loading parts…</p><div class="parts-caption"><strong id="selected-name"></strong><span id="selected-description"></span></div></section>
 <aside class="parts-cabinet" aria-label="Choose robot parts"><div class="parts-intro"><span class="eyebrow">START WITH A COMPLETE DESIGN</span><div class="preset-families"><button data-style="tank">Tank <small>3 designs</small></button><button data-style="speed">Speed <small>3 designs</small></button><button data-style="ranged">Ranged <small>3 designs</small></button></div><label class="family-label" for="family-select">Design family</label><select id="family-select" aria-label="Design family"></select><div id="family-pictures" class="family-pictures"></div><div class="tier-row" role="group" aria-label="Complete design tier">${[1,2,3,4].map(t=>`<button data-tier="${t}">Tier ${t}</button>`).join('')}</div><button id="apply-set">Use complete design</button><p class="parts-help">Or choose each part below. Left and right limbs are separate.</p></div>
 <details class="paint-workshop"><summary>Paint your robot · free</summary><div class="paint-presets" id="paint-presets"></div><p id="paint-target">Paint the selected part</p><div class="paint-colors"><label>Main<input id="paint-primary" type="color"></label><label>Panels<input id="paint-secondary" type="color"></label><label>Trim<input id="paint-trim" type="color"></label></div><div class="paint-actions"><button id="paint-mirror">Mirror limb</button><button id="paint-all">Apply to all</button><button id="paint-undo">Undo</button><button id="paint-reset">Reset part</button></div><p class="parts-help">Colour only. Metal edges, joints and your stats stay the same.</p></details><details class="paint-workshop"><summary>Your banner</summary><p class="parts-help">Your image on a garage banner and a small robot flag. Saved in this browser.</p><input id="banner-file" type="file" accept="image/png,image/jpeg,image/webp" aria-label="Choose banner image"><label class="banner-switch"><input id="banner-visible" type="checkbox"> Show banners</label><button id="banner-remove">Remove image</button><p id="banner-status" role="status">PNG, JPEG or WebP · up to 5 MB</p></details><div class="slot-tabs" role="group" aria-label="Part to change">${SLOTS.map(s=>`<button data-slot="${s}" aria-pressed="false">${LABEL[s]}</button>`).join('')}</div><section id="part-stat-panel" tabindex="0" aria-label="Part stats and comparison"></section><div class="parts-shelf" id="parts-shelf"></div><details class="paint-workshop"><summary>Weapon moves & build stats</summary><p id="build-stats"></p><label>Technique<select id="move-select" aria-label="Weapon technique"><option value="ready">Ready grip</option></select></label><p id="move-note" class="parts-help"></p><button id="move-preview">Show technique</button><p class="parts-help">Pose demonstration only. Try this robot to fight a real opponent.</p></details><details class="installed-parts"><summary>Your seven parts</summary><ul id="installed-list"></ul></details><p class="parts-save" id="parts-save">Art preview · saved only in this browser. No coins spent.</p></aside><dialog id="banner-dialog" aria-labelledby="banner-heading"><h2 id="banner-heading">Make it yours</h2><canvas id="banner-crop" width="256" height="384" aria-label="Banner crop preview"></canvas><label>Zoom<input id="banner-zoom" type="range" min="1" max="3" step=".01" value="1"></label><label>Across<input id="banner-x" type="range" min="0" max="1" step=".01" value=".5"></label><label>Up / down<input id="banner-y" type="range" min="0" max="1" step=".01" value=".5"></label><div class="paint-actions"><button id="banner-save">Use this banner</button><button id="banner-cancel">Cancel</button></div><p id="banner-crop-status" role="status"></p></dialog>`;
 const $=(id:string)=>document.getElementById(id)!,canvas=$('parts-canvas') as HTMLCanvasElement,loading=$('parts-loading');
 const response=await fetch('/assets/catalogue-2/manifest.json');if(!response.ok)throw Error('Parts manifest unavailable');const manifest=await response.json(),entries=manifest.entries as Entry[];
 if(entries.length!==36)throw Error('The nine-family catalogue is incomplete');
 const kitResponse=await fetch('/assets/weapon-kits-1/manifest.json');if(!kitResponse.ok)throw Error('Weapon kits unavailable');const kitManifest=await kitResponse.json(),kits=kitManifest.entries as Entry[];
 const byId=new Map([...entries,...kits].map(e=>[e.id,e])),library=new Map<string,T.Group>(),pending=new Map<string,Promise<void>>(),loader=new GLTFLoader(),renderer=new T.WebGLRenderer({canvas,antialias:true,preserveDrawingBuffer:true});
 renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.AgXToneMapping;renderer.toneMappingExposure=.9;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.shadowMap.autoUpdate=false;
 const scene=new T.Scene();scene.background=new T.Color('#242723');const camera=new T.PerspectiveCamera(35,1,.05,100),controls=new OrbitControls(camera,canvas),reduced=matchMedia('(prefers-reduced-motion: reduce)');controls.enableDamping=false;controls.enablePan=false;controls.minDistance=1;controls.maxDistance=30;controls.maxPolarAngle=Math.PI*.49;
 const env=new RoomEnvironment(),pmrem=new T.PMREMGenerator(renderer),environment=pmrem.fromScene(env,.045);scene.environment=environment.texture;env.dispose();pmrem.dispose();scene.add(new T.HemisphereLight('#e5e0d4','#24231e',.42));
 const key=new T.DirectionalLight('#ffe8c9',2);key.position.set(-4,9,6);key.castShadow=true;key.shadow.mapSize.set(1024,1024);Object.assign(key.shadow.camera,{left:-6,right:6,top:7,bottom:-7,near:.1,far:30});key.shadow.bias=-.00015;key.shadow.normalBias=.028;scene.add(key);
 for(const [color,power,pos]of [['#d7e0e2',1.25,[5,6,-7]],['#e9dfcc',.35,[5,3,7]]] as const){const light=new T.DirectionalLight(color,power);light.position.set(pos[0],pos[1],pos[2]);scene.add(light)}
 const floor=new T.Mesh(new T.PlaneGeometry(160,160),new T.MeshStandardMaterial({color:'#282925',roughness:.9,metalness:.02}));floor.rotation.x=-Math.PI/2;floor.position.y=.024;floor.receiveShadow=true;scene.add(floor);
 let choices=Object.fromEntries(SLOTS.map(s=>[s,'bible2.tank.t3.warden'])) as Choices,selectedSlot:Slot='head',style:Entry['style']='tank',tier=3,family='warden',current:ReturnType<typeof assemble>|null=null,isolated=false,playing=false,time=0,raf=0,last=0,alive=true,generation=0,ready=false,angle='three-quarter';
 choices.weapon='kit1.hammer.t3';
 try{const saved=JSON.parse(localStorage.getItem(STORE)||'null');if(saved?.choices){const migrated=Object.fromEntries(SLOTS.map(s=>[s,String(saved.choices[s]).replace(/^bible1\./,'bible2.')]));if(SLOTS.every(s=>byId.has(migrated[s])))choices=migrated as Choices}}catch{}
 ($('robot-stat-panel') as HTMLDetailsElement).open=innerWidth>1000;
 const requested=new URLSearchParams(location.search).get('style');if(requested&&['tank','speed','ranged'].includes(requested)){const e=entries.find(e=>e.style===requested&&e.tier===3)!;choices=Object.fromEntries(SLOTS.map(s=>[s,e.id])) as Choices}
 family=byId.get(choices.torso)!.family;style=byId.get(choices.torso)!.style;tier=byId.get(choices.torso)!.tier;
 let desiredChoices={...choices};
 let appearance=defaultAppearance(family),painter:ReturnType<typeof paintAssembly>|null=null;const paintHistory:Appearance[]=[];
 try{appearance=parseAppearance(JSON.parse(localStorage.getItem(PAINT_STORE)||'null'))??appearance}catch{}
 function commitPaint(next:Appearance){paintHistory.push(structuredClone(appearance));if(paintHistory.length>30)paintHistory.shift();appearance=next;applyPaint()}
 function applyPaint(){painter?.apply(appearance);banner.visible(appearance.banner&&hasBanner&&!isolated);($('banner-visible') as HTMLInputElement).checked=appearance.banner;try{localStorage.setItem(PAINT_STORE,JSON.stringify(appearance))}catch{$('parts-save').textContent='Your paint could not be saved in this browser.'}paintUI();request()}
 function paintUI(){for(const k of ['primary','secondary','trim'] as const)($('paint-'+k) as HTMLInputElement).value=appearance.parts[selectedSlot][k];$('paint-target').textContent='Painting: '+LABEL[selectedSlot];($('paint-mirror') as HTMLButtonElement).disabled=!/^(arm|leg)[LR]$/.test(selectedSlot);($('paint-undo') as HTMLButtonElement).disabled=!paintHistory.length}
 $('paint-presets').replaceChildren(...Object.entries(PALETTES).map(([name,p])=>{const b=document.createElement('button');b.textContent=name[0].toUpperCase()+name.slice(1);b.style.setProperty('--swatch',p.primary);b.onclick=()=>{const next=structuredClone(appearance);for(const slot of SLOTS)next.parts[slot]={...p};commitPaint(next)};return b}));
 for(const channel of ['primary','secondary','trim'] as const)($('paint-'+channel) as HTMLInputElement).onchange=e=>{const next=structuredClone(appearance);next.parts[selectedSlot][channel]=(e.target as HTMLInputElement).value;commitPaint(next)};
 $('paint-all').onclick=()=>{const next=structuredClone(appearance);for(const slot of SLOTS)next.parts[slot]={...appearance.parts[selectedSlot]};commitPaint(next)};
 $('paint-mirror').onclick=()=>{if(!/^(arm|leg)[LR]$/.test(selectedSlot))return;const next=structuredClone(appearance),other=(selectedSlot.slice(0,-1)+(selectedSlot.endsWith('L')?'R':'L')) as Slot;next.parts[other]={...next.parts[selectedSlot]};commitPaint(next)};
 $('paint-undo').onclick=()=>{const old=paintHistory.pop();if(old){appearance=old;applyPaint()}};
 $('paint-reset').onclick=()=>{const next=structuredClone(appearance);next.parts[selectedSlot]={...(PALETTES[byId.get(choices[selectedSlot])!.family]??PALETTES.warden)};commitPaint(next)};

 function render(){renderer.shadowMap.needsUpdate=true;renderer.render(scene,camera)}
 function tick(now:number){raf=0;if(!alive||document.hidden)return;if(playing&&current){time+=last?Math.min(.04,(now-last)/1000):0;last=now;const kit=KITS[byId.get(choices.weapon)!.weapon as WeaponKind],def=kit?.actions.find(a=>a.id===($('move-select') as HTMLSelectElement).value);current.articulate(time*.22,def?{path:def.path,phase:(time%2.8)/2.8}:undefined);banner.pose(time,reduced.matches);render();raf=requestAnimationFrame(tick)}else render()}
 const banner=createBanner();scene.add(banner.garage);banner.visible(false);let hasBanner=false,cropImage:ImageBitmap|null=null,bannerGeneration=0;
 const request=()=>{if(alive&&!document.hidden&&!raf)raf=requestAnimationFrame(tick)};
 function fit(){if(!current)return;const box=new T.Box3();current.model.updateMatrixWorld(true);current.model.traverse(o=>{if((o as T.Mesh).isMesh&&visible(o)){const mesh=o as T.Mesh;mesh.geometry.computeBoundingBox();box.union(mesh.geometry.boundingBox!.clone().applyMatrix4(mesh.matrixWorld))}});if(hasBanner&&appearance.banner&&!isolated)box.union(new T.Box3().setFromObject(banner.garage));if(box.isEmpty())return;
  const center=box.getCenter(new T.Vector3()),dir=(angle==='front'?new T.Vector3(0,.10,1):angle==='side'?new T.Vector3(-1,.12,0):angle==='back'?new T.Vector3(0,.12,-1):new T.Vector3(-.65,.23,1)).normalize(),right=new T.Vector3().crossVectors(new T.Vector3(0,1,0),dir).normalize(),up=new T.Vector3().crossVectors(dir,right).normalize(),tan=Math.tan(T.MathUtils.degToRad(camera.fov/2));let distance=1;
  for(const x of [box.min.x,box.max.x])for(const y of [box.min.y,box.max.y])for(const z of [box.min.z,box.max.z]){const p=new T.Vector3(x,y,z).sub(center),d=p.dot(dir);distance=Math.max(distance,d+Math.abs(p.dot(right))/(tan*camera.aspect),d+Math.abs(p.dot(up))/tan)}
  // Reserve space for the name and inspection controls above and below the model.
  controls.target.copy(center);camera.position.copy(center).addScaledVector(dir,distance*(isolated?1.22:1.27));camera.lookAt(center);controls.update();request();
 }
 function visible(o:T.Object3D):boolean{for(let n:T.Object3D|null=o;n;n=n.parent)if(!n.visible)return false;return true}
 function show(){if(!current)return;current.model.traverse(o=>o.visible=true);if(isolated){const roots=current.installed[selectedSlot]??[],allowed=new Set<T.Object3D>();
   for(const root of roots)root.traverse(o=>allowed.add(o));
   if(selectedSlot==='torso')for(const s of SLOTS)if(s!=='torso')for(const root of current.installed[s]??[])root.traverse(o=>allowed.delete(o));
   current.model.traverse(o=>{if((o as T.Mesh).isMesh)o.visible=allowed.has(o)});
  }floor.visible=!isolated;banner.visible(appearance.banner&&hasBanner&&!isolated);fit();
 }
 function ui(){paintUI();const focused=(document.activeElement as HTMLElement)?.dataset.part,scroll=document.querySelector('.parts-cabinet')!.scrollTop;const e=byId.get(choices[selectedSlot])!,allSame=SLOTS.filter(s=>s!=='weapon').every(s=>choices[s]===choices.torso);$('build-name').textContent=allSame?byId.get(choices.torso)!.name:'Your mixed build';$('build-note').textContent=isolated?LABEL[selectedSlot]+' · drag to inspect every side':allSame?byId.get(choices.torso)!.description:'Each part keeps its own shape. The body sets the attachment points.';
  const kit=byId.get(choices.weapon)!,profile=KITS[kit.weapon as WeaponKind],moves=$('move-select') as HTMLSelectElement,previous=moves.value;moves.replaceChildren(new Option('Ready grip','ready'));for(const action of profile?.actions??[])moves.add(new Option(action.name,action.id));if(Array.from(moves.options).some(o=>o.value===previous))moves.value=previous;
  if(kit.id.startsWith('kit1.')){const build=build8(choices,byId,appearance);renderBuildStats($('live-build-stats'),build);$('build-stats').textContent='The visible robot stats use the same item values as practice combat. Weapon speed includes preparation, contact and recovery for the first move.';}else {$('build-stats').textContent='Earlier equipment preview. Choose a new weapon kit to see version 8 practice stats.';$('live-build-stats').replaceChildren();const note=document.createElement('p');note.textContent='Choose a practice weapon kit to see your robot totals. Your saved parts stay fitted.';const button=document.createElement('button');button.textContent='Choose weapon';button.onclick=()=>{selectedSlot='weapon';ui();document.querySelector('[data-slot=weapon]')?.scrollIntoView({block:'nearest'})};$('live-build-stats').append(note,button)};
  $('weapon-label').textContent=kit.id.startsWith('kit1.')?kit.name+(kit.hands===2?' · Two hands':kit.offhand?' · Shield':''): kit.weapon==='hammer'?'Two-handed hammer':kit.weapon==='greatsword'?'Two-handed greatsword':kit.weapon==='rifle'?'Rifle · two-handed support':kit.weapon==='spear'?'Spear and shield':kit.offhand?'Sword and shield':'One-handed sword';
  $('selected-name').textContent=LABEL[selectedSlot]+' · '+e.name;$('selected-description').textContent=e.approval==='approved master'?'From the approved Tier 3 model.':e.description;
  const familySelect=$('family-select') as HTMLSelectElement;familySelect.replaceChildren(...[...new Set(entries.filter(e=>e.style===style).map(e=>e.family))].map(f=>{const o=document.createElement('option');o.value=f;o.textContent=f[0].toUpperCase()+f.slice(1);return o}));familySelect.value=family;
  $('family-pictures').replaceChildren(...entries.filter(e=>e.style===style&&e.tier===tier).map(e=>{const b=document.createElement('button');b.setAttribute('aria-pressed',String(e.family===family));const img=document.createElement('img');img.src=e.tier===3?`/assets/catalogue-2/painted/${e.family}.png`:`${e.thumbnailRoot}/${e.id}.whole.png`;img.alt='';img.loading='lazy';const name=document.createElement('span');name.textContent=e.family[0].toUpperCase()+e.family.slice(1);b.append(img,name);b.onclick=()=>{family=e.family;ui()};return b}));
  document.querySelectorAll<HTMLButtonElement>('[data-slot]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.slot===selectedSlot)));document.querySelectorAll<HTMLButtonElement>('[data-style]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.style===style)));document.querySelectorAll<HTMLButtonElement>('[data-tier]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.tier)===tier)));
  $('isolate').setAttribute('aria-pressed',String(isolated));$('isolate').textContent=isolated?'Back to robot':'View this part';
  $('installed-list').replaceChildren(...SLOTS.map(s=>{const li=document.createElement('li');li.textContent=LABEL[s]+': '+byId.get(choices[s])!.name;return li}));
  comparePart(e);
  const shelf=$('parts-shelf');shelf.replaceChildren(...(selectedSlot==='weapon'?kits.filter(e=>e.tier===tier):entries.filter(e=>e.style===style)).map(e=>{const button=document.createElement('button');button.className='part-tile';button.setAttribute('aria-pressed',String(e.id===choices[selectedSlot]));button.setAttribute('aria-label',`Choose ${e.name} ${LABEL[selectedSlot]}`);button.dataset.part=e.id;
   if(e.id.startsWith('kit1.')?kitManifest.thumbnails:manifest.thumbnails){const img=document.createElement('img');img.src=`${e.thumbnailRoot}/${e.id}.${selectedSlot}.png`;img.alt='';img.loading='lazy';button.append(img)}
   const title=document.createElement('strong');title.textContent=e.name;const note=document.createElement('small');note.textContent=`T${e.tier} · ${e.style==='tank'?'Tank':e.style==='speed'?'Speed':'Ranged'}${selectedSlot==='weapon'?' · '+e.weapon+(e.hands===2?' · Two hands':e.offhand?' + shield':''):''}`;button.append(title,note);button.onmouseenter=()=>comparePart(e);button.onfocus=()=>comparePart(e);button.onclick=()=>void change(selectedSlot,e.id);return button}));
  if(focused)shelf.querySelector<HTMLButtonElement>(`[data-part="${focused}"]`)?.focus({preventScroll:true});document.querySelector('.parts-cabinet')!.scrollTop=scroll;
 }
 function comparePart(entry:Entry){let currentBuild=null,projected=null;try{currentBuild=build8(choices,byId,appearance);projected=build8({...choices,[selectedSlot]:entry.id},byId,appearance)}catch{}renderPartStats($('part-stat-panel'),entry,selectedSlot,currentBuild,projected,entry.id===choices[selectedSlot])}
 function disposeModel(model:T.Object3D){const geometries=new Set<T.BufferGeometry>(),materials=new Set<T.Material>(),textures=new Set<T.Texture>();model.traverse(o=>{const m=o as T.Mesh;if(m.isMesh){geometries.add(m.geometry);for(const mat of Array.isArray(m.material)?m.material:[m.material]){materials.add(mat);Object.values(mat).forEach(t=>{if(t?.isTexture)textures.add(t)})}}});geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());textures.forEach(t=>t.dispose())}
 async function ensure(ids:string[]){for(const id of new Set(ids)){if(library.has(id))continue;if(!pending.has(id))pending.set(id,(async()=>{const gltf=await loader.loadAsync(byId.get(id)!.url);if(!alive){disposeModel(gltf.scene);return}gltf.scene.userData.weaponKind=byId.get(id)!.weapon;gltf.scene.userData.weaponHands=byId.get(id)!.hands;prepareLibrary(gltf.scene);gltf.scene.traverse(o=>{const m=o as T.Mesh;if(m.isMesh){m.castShadow=true;m.receiveShadow=true;for(const mat of Array.isArray(m.material)?m.material:[m.material])if((mat as T.MeshStandardMaterial).isMeshStandardMaterial)(mat as T.MeshStandardMaterial).envMapIntensity=.68}});library.set(id,gltf.scene)})().finally(()=>pending.delete(id)));await pending.get(id)}}
 async function rebuild(next:Choices){const token=++generation;desiredChoices={...next};ready=false;playing=false;last=0;loading.textContent='Fitting your parts…';loading.classList.remove('empty');
  try{await ensure(SLOTS.map(s=>next[s]));if(token!==generation||!alive)return;const replacement=assemble(next,library);if(current){painter?.dispose();scene.remove(current.model)}current=replacement;painter=paintAssembly(current.model,current.installed);painter.apply(appearance);banner.attach(current.model);banner.pose(0,true);choices={...next};scene.add(current.model);applyPaint();ui();show();await renderer.compileAsync(scene,camera);if(token!==generation||!alive)return;ready=true;loading.classList.add('empty');$('joint-play').setAttribute('aria-pressed','false');
   try{localStorage.setItem(STORE,JSON.stringify({version:1,choices}))}catch{$('parts-save').textContent='Art preview · this browser could not save your choices.'}
   // Only keep libraries backing the current seven choices. Replaced assets are
   // disposed after the new clone is installed, never while it uses their data.
   const used=new Set([...Object.values(choices),'__support']);for(const [id,m]of library)if(!used.has(id)){disposeModel(m);library.delete(id)}request();
  }catch(error){if(token!==generation)return;desiredChoices={...choices};loading.textContent='These parts could not load. Your previous build is kept. Try the design again.';console.error(error)}
 }
 async function change(slot:Slot,id:string){if(!SLOTS.includes(slot)||!byId.get(id)?.slots.includes(slot))throw Error('Unknown part');await rebuild({...desiredChoices,[slot]:id})}
 async function preset(id:string){if(!byId.has(id))throw Error('Unknown design');const e=byId.get(id)!;style=e.style;tier=e.tier;family=e.family;appearance={...defaultAppearance(family),bannerId:appearance.bannerId};const next=Object.fromEntries(SLOTS.map(s=>[s,id])) as Choices;const recommended:Record<string,string>={warden:'hammer',revenant:'greatsword',harrow:'axe',duelist:'sword_shield',legion:'spear_shield',hunter:'dual_blades',tracker:'rifle',sentinel:'rotary',specter:'precision_rifle'};next.weapon=`kit1.${recommended[e.family]}.t${e.tier}`;await rebuild(next)}
 document.querySelectorAll<HTMLButtonElement>('[data-slot]').forEach(b=>b.onclick=()=>{selectedSlot=b.dataset.slot as Slot;ui();show()});document.querySelectorAll<HTMLButtonElement>('[data-style]').forEach(b=>b.onclick=()=>{style=b.dataset.style as Entry['style'];family=entries.find(e=>e.style===style)!.family;ui()});document.querySelectorAll<HTMLButtonElement>('[data-tier]').forEach(b=>b.onclick=()=>{tier=Number(b.dataset.tier);ui()});$('apply-set').onclick=()=>void preset(entries.find(e=>e.style===style&&e.tier===tier&&e.family===family)!.id);
 ($('family-select') as HTMLSelectElement).onchange=e=>{family=(e.target as HTMLSelectElement).value};

 const cropDialog=$('banner-dialog') as HTMLDialogElement;
 function previewCrop(){if(!cropImage)return;const c=cropBanner(cropImage,Number(($('banner-zoom') as HTMLInputElement).value),Number(($('banner-x') as HTMLInputElement).value),Number(($('banner-y') as HTMLInputElement).value));const p=$('banner-crop') as HTMLCanvasElement;p.getContext('2d')!.drawImage(c,0,0,p.width,p.height);return c}
 for(const id of ['banner-zoom','banner-x','banner-y'])$(id).oninput=previewCrop;
 ($('banner-file') as HTMLInputElement).onchange=async e=>{const input=e.target as HTMLInputElement,file=input.files?.[0],token=++bannerGeneration;if(!file)return;try{const next=await decodeBanner(file);if(token!==bannerGeneration||!alive){next.close();return}cropImage?.close();cropImage=next;($('banner-zoom') as HTMLInputElement).value='1';($('banner-x') as HTMLInputElement).value='.5';($('banner-y') as HTMLInputElement).value='.5';$('banner-crop-status').textContent='';previewCrop();cropDialog.showModal()}catch(error){$('banner-status').textContent=(error as Error).message}input.value=''};
 $('banner-cancel').onclick=()=>cropDialog.close();cropDialog.addEventListener('close',()=>{cropImage?.close();cropImage=null;($('banner-file') as HTMLInputElement).focus()});
 $('banner-save').onclick=async()=>{const canvas=previewCrop();if(!canvas)return;const button=$('banner-save') as HTMLButtonElement;button.disabled=true;try{const blob=await bannerCanvasBlob(canvas);const id=await saveBanner(blob);if(!alive)return;appearance.bannerId=id!;banner.setCanvas(canvas);hasBanner=true;appearance.banner=true;applyPaint();show();$('banner-status').textContent='Your banner is saved in this browser.';cropDialog.close()}catch(error){$('banner-crop-status').textContent='Could not save. Your previous banner is kept.'}finally{button.disabled=false}};
 $('banner-remove').onclick=async()=>{try{await saveBanner(null);await banner.load(null);hasBanner=false;delete appearance.bannerId;applyPaint();show();$('banner-status').textContent='Image removed.'}catch{$('banner-status').textContent='Could not remove the saved image. Try again.'}};
 ($('banner-visible') as HTMLInputElement).onchange=e=>{appearance.banner=(e.target as HTMLInputElement).checked;applyPaint();show()};
 try{const saved=await readBanner(appearance.bannerId);if(saved){await banner.load(saved);hasBanner=true}else if(appearance.bannerId){await banner.load(null);hasBanner=true;$('banner-status').textContent='This local image is missing. Showing a neutral emblem.'}}catch{$('banner-status').textContent='Your saved banner could not load. Choose the image again.'}
 ($('banner-visible') as HTMLInputElement).checked=appearance.banner;
 $('move-select').onchange=()=>{playing=false;time=0;const kit=KITS[byId.get(choices.weapon)!.weapon as WeaponKind],def=kit?.actions.find(a=>a.id===($('move-select') as HTMLSelectElement).value);$('move-note').textContent=def?.requires==='parry'?'Requires a successful weapon interception in a fight.':def?.requires==='opening'?'Follows a completed attack when the weapon is ready to return.':'';current?.rest();request()};$('move-preview').onclick=()=>{if(!ready)return;const kit=KITS[byId.get(choices.weapon)!.weapon as WeaponKind],def=kit?.actions.find(a=>a.id===($('move-select') as HTMLSelectElement).value);if(reduced.matches){current?.articulate(0,def?{path:def.path,phase:.48}:undefined);render();return}playing=!playing;time=0;last=0;request()};
 $('isolate').onclick=()=>{isolated=!isolated;playing=false;current?.rest();ui();show()};$('joint-play').onclick=()=>{if(!ready)return;if(reduced.matches){current?.articulate(.25);render();return}playing=!playing;last=0;$('joint-play').setAttribute('aria-pressed',String(playing));if(!playing)current?.rest();request()};$('front').onclick=()=>{angle='front';fit()};$('angle').onclick=()=>{angle='three-quarter';fit()};$('side').onclick=()=>{angle='side';fit()};$('back').onclick=()=>{angle='back';fit()};
 controls.addEventListener('change',request);const observer=new ResizeObserver(()=>{const rect=canvas.parentElement!.getBoundingClientRect();renderer.setSize(rect.width,rect.height,false);camera.aspect=rect.width/rect.height;camera.updateProjectionMatrix();fit()});observer.observe(canvas.parentElement!);
 canvas.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();camera.position.sub(controls.target).applyAxisAngle(new T.Vector3(0,1,0),e.key==='ArrowLeft'?-.15:.15).add(controls.target);controls.update();request()}if(e.key==='Home'){e.preventDefault();fit()}});
 const hidden=()=>{if(document.hidden){cancelAnimationFrame(raf);raf=0;last=0}else request()};document.addEventListener('visibilitychange',hidden);
 function dispose(){if(!alive)return;alive=false;generation++;cancelAnimationFrame(raf);observer.disconnect();controls.dispose();painter?.dispose();banner.dispose();cropImage?.close();library.forEach(disposeModel);library.clear();floor.geometry.dispose();(floor.material as T.Material).dispose();environment.dispose();key.shadow.map?.dispose();renderer.dispose();document.removeEventListener('visibilitychange',hidden)}window.addEventListener('pagehide',dispose,{once:true});
 (window as any).partsStudio={get ready(){return ready},entries,kits,preset,change,get appearance(){return structuredClone(appearance)},paint:(next:Appearance)=>{const value=parseAppearance(next);if(!value)throw Error('Invalid paint');commitPaint(value)},choose:async(next:Choices)=>{if(!SLOTS.every(s=>byId.get(next[s])?.slots.includes(s)))throw Error('Unknown part');await rebuild(next)},selectSlot:(slot:Slot)=>{selectedSlot=slot;ui();show()},isolate:(value:boolean)=>{isolated=value;ui();show()},setView:(v:string)=>{angle=v;fit()},action:(id:string,phase:number)=>{const def=KITS[byId.get(choices.weapon)!.weapon as WeaponKind]?.actions.find(a=>a.id===id);if(!def)throw Error('Unknown action');current?.articulate(0,{path:def.path,phase:T.MathUtils.clamp(phase,0,1)});render()},articulate:(t:number)=>{current?.articulate(t);render()},inspect:()=>({...current?.inspect(),paint:painter?.inspect(),banner:{available:hasBanner,visible:banner.standard.visible},memory:renderer.info.memory,render:renderer.info.render,loaded:library.size,isolated,selectedSlot,ready}),capture:(size=320)=>{const old=renderer.getSize(new T.Vector2()),ratio=renderer.getPixelRatio();renderer.setPixelRatio(1);renderer.setSize(size,size,false);camera.aspect=1;camera.updateProjectionMatrix();fit();render();const image=canvas.toDataURL('image/png');renderer.setPixelRatio(ratio);renderer.setSize(old.x,old.y,false);camera.aspect=old.x/old.y;camera.updateProjectionMatrix();fit();return image},render,dispose};
 const support=(await loader.loadAsync('/assets/warden-support-hand.glb')).scene;support.traverse(o=>{if((o as T.Mesh).isMesh){(o as T.Mesh).castShadow=true;(o as T.Mesh).receiveShadow=true}});library.set('__support',support);
 await rebuild(choices);
}
