import * as T from 'three';
import {aggregateEquipment,ITEM_STATS_VERSION,type ItemStats8} from './equipment-stats';
import type {EquipmentMotion} from './equipment-pose';
import {KITS,BACKUP_PUNCH,RULES_VERSION,MOTION_VERSION,type WeaponKind,type ActionDef} from './weapon-actions';
import {assemble,solveTwoLink,setWorldQ,type Choices,type Entry,type Slot,SLOTS} from './parts-assembly';
import type {Appearance} from './paint';
import {installSpecialEquipment} from './special-equipment';
import {AUXILIARY_ASSET_HASHES,PREVIEW_VERSIONS} from './asset-versions';
export const STEP=1/60;
const V=(x=0,y=0,z=0)=>new T.Vector3(x,y,z),clamp=T.MathUtils.clamp;
export type Side=0|1;export type DefencePolicy='early'|'balanced'|'last_stand';
export type Build8={version:8;choices:Choices;appearance:Appearance;style:'tank'|'speed'|'ranged';tier:number;gp:number;weapon:WeaponKind;name:string;hashes:Record<string,string>;itemStatsVersion:string;itemStats:Record<Slot,ItemStats8>;stats:{body:number;speed:number;turn:number;plating:number;power:number;attackSpeed:number;precision:number;guardScale:number;backupPower:number;durability:Record<Slot,number>}};
export function build8(choices:Choices,entries:Map<string,Entry>,appearance:Appearance):Build8{
 for(const slot of SLOTS)if(!entries.get(choices[slot])?.slots.includes(slot))throw Error('Invalid '+slot);
 const body=entries.get(choices.torso)!,weapon=entries.get(choices.weapon)!;if(!KITS[weapon.weapon as WeaponKind])throw Error('Choose a new weapon kit for practice.');
 const equipment=aggregateEquipment(choices,entries);
 return {version:8,choices:{...choices},appearance:structuredClone(appearance),style:body.style,tier:body.tier,gp:equipment.gp,weapon:weapon.weapon as WeaponKind,name:body.name,hashes:Object.fromEntries(SLOTS.map(s=>[choices[s],entries.get(choices[s])!.sha256])),itemStatsVersion:ITEM_STATS_VERSION,itemStats:equipment.items,stats:equipment.stats};
}
export type Footwork='approach'|'circle'|'brace'|'backstep'|'entry'|'evade'|'escape'|'punish';
type Proxy={node:T.Object3D;box:T.Box3;slot:Slot;surfaces?:{source:T.Mesh;collision:T.Mesh}[];shield?:boolean};
type RunningAction={def:ActionDef;start:number;elapsed:number;prepare:number;active:number;recover:number;id:number;hits:Set<string>;shots:number;mount:'L'|'R';lockYaw?:number;aimPoint?:number[]};
export type Event8={id:number;tick:number;kind:'movement'|'prepare'|'shot'|'hit'|'block'|'parry'|'guard_break'|'miss'|'break'|'knockdown'|'special'|'special_end'|'defeat';who:Side;target?:Side;action?:string;amount?:number;slot?:Slot;node?:string;local?:number[];point?:number[];direction?:number[];reason?:string};
export type Actor8={build:Build8;assembly:ReturnType<typeof assemble>;aux:ReturnType<typeof installSpecialEquipment>|null;finishShots:number;finishPrevious:T.Vector3|null;finishHit:boolean;root:T.Group;proxies:Proxy[];shieldProxy:Proxy|null;feet:Record<'L'|'R',{offset:T.Vector3;plant:T.Vector3;from:T.Vector3;to:T.Vector3;start:number;end:number;q:T.Quaternion}>;position:T.Vector3;yaw:number;hp:Record<Slot,number>;initial:Record<Slot,number>;guard:number;heat:number;meter:number;damageCharge:number;specialUntil:number;shield:number;specialEnding:boolean;downUntil:number;immuneUntil:number;nextAction:number;nextDefence:number;guardUntil:number;guardRaised:number;parryUntil:number;openingUntil:number;riposteUntil:number;action:RunningAction|null;random:number;gait:number;coreHeight:number;velocity:T.Vector3;dodge:T.Vector3;dodgeUntil:number;previous:T.Vector3[];recoil:number;lastPath:string;missStreak:number;orbit:number;nextOrbit:number;nextBurst:number;knockback:T.Vector3;shots:number;dealt:number;reaction:number;reactionDirection:T.Vector3;footwork:Footwork;exchangeCount:number;lastAttackEnd:number;recoveryPose?:{path:ActionDef['path'];phase:number;mount:'L'|'R';start:number};deadAt:number|null};
export type Projectile8={id:number;who:Side;p:T.Vector3;velocity:T.Vector3;damage:number;impulse:number;life:number;action:string;ap:boolean;finisher?:boolean};
export type Snapshot8={version:8;rulesVersion:string;motionVersion:string;collisionVersion:string;presentationVersion:string;rigVersion:string;auxiliaryAssets:Record<string,string>;seed:number;builds:[Build8,Build8];inputs:{id:string;who:Side;tick:number}[];events:Event8[];winner:Side|null;tick:number;auto:[boolean,boolean];policies:[DefencePolicy,DefencePolicy]};
function random(a:Actor8){a.random=(Math.imul(a.random,1664525)+1013904223)>>>0;return a.random/4294967296}
function angle(a:number){return Math.atan2(Math.sin(a),Math.cos(a))}
function world(node:T.Object3D){return node.getWorldPosition(V())}
export function actionRate(a:Actor8,b:Actor8,tick:number){return a.build.stats.attackSpeed*(b.specialUntil>tick&&b.build.style==='ranged'?.7:1)*(a.specialUntil>tick&&a.build.style==='speed'?1.2:1)}
function bodyClearance(a:Actor8,b:Actor8){return (a.build.style==='tank'?1.32:1.06)+(b.build.style==='tank'?1.32:1.06)}
// A disabled kit gets only the surviving hand's fallback, never extra intact-kit damage.
export function needsBackup(a:Actor8){const kit=KITS[a.build.weapon];return (a.hp.armL>0||a.hp.armR>0)&&(kit.hands===2?(a.hp.armL<=0||a.hp.armR<=0):a.build.weapon!=='dual_blades'&&a.hp.armR<=0);}
function intersects(start:T.Vector3,end:T.Vector3,proxy:Proxy){const inverse=proxy.node.matrixWorld.clone().invert(),a=start.clone().applyMatrix4(inverse),b=end.clone().applyMatrix4(inverse),d=b.sub(a),length=d.length();if(length<1e-8)return null;const hit=new T.Ray(a,d.normalize()).intersectBox(proxy.box,V());if(!hit||hit.distanceTo(a)>length+.02)return null;if(proxy.surfaces){const direction=end.clone().sub(start),ray=new T.Raycaster(start,direction.clone().normalize(),0,direction.length()+.02);let nearest:T.Intersection|null=null;for(const surface of proxy.surfaces){surface.collision.matrixWorld.copy(surface.source.matrixWorld);const hits:T.Intersection[]=[];surface.collision.raycast(ray,hits);for(const candidate of hits)if(!nearest||candidate.distance<nearest.distance)nearest=candidate;}if(!nearest)return null;return {point:nearest.point.clone(),local:nearest.point.clone().applyMatrix4(inverse),proxy};}return {point:hit.clone().applyMatrix4(proxy.node.matrixWorld),local:hit,proxy}}
function proxies(model:T.Group){const list:Proxy[]=[];model.updateMatrixWorld(true);
 const nodes:[string,Slot][]=[['chest','torso'],['pelvis','torso'],['head','head'],...['L','R'].flatMap(s=>[[`shoulder${s}`,`arm${s}`],[`elbow${s}`,`arm${s}`],[`hand${s}`,`arm${s}`],[`hip${s}`,`leg${s}`],[`knee${s}`,`leg${s}`],[`ankle${s}`,`leg${s}`]] as [string,Slot][])];
 for(const [name,slot]of nodes){const node=model.getObjectByName(name)!,box=new T.Box3(),surfaces:NonNullable<Proxy['surfaces']>=[],inv=node.matrixWorld.clone().invert();
  const joints=new Set(nodes.map(n=>n[0]));function collect(child:T.Object3D){if(child!==node&&(joints.has(child.name)||['weaponR','weaponL','shieldL'].includes(child.name)))return;const mesh=child as T.Mesh;if(mesh.isMesh){surfaces.push({source:mesh,collision:new T.Mesh(mesh.geometry,mesh.material)});mesh.geometry.computeBoundingBox();box.union(mesh.geometry.boundingBox!.clone().applyMatrix4(inv.clone().multiply(mesh.matrixWorld)))}for(const c of child.children)collect(c)}collect(node);
  if(!box.isEmpty())list.push({node,box,slot,surfaces});
 }
 return list;
}
export class Practice8{
 tick=0;seed:number;actors:[Actor8,Actor8];events:Event8[]=[];inputs:Snapshot8['inputs']=[];projectiles:Projectile8[]=[];winner:Side|null=null;done=false;sequence=0;auto:[boolean,boolean]=[false,true];policies:[DefencePolicy,DefencePolicy]=['balanced','balanced'];replayCommands:Snapshot8['inputs']|null=null;pending:Snapshot8['inputs']=[];
 constructor(builds:[Build8,Build8],library:Map<string,T.Group>,seed:number){this.seed=seed>>>0;this.actors=builds.map((build,i)=>{
  const assembly=assemble(build.choices,library),aux=library.has('__special')?installSpecialEquipment(assembly.model,library.get('__special')!):null,root=new T.Group();root.add(assembly.model);const hp={...build.stats.durability};
  const shield=assembly.model.getObjectByName('shieldL'),shieldProxy:Proxy|null=shield?{node:shield,box:new T.Box3().setFromObject(shield).applyMatrix4(shield.matrixWorld.clone().invert()),slot:'armL',shield:true}:null;
  const feet=Object.fromEntries(['L','R'].map(side=>{const node=assembly.model.getObjectByName('ankle'+side)!,offset=world(node),plant=offset.clone().applyAxisAngle(V(0,1,0),i?-Math.PI/2:Math.PI/2).add(V(i?3.6:-3.6,0,i?.25:-.25));return [side,{offset,plant,from:plant.clone(),to:plant.clone(),start:0,end:0,q:node.getWorldQuaternion(new T.Quaternion())}]})) as Actor8['feet'];
  return {build,assembly,aux,finishShots:0,finishPrevious:null,finishHit:false,root,proxies:proxies(assembly.model),shieldProxy,feet,position:V(i?3.6:-3.6,0,i?.25:-.25),yaw:i?-Math.PI/2:Math.PI/2,hp,initial:{...hp},guard:KITS[build.weapon].guard*build.stats.guardScale,heat:0,meter:0,damageCharge:0,specialUntil:0,shield:0,specialEnding:false,downUntil:0,immuneUntil:0,nextAction:40,nextDefence:0,guardUntil:0,guardRaised:0,parryUntil:0,openingUntil:0,riposteUntil:0,action:null,random:(seed^(i?0x9e3779b9:0x85ebca6b))>>>0,gait:0,coreHeight:world(assembly.model.getObjectByName('chest')!).y,velocity:V(),dodge:V(),dodgeUntil:0,previous:[],recoil:0,lastPath:'',missStreak:0,orbit:i?-1:1,nextOrbit:90+(seed%80),nextBurst:100+(seed%35),knockback:V(),shots:0,dealt:0,reaction:0,reactionDirection:V(),footwork:'approach',exchangeCount:0,lastAttackEnd:-1000,deadAt:null} as Actor8;
 }) as [Actor8,Actor8];this.pose();}
 interrupt(a:Actor8){if(a.action){const action=a.action,age=action.elapsed,phase=age<action.prepare?.30*age/action.prepare:age<action.prepare+action.active?.30+.35*(age-action.prepare)/action.active:.65+.35*(age-action.prepare-action.active)/action.recover;a.recoveryPose={path:action.def.path,phase,mount:action.mount,start:this.tick};}a.action=null;a.previous=[];}
 emit(event:Omit<Event8,'id'|'tick'>){const e={...event,id:this.events.length+1,tick:this.tick};this.events.push(e);return e}
 special(who:Side,id:string){const a=this.actors[who];if(this.done||a.meter<100||a.specialUntil>this.tick||a.downUntil>this.tick||this.pending.some(i=>i.id===id||i.who===who)||this.inputs.some(i=>i.id===id))return false;this.pending.push({id,who,tick:this.tick+1});return true;}
 activate(who:Side,id:string){if(this.inputs.some(i=>i.id===id))return false;const a=this.actors[who];if(this.done||a.meter<100||a.specialUntil>this.tick||a.downUntil>this.tick)return false;
  a.meter=0;a.damageCharge=0;a.specialUntil=this.tick+300;a.shield=a.initial.torso*.35;a.specialEnding=false;a.finishShots=0;a.finishPrevious=null;a.finishHit=false;this.inputs.push({id,who,tick:this.tick});this.emit({kind:'special',who,reason:a.build.style});return true;
 }
 step(){if(this.done)return;this.tick++;
  for(const who of [0,1] as Side[]){const a=this.actors[who],b=this.actors[(1-who) as Side],kit=KITS[a.build.weapon];a.recoil*=.78;a.reaction*=.91;
   if(a.specialUntil<=this.tick){a.meter=Math.min(100,a.meter+5/60);if(a.specialUntil&&a.specialUntil===this.tick){a.specialEnding=false;this.emit({kind:'special_end',who});}}
   for(const command of (this.replayCommands??this.pending))if(command.who===who&&command.tick===this.tick)this.activate(who,command.id);const integrity=SLOTS.filter(s=>s!=='weapon').reduce((n,s)=>n+a.hp[s],0)/SLOTS.filter(s=>s!=='weapon').reduce((n,s)=>n+a.initial[s],0),policy=this.policies[who],useAuto=policy==='early'||policy==='balanced'&&(integrity<.85||!!b.action||a.position.distanceTo(b.position)<kit.range)||policy==='last_stand'&&(integrity<.5||a.hp.torso/a.initial.torso<.40);if(!this.replayCommands&&this.auto[who]&&a.meter>=100&&useAuto)this.activate(who,`auto-${who}-${this.tick}`);
   if(a.specialUntil>this.tick&&a.build.tier>=3&&!a.specialEnding&&a.specialUntil-this.tick<=44){a.specialEnding=true;this.interrupt(a);a.nextAction=a.specialUntil;if(a.build.style==='tank'&&a.shield>0){a.dodge.copy(b.position).sub(a.position).normalize().multiplyScalar(4);a.dodgeUntil=this.tick+26;} }
   a.heat=Math.max(0,a.heat-(a.action?.def.shots&&a.action.def.shots>1?.08:.23));
   if(a.guardUntil<this.tick&&(!a.action||a.action.elapsed>=a.action.prepare+a.action.active))a.guard=Math.min(kit.guard*a.build.stats.guardScale,a.guard+.18*a.build.stats.guardScale);
   if(a.action){const slow=b.specialUntil>this.tick&&b.build.style==='ranged'?.7:1,over=a.specialUntil>this.tick&&a.build.style==='speed'?1.2:1;a.action.elapsed+=actionRate(a,b,this.tick);const age=a.action.elapsed;if(age>=a.action.prepare+a.action.active+a.action.recover){if(!a.action.hits.size&&(!kit.projectile||a.action.def.path==='punch')){a.missStreak=Math.min(4,a.missStreak+1);}if(!a.action.hits.size&&(!kit.projectile||a.action.def.path==='punch'))this.emit({kind:'miss',who,action:a.action.def.id});a.openingUntil=this.tick+22;a.lastPath=a.action.def.path;a.action=null;a.lastAttackEnd=this.tick;const opponentRecovering=b.action&&b.action.elapsed>=b.action.prepare+b.action.active;const canPress=a.exchangeCount<3&&(opponentRecovering||a.riposteUntil>this.tick)&&a.position.distanceTo(b.position)<kit.range;a.nextAction=this.tick+Math.ceil((canPress?4:12+Math.floor(random(a)*12))/a.build.stats.attackSpeed);a.previous=[];}}
   if(kit.shield&&a.hp.armL>0&&a.guard>8&&a.action?.def.path==='thrust')a.guardUntil=Math.max(a.guardUntil,this.tick+2);if(a.action&&((kit.hands===2&&a.action.def.path!=='punch'&&(a.hp.armL<=0||a.hp.armR<=0))||(a.action.mount==='R'&&a.hp.armR<=0)||(a.action.mount==='L'&&a.hp.armL<=0)))this.interrupt(a);
  }
  // Decide against the same pre-movement/pre-choice opponent state, not the
  // result of whichever actor happened to be processed first.
  const decisionViews=this.actors.map(a=>({...a,position:a.position.clone(),action:a.action?{...a.action}:null}));
  for(const who of [0,1] as Side[])this.intent(who,decisionViews[1-who]);
  // Symmetric body separation, then ring projection. No style-based opponent selection.
  const [a,b]=this.actors,delta=b.position.clone().sub(a.position),d=delta.length(),spacing=bodyClearance(a,b);
  if(d<spacing&&d>.001){delta.multiplyScalar((spacing-d)/(2*d));a.position.sub(delta);b.position.add(delta)}
  for(const actor of this.actors){actor.position.addScaledVector(actor.knockback,STEP);actor.knockback.multiplyScalar(.86);const r=actor.position.length();if(r>7.1)actor.position.multiplyScalar(7.1/r)}
  for(const actor of this.actors){const raised=actor.guardUntil>this.tick&&actor.hp.armL>0&&actor.downUntil<=this.tick&&!needsBackup(actor);actor.guardRaised=clamp(actor.guardRaised+(raised?.2:-.15),0,1);}
  this.pending=this.pending.filter(i=>i.tick>this.tick);this.updateFeet();this.pose();
  // Same-tick contact priority alternates deterministically; neither screen side owns it.
  for(const who of ((this.seed+this.tick)%2?[1,0]:[0,1]) as Side[]){this.attack(who);this.finisher(who)}
  for(const p of [...this.projectiles]){const old=p.p.clone();p.p.addScaledVector(p.velocity,STEP);p.life--;const hit=this.trace((1-p.who) as Side,old,p.p);if(hit){this.damage(p.who,(1-p.who) as Side,p.damage,p.impulse,p.action,hit,p.velocity.clone().normalize(),p.ap);p.life=0;}if(p.life<=0||p.p.length()>30)this.projectiles.splice(this.projectiles.indexOf(p),1)}
  for(const who of [0,1] as Side[]){const a=this.actors[who],kit=KITS[a.build.weapon],disabled=kit.hands===2?(a.hp.armL<=0||a.hp.armR<=0):a.build.weapon==='dual_blades'?(a.hp.armL<=0&&a.hp.armR<=0):a.hp.armR<=0;
   if(a.hp.torso<=0||a.hp.head<=0||(a.hp.armL<=0&&a.hp.armR<=0)){a.deadAt=this.tick;this.emit({kind:'defeat',who,reason:a.hp.armL<=0&&a.hp.armR<=0?'both arms disabled':'core disabled'});this.done=true;this.winner=this.actors[(1-who) as Side].deadAt===this.tick?null:(1-who) as Side;}
  }
  if(this.tick>=7200&&!this.done){this.done=true;const values=this.actors.map(a=>a.hp.torso/a.initial.torso+a.hp.head/a.initial.head);this.winner=Math.abs(values[0]-values[1])<1e-9?null:values[0]>values[1]?0:1;}
 }
 intent(who:Side,rival?:Actor8){const a=this.actors[who],b=rival??this.actors[(1-who) as Side],originalKit=KITS[a.build.weapon],backup=needsBackup(a),kit=backup?{...originalKit,hands:1,shield:false,projectile:false,range:2.9,minimum:1.8,guard:0,actions:[BACKUP_PUNCH]}:originalKit.projectile?originalKit:{...originalKit,range:Math.max(originalKit.range,bodyClearance(a,b)+.15)},to=b.position.clone().sub(a.position),d=to.length(),dir=to.normalize(),slow=b.specialUntil>this.tick&&b.build.style==='ranged'?.7:1,over=a.specialUntil>this.tick&&a.build.style==='speed',speed=a.build.stats.speed*slow*(over?1.5:1)*(a.hp.legL<=0||a.hp.legR<=0?.4:1);
  const desired=Math.atan2(dir.x,dir.z),turn=a.build.stats.turn*slow*STEP;const aiming=kit.projectile&&a.action;if(a.action&&a.action.elapsed>=a.action.prepare-(kit.projectile?8:4)&&a.action.lockYaw===undefined){a.action.lockYaw=a.yaw;a.action.aimPoint=b.position.clone().add(V(0,b.coreHeight,0)).toArray();}if(a.action?.lockYaw!==undefined&&(!kit.projectile?a.action.elapsed<a.action.prepare+a.action.active:!['tracking','moving_shot'].includes(a.action.def.path)))a.yaw=a.action.lockYaw;else a.yaw+=clamp(angle(desired-a.yaw),-turn,turn);
  if(a.downUntil>this.tick){a.velocity.multiplyScalar(.75);a.position.addScaledVector(a.velocity,STEP);return;}
  const polearm=!backup&&['spear_shield','long_spear'].includes(a.build.weapon),side=a.orbit,tangent=V(dir.z,0,-dir.x),unarmed=!backup&&(kit.hands===2&&(a.hp.armL<=0||a.hp.armR<=0)||a.build.weapon!=='dual_blades'&&a.hp.armR<=0),goal=Math.max(!kit.projectile?bodyClearance(a,b)+.05:0,backup?2.2:unarmed?4:kit.projectile?kit.minimum+.9:polearm?3.4:({hammer:2.65,greatsword:2.95,axe:2.75,flail:2.85,sword_shield:2.25,dual_blades:2.32} as Partial<Record<WeaponKind,number>>)[a.build.weapon]??kit.range-.3);
  if(this.tick>=a.nextOrbit&&!a.action){a.orbit*=-1;a.nextOrbit=this.tick+90+Math.floor(random(a)*100);}
  const rivalRecovering=!!b.action&&b.action.elapsed>=b.action.prepare+b.action.active;
  const incoming=!!b.action&&b.action.elapsed<b.action.prepare+b.action.active;
  if(this.tick-a.lastAttackEnd>90||d>kit.range+1)a.exchangeCount=0;
  // Short periods of stillness make the next step readable; don't treadmill around a target.
  const circleWindow=(this.tick+Math.floor(a.random%97))%150<68;
  let forward=clamp((d-goal)*1.7,-1,1),lateral=circleWindow?(kit.projectile?.30:a.build.style==='speed'?.58:.22):0;
  a.footwork=d>goal+.35?'approach':d<goal-.25?'backstep':lateral?'circle':'brace';
  if(rivalRecovering&&!a.action&&d<kit.range+.35){a.footwork='punish';lateral*=.3;}

  if(a.action){const age=a.action.elapsed,prep=age<a.action.prepare,active=age>=a.action.prepare&&age<a.action.prepare+a.action.active,recover=age>=a.action.prepare+a.action.active;
   if(kit.projectile){forward=a.action.def.path==='moving_shot'?(d<goal?-.70:.15):a.action.def.path==='retreat_shot'&&prep?-.8:recover&&d<goal?-.6:0;lateral=a.action.def.path==='moving_shot'?.38:recover?.42:.04;}
   else{
    // Prepare with a measured step, plant at contact, then recover toward the next real opening.
    forward=prep?clamp((d-goal)*1.8,-.35,.65):active?clamp((d-goal)*1.3,0,.35):incoming?-.65:d<goal-.22?-.4:d>goal+.30?.35:0;
    lateral=active?0:prep?0:incoming?(a.build.style==='speed'?.75:.38):rivalRecovering?.10:.30;
    a.footwork=active||prep?'brace':incoming?'backstep':rivalRecovering?'punish':'circle';
   }
  }
  if(b.action&&this.tick>=a.nextDefence&&b.action.elapsed>b.action.prepare*.45&&b.action.elapsed<b.action.prepare+b.action.active&&d<(KITS[b.build.weapon].projectile?8:KITS[b.build.weapon].range+.55)&&!a.action&&a.dodgeUntil<=this.tick){
   if(kit.shield&&a.hp.armL>0&&a.guard>8){a.guardUntil=this.tick+Math.ceil((b.action.prepare+b.action.active-b.action.elapsed)/actionRate(b,a,this.tick));a.nextDefence=this.tick+48;}
   else if(!KITS[b.build.weapon].projectile&&kit.guard>20&&a.guard>16&&a.hp.armR>0&&(kit.hands!==2||a.hp.armL>0)&&random(a)<.40){a.parryUntil=this.tick+Math.ceil((b.action.prepare+b.action.active-b.action.elapsed)/actionRate(b,a,this.tick));a.nextDefence=this.tick+72;}
   else if(a.hp.legL>0&&a.hp.legR>0){a.dodge.copy(tangent).multiplyScalar(side*(over?4.9:3.5));a.dodge.addScaledVector(dir,kit.projectile?-1.6:-.4);a.dodgeUntil=this.tick+18;a.nextDefence=this.tick+(over?48:a.build.style==='speed'?66:94);a.footwork='evade';this.emit({kind:'movement',who,reason:'sidestep',point:a.position.toArray(),direction:a.dodge.clone().normalize().toArray()});}
  }
  // A committed step covers real ground; it does not grant invulnerability.
  // Firearms use the same bounded burst to regain space when crowded.
  if(!unarmed&&!a.action&&a.hp.legL>0&&a.hp.legR>0&&this.tick>=a.nextBurst&&a.dodgeUntil<=this.tick&&Math.abs(angle(desired-a.yaw))<.25){
   const escape=kit.projectile&&d<kit.minimum-.25,entry=!kit.projectile&&d>goal+.38&&d<kit.range+1.8;
   if(escape||entry){a.dodge.copy(dir).multiplyScalar(speed*(escape?-1.7:a.build.style==='speed'?2.2:1.9));a.dodge.addScaledVector(tangent,side*speed*(escape?.75:a.build.style==='speed'?.45:.10));a.dodgeUntil=this.tick+(a.build.style==='tank'?18:15);a.nextBurst=this.tick+(a.build.style==='speed'?110:150)+Math.floor(random(a)*25);a.footwork=escape?'escape':'entry';this.emit({kind:'movement',who,reason:escape?'escape':'entry',point:a.position.toArray(),direction:a.dodge.clone().normalize().toArray()});}
  }
  if(a.guardUntil>this.tick)forward*=.38;
  const movement=dir.clone().multiplyScalar(forward*speed).addScaledVector(tangent,side*lateral*speed);
  if(a.action&&!kit.projectile&&a.action.elapsed>=a.action.prepare&&a.action.elapsed<a.action.prepare+a.action.active){movement.set(Math.sin(a.yaw)*forward*speed,0,Math.cos(a.yaw)*forward*speed);}if(a.dodgeUntil>this.tick){movement.copy(a.dodge);a.footwork=a.dodge.dot(dir)<-speed*.6?'escape':a.dodge.dot(dir)>speed?'entry':'evade';}if(a.specialEnding&&a.specialUntil>this.tick&&a.build.style==='speed'&&a.hp.legL>0&&a.hp.legR>0){const rear=b.position.clone().add(V(-Math.sin(b.yaw)*1.9,0,-Math.cos(b.yaw)*1.9));movement.copy(rear.sub(a.position)).clampLength(0,speed*1.5);}
  if(a.position.length()>6.6){const out=a.position.clone().normalize();const radial=movement.dot(out);if(radial>0)movement.addScaledVector(out,-radial).addScaledVector(tangent,.7*side);}
  a.velocity.lerp(movement,a.dodgeUntil>this.tick?.34:.20);a.position.addScaledVector(a.velocity,STEP);a.gait+=a.velocity.length()*STEP;a.reaction=Math.max(0,a.reaction);
  if(!a.action&&a.dodgeUntil<=this.tick&&this.tick>=a.nextAction&&a.guardUntil<=this.tick&&a.parryUntil<=this.tick&&d<kit.range&&Math.abs(angle(desired-a.yaw))<.30&&a.heat<82){
   const legal=kit.actions.filter(x=>(!kit.projectile||d>=kit.minimum-.4||['moving_shot','retreat_shot'].includes(x.path)||a.build.weapon==='arm_cannon'&&x.path==='shot')&&(!polearm||(x.path==='butt'?d<2.75:d>2.65))&&(kit.hands!==2||a.hp.armL>0&&a.hp.armR>0)&&(a.hp.armR>0||(backup||a.build.weapon==='dual_blades')&&a.hp.armL>0)&&(x.path!=='combo'||a.hp.armL>0&&a.hp.armR>0)&&(x.requires!=='parry'||a.riposteUntil>this.tick)&&(x.requires!=='opening'||a.openingUntil>this.tick&&['cross','thrust','overhead'].includes(a.lastPath))&&(!(x.path==='shield')||a.hp.armL>0)&&(!(x.path==='supported')||a.hp.armL>0));
   const score=(x:ActionDef)=> (x.requires&&a.openingUntil>this.tick?4:0)+((polearm||a.missStreak<2)&&d<kit.minimum&&['butt','cross','shield'].includes(x.path)?3:0)+(b.action&&b.action.elapsed>b.action.prepare+b.action.active&&x.damage>28?2:0)+(kit.projectile&&a.velocity.length()>1&&['moving_shot','retreat_shot'].includes(x.path)?2:0)+(x.path!==a.lastPath?.6:0)+random(a)*1.5;
   const ranked=legal.map(def=>({def,score:score(def)})).sort((x,y)=>y.score-x.score),def=ranked[0]?.def;if(!def)return;const rate=slow*(over?1.2:1);
   a.exchangeCount++;a.action={def,start:this.tick,elapsed:0,prepare:def.prepare,active:def.active,recover:def.recover,id:++this.sequence,hits:new Set(),shots:0,mount:(backup||a.build.weapon==='dual_blades')&&a.hp.armR<=0?'L':'R'};a.previous=[];this.emit({kind:'prepare',who,action:def.id,reason:a.riposteUntil>this.tick?'parry counter':rivalRecovering?'punish recovery':a.exchangeCount>1?'follow-up':'opening attack'});
  }
 }
 pose(){for(const a of this.actors){a.root.position.set(0,0,0);a.root.quaternion.identity();a.root.updateMatrixWorld(true);const action=a.action,age=action? action.elapsed:0,phase=action?(age<action.prepare?.30*age/action.prepare:age<action.prepare+action.active?.30+.35*(age-action.prepare)/action.active:.65+.35*(age-action.prepare-action.active)/action.recover):0;
  const opponent=this.actors.find(b=>b!==a)!,target=(action?.aimPoint&&!['tracking','moving_shot'].includes(action.def.path)?V().fromArray(action.aimPoint):opponent.position.clone().add(V(0,opponent.coreHeight,0))).sub(a.position).applyAxisAngle(V(0,1,0),-a.yaw).toArray();
  const localVelocity=a.velocity.clone().applyAxisAngle(V(0,1,0),-a.yaw),reaction=a.reactionDirection.clone().applyAxisAngle(V(0,1,0),-a.yaw);
  const motion:EquipmentMotion=action?{path:action.def.path,phase,mount:action.mount,recoil:a.recoil,contactHeight:opponent.coreHeight,contactTarget:target}:a.recoveryPose&&this.tick-a.recoveryPose.start<12?{path:a.recoveryPose.path,phase:a.recoveryPose.phase+(1-a.recoveryPose.phase)*clamp((this.tick-a.recoveryPose.start)/12,0,1),mount:a.recoveryPose.mount}:a.parryUntil>this.tick?{path:'guard',phase:.5}:needsBackup(a)?{path:'punch',phase:0,mount:a.hp.armR>0?'R':'L'}:KITS[a.build.weapon].projectile?{path:'shot',phase:0,recoil:a.recoil}:{path:'ready' as const,phase:0};
  a.assembly.articulate(0,{...motion,travel:localVelocity.toArray(),gait:a.gait,burst:a.dodgeUntil>this.tick,overdrive:a.specialUntil>this.tick&&a.build.style==='speed',reaction:[reaction.x*a.reaction,reaction.z*a.reaction],brace:a.guardUntil>this.tick||a.parryUntil>this.tick,shieldGuard:a.hp.armL>0? a.guardRaised:0});
  const model=a.assembly.model;if(a.downUntil>this.tick)model.getObjectByName('pelvis')!.position.y-=.30;model.updateMatrixWorld(true);
  for(const side of ['L','R'] as const){const f=a.feet[side],progress=f.end>f.start?clamp((this.tick-f.start)/(f.end-f.start),0,1):1,target=f.from.clone().lerp(f.to,progress);target.y+=Math.sin(progress*Math.PI)*(a.build.style==='speed'?.24:.18);target.sub(a.position).applyAxisAngle(V(0,1,0),-a.yaw);solveTwoLink(model,'hip'+side,'knee'+side,'ankle'+side,target,V(side==='L'?1:-1,1,3));setWorldQ(model.getObjectByName('ankle'+side)!,f.q);}
  model.updateMatrixWorld(true);a.aux?.pose(a.build.style,a.specialEnding&&a.specialUntil>this.tick?1-(a.specialUntil-this.tick)/44:-1,[a.hp.armL>0,a.hp.armR>0],target);a.root.position.copy(a.position);a.root.rotation.y=a.yaw;a.root.updateMatrixWorld(true);
 }}
 updateFeet(){for(const a of this.actors){if(a.downUntil>this.tick)continue;for(const side of ['L','R'] as const){const f=a.feet[side],other=a.feet[side==='L'?'R':'L'];if(this.tick>=f.end)f.plant.copy(f.to);const desired=f.offset.clone().applyAxisAngle(V(0,1,0),a.yaw).add(a.position);if(this.tick>=f.end&&this.tick>=other.end&&desired.distanceTo(f.plant)>(a.build.style==='speed'?.38:.34)){f.from.copy(f.plant);f.to.copy(desired).addScaledVector(a.velocity,.15);f.start=this.tick;f.end=this.tick+(a.build.style==='speed'?11:16);}}}}
 trace(target:Side,start:T.Vector3,end:T.Vector3){const a=this.actors[target];let best:ReturnType<typeof intersects>=null;for(const proxy of [...a.proxies,...(a.shieldProxy&&a.guardUntil>this.tick&&a.hp.armL>0&&a.downUntil<=this.tick&&!needsBackup(a)?[a.shieldProxy]:[])]){if(a.hp[proxy.slot]<=0)continue;const hit=intersects(start,end,proxy);if(hit&&(!best||hit.point.distanceToSquared(start)<best.point.distanceToSquared(start)))best=hit}return best}
 fistPoints(a:Actor8,mount:'L'|'R'){
  const hand=a.assembly.model.getObjectByName('hand'+mount)!,p=world(hand),q=hand.getWorldQuaternion(new T.Quaternion());
  // Sample the actual hand's bounds; no extra invisible weapon extension.
  const points=[p],inverse=hand.matrixWorld.clone().invert(),box=new T.Box3();hand.traverse(o=>{const mesh=o as T.Mesh;if(!mesh.isMesh||mesh.name.toLowerCase().includes('weapon'))return;let weapon=false;for(let n:T.Object3D|null=mesh;n&&n!==hand;n=n.parent)if(n.name==='weaponR'||n.name==='weaponL')weapon=true;if(weapon)return;mesh.geometry.computeBoundingBox();box.union(mesh.geometry.boundingBox!.clone().applyMatrix4(inverse.clone().multiply(mesh.matrixWorld)));});
  if(!box.isEmpty())for(const x of [box.min.x,box.max.x])for(const y of [box.min.y,box.max.y])for(const z of [box.min.z,box.max.z])points.push(hand.localToWorld(V(x,y,z)));
  return points;
 }
 weaponPoints(a:Actor8,mount:'L'|'R'='R'){const model=a.assembly.model,tip=model.getObjectByName(mount==='L'?'leftWeaponTip':a.build.weapon==='hammer'?'hammerFace':'weaponTip'),grip=model.getObjectByName(mount==='L'?'handGripL':'gripR');if(!tip||!grip)return [];const end=world(tip),base=world(grip),points=[end];if(a.build.weapon==='flail'){const q=tip.getWorldQuaternion(new T.Quaternion());for(const offset of [V(.20,0,0),V(-.20,0,0),V(0,.20,0),V(0,-.20,0),V(0,0,.13),V(0,0,-.13)])points.push(end.clone().add(offset.applyQuaternion(q)))}else if(a.build.weapon==='hammer'){const q=tip.getWorldQuaternion(new T.Quaternion());for(const offset of [V(.13,0,0),V(-.13,0,0),V(0,0,.13),V(0,0,-.13)])points.push(end.clone().add(offset.applyQuaternion(q)))}else if(a.build.weapon==='axe'){const q=tip.getWorldQuaternion(new T.Quaternion());for(const offset of [V(0,0,.13),V(0,0,-.13)])points.push(end.clone().add(offset.applyQuaternion(q)))}else if(!['long_spear','spear_shield'].includes(a.build.weapon))for(const f of [.62,.80,.93])points.push(base.clone().lerp(end,f));return points}
 attack(who:Side){const a=this.actors[who],b=this.actors[(1-who) as Side],action=a.action,kit=KITS[a.build.weapon];if(!action||a.downUntil>this.tick||a.hp.torso<=0||a.hp.head<=0||a.hp[action.mount==='L'?'armL':'armR']<=0||kit.hands===2&&action.def.path!=='punch'&&(a.hp.armL<=0||a.hp.armR<=0))return;const age=action.elapsed,active=age>=action.prepare&&age<action.prepare+action.active;
  if(action.def.path==='punch'){
   if(a.hp[action.mount==='L'?'armL':'armR']<=0)return;
   const points=this.fistPoints(a,action.mount);
   if(active&&!action.hits.size&&a.previous.length===points.length)for(let i=0;i<points.length;i++){const hit=this.trace((1-who) as Side,a.previous[i],points[i]);if(hit){action.hits.add('fist');this.damage(who,(1-who) as Side,action.def.damage*a.build.stats.backupPower,action.def.impulse,action.def.id,hit,points[i].clone().sub(a.previous[i]).normalize(),false);break;}}
   a.previous=points;return;
  }
  if(kit.projectile&&active){const desiredShots=Math.min(action.def.shots,1+Math.floor((age-action.prepare)*action.def.shots/action.active));while(action.shots<desiredShots){action.shots++;const muzzle=world(a.assembly.model.getObjectByName('muzzle')!),barrel=world(a.assembly.model.getObjectByName('weaponAxis')!).sub(world(a.assembly.model.getObjectByName('gripR')!)).normalize(),spread=action.def.spread/a.build.stats.precision;
    const direction=barrel.clone().add(V((random(a)-.5)*spread,(random(a)-.5)*spread,0)).normalize();this.projectiles.push({id:++this.sequence,who,p:muzzle,velocity:direction.multiplyScalar(a.build.weapon==='arm_cannon'?22:32),damage:action.def.damage*a.build.stats.power/action.def.shots,impulse:action.def.impulse,life:60,action:action.def.id,ap:a.build.weapon==='precision_rifle'});a.recoil=1;a.shots++;a.heat+=action.def.heat/action.def.shots;this.emit({kind:'shot',who,action:action.def.id,point:muzzle.toArray(),direction:barrel.toArray()});}}
  if(kit.projectile)return;
  let mount=action.mount;if(action.def.path==='combo'&&age>action.prepare+action.active*.5)mount='L';if((mount==='L'?a.hp.armL:a.hp.armR)<=0)return;
  let pts=this.weaponPoints(a,mount);if(action.def.path==='shield'&&a.shieldProxy){const box=a.shieldProxy.box,center=box.getCenter(V());pts=[center,center.clone().add(V(.15,0,0)),center.clone().add(V(-.15,0,0))].map(p=>p.applyMatrix4(a.shieldProxy!.node.matrixWorld))}else if(action.def.path==='butt'&&a.build.weapon==='long_spear'){const butt=a.assembly.model.getObjectByName('weaponButt');pts=butt?[world(butt)]:pts;}const hitKey=action.def.path==='combo'?mount:'one';
  if(active&&!action.hits.has(hitKey)&&a.previous.length===pts.length&&b.parryUntil>this.tick&&b.hp.armR>0&&action.def.impulse<.60){
   const front=V(Math.sin(b.yaw),0,Math.cos(b.yaw)),toward=a.position.clone().sub(b.position).normalize(),cost=action.def.damage*a.build.stats.power+action.def.impulse*40;
   const defense=this.weaponPoints(b),contact=pts.find((point,i)=>defense.some(q=>new T.Line3(a.previous[i],point).closestPointToPoint(q,true,V()).distanceToSquared(q)<.12*.12));
   if(contact&&front.dot(toward)>.45&&b.guard>=cost){b.guard-=cost;b.parryUntil=0;b.riposteUntil=this.tick+36;this.interrupt(a);a.nextAction=this.tick+24;this.emit({kind:'parry',who:(1-who) as Side,target:who,action:action.def.id,amount:cost,point:contact.toArray()});return;}
  }
  if(active&&!action.hits.has(hitKey)&&a.previous.length===pts.length){for(let i=0;i<pts.length;i++){const hit=this.trace((1-who) as Side,a.previous[i],pts[i]);if(hit){action.hits.add(hitKey);this.damage(who,(1-who) as Side,action.def.damage*a.build.stats.power/(action.def.path==='combo'?2:1),action.def.impulse,action.def.id,hit,pts[i].clone().sub(a.previous[i]).normalize(),false);break;}}}
  a.previous=pts;

 }
 finisher(who:Side){const a=this.actors[who],target=(1-who) as Side,b=this.actors[target];if(!a.specialEnding||a.specialUntil<=this.tick||a.downUntil>this.tick||a.hp.torso<=0||a.hp.head<=0)return;const phase=1-(a.specialUntil-this.tick)/44;
  if(a.build.style==='tank'&&a.shield>0&&!a.finishHit&&a.hp.legL>0&&a.hp.legR>0&&a.position.distanceTo(b.position)<(a.build.style==='tank'?1.32:1.06)+(b.build.style==='tank'?1.32:1.06)+.08){a.finishHit=true;if(b.immuneUntil<=this.tick){b.downUntil=this.tick+72;b.immuneUntil=b.downUntil+120;this.interrupt(b);this.emit({kind:'knockdown',who,target,reason:'shield charge',point:a.position.clone().lerp(b.position,.5).add(V(0,2,0)).toArray()});}}
  if(a.build.style==='ranged'&&a.aux&&phase>=.28&&phase<.82){const desired=Math.min(8,Math.floor((phase-.28)/.54*8)+1);while(a.finishShots<desired){const shot=a.finishShots++,side=shot%2?'L':'R';if(a.hp[side==='L'?'armL':'armR']<=0)continue;const muzzle=a.aux.muzzle(side),dir=a.aux.direction(side);this.projectiles.push({id:++this.sequence,who,p:muzzle,velocity:dir.clone().multiplyScalar(32),damage:KITS.rifle.actions[0].damage*2*a.build.stats.power/8,impulse:.04,life:60,action:'special.pistol_burst',ap:false,finisher:true});a.shots++;a.recoil=1;this.emit({kind:'shot',who,action:'special.pistol_burst',point:muzzle.toArray(),direction:dir.toArray()});}}
  if(a.build.style==='speed'&&a.aux&&a.hp.armR>0){const tip=a.aux.bladeTip();if(phase>.35&&phase<.84&&!a.finishHit&&a.finishPrevious){const hit=this.trace(target,a.finishPrevious,tip);if(hit){a.finishHit=true;const rear=V(Math.sin(b.yaw),0,Math.cos(b.yaw)).dot(a.position.clone().sub(b.position).normalize())<-.45,limb=/^(arm|leg)/.test(hit.proxy.slot),weak=b.hp[hit.proxy.slot]<b.initial[hit.proxy.slot]*.25;const damage=rear&&limb&&weak?b.hp[hit.proxy.slot]/Math.max(.1,(1-b.build.stats.plating)*1.25):28*a.build.stats.power;this.damage(who,target,damage,.13,'special.flank',hit,tip.clone().sub(a.finishPrevious).normalize(),false);}}a.finishPrevious=tip;}
 }

 damage(who:Side,target:Side,amount:number,impulse:number,action:string,hit:NonNullable<ReturnType<typeof intersects>>,direction:T.Vector3,ap:boolean){const a=this.actors[who],b=this.actors[target],kit=KITS[b.build.weapon],delta=a.position.clone().sub(b.position).normalize(),front=V(Math.sin(b.yaw),0,Math.cos(b.yaw)),facing=front.dot(delta)>.45;
  const event={who,target,action,slot:hit.proxy.slot,node:hit.proxy.node.name,local:hit.local.toArray(),point:hit.point.toArray(),direction:direction.toArray()};
  if(hit.proxy.shield&&b.guardUntil>this.tick&&kit.shield&&b.hp.armL>0&&b.downUntil<=this.tick&&!needsBackup(b)&&facing){const cost=amount*.85+impulse*25;if(b.guard>=cost){b.guard-=cost;b.reaction=Math.max(b.reaction,.30);b.reactionDirection.copy(direction).setY(0).normalize();this.emit({...event,kind:'block',amount});return;}b.guard=0;b.guardUntil=0;b.downUntil=this.tick+18;b.immuneUntil=Math.max(b.immuneUntil,b.downUntil+120);this.emit({...event,kind:'guard_break'});}
  if(!KITS[a.build.weapon].projectile&&b.parryUntil>this.tick&&facing&&b.guard>=amount+impulse*40&&b.hp.armR>0&&impulse<.60){
   const their=this.weaponPoints(b),ours=this.weaponPoints(a);if(their.some(p=>ours.some(q=>p.distanceToSquared(q)<.34))){b.guard-=amount+impulse*40;b.riposteUntil=this.tick+36;b.parryUntil=0;this.interrupt(a);a.nextAction=this.tick+24;this.emit({...event,kind:'parry',amount});return;}}
  if(a.specialUntil>this.tick&&a.build.style==='speed')amount*=1.25;
  amount*=1-b.build.stats.plating*(ap?.5:1);
  if(b.specialUntil>this.tick&&b.build.style==='tank'&&b.shield>0){const absorbed=Math.min(b.shield,amount*.9);b.shield-=absorbed;amount-=absorbed;if(b.shield<=0){b.specialUntil=this.tick;this.emit({kind:'special_end',who:target,reason:'shield exhausted'})}}
  amount=Math.min(amount,b.hp[hit.proxy.slot]);b.hp[hit.proxy.slot]=Math.max(0,b.hp[hit.proxy.slot]-amount);a.dealt+=amount;a.missStreak=0;b.reaction=Math.min(1,amount/25);b.reactionDirection.copy(direction).setY(0).normalize();
  if(hit.proxy.slot==='torso'&&b.specialUntil<=this.tick){const earn=Math.min(40-b.damageCharge,amount/b.initial.torso*100);b.damageCharge+=earn;b.meter=Math.min(100,b.meter+earn)}
  b.knockback.addScaledVector(direction.clone().setY(0).normalize(),impulse*6);this.emit({...event,kind:'hit',amount,reason:b.action&&b.action.elapsed>=b.action.prepare+b.action.active?'caught recovery':b.action&&b.action.elapsed<b.action.prepare?'interrupted preparation':undefined});
  if(b.hp[hit.proxy.slot]<=0)this.emit({...event,kind:'break'});
  if(impulse>.65&&b.immuneUntil<=this.tick){b.downUntil=this.tick+72;b.immuneUntil=b.downUntil+120;this.interrupt(b);b.nextAction=b.downUntil+10;this.emit({...event,kind:'knockdown'});}
  else if(amount>b.initial.torso*.075&&b.action&&b.action.elapsed<b.action.prepare){this.interrupt(b);b.nextAction=this.tick+18;b.previous=[];}
 }
 snapshot():Snapshot8{return {version:8,rulesVersion:RULES_VERSION,motionVersion:MOTION_VERSION,collisionVersion:'mk8-swept-surfaces-1',presentationVersion:'mk8-personal-toys-'+PREVIEW_VERSIONS.presentation,rigVersion:'bible2-modular-1',auxiliaryAssets:{...AUXILIARY_ASSET_HASHES},auto:[...this.auto],policies:[...this.policies],seed:this.seed,builds:this.actors.map(a=>structuredClone(a.build)) as [Build8,Build8],inputs:this.inputs.map(i=>({...i})),events:this.events.map(e=>({...e})),winner:this.winner,tick:this.tick}}
}
