import type {Choices,Appearance} from '../workshop8/catalogue';
export const PIT_RULES='mk10-pit-3';
export const PIT_ASSETS='mk10-reactor-4';
export const HZ=60,BUFFER=6,EDGE=6600;
export type Style='tank'|'speed'|'ranged';
export type Side=0|1;
export type Action='left'|'right'|'up'|'down'|'light'|'heavy'|'special'|'guard'|'throw'|'super'|'enhance'|'escape'|'dash'|'finish'|'clear'|'skip';
export type Command={tick:number;sequence:number;side:Side;action:Action;down:boolean};
export type Difficulty='easy'|'normal'|'hard';
export type InputMove='light'|'heavy'|'low'|'launcher'|'advance'|'overhead'|'airLight'|'airHeavy'|'special'|'forwardSpecial'|'bodySpecial'|'throw'|'super';
export type Motion='jab'|'cross'|'low'|'uppercut'|'kick'|'overhead'|'airKick'|'airHeavy'|'weaponCross'|'weaponOverhead'|'weaponThrust'|'weaponShot'|'weaponButt'|'weaponShield'|'weaponFlail'|'weaponBlades'|'stomp'|'slide'|'pulse'|'throw'|'super';
export type Level='high'|'mid'|'low'|'overhead'|'throw';
export type Move={id:InputMove;name:string;motion:Motion;startup:number;active:number;recovery:number;damage:number;hitstun:number;blockstun:number;push:number;level:Level;reach:number;height:number;radius:number;launch:number;knockdown:boolean;travel:number;stepIn?:number;hitFrames?:number[];projectile?:{speed:number;life:number;count:number};cost:number;cancel:InputMove[];hitstop:number};
export type Spec={name:string;style:Style;weapon:string;gp:number;choices:Choices;appearance:Appearance;hp:number;power:number;plating:number;speed:number;handling:number;guard:number;precision:number;muzzle?:[number,number,number];superMuzzle?:[number,number,number];contacts?:Partial<Record<InputMove,[number,number][]>>;loaner?:boolean};
export type Attack={move:Move;frame:number;facing:1|-1;instance:number;hits:number[];strikes?:number[];enhanced:boolean;shots:number;stepScale?:number};
export type Fighter={spec:Spec;x:number;y:number;vx:number;vy:number;facing:1|-1;hp:number;guard:number;energy:number;wins:number;held:Set<Action>;attack:Attack|null;buffer:{move:InputMove;until:number;confirmOnly?:boolean}|null;stun:number;blockstun:number;down:number;dash:number;enhance:boolean;crouch:boolean;combo:number;comboDamage:number;comboOwner:Side|null;juggles:number;safe:number;lastHit:number;lastDirection:{direction:number;tick:number};throwHold:{by:Side;until:number;damage:number;instance:number}|null;reason:string;reasonUntil?:number;reaction:Level|'launch'|'land'|null;reactionUntil:number};
export type Projectile={id:number;owner:Side;instance:number;x:number;y:number;z:number;vx:number;vy:number;life:number;damage:number;move:Move;enhanced:boolean};
export type PitEvent={id:number;tick:number;kind:'hit'|'block'|'guardBreak'|'throw'|'tech'|'escape'|'shot'|'land'|'round'|'finish'|'super';who:Side;target?:Side;x:number;y:number;amount?:number;move?:string;combo?:number};
export type Phase='intro'|'ready'|'fight'|'roundEnd'|'finishPrompt'|'finisher'|'result';
export type Options={seed:number;difficulty:Difficulty;training:boolean;dummy:'idle'|'block'|'ai';unlimited:boolean};
export type Packet={rules:typeof PIT_RULES;assets:typeof PIT_ASSETS;fighters:[Spec,Spec];options:Options;commands:Command[];endTick:number;practiceOnly:true};
