import assert from "node:assert/strict";
import { createWorld, applyAction, cellsOf, validateLayout, stepWorld, WORLD_FIXED_DT } from "../src/app/chef/game/_engine/world";
import { buildGrid } from "../src/app/chef/game/_engine/path";
import { comfortOf } from "../src/app/chef/game/_engine/items";
import { SHELL } from "../src/app/chef/game/_engine/rooms";
import { sanitizeSave, serializeSave } from "../src/app/chef/game/_engine/save";
import { availableDishes } from "../src/app/chef/game/_engine/cookbook";

const w = createWorld("building-v7", SHELL, { playMoney: 10000 });
assert.equal(applyAction(w, SHELL, { type: "finish", surface: "floor", id: "sage" }), false);
assert.equal(applyAction(w, SHELL, { type: "edit", on: true }), true);
const before = w.layout.map((p) => ({ ...p }));
assert.equal(applyAction(w, SHELL, { type: "rotate", uid: w.layout.find((p) => p.itemId === "counter_basic")!.uid }), true);
const counter = w.layout.find((p) => p.itemId === "counter_basic")!;
assert.deepEqual(cellsOf(counter.itemId, counter.gx, counter.gy, counter.facing), [{ x: 5, y: 0 }, { x: 5, y: 1 }]);
const grid = buildGrid(SHELL.w, SHELL.h, w.layout);
assert.equal(grid.cells[1 * SHELL.w + 5], 1);
assert.equal(grid.cells[0 * SHELL.w + 6], 0);
for (let i = 0; i < 3; i++) assert.equal(applyAction(w, SHELL, { type: "rotate", uid: counter.uid }), true);
assert.deepEqual(w.layout.map((p) => ({ ...p })), before);
assert.equal(applyAction(w, SHELL, { type: "replaceLayout", layout: [...before, { itemId: "table_basic", gx: 8, gy: 6 }] }), false, "undo cannot mint furniture");
const chair = w.layout.find((p) => p.itemId === "chair_basic")!;
assert.equal(applyAction(w, SHELL, { type: "store", uid: chair.uid }), true);
assert.equal(applyAction(w, SHELL, { type: "replaceLayout", layout: before }), true);
assert.equal(w.inventory.chair_basic ?? 0, 0, "undo takes restored furniture out of storage");
assert.equal(validateLayout(SHELL, [...w.layout, { itemId: "partition_basic", gx: 4, gy: 7, facing: "se", uid: 999 }]), "Something is already there.");
assert.notEqual(validateLayout(SHELL, [{ itemId: "counter_basic", gx: 9, gy: 7, facing: "sw", uid: 1 }]), "");
assert.notEqual(validateLayout(SHELL, [{ itemId: "wallArt_basic", gx: 3, gy: 3, facing: "se", uid: 1 }]), "");
assert.equal(applyAction(w, SHELL, { type: "finish", surface: "floor", id: "sage", gx: 2, gy: 3 }), true);
assert.equal(applyAction(w, SHELL, { type: "finish", surface: "wall", id: "rose", side: "left", index: 2 }), true);
assert.equal(applyAction(w, SHELL, { type: "storefront", awning: "blue", sign: "Café Rosa" }), true);
assert.equal(applyAction(w, SHELL, { type: "finish", surface: "floor", id: "sage", gx: NaN, gy: 3 }), false);
const saved = sanitizeSave(serializeSave(w, "trattoria"));
assert.equal(saved.v, 8);
assert.deepEqual(saved.design, w.design);
const migrated = sanitizeSave({ ...saved, v: 6, market: "boner.com", layout: [{ itemId: "counter_basic", gx: 5, gy: 0, facing: "sw" }], pantry: { levels: { special: 3 } }, menu: { specialUnlocked: true, specialServes: 42 } });
assert.equal(migrated.layout[0].facing, "se", "legacy mirrored counters preserve occupied cells");
assert.equal(migrated.pantry.levels.boner_broth, 3);
assert.equal(migrated.pantry.levels.software_noodles, 1, "migration only maps the original market");
assert.equal(migrated.menu.serves.boner_broth, 42);
assert.ok(migrated.menu.selected.includes("boner_broth"));
assert.ok(comfortOf(Array.from({ length: 100 }, () => ({ itemId: "plant_basic" }))).total <= 4);
assert.ok(comfortOf([{ itemId: "plant_basic" }, { itemId: "rug_basic" }, { itemId: "wallArt_basic" }]).total > comfortOf([{ itemId: "plant_basic" }, { itemId: "plant_basic" }, { itemId: "plant_basic" }]).total);
applyAction(w, SHELL, { type: "edit", on: false });
stepWorld(w, SHELL);
assert.ok(availableDishes(w).some((dish) => dish.id === "software_noodles"));
assert.equal(applyAction(w, SHELL, { type: "selectMenu", keys: ["software_noodles"] }), true);
w.pantry.stock = { herb: 2, lemon: 1 };
assert.equal(applyAction(w, SHELL, { type: "upgradeDish", key: "software_noodles" }), true);
assert.equal(w.pantry.levels.software_noodles, 2);
assert.equal(w.pantry.levels.boner_broth, 1);
applyAction(w, SHELL, { type: "market", id: "boner.com" });
assert.ok(availableDishes(w).some((dish) => dish.id === "software_noodles"), "unlocked cookbook survives market changes");
assert.ok(!availableDishes(w).some((dish) => dish.id === "boner_broth"), "market selection alone grants no new recipe");
assert.ok(!sanitizeSave(serializeSave(w, "bistro")).menu.unlocked.includes("boner_broth"), "reloading cannot unlock the newly selected market");
for (let tick = 0; tick < 240 / WORLD_FIXED_DT; tick++) stepWorld(w, SHELL);
assert.ok(w.menu.dishes.find((dish) => dish.key === "software_noodles")!.serves > 0);
assert.ok(w.menu.dishes.find((dish) => dish.key === "margherita")!.serves > 0, "installed equipment serves all supported recipes without a menu activation step");
assert.deepEqual(w.menu.selected,w.operations.menu);
w.maintenance = { cleanliness: 40, equipment: 20, lastSettledAt: 1000 };
assert.equal(applyAction(w, SHELL, { type: "maintain", task: "repair" }), true);
assert.equal(w.maintenance.equipment, 40);
assert.deepEqual(sanitizeSave(serializeSave(w, "bistro")).maintenance, w.maintenance);
console.log("building/cookbook v8 checks PASS");
