import assert from 'node:assert/strict';
import {buildServiceLoadout,makeStation,makeTable} from '../src/lib/chef/diner/geometry';
import {createService,dispatchService,sanitizeService,servicePatienceMinimum,serviceRecipeSteps,stepService} from '../src/lib/chef/diner/service';
import {RECIPE_BY_ID,SERVICE_RULES,ingredientSupply} from '../src/lib/chef/diner/content';
import {recipeVessel,vesselSupplyStation} from '../src/lib/chef/diner/batch';
import type {CreateServiceOptions,ServiceAction,ServiceState,CustomerType} from '../src/lib/chef/diner/types';
let groups=0;function test(name:string,fn:()=>void){fn();groups++;console.log(`PASS ${name}`);}
/** These scenarios deliberately keep a spare plate rack for cross-vessel/old-save checks. */
function withPlateRack(menu:string[]){const layout=buildServiceLoadout(1,menu);if(!layout.stations.some(s=>s.kind==='plates'))layout.stations.push(makeStation('plates','plates',0,4,1,3));return layout;}
class Kitchen{
 s:ServiceState;
 constructor(options:CreateServiceOptions={}){const menu=options.menu??['classic_burger'];this.s=dispatchService(createService({...buildServiceLoadout(options.tier??1,menu),menu,customers:6,tables:[makeTable('table',3,5,1)],...options}),{type:'prepare'});assert.equal(this.s.phase,'preparing',this.s.notice);}
 send(a:ServiceAction){this.s=dispatchService(this.s,a);}
 until(f:()=>boolean,max=5000){let n=0;while(!f()&&n++<max&&['preparing','playing','closing'].includes(this.s.phase))stepService(this.s);assert(f(),this.s.notice);}
 touch(targetId:string,ingredientId?:string,recipeId?:string,seatId?:string){this.send({type:'interact',targetId,ingredientId,recipeId,seatId});this.until(()=>!this.s.chef.path.length);}
 ingredient(id:string,recipeId='classic_burger'){this.touch(ingredientSupply(id),id,recipeId);}
 burger(){this.ingredient('beef');this.touch('grill');this.until(()=>!!this.s.stations.find(st=>st.kind==='grill')!.slots[0].job?.ready);this.touch('grill');this.touch('prep');this.ingredient('bun');this.touch('prep');this.send({type:'hold',active:true});this.until(()=>!!this.s.stations.find(st=>st.kind==='prep')!.slots[0].job?.ready);this.send({type:'hold',active:false});this.touch('plates');this.touch('prep');assert.equal(this.s.chef.held?.kind,'dish');}
 clear(){const seat=this.s.tables[0].seats[0];this.touch('table',undefined,undefined,seat.id);}
 serve(){const guest=this.s.customers.find(c=>c.phase==='seated')!;assert(guest);this.touch(guest.tableId!,undefined,undefined,guest.seatId!);}
 wash(){this.touch('sink');this.send({type:'hold',active:true});this.until(()=>this.s.stations.find(st=>st.kind==='sink')!.slots.every(slot=>!slot.item));this.send({type:'hold',active:false});}
}
test('preparation is real cooking with no arrivals and preserves food when lunch opens',()=>{
 const k=new Kitchen();k.burger();stepService(k.s,2000);assert.equal(k.s.spawned,0);assert.equal(k.s.phase,'preparing');assert(k.s.chef.held?.cold);
 const id=k.s.chef.held!.id,plate=k.s.chef.held!.plateId;const restored=sanitizeService(k.s)!;assert(restored);assert.equal(restored.pausedPhase,'preparing');k.s=dispatchService(restored,{type:'resume'});k.send({type:'open'});assert.equal(k.s.chef.held?.id,id);assert.equal(k.s.chef.held?.plateId,plate);assert.equal(k.s.cleanPlates,1);k.until(()=>k.s.customers.some(c=>c.phase==='seated'));k.serve();assert.equal(k.s.served,1);
});
test('every customer type receives finite cooking and travel time even from a two-second configuration',()=>{
 for(const type of ['walk_in','office','kid','family','critic','influencer','regular'] as CustomerType[]){const k=new Kitchen({menu:['lemonade'],queuePatienceTicks:40,tablePatienceTicks:40,customerTypes:[type],specials:[],spices:['rush_hour'],tutorialFailure:true});k.send({type:'open'});k.until(()=>k.s.customers.some(c=>c.phase==='seated'));const c=k.s.customers[0],minimum=servicePatienceMinimum(k.s,c.recipeId);assert(c.maxPatience>=minimum.table);assert(c.queuePatience>=minimum.queue);assert(c.maxPatience/1.25>=45*20);stepService(k.s,40);assert.equal(k.s.strikes,0);stepService(k.s,4000);assert(k.s.strikes>0,'patience must still expire');}
});
test('guests sit before dirty dishes are cleared; serving waits for cleanup and old wash preserves their meal',()=>{
 const k=new Kitchen({arrivalTicks:100,customers:3,queuePatienceTicks:12000,tablePatienceTicks:12000});k.burger();k.send({type:'open'});k.until(()=>k.s.customers[0]?.phase==='seated');k.until(()=>k.s.customers[1]?.phase==='queue');stepService(k.s,300);assert(k.s.customers[1].patience<k.s.customers[1].queuePatience);k.serve();k.until(()=>k.s.customers[1].phase==='seated');
 const old=k.s.customers[0],oldMeal=old.mealId,newGuest=k.s.customers[1],newMeal=newGuest.mealId,oldPlate=k.s.tables[0].seats[0].item!.id;assert.equal(k.s.tables[0].seats[0].status,'occupied');assert.equal(k.s.tables[0].seats[0].item?.kind,'dirty');assert.equal(k.s.tables[0].seats[0].item?.meal?.mealId,oldMeal);assert(newGuest.patience>newGuest.maxPatience-5);assert(sanitizeService(k.s));
 k.burger();const nextPlate=k.s.chef.held!.plateId;k.serve();assert.equal(k.s.served,1);assert.equal(k.s.chef.held?.plateId,nextPlate);assert.match(k.s.notice,/clear.*old dish/i);assert.equal(k.s.tables[0].seats[0].item?.id,oldPlate);k.touch('prep');k.clear();assert.equal(k.s.chef.held?.id,oldPlate);assert.equal(k.s.tables[0].seats[0].status,'occupied');assert.equal(k.s.tables[0].seats[0].customerId,newGuest.id);assert.equal(k.s.tables[0].seats[0].mealId,newMeal);assert.equal(k.s.tables[0].seats[0].item,null);assert(sanitizeService(k.s));
 k.touch('sink');k.touch('prep');k.serve();assert.equal(k.s.served,2);assert.equal(k.s.washed,0);k.touch('sink');k.send({type:'hold',active:true});k.until(()=>k.s.washed===1);assert.equal(k.s.customers[0].washed,true);assert.equal(k.s.customers[1].servedTick!==null,true);assert.notEqual(k.s.tables[0].seats[0].item?.id,oldPlate);assert.equal(k.s.cleanPlates,1);assert(sanitizeService(k.s));
});
test('an angry new guest leaves the old dish intact across pause/reload',()=>{
 const k=new Kitchen({arrivalTicks:100,customers:2,queuePatienceTicks:12000,tablePatienceTicks:12000});k.burger();k.send({type:'open'});k.until(()=>k.s.customers[0]?.phase==='seated');k.serve();k.until(()=>k.s.customers[1]?.phase==='seated');const oldPlate=structuredClone(k.s.tables[0].seats[0].item!);assert.equal(oldPlate.kind,'dirty');assert.equal(k.s.tables[0].seats[0].mealId,k.s.customers[1].mealId);k.s=dispatchService(sanitizeService(k.s)!,{type:'resume'});k.s.customers[1].patience=1;stepService(k.s);assert.equal(k.s.strikes,1);assert.equal(k.s.customers[1].phase,'leaving');assert.deepEqual(k.s.tables[0].seats[0].item,oldPlate);assert.equal(k.s.tables[0].seats[0].status,'dirty');assert.equal(k.s.tables[0].seats[0].customerId,null);assert.equal(k.s.tables[0].seats[0].mealId,null);assert(sanitizeService(k.s));
 k.clear();assert.equal(k.s.chef.held?.id,oldPlate.id);assert.equal(k.s.chef.held?.meal?.mealId,oldPlate.meal!.mealId);assert.equal(k.s.cleanPlates,1);assert(sanitizeService(k.s));
});
test('a washer carries the historical plate while preserving the next guest’s reservation',()=>{
 const k=new Kitchen({tier:2,customers:2,arrivalTicks:100,queuePatienceTicks:12000,tablePatienceTicks:12000,helpers:[{id:'jo',role:'washer'}]});k.burger();k.send({type:'open'});k.until(()=>k.s.customers[0]?.phase==='seated');k.until(()=>k.s.customers[1]?.phase==='queue');k.serve();k.until(()=>k.s.helpers[0].held?.kind==='dirty');const first=k.s.customers[0],second=k.s.customers[1];assert(second.mealId);assert.equal(k.s.helpers[0].held?.meal?.mealId,first.mealId);assert.equal(k.s.tables[0].seats[0].customerId,second.id);assert.equal(k.s.tables[0].seats[0].mealId,second.mealId);assert.equal(k.s.tables[0].seats[0].item,null);assert(['reserved','occupied'].includes(k.s.tables[0].seats[0].status));assert(sanitizeService(k.s));k.until(()=>k.s.washed===1);assert.equal(k.s.tables[0].seats[0].customerId,second.id);assert.equal(k.s.tables[0].seats[0].mealId,second.mealId);assert.equal(k.s.served,1);assert.equal(k.s.cleanPlates,2);assert(sanitizeService(k.s));
});
test('base sink stores two physical dishes and washes both sequentially without losing stock',()=>{
 const k=new Kitchen();k.burger();k.touch('bin');k.touch('sink');k.burger();k.touch('bin');k.touch('sink');const sink=()=>k.s.stations.find(st=>st.kind==='sink')!;assert.equal(sink().slots.length,2);assert.equal(sink().slots.filter(slot=>slot.item).length,2);assert.equal(k.s.cleanPlates,0);assert(sanitizeService(k.s));
 k.send({type:'hold',active:true});stepService(k.s,SERVICE_RULES.washTicks);assert.equal(k.s.cleanPlates,1);assert.equal(sink().slots.filter(slot=>slot.item).length,1);stepService(k.s,SERVICE_RULES.washTicks);assert.equal(k.s.cleanPlates,2);assert.equal(sink().slots.filter(slot=>slot.item).length,0);stepService(k.s,200);assert.equal(k.s.cleanPlates,2);assert(sanitizeService(k.s));
});
test('three boxed fry portions require cutting, cooking and explicitly raising one basket',()=>{
 const k=new Kitchen({...buildServiceLoadout(1,['fries'],{fryer:2}),menu:['fries']});k.ingredient('potato','fries');k.touch('prep');k.send({type:'hold',active:true});k.until(()=>!!k.s.stations.find(st=>st.kind==='prep')!.slots[0].job?.ready);k.touch('prep');k.touch('fryer');k.until(()=>!!k.s.stations.find(st=>st.kind==='fryer')!.slots[0].job?.ready);k.touch('boxes');k.touch('fryer');assert.equal(k.s.chef.held?.kind,'plate');assert.match(k.s.notice,/raise/i);k.touch('boxes');k.touch('fryer');assert.equal(k.s.stations.find(st=>st.kind==='fryer')!.slots[0].batch?.phase,'raised');
 k.s=dispatchService(sanitizeService(k.s)!,{type:'resume'});for(let n=0;n<3;n++){k.touch('boxes');k.touch('fryer');assert.equal(k.s.chef.held?.kind,'dish');assert.equal(k.s.chef.held?.vesselKind,'fry_box');assert(sanitizeService(k.s));k.touch('bin');}assert.equal(k.s.stations.find(st=>st.kind==='fryer')!.slots[0].item,null);k.touch('boxes');k.touch('fryer');assert.equal(k.s.chef.held?.kind,'plate');assert.equal(k.s.cleanPlates,k.s.config.plateCount);
});
test('cups have their own finite washable pool and reject a mismatched plate',()=>{
 const k=new Kitchen({...withPlateRack(['lemonade']),menu:['lemonade']});k.ingredient('lemon','lemonade');k.touch('drinks');k.send({type:'hold',active:true});k.until(()=>!!k.s.stations.find(st=>st.kind==='drinks')!.slots[0].job?.ready);k.touch('plates');k.touch('drinks');assert.equal(k.s.chef.held?.vesselKind,'plate');k.touch('plates');k.touch('cups');k.touch('drinks');assert.equal(k.s.chef.held?.vesselKind,'cup');assert.equal(k.s.cleanCups,1);assert.equal(k.s.cleanPlates,2);k.touch('bin');assert.equal(k.s.chef.held?.vesselKind,'cup');k.wash();assert.equal(k.s.cleanCups,2);assert.equal(k.s.cleanPlates,2);assert(sanitizeService(k.s));
});
test('old physical fries and one-slot sink checkpoints preserve item meaning and gain safe empty capacity',()=>{
 const k=new Kitchen({...withPlateRack(['fries']),menu:['fries'],batchVersion:0});k.ingredient('potato','fries');k.touch('fryer');k.until(()=>!!k.s.stations.find(st=>st.kind==='fryer')!.slots[0].job?.ready);k.touch('fryer');assert.equal(k.s.chef.held?.step,1);assert.equal(k.s.chef.held?.stage,'prepared_fries');const id=k.s.chef.held!.id;delete (k.s.config as any).batchVersion;delete (k.s.config as any).cupCount;delete (k.s as any).cupStock;delete (k.s as any).cleanCups;k.s.stations.find(st=>st.kind==='sink')!.slots.length=1;const restored=sanitizeService(k.s)!;assert(restored);assert.equal(restored.config.batchVersion,0);assert.equal(restored.chef.held?.id,id);assert.equal(restored.stations.find(st=>st.kind==='sink')!.slots.length,2);assert.equal(serviceRecipeSteps(restored,'fries').length,1);
});
test('unraised baskets burn during preparation and cannot yield a forged fourth portion',()=>{
 const k=new Kitchen({menu:['fries']});k.ingredient('potato','fries');k.touch('prep');k.send({type:'hold',active:true});k.until(()=>!!k.s.stations.find(st=>st.kind==='prep')!.slots[0].job?.ready);k.touch('prep');k.touch('fryer');stepService(k.s,201);const basket=k.s.stations.find(st=>st.kind==='fryer')!.slots[0];assert.equal(basket.batch?.phase,'burnt');assert.equal(k.s.burnt,1);assert.equal(k.s.spawned,0);assert(sanitizeService(k.s));k.touch('boxes');k.touch('fryer');assert.equal(k.s.chef.held?.kind,'plate');k.touch('boxes');k.touch('fryer');assert.equal(k.s.chef.held?.kind,'burnt');k.touch('bin');assert.equal(k.s.stations.find(st=>st.kind==='fryer')!.slots[0].batch,null);
});
test('checkpoint rejects unknown batch versions and duplicate or malformed vessel pools',()=>{
 const k=new Kitchen({...withPlateRack(['lemonade']),menu:['lemonade']});assert(sanitizeService(k.s));
 for(const mutate of [(s:any)=>{s.config.batchVersion=2;},(s:any)=>{s.cupStock[0]=s.plateStock[0];},(s:any)=>{s.cupStock[0]=32;},(s:any)=>{s.cupStock[0]='';}]){const altered=structuredClone(k.s);mutate(altered);assert.equal(sanitizeService(altered),null);}
});
test('a returning learner with boxed fries progresses after clearing instead of waiting for an impossible wash',()=>{
 const k=new Kitchen({menu:['fries'],tutorialLearning:true});k.ingredient('potato','fries');k.touch('prep');k.send({type:'hold',active:true});k.until(()=>!!k.s.stations.find(st=>st.kind==='prep')!.slots[0].job?.ready);k.touch('prep');k.touch('fryer');k.until(()=>!!k.s.stations.find(st=>st.kind==='fryer')!.slots[0].job?.ready);k.touch('fryer');k.touch('boxes');k.touch('fryer');k.send({type:'open'});k.until(()=>k.s.customers[0]?.phase==='seated');k.serve();k.until(()=>k.s.tables[0].seats[0].status==='dirty');stepService(k.s,500);assert.equal(k.s.spawned,1);k.clear();assert.equal(k.s.chef.held,null);assert.equal(k.s.washed,0);k.until(()=>k.s.spawned===2);assert.equal(k.s.strikes,0);assert(sanitizeService(k.s));
});
console.log(`PASS ${groups} service flow, preparation and batch/vessel groups`);
