/** Holding any carried object, exact slot pickup, warming and safe old saves. */
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {EQUIPMENT_BY_ID,SERVICE_RULES} from '../src/lib/chef/diner/content';
import {buildServiceLoadout,makeStation} from '../src/lib/chef/diner/geometry';
import {createService,dispatchService,sanitizeService,serviceTargetIntent} from '../src/lib/chef/diner/service';
import {createDinerRecord,migrateDinerRecord,replayDiner} from '../src/lib/chef/diner/authority';
import {dispatchDiner} from '../src/lib/chef/diner/progression';
import type {CreateServiceOptions,ServiceAction,ServiceState} from '../src/lib/chef/diner/types';
import {Cook} from './dk-diner-cook-fixture';
let groups=0;function test(name:string,fn:()=>void){fn();groups++;console.log(`PASS ${name}`);}
class CounterKitchen {
 s:ServiceState;cook:Cook;
 constructor(readonly recipe='classic_burger',tier:1|2|3=1,options:CreateServiceOptions={}){const loadout=buildServiceLoadout(1,[recipe]);loadout.stations.push(makeStation('holding','pass',5,5,tier));this.s=dispatchService(createService({...loadout,menu:[recipe],customers:4,tutorialLearning:true,queuePatienceTicks:12000,tablePatienceTicks:12000,...options}),{type:'open'});assert.equal(this.s.phase,'playing',this.s.notice);this.cook=new Cook(()=>this.s,a=>this.send(a));}
 send(action:ServiceAction){this.s=dispatchService(this.s,action);}
 touch(id:string,ingredientId?:string){this.cook.touch(id,this.recipe,undefined,ingredientId);}
 counter(){return this.s.stations.find(st=>st.kind==='pass')!;}
 advance(ticks:number){while(ticks>0){const chunk=Math.min(ticks,SERVICE_RULES.maxTicksPerAction);this.send({type:'tick',ticks:chunk});ticks-=chunk;}}
 take(itemId:string){this.send({type:'interact',targetId:'holding',itemId});this.cook.until(()=>!this.s.chef.path.length);}
 reload(){const before=structuredClone(this.s),loaded=sanitizeService(JSON.parse(JSON.stringify(this.s)));assert(loaded);assert.equal(loaded.phase,'paused');assert.deepEqual(loaded.stations,before.stations);const frozen=dispatchService(loaded,{type:'tick',ticks:100});assert.equal(frozen.tick,loaded.tick);assert.deepEqual(frozen.stations,loaded.stations);this.s=dispatchService(loaded,{type:'resume'});}
 roundtrip(){const held=structuredClone(this.s.chef.held!);assert(held);assert.equal(serviceTargetIntent(this.s,'holding').disabled,false);this.touch('holding');assert.equal(this.s.chef.held,null);const slot=this.counter().slots.find(slot=>slot.item?.id===held.id)!;assert(slot);assert.equal(slot.job,null);assert.deepEqual(slot.item,held);this.reload();this.take(held.id);assert.deepEqual(this.s.chef.held,held);assert(this.counter().slots.every(slot=>!slot.item));assert(sanitizeService(this.s));return held;}
 prepared(){this.touch('fridge','beef');this.touch('grill');this.cook.until(()=>!!this.s.stations.find(st=>st.kind==='grill')!.slots[0].job?.ready);this.touch('grill');this.touch('prep');this.touch('crate','bun');this.touch('prep');this.send({type:'hold',active:true});this.cook.until(()=>!!this.s.stations.find(st=>st.kind==='prep')!.slots[0].job?.ready);this.send({type:'hold',active:false});this.touch('prep');assert.equal(this.s.chef.held?.stage,'prepared_classic_burger');}
}
test('holding counters store raw ingredients, processed food, prepared meals and burnt food unchanged',()=>{
 const bun=new CounterKitchen();bun.touch('crate','bun');bun.roundtrip();
 const patty=new CounterKitchen();patty.touch('fridge','beef');patty.touch('grill');patty.cook.until(()=>!!patty.s.stations.find(st=>st.kind==='grill')!.slots[0].job?.ready);patty.touch('grill');assert.equal(patty.s.chef.held!.stage,'cooked_patty');patty.roundtrip();
 const prepared=new CounterKitchen();prepared.prepared();prepared.roundtrip();
 const burnt=new CounterKitchen();burnt.touch('fridge','beef');burnt.touch('grill');burnt.cook.until(()=>burnt.s.stations.find(st=>st.kind==='grill')!.slots[0].item?.kind==='burnt');burnt.touch('grill');burnt.roundtrip();
 const legacy=new CounterKitchen('classic_burger',1,{physicalSupplies:false,batchVersion:0});legacy.touch('crate');assert.equal(legacy.s.chef.held!.kind,'raw');legacy.roundtrip();
});
test('clean plates, cups and bowls remain the same finite objects through storing and pickup',()=>{
 for(const [recipe,rack,pool] of [['classic_burger','plates','plateStock'],['coffee','cups','cupStock'],['tomato_pasta','bowls','bowlStock']] as const){const k=new CounterKitchen(recipe),initial=[...k.s[pool]];k.touch(rack);const held=k.roundtrip();assert.equal(held.kind,'plate');assert.equal(k.s[pool].length,initial.length-1);k.touch(rack);assert.deepEqual([...k.s[pool]].sort(),initial.sort());assert(sanitizeService(k.s));}
});
test('storing a dirty customer dish neither washes it nor loses its historical meal receipt',()=>{
 const k=new CounterKitchen();k.cook.until(()=>k.s.customers.some(c=>c.phase==='seated'));k.cook.dish('classic_burger');k.roundtrip();const guest=k.s.customers.find(c=>c.phase==='seated')!;k.cook.touch(guest.tableId!,undefined,guest.seatId!);k.cook.until(()=>k.s.tables.some(t=>t.seats.some(seat=>seat.item?.kind==='dirty')));k.cook.touch(guest.tableId!,undefined,guest.seatId!);const dish=k.roundtrip();assert.equal(dish.kind,'dirty');assert.equal(dish.meal!.mealId,guest.mealId);assert.equal(k.s.washed,0);assert.equal(k.s.cleanPlates,1);k.touch('sink');k.send({type:'hold',active:true});k.cook.until(()=>k.s.washed===1);assert.equal(k.s.cleanPlates,2);assert(k.s.plateStock.includes(dish.id));assert(sanitizeService(k.s));
});
test('mixed counters do not combine stored objects and exact pickup survives walking and reload',()=>{
 const k=new CounterKitchen();k.prepared();const food=structuredClone(k.s.chef.held!);k.touch('holding');k.touch('plates');const plate=structuredClone(k.s.chef.held!);k.touch('holding');assert.equal(k.s.chef.held,null);assert.equal(k.counter().slots[0].item!.kind,'processed');assert.equal(k.counter().slots[1].item!.kind,'plate');assert.equal(k.counter().slots.filter(slot=>slot.item).length,2);k.touch('crate','bun');const bun=structuredClone(k.s.chef.held!);assert.equal(serviceTargetIntent(k.s,'holding').disabled,true);k.touch('holding');assert.deepEqual(k.s.chef.held,bun);assert.equal(k.counter().slots.filter(slot=>slot.item).length,2);k.touch('bin');
 k.send({type:'move',x:1,y:1});k.cook.until(()=>!k.s.chef.path.length);k.send({type:'interact',targetId:'holding',itemId:plate.id});assert(k.s.chef.path.length);assert.equal(k.s.chef.targetItemId,plate.id);k.reload();assert.equal(k.s.chef.targetItemId,plate.id);k.cook.until(()=>!k.s.chef.path.length);assert.deepEqual(k.s.chef.held,plate);assert.equal(k.counter().slots[0].item!.id,food.id);k.touch('plates');k.take(plate.id);assert.equal(k.s.chef.held,null,'a repeated pickup never takes the other object');assert.equal(k.s.chef.targetItemId,null);assert.equal(k.counter().slots[0].item!.id,food.id);assert(sanitizeService(k.s));
});
test('an item disappearing during approach cannot redirect the pickup to another slot',()=>{
 const k=new CounterKitchen();k.touch('crate','bun');const first=k.s.chef.held!.id;k.touch('holding');k.touch('plates');const chosen=k.s.chef.held!.id;k.touch('holding');k.send({type:'move',x:1,y:1});k.cook.until(()=>!k.s.chef.path.length);k.send({type:'interact',targetId:'holding',itemId:chosen});assert(k.s.chef.path.length);
 // A competing actor has taken the selected plate to another legal surface.
 const slot=k.counter().slots.find(slot=>slot.item?.id===chosen)!,prep=k.s.stations.find(st=>st.kind==='prep')!.slots[0];prep.item=slot.item;slot.item=null;k.reload();k.cook.until(()=>!k.s.chef.path.length);assert.equal(k.s.chef.held,null);assert.equal(k.s.chef.targetId,null);assert.equal(k.s.chef.targetItemId,null);assert.equal(k.counter().slots[0].item!.id,first);assert.equal(prep.item!.id,chosen);assert(sanitizeService(k.s));
});
test('the base counter cools food; the lamp preserves warmth but never reheats cold food',()=>{
 assert.equal(EQUIPMENT_BY_ID.pass.tiers[0].warm,undefined);assert.equal(EQUIPMENT_BY_ID.pass.tiers[1].warm,true);assert.deepEqual(EQUIPMENT_BY_ID.pass.tiers.map(spec=>spec.capacity),[2,4,6]);
 for(const tier of [1,2,3] as const){const k=new CounterKitchen('classic_burger',tier);k.cook.dish('classic_burger');const id=k.s.chef.held!.id;k.touch('holding');k.advance(SERVICE_RULES.coldTicks+20);assert.equal(k.counter().slots[0].item!.cold,tier===1);assert.equal(k.counter().slots[0].item!.id,id);k.take(id);if(tier>1){k.advance(SERVICE_RULES.coldTicks+1);assert.equal(k.s.chef.held!.cold,true);k.touch('holding');k.advance(40);assert.equal(k.counter().slots[0].item!.cold,true,'lamp preserves warmth without erasing the cold penalty');}assert(sanitizeService(k.s));}
});
test('old active heat-lamp passes migrate without moving, dropping items, advancing time or duplicating stock',()=>{
 const k=new CounterKitchen();k.cook.dish('classic_burger');k.touch('holding');k.touch('plates');k.touch('holding');const before=structuredClone(k.counter()),clock=k.s.tick;delete (k.s.config as any).counterVersion;const restored=sanitizeService(k.s);assert(restored);const pass=restored.stations.find(st=>st.kind==='pass')!;assert.equal(pass.tier,2);assert.equal(pass.slots.length,4);assert.deepEqual(pass.slots.slice(0,2),before.slots);assert.deepEqual(pass.slots.slice(2),[{item:null,job:null},{item:null,job:null}]);assert.deepEqual([pass.x,pass.y,pass.facing],[before.x,before.y,before.facing]);assert.equal(restored.tick,clock);assert.deepEqual(restored.plateStock,k.s.plateStock);assert.equal(restored.config.counterVersion,1);assert.deepEqual(sanitizeService(restored)!.stations,restored.stations);
 const now=Date.UTC(2026,8,21,12),record=createDinerRecord(now,'counter-migration');record.state.equipment.pass={tier:1,truckOwned:true,homeCopies:0};delete record.state.counterVersion;record.state=dispatchDiner(record.state,{type:'startPractice'},{now}).state;record.state.run!.service=structuredClone(k.s);const migrated=migrateDinerRecord(record);assert.equal(migrated.state.equipment.pass.tier,2);assert.equal(migrated.state.run!.service!.phase,k.s.phase);assert.deepEqual(migrated.state.run!.service!.stations.find(st=>st.kind==='pass')!.slots.slice(0,2),before.slots);assert.deepEqual(migrated.clock,record.clock);
});
test('server replay accepts exact stored-item pickup and replaying it cannot mint another dish',()=>{
 const now=Date.UTC(2026,8,21,12),record=createDinerRecord(now,'counter-command'),k=new CounterKitchen();k.touch('plates');const id=k.s.chef.held!.id;k.touch('holding');record.state.equipment.pass={tier:1,truckOwned:true,homeCopies:0};record.state=dispatchDiner(record.state,{type:'startPractice'},{now}).state;record.state.run!.service=structuredClone(k.s);let next=replayDiner(record,[{type:'service',action:{type:'interact',targetId:'holding',itemId:id}}],now).record;assert.equal(next.state.run!.service!.chef.held!.id,id);assert.equal(next.state.run!.service!.stations.find(st=>st.kind==='pass')!.slots[0].item,null);next=replayDiner(next,[{type:'service',action:{type:'interact',targetId:'holding',itemId:id}}],now).record;assert.equal(next.state.run!.service!.chef.held!.id,id);assert.equal(next.state.run!.service!.cleanPlates,1);assert(sanitizeService(next.state.run!.service));
});
test('targeted pickups have identical replay hashes across serialized walking checkpoints',()=>{
 const now=Date.UTC(2026,8,21,12),record=createDinerRecord(now,'counter-replay'),k=new CounterKitchen();k.touch('crate','bun');k.touch('holding');k.touch('plates');const id=k.s.chef.held!.id;k.touch('holding');k.send({type:'move',x:1,y:1});k.cook.until(()=>!k.s.chef.path.length);record.state.equipment.pass={tier:1,truckOwned:true,homeCopies:0};record.state=dispatchDiner(record.state,{type:'startPractice'},{now}).state;record.state.run!.service=structuredClone(k.s);
 const action={type:'service' as const,action:{type:'interact' as const,targetId:'holding',itemId:id}},tick=(ticks:number)=>({type:'service' as const,action:{type:'tick' as const,ticks}});
 const uninterrupted=replayDiner(record,[action,tick(60)],now+3000).record;
 let checkpoint=replayDiner(record,[action,tick(3)],now+150).record;assert(checkpoint.state.run!.service!.chef.path.length);assert.equal(checkpoint.state.run!.service!.chef.targetItemId,id);checkpoint=JSON.parse(JSON.stringify(checkpoint));const hydrated=sanitizeService(checkpoint.state.run!.service);assert(hydrated);checkpoint.state.run!.service=dispatchService(hydrated,{type:'resume'});const resumed=replayDiner(checkpoint,[tick(57)],now+3000).record;
 const hash=(s:ServiceState)=>createHash('sha256').update(JSON.stringify(s)).digest('hex');assert.equal(hash(resumed.state.run!.service!),hash(uninterrupted.state.run!.service!));assert.deepEqual(resumed.clock,uninterrupted.clock);assert.equal(resumed.state.run!.service!.chef.held!.id,id);
});
test('two runners skip an unrequested first dish and collect distinct later orders from one counter',()=>{
 const layout=buildServiceLoadout(4,['classic_burger','coffee']);layout.stations.push(makeStation('holding','pass',8,6,2));const options={...layout,tier:4 as const,menu:['classic_burger','coffee'],customers:2,arrivalTicks:20,queuePatienceTicks:12000,tablePatienceTicks:12000,helpers:[{id:'runner-one',role:'runner' as const},{id:'runner-two',role:'runner' as const}]};
 let seed='';for(let i=0;i<100&&!seed;i++){let probe=dispatchService(createService({...options,seed:`mixed-counter-${i}`}),{type:'open'});probe=dispatchService(probe,{type:'tick',ticks:80});if(probe.customers.length===2&&probe.customers.every(c=>c.recipeId==='coffee'))seed=`mixed-counter-${i}`;}assert(seed,'a deterministic two-coffee service fixture is required');
 let s=dispatchService(createService({...options,seed}),{type:'prepare'});const send=(a:ServiceAction)=>{s=dispatchService(s,a);},cook=new Cook(()=>s,send);cook.until=(done,limit=4000)=>{let guard=0;while(!done()&&guard++<limit)send({type:'tick',ticks:1});assert(done(),s.notice);};
 cook.dish('classic_burger');const burgerId=s.chef.held!.id;cook.touch('holding');const cups:string[]=[];for(let i=0;i<2;i++){cook.dish('coffee');cups.push(s.chef.held!.id);cook.touch('holding');}assert.equal(s.spawned,0);send({type:'open'});cook.until(()=>s.served===2);assert.equal(s.customers.filter(c=>c.phase==='eating').length,2);assert(s.customers.every(c=>c.recipeId==='coffee'));assert.equal(s.stations.find(st=>st.kind==='pass')!.slots[0].item!.id,burgerId);assert(s.stations.find(st=>st.kind==='pass')!.slots.slice(1).every(slot=>!slot.item));assert.equal(new Set(s.tables.flatMap(t=>t.seats.flatMap(seat=>seat.item?[seat.item.id]:[]))).size,2);assert(sanitizeService(s));
});
console.log(`PASS ${groups} holding counter groups`);
