import assert from 'node:assert/strict';
import {initialQuality,qualitySample,observeAction,actionEnvelope,QUALITY_BUDGETS} from '../src/app/chef/diner-preview/presentation';
import type {ScenePerson} from '../src/app/chef/diner-preview/scene-types';
const guest:ScenePerson={id:'chef',role:'chef',x:0,y:0,pose:'idle'};
const carrying:ScenePerson={...guest,held:{kind:'dish',recipeId:'classic_burger'}};
const before=JSON.stringify([guest,carrying]);
const pickup=observeAction(guest,carrying,1)!;assert.equal(pickup.kind,'pickup');
assert.equal(observeAction(carrying,guest,2)?.kind,'setDown');
assert.equal(observeAction(guest,{...carrying,held:{kind:'dirty',recipeId:''}},3)?.kind,'clear');
assert.equal(observeAction(guest,{...guest,pose:'takeOrder'},4)?.kind,'acknowledge');
assert.equal(observeAction(carrying,structuredClone(carrying),4),null);
assert.equal(JSON.stringify([guest,carrying]),before,'presentation must never mutate simulated ownership');
assert.equal(actionEnvelope(pickup,3),0);assert.equal(actionEnvelope(pickup,.5),0);
assert(actionEnvelope(pickup,1.25,true)<actionEnvelope(pickup,1.25));
assert.equal(initialQuality(390,8),'medium');assert.equal(initialQuality(1280,8),'high');
let sample={quality:'high' as const,slowSamples:0} as {quality:'high'|'medium'|'low';slowSamples:number};
for(let i=0;i<2;i++)sample=qualitySample(sample.quality,sample.slowSamples,20,false);assert.equal(sample.quality,'high');
sample=qualitySample(sample.quality,sample.slowSamples,20,false);assert.equal(sample.quality,'medium');
sample=qualitySample(sample.quality,sample.slowSamples,60,false);assert.equal(sample.slowSamples,0);
for(let i=0;i<6;i++)sample=qualitySample(sample.quality,sample.slowSamples,20,true);assert.equal(sample.quality,'low');assert.equal(QUALITY_BUDGETS.low.shadows,false);
console.log('PASS presentation ownership, finite gestures, reduced motion and bounded automatic quality');
