import assert from 'node:assert/strict';
import { createRestaurantBlueprint, roomModuleGeometry, roomCanStep, roomZoneAt, bathroomBays, validateRoomPlan, ROOM_RULES, moveRoomModule, moveRoomZone, moveRoomZoneLayout, resolveRoomMount, alignRoomMounts, type RestaurantStage } from '../src/lib/chef/diner/room-plan';
import { createHomeWorld, homePath, stepHomeWorld, setHomeFixtureCondition, measureHomeRates, type HomeSimulationConfig } from '../src/lib/chef/diner/home-simulation';
let groups=0;function check(name:string,run:()=>void){run();groups++;console.log(`PASS ${name}`);}
function config(stage:RestaurantStage):HomeSimulationConfig {const b=createRestaurantBlueprint(stage);return {w:b.roomPlan.w,h:b.roomPlan.h,roomPlan:b.roomPlan,layout:b.layout,...b.staff,equipment:{grill:{tier:1},prep:{tier:1},sink:{tier:1},table_2:{tier:1}},menu:['classic_burger'],recipeLevels:{classic_burger:0},arrivalRate:90};}
check('all three stage blueprints have literal dimensions, reachable stools and role-aware walls',()=>{
 for(const stage of ['burger_shop','diner','restaurant'] as const){const c=config(stage);assert.equal(validateRoomPlan(c.roomPlan!,c.layout),null);const w=createHomeWorld(c);assert.equal(w.notice,'');assert.equal(w.tables.reduce((n,t)=>n+t.capacity,0),stage==='burger_shop'?3:stage==='diner'?5:6);assert(homePath(w,w.door,w.stations[0].front));assert.equal(homePath(w,w.door,w.stations[0].front,new Set(),'customer'),null);for(const table of w.tables)for(const seat of table.seats)assert(homePath(w,w.door,seat,new Set(),'customer'));}
});
check('starter stools face the opposite wall and every toilet is reached through its stall door',()=>{
 const starter=config('burger_shop'),console=starter.roomPlan!.modules.find(m=>m.kind==='console')!,bath=starter.roomPlan!.zones.find(z=>z.kind==='bathroom')!;
 assert.deepEqual({x:console.x,y:console.y,rotation:console.rotation},{x:0,y:5,rotation:3});
 assert.equal(roomModuleGeometry(console).seats.length,3);assert(roomModuleGeometry(console).seats.every(s=>bath.x-s.x>=6));
 for(const stage of ['burger_shop','diner','restaurant'] as const){const c=config(stage),w=createHomeWorld(c),plan=c.roomPlan!;
  for(const [i,p] of bathroomBays(plan).toilets.entries()){
   for(const y of [0,1])assert.equal(roomCanStep(plan,{x:p.x-1,y},{x:p.x,y},'customer'),false,`${stage} stall ${i} has no side entrance`);
   const path=homePath(w,w.door,{x:p.x,y:p.y+1},new Set(),'customer');assert(path,`${stage} stall ${i} is reachable`);
   const steps=[w.door,...path!];assert(steps.some((point,index)=>index>0&&point.x===p.x&&point.y===1&&steps[index-1].x===p.x&&steps[index-1].y===2),`${stage} stall ${i} enters from its visible door`);
  }
 }
});
check('the included server starts in the dining room, works visibly and returns there between shifts',()=>{
 for(const stage of ['burger_shop','diner','restaurant'] as const){const c=config(stage),w=createHomeWorld(c),servers=w.actors.filter(a=>a.role==='waiter');assert.equal(servers.length,stage==='burger_shop'?1:2);
  for(const server of servers)assert.equal(roomZoneAt(c.roomPlan!,server),undefined,`${stage} server starts on public floor`);
  assert(w.actors.filter(a=>a.role==='chef'||a.role==='cashier').every(a=>roomZoneAt(c.roomPlan!,a)?.kind==='kitchen'));
  assert.equal(new Set(w.actors.map(a=>`${a.x},${a.y}`)).size,w.actors.length);
  let carried=false,returned=false;for(let i=0;i<9000;i++){stepHomeWorld(w);carried ||= w.actors.some(a=>a.role==='waiter'&&a.held?.kind==='dish');returned ||= w.actors.some(a=>a.role==='waiter'&&a.held?.kind==='dirty');}
  assert(carried&&returned,`${stage} server delivers and clears physical plates`);assert(w.metrics.plates>5);
  const quiet=createHomeWorld({...c,arrivalRate:0}),server=quiet.actors.find(a=>a.role==='waiter')!;server.x=3;server.y=1;
  stepHomeWorld(quiet,300);assert.equal(roomZoneAt(quiet.config.roomPlan!,server),undefined,`${stage} idle server leaves the kitchen`);assert.equal(server.path.length,0);
 }
});
check('cashier or waiter takes real orders; kitchens transfer exact dishes and return dirty plates',()=>{
 for(const stage of ['burger_shop','diner','restaurant'] as const){const w=createHomeWorld(config(stage));let counterFood=false,dirtyReturn=false,taken=false;for(let i=0;i<18000;i++){stepHomeWorld(w);counterFood ||= w.stations.some(s=>s.moduleId&&s.slots.some(slot=>slot.item?.kind==='dish'));dirtyReturn ||= w.stations.some(s=>s.dirtySlots?.some(slot=>slot.item?.kind==='dirty'));taken ||= w.actors.some(a=>a.pose==='takeOrder');const items=[...w.actors.map(a=>a.held),...w.stations.flatMap(s=>[...s.slots.map(slot=>slot.item),...(s.dirtySlots??[]).map(slot=>slot.item)]),...w.tables.flatMap(t=>t.seats.map(s=>s.item))].filter(Boolean);assert.equal(new Set(items.map(i=>i!.id)).size,items.length);for(const person of [...w.actors,...w.customers])assert(w.walkable[Math.round(person.y)*w.config.w+Math.round(person.x)],`${stage}: ${person.id} crossed furnishing`);}
  console.log(stage,JSON.stringify({plates:w.metrics.plates,washed:w.metrics.washed,orders:w.metrics.ordersTaken,fixtures:w.metrics.fixtureUses,}));assert(w.metrics.plates>=8,`${stage} meals ${w.metrics.plates}`);assert(w.metrics.washed>=7);assert(counterFood&&dirtyReturn&&taken);assert.equal(w.metrics.tips>0,stage!=='burger_shop');assert(Object.values(w.metrics.fixtureUses).some(n=>n>0));}
});
check('bathroom failures reduce service but recover without losing table receipts',()=>{const w=createHomeWorld(config('burger_shop'));for(const f of w.bathrooms)setHomeFixtureCondition(w,f.id,20);stepHomeWorld(w,12000);assert(w.metrics.plates>0);assert(w.metrics.bathroomMisses>0);assert.equal(Object.values(w.metrics.fixtureUses).reduce((a,b)=>a+b,0),0);for(const f of w.bathrooms)setHomeFixtureCondition(w,f.id,100);stepHomeWorld(w,12000);assert(Object.values(w.metrics.fixtureUses).some(n=>n>0));assert(w.bathrooms.every(f=>f.condition<100));});
check('rotated explicit stool anchors and room worlds survive deterministic JSON reload',()=>{for(const rotation of [0,1,2,3] as const){const g=roomModuleGeometry({id:'console',kind:'console',x:3,y:3,rotation});assert.equal(g.seats.length,3);assert.equal(new Set(g.seats.map(p=>`${p.x},${p.y}`)).size,3);}const a=createHomeWorld(config('diner'));stepHomeWorld(a,1234);const b=JSON.parse(JSON.stringify(a));stepHomeWorld(a,5000);stepHomeWorld(b,5000);assert.deepEqual(b,a);});
check('module and bathroom-area drafts preserve openings and never mutate the original plan',()=>{const c=config('burger_shop'),original=JSON.stringify(c);const narrower=structuredClone(c.roomPlan!);const counter=narrower.modules.find(m=>m.kind==='display_counter')!;counter.x=1;counter.width=3;const moved=moveRoomModule(narrower,'staff-gate',0,3,0);assert.equal(validateRoomPlan(moved,c.layout),null);assert.equal(moved.edges.find(e=>e.id==='kitchen-4')!.kind,'wall');assert.equal(moved.edges.find(e=>e.id==='kitchen-0')!.kind,'staff_gate');const bath=c.roomPlan!.zones.find(z=>z.id==='bathroom')!,translated=moveRoomZone(c.roomPlan!,'bathroom',bath.x-1,bath.y),layout=moveRoomZoneLayout(c.layout,c.roomPlan!,'bathroom',bath.x-1,bath.y);assert.equal(validateRoomPlan(translated,layout),null);const w=createHomeWorld({...c,roomPlan:translated,layout});stepHomeWorld(w,9000);assert(w.metrics.plates>5);assert(Object.values(w.metrics.fixtureUses).some(n=>n>0));assert.equal(JSON.stringify(c),original);assert(validateRoomPlan(moveRoomModule(c.roomPlan!,'starter-console',0,0,0),c.layout));});
check('mounted decor uses real support positions, leaves navigation clear and rejects stale anchors',()=>{const c=config('burger_shop'),mount={kind:'counter' as const,targetId:'starter-console',slot:1},resolved=resolveRoomMount(c.roomPlan!,mount)!;const p={id:'flower',equipmentId:'daisy_pot',x:Math.floor(resolved.x),y:Math.floor(resolved.y),rotation:0 as const,mount};assert.equal(validateRoomPlan(c.roomPlan!,[...c.layout,p]),null);const plain=createHomeWorld(c),decorated=createHomeWorld({...c,layout:[...c.layout,p]});assert.deepEqual(decorated.walkable,plain.walkable);assert(validateRoomPlan(c.roomPlan!,[...c.layout,{...p,x:p.x+1}]));assert(validateRoomPlan(c.roomPlan!,[...c.layout,p,{...p,id:'second'}]));const moved=moveRoomModule(c.roomPlan!,'starter-console',0,4,3),aligned=alignRoomMounts([p],moved);assert.equal(aligned[0].y,p.y-1);assert.equal(p.y,Math.floor(resolved.y));});
check('staged table chairs need public access and preserve all rotated valid arrangements',()=>{const c=config('burger_shop');const kitchen={id:'bad-table',equipmentId:'table_1',x:1,y:0,rotation:0 as const};assert.match(validateRoomPlan(c.roomPlan!,[...c.layout,kitchen])!,/public dining/);for(const rotation of [0,1,2,3] as const){const p={id:'dining-table',equipmentId:'table_1',x:5,y:5,rotation};const layout=[...c.layout,p];assert.equal(validateRoomPlan(c.roomPlan!,layout),null);const w=createHomeWorld({...c,layout});assert.equal(w.tables.find(t=>t.id===p.id)?.seats.length,1);assert(homePath(w,w.door,w.tables.find(t=>t.id===p.id)!.seats[0],new Set(),'customer'));}});
check('a blocked first clean seat does not starve another reachable table',()=>{const w=createHomeWorld(config('restaurant'));w.actors=[];w.config.chefs=0;w.config.waiters=0;const original=w.tables[0];w.tables.unshift({...structuredClone(original),id:'unreachable-old-table',seats:[{...structuredClone(original.seats[0]),id:'unreachable-chair',x:1,y:1}]});w.customers.push({...w.door,id:'waiting',phase:'queue',path:[],tableId:null,seatId:null,orderId:null,recipeId:'classic_burger',eatRemaining:0});stepHomeWorld(w);assert.equal(w.customers[0].tableId,original.id);assert.equal(w.tables[0].seats[0].status,'clean');});
check('stage structures and reserved bathroom boundaries cannot disappear',()=>{for(const stage of ['burger_shop','diner','restaurant'] as const){const c=config(stage);for(const kind of ['lift_gate',stage==='burger_shop'?'display_counter':stage==='diner'?'service_hatch':'internal_pass']){const p=structuredClone(c.roomPlan!);p.modules=p.modules.filter(m=>m.kind!==kind);assert(validateRoomPlan(p,c.layout),`${stage} missing ${kind}`);}const noBath=structuredClone(c.roomPlan!);noBath.modules=noBath.modules.filter(m=>!['toilet','handwash_sink'].includes(m.kind));noBath.zones=noBath.zones.filter(z=>z.kind!=='bathroom');noBath.edges=noBath.edges.filter(e=>e.zoneId!=='bathroom');assert(validateRoomPlan(noBath,c.layout));const noSide=structuredClone(c.roomPlan!);noSide.edges=noSide.edges.filter(e=>e.id!=='kitchen-side-0');assert(validateRoomPlan(noSide,c.layout));const stored=structuredClone(c.roomPlan!);stored.modules=stored.modules.filter(m=>!['toilet','handwash_sink'].includes(m.kind));assert.equal(validateRoomPlan(stored,c.layout),null,'owned bathroom fittings may be stored without deleting reserved room');}});
check('counter mounts reserve tills and keep pots between plated meal centers in all rotations',()=>{const c=config('burger_shop');assert.equal(resolveRoomMount(c.roomPlan!,{kind:'counter',targetId:'service-counter',slot:0}),null);for(const rotation of [0,1,2,3] as const){const p=structuredClone(c.roomPlan!),module=p.modules.find(m=>m.kind==='console')!;module.x=4;module.y=4;module.rotation=rotation;const geometry=roomModuleGeometry(module);for(let slot=0;slot<3;slot++){const at=resolveRoomMount(p,{kind:'counter',targetId:module.id,slot})!;assert(Math.abs(Math.hypot(at.x-geometry.cells[slot].x,at.y-geometry.cells[slot].y)-.36)<1e-8);assert(geometry.cells.every(cell=>Math.hypot(at.x-cell.x,at.y-cell.y)>=.359999));}}});
check('starter trinkets leave serving routes clear and a welcome mat remains walkable',()=>{
 const c=config('burger_shop'),plain=createHomeWorld(c),mat={id:'mat',equipmentId:'welcome_mat',...plain.door,rotation:0 as const};
 const mount={kind:'counter' as const,targetId:'service-counter',slot:1},at=resolveRoomMount(c.roomPlan!,mount)!;
 const mascot={id:'mascot',equipmentId:'burger_mascot',x:Math.floor(at.x),y:Math.floor(at.y),rotation:0 as const,mount};
 assert.equal(validateRoomPlan(c.roomPlan!,[...c.layout,mat,mascot]),null);
 const decorated=createHomeWorld({...c,layout:[...c.layout,mat,mascot]});assert.equal(decorated.notice,'');assert.deepEqual(decorated.walkable,plain.walkable);
 assert(validateRoomPlan(c.roomPlan!,[...c.layout,mat,{...mat,id:'duplicate-mat'}]));
 assert(validateRoomPlan(c.roomPlan!,[...c.layout,{...mat,x:-1}]));
 stepHomeWorld(decorated,9000);assert(decorated.metrics.plates>5);assert(decorated.metrics.washed>5);
});
check('outer wall slots face into the room, reject invalid slots and leave internal mounts unchanged',()=>{
 for(const stage of ['burger_shop','diner','restaurant'] as const){const c=config(stage),plan=c.roomPlan!;
  for(const [targetId,count,rotation] of [['outer-back',plan.w,0],['outer-side',plan.h,3]] as const){
   for(let slot=0;slot<count;slot++){const mount={kind:'wall' as const,targetId,slot},point=resolveRoomMount(plan,mount)!;
    assert.deepEqual(point,targetId==='outer-back'?{x:slot,y:-.55,rotation,surfaceHeight:1.5}:{x:-.55,y:slot,rotation,surfaceHeight:1.5});
    const p={id:'print',equipmentId:'burger_print',x:Math.floor(point.x),y:Math.floor(point.y),rotation,mount};assert.equal(validateRoomPlan(plan,[...c.layout,p]),null);
    assert(validateRoomPlan(plan,[...c.layout,p,{...p,id:'duplicate'}]));
   }
   for(const slot of [-1,.5,count])assert.equal(resolveRoomMount(plan,{kind:'wall',targetId,slot}),null);
  }
  const edge=plan.edges.find(e=>e.kind==='wall')!,point=resolveRoomMount(plan,{kind:'wall',targetId:edge.id,slot:0});
  assert.deepEqual(point,{x:(edge.a.x+edge.b.x)/2,y:(edge.a.y+edge.b.y)/2,rotation:edge.a.x===edge.b.x?0:1,surfaceHeight:1.5});
 }
});
check('additional staff keep producing without remote jobs or wall crossings',()=>{for(const stage of ['burger_shop','diner','restaurant'] as const){const c=config(stage);c.chefs=2;c.waiters=3;c.arrivalRate=180;const w=createHomeWorld(c);stepHomeWorld(w,9000);const first=w.metrics.plates;for(let i=0;i<9000;i++){const previous=new Map([...w.actors,...w.customers].map(p=>[p.id,{x:Math.round(p.x),y:Math.round(p.y)}]));stepHomeWorld(w);for(const person of [...w.actors,...w.customers]){const from=previous.get(person.id),to={x:Math.round(person.x),y:Math.round(person.y)};if(from&&Math.abs(from.x-to.x)+Math.abs(from.y-to.y)===1)assert(roomCanStep(w.config.roomPlan,from,to,'role' in person?person.role:'customer'),`${person.id} crossed a blocked edge`);}for(const station of w.stations)for(const slot of station.slots)if(slot.job&&!slot.job.ready&&(slot.job.action==='hold'||slot.job.action==='wash')&&slot.workerId){const actor=w.actors.find(a=>a.id===slot.workerId)!;if(actor.task?.phase==='work')assert(Math.hypot(actor.x-station.front.x,actor.y-station.front.y)<.001);}}assert(first>5,`${stage} first ${first} second ${w.metrics.plates-first} ${JSON.stringify({actors:w.actors,customers:w.customers})}`);assert(w.metrics.plates-first>5,`${stage} second ${w.metrics.plates-first} ${JSON.stringify(w.actors)}`);console.log(`  ${stage}: ${w.metrics.plates} meals / ${w.metrics.washed} washes with five floor staff`);}});
check('steady rate samples count physical bathroom use without double-applying persistent wear',()=>{const c=config('burger_shop'),start=performance.now(),rate=measureHomeRates(c),elapsed=performance.now()-start;assert(rate.fixtureUses['toilet-1']>0);assert(rate.fixtureUses['handwash-1']>0);assert.equal(c.roomPlan!.modules.find(m=>m.id==='toilet-1')!.condition,100);const worn=structuredClone(c);worn.roomPlan!.modules.find(m=>m.id==='toilet-1')!.condition=70;assert.deepEqual(measureHomeRates(worn),rate);const broken=structuredClone(c);for(const module of broken.roomPlan!.modules)if(module.condition!==undefined)module.condition=ROOM_RULES.minimumCondition;const degraded=measureHomeRates(broken);assert(degraded.plates<rate.plates);assert(degraded.bathroomMisses>0);console.log(`  cold room rate sample ${Math.round(elapsed)} ms; ${rate.plates} healthy vs ${degraded.plates} degraded plates/hour`);});
console.log(`PASS ${groups} staged restaurant engine groups`);
