import assert from 'node:assert/strict';
import { createDiner, sanitizeDinerSave } from '../src/lib/chef/diner/progression';
import { addStoredRoomFixture, moveRoomDraft, rotateRoomDraft, validateRoomDraft } from '../src/app/chef/diner-preview/room-editor';
import { bathroomBays, resolveRoomMount } from '../src/lib/chef/diner/room-plan';
let groups=0;function check(name:string,f:()=>void){f();groups++;console.log(`PASS ${name}`);}
const state=createDiner(Date.UTC(2026,8,21),'room-editor'),initial={roomPlan:structuredClone(state.home.roomPlan!),layout:structuredClone(state.home.layout)};
check('room drafts rotate and move before validation without changing persistent state',()=>{const before=JSON.stringify(state),rotated=rotateRoomDraft(initial,'starter-console');assert.equal(rotated.roomPlan.modules.find(m=>m.id==='starter-console')!.rotation,0);assert(validateRoomDraft(state,moveRoomDraft(rotated,'starter-console',9,7)));const moved=moveRoomDraft(initial,'staff-gate',0,3);assert.equal(validateRoomDraft(state,moved),null);assert.equal(JSON.stringify(state),before);assert.deepEqual(initial.roomPlan,state.home.roomPlan);assert(sanitizeDinerSave(state));});
check('bathroom groups carry fittings and walls together, with a validated undo by discarded draft',()=>{const bath=initial.roomPlan.zones.find(z=>z.id==='bathroom')!,moved=moveRoomDraft(initial,'zone:bathroom',bath.x-1,bath.y);assert.equal(validateRoomDraft(state,moved),null);assert.equal(moved.roomPlan.modules.find(m=>m.id==='toilet-1')!.x,initial.roomPlan.modules.find(m=>m.id==='toilet-1')!.x-1);assert.equal(initial.roomPlan.zones.find(z=>z.id==='bathroom')!.x,bath.x);assert(validateRoomDraft(state,moveRoomDraft(initial,'zone:bathroom',0,0)));});
check('stored fixtures are placed once in real reserved bays and retain condition',()=>{const owned=structuredClone(state);owned.home.fixtureInventory!['toilet-2']={kind:'toilet',condition:36};const placed=addStoredRoomFixture(initial,'toilet-2','toilet',36);assert.equal(validateRoomDraft(owned,placed),null);const fixture=placed.roomPlan.modules.find(m=>m.id==='toilet-2')!;assert.equal(fixture.condition,36);assert.deepEqual({x:fixture.x,y:fixture.y},bathroomBays(initial.roomPlan).toilets[1]);assert.equal(addStoredRoomFixture(placed,'toilet-2','toilet',100).roomPlan.modules.filter(m=>m.id==='toilet-2').length,1);assert(validateRoomDraft(state,placed));});
check('attached counter decorations follow their support and retain copy identity',()=>{const mount={kind:'counter' as const,targetId:'starter-console',slot:1},point=resolveRoomMount(initial.roomPlan,mount)!,draft=structuredClone(initial);draft.layout.push({id:'owned-daisy',equipmentId:'daisy_pot',x:Math.floor(point.x),y:Math.floor(point.y),rotation:0,mount});const rotated=rotateRoomDraft(draft,'starter-console'),m=rotated.layout.find(p=>p.id==='owned-daisy')!,at=resolveRoomMount(rotated.roomPlan,mount)!;assert.equal(m.x,Math.floor(at.x));assert.equal(m.y,Math.floor(at.y));assert.equal(rotated.layout.filter(p=>p.id==='owned-daisy').length,1);});
console.log(`PASS ${groups} restaurant room editor groups`);
