/**
 * Season 4 arcade — the STEAM-LIBRARY presentation of the game slate.
 *
 * A big FEATURED HERO (the first game, a full-bleed cover banner) over a grid
 * of cover-art tiles, exactly the Steam library feel Mike asked for. The server
 * page (./page.tsx) owns the data: it reads the registry (src/lib/s4/games.ts),
 * maps each game to a serializable card, and hands them here. This component is
 * purely presentational so it can be a client component (hover polish + the
 * missing-art swap need the browser).
 *
 * ART: each card's background is /s4-art/games/<key>/capsule.png. That art is
 * generated by a separate pass and may be ABSENT — so every hero and tile uses
 * the proven hydration-safe missing-art pattern (ref checks complete &&
 * naturalWidth === 0 at mount, plus onError) and falls back to a premium
 * accent gradient with the game name, looking intentional with zero images.
 *
 * Palette: charcoal #07080c base; per-game accents crimson / gold / violet /
 * ice arrive as props (each game carries its own). No themed WORD is hardcoded
 * here — display names come from the registry via props.
 */
"use client";

import Link from "next/link";
import { useState } from "react";

export type LibraryCard = {
  key: string; // stable registry key; routes to /s4/games/<key>
  name: string; // display name from the registry
  blurb: string; // one-liner
  accent: string; // per-game accent hex
  comingSoon: boolean;
};

const INK = "#07080c";

/**
 * Cover art with graceful absence. A premium accent gradient is always the base
 * layer (it shows through until the PNG paints, and stays if the PNG is
 * missing); the cover image sits on top and hides the gradient when it loads.
 * The ref check catches a 404 that resolved before hydration (onError never
 * fires for those), the proven S4 hero pattern.
 */
function Cover({ src, accent }: { src: string; accent: string }) {
  const [missing, setMissing] = useState(false);
  return (
    <>
      <div
        aria-hidden="true"
        style={{
          position: "absolute",
          inset: 0,
          background:
            "radial-gradient(135% 108% at 50% 0%, " +
            accent +
            "40 0%, rgba(7,8,12,0) 52%), linear-gradient(180deg, #12141d 0%, " +
            INK +
            " 72%)",
        }}
      />
      {!missing ? (
        // eslint-disable-next-line @next/next/no-img-element
        <img
          src={src}
          alt=""
          className="s4lib-cover"
          ref={(el) => {
            if (el && el.complete && el.naturalWidth === 0) setMissing(true);
          }}
          onError={() => setMissing(true)}
          style={{
            position: "absolute",
            inset: 0,
            width: "100%",
            height: "100%",
            objectFit: "cover",
            objectPosition: "center",
            display: "block",
          }}
        />
      ) : null}
    </>
  );
}

function accentVars(accent: string): React.CSSProperties {
  return { "--s4-accent": accent, "--s4-glow": accent + "55" } as React.CSSProperties;
}

/** The featured banner: first game, full-bleed cover, dark left+bottom scrim. */
function Hero({ card }: { card: LibraryCard }) {
  const live = !card.comingSoon;
  return (
    <div
      className="s4lib-hero"
      style={{
        position: "relative",
        overflow: "hidden",
        borderRadius: 18,
        border: "1px solid " + card.accent + "44",
        background: INK,
        minHeight: "clamp(300px, 44vw, 430px)",
        marginBottom: 30,
        boxShadow: "0 20px 60px rgba(0,0,0,0.5)",
        ...accentVars(card.accent),
      }}
    >
      <Cover src={"/s4-art/games/" + card.key + "/capsule.png"} accent={card.accent} />
      {/* legibility scrim: dark from the left and from the bottom */}
      <div
        aria-hidden="true"
        style={{
          position: "absolute",
          inset: 0,
          background:
            "linear-gradient(90deg, rgba(4,5,8,0.94) 0%, rgba(4,5,8,0.62) 38%, rgba(4,5,8,0) 72%), linear-gradient(0deg, rgba(4,5,8,0.92) 0%, rgba(4,5,8,0) 55%)",
        }}
      />
      <div
        style={{
          position: "relative",
          zIndex: 1,
          height: "100%",
          minHeight: "inherit",
          display: "flex",
          flexDirection: "column",
          justifyContent: "flex-end",
          padding: "clamp(20px, 4vw, 40px)",
          maxWidth: 620,
        }}
      >
        <span
          style={{
            alignSelf: "flex-start",
            display: "inline-block",
            padding: "4px 12px",
            borderRadius: 999,
            border: "1px solid " + card.accent + "66",
            background: card.accent + "1f",
            color: card.accent,
            fontSize: 11,
            fontWeight: 800,
            letterSpacing: "0.14em",
            textTransform: "uppercase",
          }}
        >
          ★ Featured
        </span>
        <h2
          style={{
            margin: "14px 0 8px",
            fontSize: "clamp(30px, 6vw, 52px)",
            fontWeight: 900,
            lineHeight: 1.02,
            letterSpacing: "-0.01em",
            color: "#fff",
            textShadow: "0 4px 24px rgba(0,0,0,0.5)",
          }}
        >
          {card.name}
        </h2>
        <p
          style={{
            margin: "0 0 20px",
            fontSize: "clamp(14px, 2vw, 18px)",
            color: "rgba(232,236,245,0.85)",
            lineHeight: 1.5,
            maxWidth: 460,
          }}
        >
          {card.blurb}
        </p>
        {live ? (
          <div style={{ display: "flex", gap: 12, flexWrap: "wrap" }}>
            <Link
              href={"/s4/games/" + card.key}
              className="s4lib-btn s4lib-btn-primary"
              style={{
                display: "inline-flex",
                alignItems: "center",
                gap: 8,
                minHeight: 44,
                boxSizing: "border-box",
                padding: "13px 28px",
                borderRadius: 11,
                background: card.accent,
                color: INK,
                fontSize: 15.5,
                fontWeight: 800,
                textDecoration: "none",
              }}
            >
              <span aria-hidden="true">▶</span> Play
            </Link>
            <Link
              href={"/s4/games/" + card.key + "?practice=1"}
              className="s4lib-btn s4lib-btn-ghost"
              style={{
                display: "inline-flex",
                alignItems: "center",
                gap: 8,
                minHeight: 44,
                boxSizing: "border-box",
                padding: "13px 24px",
                borderRadius: 11,
                background: "rgba(255,255,255,0.07)",
                color: "#e8ecf5",
                border: "1px solid rgba(255,255,255,0.24)",
                fontSize: 15.5,
                fontWeight: 700,
                textDecoration: "none",
              }}
            >
              Practice
            </Link>
          </div>
        ) : (
          <span
            style={{
              alignSelf: "flex-start",
              padding: "10px 18px",
              borderRadius: 10,
              border: "1px solid rgba(255,255,255,0.16)",
              background: "rgba(255,255,255,0.05)",
              color: "#aeb6c8",
              fontSize: 13,
              fontWeight: 700,
              letterSpacing: "0.08em",
              textTransform: "uppercase",
            }}
          >
            Coming soon
          </span>
        )}
      </div>
    </div>
  );
}

/** A Steam-library tile: cover art, bottom scrim, name + one-liner, Play. */
function Tile({ card }: { card: LibraryCard }) {
  const body = (
    <>
      <Cover src={"/s4-art/games/" + card.key + "/capsule.png"} accent={card.accent} />
      {/* accent top hairline for at-a-glance identity */}
      <div
        aria-hidden="true"
        style={{ position: "absolute", top: 0, left: 0, right: 0, height: 3, background: card.accent, opacity: 0.9 }}
      />
      {/* bottom scrim so the name stays legible over any art */}
      <div
        aria-hidden="true"
        style={{
          position: "absolute",
          inset: 0,
          background:
            "linear-gradient(0deg, rgba(4,5,8,0.95) 0%, rgba(4,5,8,0.55) 32%, rgba(4,5,8,0) 62%)",
        }}
      />
      <div
        style={{
          position: "relative",
          zIndex: 1,
          height: "100%",
          display: "flex",
          flexDirection: "column",
          justifyContent: "flex-end",
          padding: 16,
        }}
      >
        <div style={{ fontSize: 18, fontWeight: 800, color: "#fff", lineHeight: 1.12 }}>{card.name}</div>
        <div style={{ fontSize: 12.5, color: "rgba(232,236,245,0.8)", marginTop: 4, lineHeight: 1.4 }}>
          {card.blurb}
        </div>
        {card.comingSoon ? (
          <span
            style={{
              alignSelf: "flex-start",
              marginTop: 12,
              padding: "6px 12px",
              borderRadius: 999,
              border: "1px solid rgba(255,255,255,0.16)",
              background: "rgba(255,255,255,0.05)",
              color: "#aeb6c8",
              fontSize: 11,
              fontWeight: 700,
              letterSpacing: "0.08em",
              textTransform: "uppercase",
            }}
          >
            Coming soon
          </span>
        ) : (
          <span
            className="s4lib-play"
            style={{
              alignSelf: "flex-start",
              marginTop: 12,
              display: "inline-flex",
              alignItems: "center",
              gap: 7,
              padding: "8px 16px",
              borderRadius: 9,
              border: "1px solid " + card.accent + "88",
              background: card.accent + "1f",
              color: "#fff",
              fontSize: 13,
              fontWeight: 800,
              letterSpacing: "0.02em",
            }}
          >
            <span aria-hidden="true">▶</span> Play
          </span>
        )}
      </div>
    </>
  );

  const shellStyle: React.CSSProperties = {
    position: "relative",
    overflow: "hidden",
    display: "block",
    aspectRatio: "3 / 4",
    borderRadius: 14,
    border: "1px solid #1c2236",
    background: INK,
    textDecoration: "none",
    ...accentVars(card.accent),
  };

  if (card.comingSoon) {
    return (
      <div className="s4lib-tile" style={shellStyle}>
        {body}
      </div>
    );
  }
  return (
    <Link className="s4lib-tile" style={shellStyle} href={"/s4/games/" + card.key} aria-label={"Play " + card.name}>
      {body}
    </Link>
  );
}

export function GameLibrary({ cards }: { cards: LibraryCard[] }) {
  if (cards.length === 0) return null;
  // The featured hero spotlights the first game; the grid below still lists
  // every game (the featured one included), the way a Steam library shows the
  // spotlight AND the full shelf.
  const featured = cards[0];
  return (
    <div>
      <style dangerouslySetInnerHTML={{ __html: LIBRARY_CSS }} />
      <Hero card={featured} />
      <div
        style={{
          fontSize: 11,
          letterSpacing: "0.28em",
          color: "#8b95ad",
          textTransform: "uppercase",
          fontWeight: 700,
          margin: "0 0 14px",
        }}
      >
        All games
      </div>
      <div className="s4lib-grid">
        {cards.map((c) => (
          <Tile key={c.key} card={c} />
        ))}
      </div>
    </div>
  );
}

// No backticks or quotes inside this CSS string (server HTML-escaping of a
// <style> text child corrupts quotes and desyncs hydration; the hero uses the
// same dangerouslySetInnerHTML approach for the same reason).
const LIBRARY_CSS =
  ".s4lib-grid{display:grid;gap:16px;grid-template-columns:repeat(4,1fr);}" +
  "@media (max-width:900px){.s4lib-grid{grid-template-columns:repeat(2,1fr);}}" +
  "@media (max-width:460px){.s4lib-grid{grid-template-columns:1fr;}}" +
  ".s4lib-tile{transition:box-shadow .2s ease,border-color .2s ease,transform .2s ease;}" +
  ".s4lib-tile:hover,.s4lib-tile:focus-visible{box-shadow:0 22px 50px rgba(0,0,0,.6),0 0 32px var(--s4-glow);border-color:var(--s4-accent);outline:none;}" +
  ".s4lib-tile:hover .s4lib-play,.s4lib-tile:focus-visible .s4lib-play{background:var(--s4-accent);color:#07080c;border-color:var(--s4-accent);}" +
  ".s4lib-cover{transition:transform .4s ease;}" +
  ".s4lib-hero{transition:box-shadow .2s ease,border-color .2s ease;}" +
  ".s4lib-hero:hover{box-shadow:0 26px 70px rgba(0,0,0,.6),0 0 40px var(--s4-glow);}" +
  ".s4lib-btn{transition:transform .16s ease,filter .16s ease,background .16s ease,border-color .16s ease;}" +
  ".s4lib-btn-primary:hover{filter:brightness(1.08);}" +
  ".s4lib-btn-ghost:hover{background:rgba(255,255,255,.13);border-color:rgba(255,255,255,.42);}" +
  "@media (prefers-reduced-motion: no-preference){" +
  ".s4lib-tile:hover,.s4lib-tile:focus-visible{transform:translateY(-6px) scale(1.02);}" +
  ".s4lib-tile:hover .s4lib-cover,.s4lib-hero:hover .s4lib-cover{transform:scale(1.05);}" +
  ".s4lib-btn-primary:hover,.s4lib-btn-ghost:hover{transform:translateY(-2px);}" +
  "}";
